apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-secret
  namespace: observability
type: Opaque
stringData:
  GF_DATABASE_TYPE: ENC[AES256_GCM,data:pQ9Alfy64+c=,iv:eQz+QbP0PCrRRwzk5oCEpjQBIKPD5jDXeNIUznmson4=,tag:JE7MRuSAiCS7dK0s5XvQig==,type:str]
  GF_DATABASE_HOST: ENC[AES256_GCM,data:tpDFzGanSQE26ahg1gOHOrznRm60loP/muxQYp8WJqJ9+LgKFOFur4t5GB4=,iv:rRtoGWwXa6A39vK91Unhu1jLLd++EqIecQh37DNg6sU=,tag:SDKuaWqfJoubXpXnSsLCuA==,type:str]
  GF_DATABASE_NAME: ENC[AES256_GCM,data:Nll5WuNY6w==,iv:iCAqas2v5TzVRVu5Bii7xNro/63c+G9XdFkJwJFXz8s=,tag:tzltCRzGAm/C25vMBAJuJA==,type:str]
  GF_DATABASE_USER: ENC[AES256_GCM,data:V38eKZCMIg==,iv:2Q20U0XgrxRyXPiYAPL3q+rj+4rYWg1Ygdq7i5wOl6c=,tag:/8voT/4t0EHErkqSaF9HUA==,type:str]
  GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:fz/d08d4Nig=,iv:0AHTXM99BktLeZD33xeRbvdY8ZgXzV9n9pxbMLasUSk=,tag:Fj+4aHm6R+nUJcw97E3tiQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:xsUpC905GQ==,iv:baUenqtAkgpbHZQFkrreM+8XoZl06cpUemfIQxvR0AQ=,tag:VMopWBcgZBzS3GYapEAnHQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:kOHMeVGFOPHQKcmPCnsTT17mOs8s9QP7ysReg+ovY7KZE4ALec6tW/tQCqg=,iv:kGVgk2ytIoGoJzf7Ouk6tNHE64I8W+5Nby2sZqwbmLQ=,tag:bVXg2ch3eA4gGrJEHsTo/Q==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:NIqbOmbTsg==,iv:tbR7kJggRHCtn37A+jTRIfhZHG9j170eW7w03Jqr+nA=,tag:/BUhVAGL7TK2r31O3v9BCg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:SmUKRo4YqlM=,iv:MuVrhBzvGBAhQaIbBv/+3sUjgFOk/DruBemyIttPQDY=,tag:5KTBjPFR+UCo2WNgqgmAPg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:qZDgu3oYvOw=,iv:UKQw8oRD1zdHWljptJlmc1qISZEqFrBmuQeOPyQcLs0=,tag:e+gctwnLfOIklhJU3LcTtA==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWHRpNVQ3cFJOZkYwZFA3
        K0Jjc3dLWE9GZ2ovQ1hQRkJtWkRmMzJ4MVRRCkw0VXNwQmM0ZTI0VE5HdEQyaUR3
        UWp1bzcyeGZTa3Rzbk5WR0R5NWJzUW8KLS0tIEVQRnQvYjhKeUR3TTZ0SnFEbERW
        NjFwRTlZYks5aFRId3pMTkYyeWNGN2sK+dZuWWW88xH0aG108KV5V4nAWwz+PsMB
        bKUoVAaArVymcb0JZJs2/eB2NPEZ6DPLFC4RlR20nvM9TdUty2cv5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T00:26:58Z"
  mac: ENC[AES256_GCM,data:pa29EycutMNZIHK/usdGz1gfSNk4w+0Z0CPJ3qFWEtQVmPwpp+f09y/6HIUWWvcoOe/9z6IM4wGK0zq73D8jzagwo0qetERFw+Ig5y2uYHP62wx6yCWneFyfAon173Xx/deZ337iKBdslMwLYMvsVkfB5QIUIf1ySJaSHmwLyL0=,iv:codumA3WxWNDuiS1+9cUd9NjG27synFDDZi1ATGpLtE=,tag:RXH2A5Yp826uwCpLNP+oSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
