apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-secret
  namespace: observability
type: Opaque
stringData:
  GF_DATABASE_TYPE: ENC[AES256_GCM,data:pQ9Alfy64+c=,iv:eQz+QbP0PCrRRwzk5oCEpjQBIKPD5jDXeNIUznmson4=,tag:JE7MRuSAiCS7dK0s5XvQig==,type:str]
  GF_DATABASE_HOST: ENC[AES256_GCM,data:tpDFzGanSQE26ahg1gOHOrznRm60loP/muxQYp8WJqJ9+LgKFOFur4t5GB4=,iv:rRtoGWwXa6A39vK91Unhu1jLLd++EqIecQh37DNg6sU=,tag:SDKuaWqfJoubXpXnSsLCuA==,type:str]
  GF_DATABASE_NAME: ENC[AES256_GCM,data:Nll5WuNY6w==,iv:iCAqas2v5TzVRVu5Bii7xNro/63c+G9XdFkJwJFXz8s=,tag:tzltCRzGAm/C25vMBAJuJA==,type:str]
  GF_DATABASE_USER: ENC[AES256_GCM,data:V38eKZCMIg==,iv:2Q20U0XgrxRyXPiYAPL3q+rj+4rYWg1Ygdq7i5wOl6c=,tag:/8voT/4t0EHErkqSaF9HUA==,type:str]
  GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:fz/d08d4Nig=,iv:0AHTXM99BktLeZD33xeRbvdY8ZgXzV9n9pxbMLasUSk=,tag:Fj+4aHm6R+nUJcw97E3tiQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:xsUpC905GQ==,iv:baUenqtAkgpbHZQFkrreM+8XoZl06cpUemfIQxvR0AQ=,tag:VMopWBcgZBzS3GYapEAnHQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:kOHMeVGFOPHQKcmPCnsTT17mOs8s9QP7ysReg+ovY7KZE4ALec6tW/tQCqg=,iv:kGVgk2ytIoGoJzf7Ouk6tNHE64I8W+5Nby2sZqwbmLQ=,tag:bVXg2ch3eA4gGrJEHsTo/Q==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:NIqbOmbTsg==,iv:tbR7kJggRHCtn37A+jTRIfhZHG9j170eW7w03Jqr+nA=,tag:/BUhVAGL7TK2r31O3v9BCg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:SmUKRo4YqlM=,iv:MuVrhBzvGBAhQaIbBv/+3sUjgFOk/DruBemyIttPQDY=,tag:5KTBjPFR+UCo2WNgqgmAPg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:qZDgu3oYvOw=,iv:UKQw8oRD1zdHWljptJlmc1qISZEqFrBmuQeOPyQcLs0=,tag:e+gctwnLfOIklhJU3LcTtA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb0NZeXI5ZVE2UC9wMnRT
        alB1bkV1cnp0NEdWWmpKOHh4K0sxRHVkczBNCitkeUc1R0FoWnFHcmo1UEF0MG16
        Y2QwOGhZSnU0bVJnZ3ByY2o1alg5YVEKLS0tIEZZSGNQWHV0ZTZxeUZpdGM5Yjg5
        bGZFdnJyaVp6OWN5U2J1amxyRXEyTmsKhDm87tWThvoGKV6OgUvG12QkX3LLi1CH
        8IT9rGLaiB61spsbflE5NoQzOl5fhQfeumI/78WyoF1vko7aEq147Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDBIZ05kSk9l
        SlhBZFRNSmZ6ZjBHc2ZoYmVVbHg2dkZWbVU4SW4rNXFzZjBFQ3h4ajU1NnlEL0o4
        NHhNRUIxM0dLdHlSL2N0L3Y5U1dnOUlkNWROUEpoemJ0dy9FR2ZQY0xDQ2NxV0RY
        djB0SUZYcC9URTQ5UVh2RkRsamlJU0lnOWltYldXdDhidkdnZGJ4d2NNNFlKRDBX
        SVQ5UnJSRHN6dGpBTWc3WEZGZHE5SWoxYlVjSXlsY0QwRlJMTFNUNjdnQ0MrWWEr
        b0FnSHpFcUdvSEVGak1rVmVxemxkQkdib29aU2VueFhCYnVPcmtDQWU1LzlUdWJk
        cGJKeDNsblpYbkNEUE02d2hYZkl4c1g4RXdkUTVFVWtncDRheEFpUkNYR2pFWEhn
        VnM3UXhLNE4zKy9DUXN3Y1pWekt1SGhieDFLbS9xdUp3U3YrM2JqSkdjUkRNV0Zk
        VDFKSWtlUGZYcWJBZFRkbWk1Z1pPNDMvRCtOR1BpQlFGbUcvc1BoaDRrdlY5WTFV
        aEpKTTIwZE9xZU1FbEUxd0psVXgvaTB5N2JwMlgvVS9RWEMyNEFtQWVvN2dCWlp0
        YUp1ZzBkUm8xSEcvYlhuNmdJUDFJZTVKQU9VZzFFTm9lQTRmOGdjOHUybTdha25K
        czRnNlhLL2hFR0xvbnd2RkxmWVJSSFMxZHkyM29DN01WKzN3MXIrNUczQi9qWUJy
        NHRWTlQ3K1RnYmx0cjFGajAyMWt6cDNtVjN0a1JhRHVkSUtZeEpFV3JnVUg0WWdv
        NFlRbHBwQ0hHbkZKUzZZeWVUTU1hckRZbC8wVG9MLys1cEhUcFhmY2NFaTViRGFK
        K0lFOGFZOUVFb2hnT25DUVNTbnB2cVNpNFdvWlFyU3I2dGpjV1VtSmxOc0FaZTlH
        Smx2enFLM1o5dkFKalFwY2hmaDdiL2RjN0FBTlF0SVR1T2hDTURibDZrakZvSFEr
        aEU0eDNHSEhLSlVJRi9VTm1pTjU5clVhbEkxb0lWbzRqWE16TlBJNXFLZTNXVFFj
        RHFNU3c2ODIwMWtLaE1zRVhYVnJsT3FwcWhqTzdIbTdUT3FXVjRkZTNObmlLNUFr
        enFWQlNUQXNIdXU0enJneWh0SDB1SWFuU3FEcUo2d2dhSHQvczlZY09tTjZ4RU0z
        K0VoRjdTakhyTFZyR3JDbnpldGt3SC93MFd3RzNOUHU4TGlDR0ZNQW1WR3lvbU9M
        U3JYRWVWSE81cmd4cVUwd1cvTGdabFF4U1JmcmJHelBCOExxYnd1RG9wbUl2c0VZ
        Q2R6NHZ1cVVXdStFM0dUSWwvR2ZRMnlRRTh3Qi9sb2NHbngrbXh3ZHZaNDBsdmhJ
        dExSQlZSbjZVNGJmUURBVkpWYXUvRzYrcFRFSThsUnA1ZWxtbnpMWXcxRjZYRWFB
        Q3VMTVBTM3cySUtwUm5GU3BBUXluelBCTytUWWNmeWw1VTRPVTZkVkUyUjhoa2x3
        NVE0OXFyaDFKbjVkL2lOUnFQeWU4Y3dUU1hCZFRIWXplSE55YVhIL3hTTDhJallt
        dnhMblVCMm5UOTVTd3NpVElpMUxIZCtUTm1DZDlaQlRybCtUQW9GTWsrZ2d4OGlk
        WUc2UEo1a0RRMFBQaU9Vd0doeThFMWZKaFBGRmZYbEVqTm1NMHNJaW5US1QyODY5
        eGZMZUZvSnQraU5MTlBtSXJMaHFWRjlaSmxWZ1BwUG9QaWxvQkJ6NTBMN2NCOWg4
        S0NWYmhmbUxJV2hHamFhdlZ3bWdrbXFqanhuYnNRM3dWckFaQ0duQWc2eENGT29E
        NEt2bDlnUWxDc0UzQzdWYnFRSG54SUVpY0h2K0dQdytYV1FmN251VkJXOVZoWnRm
        TTNwRDlPY2hNS21jSENYRk0ydFR2TG43dklHeUlZMDRmQ3daZzRaSm5mTmdOc082
        bXI5dGsvWFEwaHhHWEcxMWFnc28zOStPVHl2ZEIwVTBVL3BQS0xTWlYwM3NIQQp2
        R3B0TU5qTk9JNEU1bWxuQnc0TUtrY29wUjVuTzZSVkNaK1pFTlpIUVEwCi0tLSBT
        TGloUmlRcitsMHlXTEZGQzB5NXN0dGpCOHZYRGIrenRBOVJHNTVveFp3CgRKdfwU
        duxwSY17ETcAH8/idHqxyYbK/aw4sk14FnFLnGa9jI/StZleUgBE4HVBlsRrhDon
        sJXEFZNafYqEgAg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-25T00:26:58Z"
  mac: ENC[AES256_GCM,data:pa29EycutMNZIHK/usdGz1gfSNk4w+0Z0CPJ3qFWEtQVmPwpp+f09y/6HIUWWvcoOe/9z6IM4wGK0zq73D8jzagwo0qetERFw+Ig5y2uYHP62wx6yCWneFyfAon173Xx/deZ337iKBdslMwLYMvsVkfB5QIUIf1ySJaSHmwLyL0=,iv:codumA3WxWNDuiS1+9cUd9NjG27synFDDZi1ATGpLtE=,tag:RXH2A5Yp826uwCpLNP+oSg==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
