apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-secret
    namespace: observability
type: Opaque
stringData:
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:pQ9Alfy64+c=,iv:eQz+QbP0PCrRRwzk5oCEpjQBIKPD5jDXeNIUznmson4=,tag:JE7MRuSAiCS7dK0s5XvQig==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:WvK7+l4JAIm5v4PsmXUjRbWAcnh2Y9UV5xYZ50Nlf9XdH0LaXWI2,iv:/DcuaUH2pxp9GBccfqazeFmbUdXGwPgEob3bCN5ATIQ=,tag:HIDSn5rGrneoP35hqJZOUQ==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:Nll5WuNY6w==,iv:iCAqas2v5TzVRVu5Bii7xNro/63c+G9XdFkJwJFXz8s=,tag:tzltCRzGAm/C25vMBAJuJA==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:V38eKZCMIg==,iv:2Q20U0XgrxRyXPiYAPL3q+rj+4rYWg1Ygdq7i5wOl6c=,tag:/8voT/4t0EHErkqSaF9HUA==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:fz/d08d4Nig=,iv:0AHTXM99BktLeZD33xeRbvdY8ZgXzV9n9pxbMLasUSk=,tag:Fj+4aHm6R+nUJcw97E3tiQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:xsUpC905GQ==,iv:baUenqtAkgpbHZQFkrreM+8XoZl06cpUemfIQxvR0AQ=,tag:VMopWBcgZBzS3GYapEAnHQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:zv7oUJ9kwPH5INn/2psiflsYGvzrbxCN3uo5rax4olQOJCD0SXMY,iv:aJwPBTrIHqRyZPp5Vz5IdL6lGfJdYLacUGJbuj5aVo4=,tag:5pVK6DzhfPWQUMRP5k6qJQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:NIqbOmbTsg==,iv:tbR7kJggRHCtn37A+jTRIfhZHG9j170eW7w03Jqr+nA=,tag:/BUhVAGL7TK2r31O3v9BCg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:SmUKRo4YqlM=,iv:MuVrhBzvGBAhQaIbBv/+3sUjgFOk/DruBemyIttPQDY=,tag:5KTBjPFR+UCo2WNgqgmAPg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:qZDgu3oYvOw=,iv:UKQw8oRD1zdHWljptJlmc1qISZEqFrBmuQeOPyQcLs0=,tag:e+gctwnLfOIklhJU3LcTtA==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWHRpNVQ3cFJOZkYwZFA3
            K0Jjc3dLWE9GZ2ovQ1hQRkJtWkRmMzJ4MVRRCkw0VXNwQmM0ZTI0VE5HdEQyaUR3
            UWp1bzcyeGZTa3Rzbk5WR0R5NWJzUW8KLS0tIEVQRnQvYjhKeUR3TTZ0SnFEbERW
            NjFwRTlZYks5aFRId3pMTkYyeWNGN2sK+dZuWWW88xH0aG108KV5V4nAWwz+PsMB
            bKUoVAaArVymcb0JZJs2/eB2NPEZ6DPLFC4RlR20nvM9TdUty2cv5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T19:17:10Z"
    mac: ENC[AES256_GCM,data:MydaDcBe1juIvV060KFBVfUjX7ZuyxBswl/V59iqTuKffnmncnTA+aS5T7cEmif7z1GPm3YOTfS75Z8ltv0Xj3J6Gssm9/9IdOeWgndgjk5Pa/r5VG56wYBhcDua2qKYBng2ZXCm1cvHP3YfdzGqf5jd1mDOhylS/ICZYpfwtBc=,iv:sLqpQbz8J0l9Lhi/N34xUaBjCsjRbj0PY+n7Md//6KA=,tag:48Jwvuw/G347Da094ZhAtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
