apiVersion: v1
kind: Secret
metadata:
  name: litellm-db
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:dvx4n1piRw==,iv:o1LXPlm+EjxYmgQvgH94jdPh3Ujn5KJXeqbWdSHYCvQ=,tag:if+zg4seBfrZCHQ2Rrv+0w==,type:str]
  password: ENC[AES256_GCM,data:JTktP34iHd/e1u8ekwXQcV/CqnEJq6MoXBUf8KbNWg==,iv:9U4MKbnpuSaGciPTm0TXhKahimQpVoIMHl31nt9ePzQ=,tag:/X7LIf+xyeGKcoonZNz50g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQVNRU0hZRHJMeDJqNnlw
        QkdWZEV6MUw5NVFpOGhsam9UMzV0R0tUSGprCkdzb0xPZXYrRFRXUEhOSGJiTHo5
        dXJZdnhDUEJ1RnF1WW0vcFBoWTBEejgKLS0tICtZcmtFQXcvMTZyck9oajFxTlFx
        VEJ3M0dreEJvdkZyUjdibXRsVUh2bncKqB+sbZp3X2XWsARtJ6E9+ifQLKFya/zO
        hvE4j/tzItH1+jCQ7oNJ2ZH9xUIvy8D1CRo/6tP5zYMjDxZzVFqVQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T13:39:40Z"
  mac: ENC[AES256_GCM,data:owlhOTERXB5ivkf+yYM4LppLylkI5arBkxopQhu2eoTsZP6YrdswFlIUap7ai4FM/86dwLYMQaLYq0P64WdmNINXVJEG77DTc/Gr/fq2e42L7TVXyJfdzXfa0yfVoRZMj+l7Tra4vvyyb91nTwDYJEH7vLnYyZrDbMvrpgs+rjw=,iv:vmrpTcBsWDv7sUDnFZa7X9s9+aOiFt2dV23PXkcjzJk=,tag:dssbxT49w8i7Qq7kA8UH/Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
