---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rook-ceph-cluster
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.19.3
    digest: sha256:4efadb7e27548cd81523ee9b38b0cdd231cfe6c86eb58c0dc7f80decd67b3759
  url: oci://ghcr.io/rook/rook-ceph-cluster
