apiVersion: v1
kind: Secret
metadata:
  name: opnsense-exporter-secret
  namespace: observability
type: Opaque
stringData:
  OPNSENSE_EXPORTER_OPS_API_KEY: ENC[AES256_GCM,data:RSZHDeodYJgWKL4kG56N7kPN+t2ic6LUlE+OxewN70sQvMFhz8C0zIPj13hS86MJ482nNZwEzQF6XM7pp5DxIzTnNTX2alyTheOMrLfmaUM=,iv:ok4yKiIWpA2zPbvN2MFQkYz8ednBJkcORzKRoUlh1HM=,tag:joVixt2oy2fE1zLTrIRn7g==,type:str]
  OPNSENSE_EXPORTER_OPS_API_SECRET: ENC[AES256_GCM,data:YqU4TP/zfxZI6TFkuwBw49D9FIfe/IKTvoRwQEqxm0n8ynrbZsz4qb+xl70m1y+f2NaCHa480jWMJ5cZ1kkLa2N/BnrYGzrD2QcBBq+OFc0=,iv:3FD7PBVQYEeQ6my/9I45DnIzLy/2+x32J3p0wVO7Da4=,tag:PR5Ql5WLXDq8ljZQ5OkAdA==,type:str]
  OPNSENSE_EXPORTER_OPS_API: ENC[AES256_GCM,data:IjQh9v4mvzFqiV4=,iv:mXnbx4TiGVrHnBGem6urLoPXR1rYd3BXa8Qw157B/G8=,tag:M3Se1YfD5elo0ODSN/O3JA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG13QXU5bjYy
        NDhlcnJKbDFWMFZPVVlQbmZKc0pPTmJXREM5YjNBemhxRHlFN2p1SUF6ZWFWbitY
        aEM2TjJjb0lvL2puVi94NXNVcUVqdUxiRkdwcHJ4WXhtWmV2dndlZ3JZTGlDWXRP
        cWZWOUhPbGVNelF1bW5pUnRCTDI3T3d0eExCQWRKS25jMUVEc0F2ZDI1Q2Z6eXhz
        VGdoUDdmOFl5R21VSllpUFNseG9IOVBoZlJETE5zbFdYT0d4T1dhSU9SRG5BYktK
        T0dxV2xzWFlJWlEvM3F4TUNJdWZLaEdDSkhrUXFIOTdwbjE2VmprSTdzYWI1YVB0
        NXBLZ3djSkVLNFA2bWNlZkQ5ekJPT1IrdFBIdkFzZDViMWQvQkIxOGJDY0JpQk1H
        ekVGK08wYnVEcDJFYzVybHZvR2tVODlTOWtqYnUyUnZ5NWoyRW1CT1AvV0dZRDNx
        aVBqMFEyN2dTSzA5bjVHby9UM0xkbHhhY3VHNEJXZTczTVMvUnpoc1JLcnJjdWUy
        dGY4NVFXRVJoN3A1cFJweHJRVmdsRnBDaStnMHJYUVJBWUx0WU54YkZjeHdudGRI
        djVaRHRnZE1jbllkQThQUTZROTNrL1pZS2UvWWFkZy9QVEhJc1N0Q2p1VGk0Vmh5
        amI3UFN6bU1QVW5ZWm9WblR3bEJSSUx3amdlWE5NU1pkSFoxbXdEY3loMThBSTgy
        ellNS2VNNlBWOFdORE1mMFVkd1Blelp2NjZmdGI3bUN1NXVGUGxwQXhWcWNGZDQw
        RGhWZ2RyTjFxU25MLzFBbFFKcVR6YkEreW1teFNmWmViVmd1SlN2dXV4em10Z2xS
        bXFYTFRVdm9nUiswNDhYWjF3TEVyQXpTTXdhQTZQcWd3MTFxVG5JWlpKSU1qM0xM
        M1FEK1hWNCtsSVBuMWhib1l5cmpvSkRIQzNLZ200cnBhZ3J0VW5GbkhoQ09IMk9G
        Y01rTExpWXY0TGhPbTRWdWpPa1FMMWFHRjlHOXdXN1RsRmJXbXIyUjZubHV1YTUw
        cWpMc295Y0I3citmR1oxaFlMSnk5ZDA5TUZBcjI4c3VsRXNOL0ZWVjBZRVNUUlYv
        ek5CK21XeUNGVStPeDluRjZGVTg5aWNzbk5qTlU0SVk5NzFUYlAzMkppNTBvU0Yx
        VVo1cjA5VEppcUFUdlhNL09IZ01FK1QwbTJTWGx2UkdHMk1vNzE4K1c3ZGhyRk1z
        ZnF2a2pDTW1VYlpxaGtSdC9MRWVxMjF3L1Vsb1NjcDBJT2t1VHBRT2R6Y0NuUjFT
        aDdQUXEwaS9MV2ZxQlFid3BIc2p6elRlbFI0My9SeHNvVDRkV2ljdnUyWXNrQks1
        Unh6bzJtbEtQdGZ6R01XWHdUZUFWdHVmSDdXcVAyUWJHOUliQW9DYU5yR1AyeDd3
        S2U2WFpLb0xsWnZrM3kxUU5CL0hFNU51WVJHS2k4ZHFXUURyVUoxUmNhS1YrNXpV
        aUFDdlJ1K1NGKzV0Z2hvQzBublBINnk5ck5PQlpEdW9UMXhKRHJLc09pK0FoSWVH
        ZjlrSkNGc3lvSzhGNXpGcFZBaVdJRmhOdlloR0lyNXpqaEVqUndDZ3Yvb1pNdnhN
        K080dFVVNi9DeU4yWXVVRVJpK2hpcG54T3Nsc2EvM2pKVFpNSW9yNnpCbWhxQjhY
        eW5CSFJ2czRHaUl5cGpxbExRbFltMWExNjhFdjNGMUduYTBycmU4Q3ExUjVnTTJJ
        U2ZoR0RJTnhYV1lERE84Nm9lamRmVkQ2MGM0Yi9XSEhvY2EzcUY5V0wrRWl1Y3ZJ
        WlRldllWc2paaDBURkYvMUV0Q0dDTVZBOE8wbHNzUTV2dnVSZVp0Mm5tdWJsYkxY
        Y3JuTzF3ZjNJM0htKzBVa042S0lSYW5MeHFKeUVieUV2UFNNNkJLWG5lY1dib0R0
        TVBtNEZzN2cyejRnRkFuKzJOTENkbEZZc3pjazkrY0lHU2RVUklSdFlGbzNOQQpq
        SVlVNjB5bzZOQ2JTRWZZendacmVGSDBIWnNOQUJPV2tGMFFzVnRsMHRBCi0tLSBQ
        ZW04ZHUrR2dXVGQ2UHJ4NXJaSDBuYTFHRjJ0enJUMFBuM2w4MDRwaXo0CrfvdhUw
        cm4+R8gEAuJXqzHL2KTDaBBAPCIf7ahyWQzJogC+daXz0b/hURi79J6SMRAwCHXI
        eRSBgSv0wko4UmI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-06-04T21:44:47Z"
  mac: ENC[AES256_GCM,data:0o2iSzkfHek2eZGg/UBpXGRqzRMEx0CVWQDSDs84b5+vU8CChqDvUXez8TTBrVTexgdbwYQeFb3lyCPfPcIUlzNJa2XVcSyHL2HynMgfZ0njSuJC9/mXiXbFDJ00Ug7hrtr5aGwPdxnY5LJcxBbNJNeIaJToYK0HysYPT0P8riY=,iv:lK2Yx0wMN4cmVPlD5X4mY4wBpo3UeYzy3stbhHn8RmA=,tag:jWCqS1lVKHj1RFJNvm8Xhw==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
