---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm
  namespace: ai
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 50Gi
