---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./embedder-recycle.yaml

configMapGenerator:
  - name: embedder-recycle-script
    files:
      - scripts/embedder-recycle.sh
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
generatorOptions:
  disableNameSuffixHash: true
