---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Namespace
      name: not-used
    patch: |
      - op: add
        path: /metadata/annotations/kopiur.home-operations.com~1privileged-movers
        value: "true"
