apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-envoy-bouncer-secret
type: Opaque
stringData:
  ENVOY_BOUNCER_BOUNCER_APIKEY: ENC[AES256_GCM,data:F65L/OaYV+B/gxSwMCZiJYSYjRPU3xk/OYqrcX6r9/8LBiR0WKQ4malNug==,iv:sf4+0n50d0+yj2cjjGwNZzoMTnqEGFFvOVwH67enrUQ=,tag:BrjLHSu8+koe5QOYu77WyA==,type:str]
  ENVOY_BOUNCER_WAF_APIKEY: ENC[AES256_GCM,data:WwRHu6g8Tu9mqZRfjwmxGLN3sFEhmlfcW9IEx6ROMIvV6v8aP79yQogZ+g==,iv:vQkziYq8l1Jm4znR2oHnGTmiwTC2qZA05NFolXpoMJY=,tag:lALNRQKA+rh7X16dBskulw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFBvSVNVYXU1
        WUZKN2djVnovMWxJRUlNaWU5WGlkOWdtWFhiaXhyb003clE3YlJOY3BKSTY0NU9j
        OUJreDRJVDlnMzNIU3hXdyt2bDdPV1RmTGgwdzE0dm9HRVlkUEZJRUdlSitrWlMy
        cW41MGFETG95dWFIdnphRE5ENm1vU3E5VDdjSkVMTzFwMDZjKy80cTdtUWRueXo0
        RXBNZkRFKy9FNG8rVlFEcityOGdOTWs5Uk1xNzVmVWwvTlpycEtNVFlMLzhNSlF1
        RjhmNERKRm9SRmRvUUNxNFJKRi9QdDA2cDZLL0RMdEhUMzhmdndaQ3JLZjJSd0Ri
        K2RXc1JxeDd1alV1d3RUMVNyTFR6ZGRVeC9uS2tETjVIdlRtVEk5MEQ3cVU4VE1s
        NHorZERPSVM2Q1BMRXprMWx3Ui9LZWwwT0IxaTVqRXRMK0YxYzRHRjdUM0k2NXJm
        V0lhSWVjUGRybWNvQ2E5aG5neUladjBmdVpzdGRSLy9LeUJPQ0p1cEZGL1RPaURF
        MVFlcjF3VkpJZzUwbzRyeVZzZW54YXVKSXdpTmJxQmUwKzY5ekNoYWlpTkw4Qm9G
        Q0k3RjAvd0VITHR3cEJ2T3Y4dVZvWXVnTzBDTXVBeVhNdzgvNS9LNUQ3ZGs5ZHdu
        bzNLWEhWSERsYkxZVWs4cC9Qci9rU2ErZUxwaWVjR3o0M0RSNTNYeTRVbWNWbVVx
        V2c0MnVpaE9SNWM4ZmZWWUN0K2trZ1RFalV5WWQ4ZmFvaTlSbFRFSTlTbmxGZ3cx
        c2NGN1ZsbGgvM2JReHdCdkFlcXhRa0xPVWZNdGZJMGoyaVRBYVZkRHpWajlYQ284
        alpkSWtCU0plSG5teDJlYnFnMC9lcE1SRUV0bThlalFhc3JpSlBVY1dUMzYxUkMx
        YTFmRVcvWmh6LzE2dmYySHo3cHFmSk5yUkQ1WllyWm1hMzBLQ2ppMlVFMHdlRXRW
        dTBqL0hrNGd3cXN5SDVuZi82MUJuTDA3QTJxNTFSSDhJNkFkRnMwQ3JuekJSaTk2
        TGdnMXUwbVFVRVpVdXhsVlQvSXgwczg4TGdkOFREUGVNUGVnaTNzeSt5SDJaUUg2
        NTVLeG1kRENENEVSd2NiYWZ3R1lPQndFUTIyZzBhMzE0NmdsTHVUN2owQ2JQbTNB
        WFFQWDdBYjRibHAvSjVaN0t3RXlNZXNyTTBnRUxwc1hXOFVOZkJ0USt3cnYySDFy
        aGxnYUd3NXhvdG43eWFBNFpQVmlGeSt0L21oanNEZk0zRURqQi83cFpzS2psRnJ0
        RGowNkZFcnBuMjFtQUxRU3ZGanNnRFl5M0l2N2cyYy9SRjI5cTQ3VnhDOUc3MG1n
        VnJIZnN5OHJtZXNhRURvcG5lTks4VkdWTW5nUUgrZXE5dXNRMDlwZ0NIWHZ3NEhL
        aVBFNjdmajBPSlpzZW5wMFBuYVVxd3NPb0NnV3p3am80VXNUcThrbm4yUHcrZkdr
        VzJIMVVtMzhsbHlkeWVxZkcrZXBsdGQ2ZlJtVXpmUFVzYTFwL1k4M1hBT3pQZ3NX
        bXhHY0c5L1NvSStIK0xCRmVhdVV5V0tlZkJISFFLdlJRT3JibjlpMVZPYUVxMEVq
        MEppYStCaEgweWl0a2t6OE01Z0VabWpLNkJrNFVlNi8zWWlNMDY4UFhHYnJUcm51
        UlRxNzFOeVpWYzhpbDEzRXRQUEVWWjhTeGQwTzBmaWY0a3BKbWsvaG5jWmNHcExI
        THJVZkg3NGRESE5WTVE1NDdaZFNVMkhMZExaUEd2c2YybE1iWTJYL2N3Uk13TGZw
        NmxrTTN3ekJ5N3FYVEgwYkgrK0hqaUdNamx5Y3pDRmVyNVdlSlJaVDdqMHcwYytV
        dzBrcHBXYWltZjF3S1F4SSswQkFPYTM4RFN4TS92b2tMd0xDWGhDV0wzbE5sbFlV
        b0ZLNGJEVEdvbmI0c1FXcXdMcTJORlo3YUcxUVRsTGpaakh0aC9lUDVVbUpVUQpK
        bHpKQnFwZDUvSmw1cm9MbUM1Z2l5WkhKSUsrOGNmMldEZ3JBb2ZvcXRjCi0tLSAx
        THp4RitFRk9NM2t4TEdsUWNKT2VhVHhyOVFGUWNvdmJqSkx4ZlI2UXRRCnvTcOMI
        IFAwfg+9dpOkNa1iNSLBq/RszEyFAzdsrF/zDb3+LvyyiM49XOAXj52X5dPcmWhr
        rZ7O2MnCIdgvjpQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-12-29T23:45:49Z"
  mac: ENC[AES256_GCM,data:zFouAGYHGLCY7P06QMfou4tsyZlJRPB68LLLs/yTEWTidz73qNo/ij1r2cR9LB3IUIMj6JhfhbhXUvutMdxb9J9GTFvdVTq9cxYyzkV9xOUKRjlzHOh44uJmrQH3cSXo+UJsmNyxTAgu/cY1gc9Pc0ZwJhnaKFsVDRVRMqPakvc=,iv:hdY457tlQq29zqj8MIhUZM/y8uNGawg0tKhzAKe5XoY=,tag:HrM6amdRDNv2j5CmtBnUTg==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
