apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-envoy-bouncer-secret
type: Opaque
stringData:
  ENVOY_BOUNCER_BOUNCER_APIKEY: ENC[AES256_GCM,data:F65L/OaYV+B/gxSwMCZiJYSYjRPU3xk/OYqrcX6r9/8LBiR0WKQ4malNug==,iv:sf4+0n50d0+yj2cjjGwNZzoMTnqEGFFvOVwH67enrUQ=,tag:BrjLHSu8+koe5QOYu77WyA==,type:str]
  ENVOY_BOUNCER_WAF_APIKEY: ENC[AES256_GCM,data:WwRHu6g8Tu9mqZRfjwmxGLN3sFEhmlfcW9IEx6ROMIvV6v8aP79yQogZ+g==,iv:vQkziYq8l1Jm4znR2oHnGTmiwTC2qZA05NFolXpoMJY=,tag:lALNRQKA+rh7X16dBskulw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcTRZM2FLTHZwMTRFWkh1
        L05ZSFVLc0xaTVZSaGpvczY1VGhuQVYrSUI4ClA0OVp0c0YzeklqMTlKOVE0Q0xP
        WGVHSHU0MFhvdW12cnE2YUhIeEhhbFEKLS0tIEMwOXg2bXlmQ1dtd2pMTHhEVzc4
        YUxrandxRVVOZlAwK2YxejVlMnBnQ2cK2a/nrj3ErOsbEkOGV5oaWdlB+2dT3mcW
        AKucs/OnYkACT54OsErsU9GZflUdXnRHikMgLabHluMMbONxjzKI+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHhOVStzVzAz
        YW84ZldpblJSNzAwQzg4TkV3VHo3NlArS0Z6YTZjaHhvbjhDL1lSM09vMGp3WUZF
        VXJvV25VNnFEWnVaQVpZN1N2cC9NS0gvZVo4d0tLY2JBTVluZ1p0T3JNSzlnUU9H
        dGxSenVOWnM3MGZtTnFqKzlieENObWhqQi9nVmtMSzdabDJDWjFBNnhjcmdRMHNC
        SFJQSGJSZ2RmM0tuQnRMdlViV0lMQzRPakJGdjNQV0NNang2L21URTFyQkUwaGhP
        UUdVWmpBazEvM1N2MEI0TC8yOVVTME5HNTg4VWY3ZFlKay9lSk84a3BaQnU0RHBj
        REZoSFBvMzhsMjZkYklWOUVOSllIcENMSUFabFNleXJubnlhYTVpeVU0WVVleTJs
        ZUc3ZGp0dlVnbWRkRUp0ZjdYbWtCRTJlSmlZQ2lJMFRxWk1XenV1Ri80T012bVgy
        MHo1T29aY09uVDhQeWlWekFwRThGWGI3ZFRLd0dWUUJqdjIwZ2EzdWFxR0JBaURJ
        cExDN0xvOEJPYmxQOUtYRlNkMEVGSlVmN1k3YVdJQXJoYWFhcmpXNTVIYlFzMk80
        dmhrNit3YTQ3ODA2eitHTy9YbUYrdWhQb0hBTDU2SUVTN3lyc0RydmJKOXRRa2Ni
        MGFlOXZxZFRWaDBjN3Qrd0ZJdVlnMS9MYUppdWZSL05iL3FPTXpXRVczR2wvQUt3
        MWx3TGdEaHFOY0lpbnEvTVZuME52WWVOKzIvSUZIUHNJMXJVRFg3TTlyVGxJR1BW
        SGF3WU53a0p0YkVHYWZHdlVBanB4TitCRFU3clJ0VkpMMnI1aHJqaEZKTlNMMW1H
        Rk5PSlNuSjJGWXJVS0cvcWZlbmNnNU9rTXprYmIwL083OXlmaUtXWEVValVaMGpN
        WTBYTHBEMkRHYkh6aXYwK1Zad0ZoaE5xcW5yc2xPQkRGTVJFdXE5UDZzZ0Zndyti
        YVJhL0M3anRucUJDb3dYSEFaYm0yS0sxZDlPZXhaKzZWSGo0TmJxeVVqaGlLYno4
        QUs4SlA2ZkNUaUZvSzU3ZGpYaXlKTmhJWHA1bitGci9lR1dEZThZMkx5elpobDBP
        S1B2OHJxMGZCMmNNVW9LOVI5OUVobjFDRzl0dTUxNzdzRzlXTmlQa0I5Qk03dk4x
        dXZIc21ScENUSnVYWGtLZTJkaGZkVmNPYi9Nb2U0Qk9mUllSNWl5TnZ4VFh3dWNs
        TGlibU4zblMyT2krd1RRaW9WOHZabGtFeG41KzRYZUttaUdWRUZEc3I5Q3crcXpY
        REZmRnNoNzQvdTJ3VExmMS9hTHFzTlZtSWQzOW5mcVh1L25VNFliMUQvSnZrUCtE
        QUg1dFUxbk14MURCOU1jRXpCeHo4bXU2Qm84c1hmSEtKd29TUzJrTDRkeVY4R29m
        RVowb09YQzE3WXEyKzhJRTV6akFubElRWUdEK1F0bkdGQjRmWW9hWWVoV1N2czFB
        TEtjVG5rUEk2QUZiak9QZkdCY1hyUURBU3kzM3drWEE0d01JeDNIdkFaMlVWYnZQ
        aHJlcm5HQVlCdlUwZU0rZEVJRENkOFNYTHNqb0lFcTloQktDeFl5KzczNGpzOUxw
        UUdDaFNwSDNoSVhhTzBONUxRek8wWU9tdU1rcFNwdloxMUZDSlFUZ0hyejFhdE1M
        NXJ5MkkyTE9TVWJTWGp6S0VJTCs2VXZvUXB5UFdzVEE5WDZIbDY1VzFjUVpMVVVE
        UVRxbXpVbEQzYTJYd3BCQU5TbmdZZDB6YU9rQkY2M0NNaGdVcXVDNzFpNlJibUdi
        eFo1c29LUzRGY3NuRUFRQzJHdTdCano2TU56czB3enJSa0FNQnQ1Nk1VV0dxeDlY
        MXZVK1UzOUtiZk13Y05zdHJ4aEk4Qm11NnhpTThiWElKMUc2eWVvMWhmYUlnMHpt
        eE10SHFlRU5OZ1RMZ25oNVhpTGIzUGw5clIyc1gzR3MvWHdCd3NCMmV6bmhKdwpL
        dHd1Ly92L1BYbEIrc3I1TDNzeDBWNmNvZ0ZBbWxBWnh0N1hBaWJGTklBCi0tLSBj
        aXZ3bHl5dnRWSVJxR3laa3oxOVpQODA0dXdYNzlZMVprN1AvN2VwN1ZRCm7rNb3Q
        wtAyQf8SEWDQXQfqIU3r8fxk2TxSsjwaNL1BdDkzv80ObGKgVtsGTbk5NEe1qvcF
        W0i3Mz0SB6qebiU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-12-29T23:45:49Z"
  mac: ENC[AES256_GCM,data:zFouAGYHGLCY7P06QMfou4tsyZlJRPB68LLLs/yTEWTidz73qNo/ij1r2cR9LB3IUIMj6JhfhbhXUvutMdxb9J9GTFvdVTq9cxYyzkV9xOUKRjlzHOh44uJmrQH3cSXo+UJsmNyxTAgu/cY1gc9Pc0ZwJhnaKFsVDRVRMqPakvc=,iv:hdY457tlQq29zqj8MIhUZM/y8uNGawg0tKhzAKe5XoY=,tag:HrM6amdRDNv2j5CmtBnUTg==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
