---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: crowdsec-secret
    template:
      data:
        CROWDSEC_LAPI_SECRET: "{{ .CROWDSEC_LAPI_SECRET }}"
        DB_HOST: postgres16-rw.database.svc.cluster.local
        DB_NAME: crowdsec
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DB_USERNAME: "{{ .DB_USERNAME }}"
        ENROLL_KEY: "{{ .ENROLL_KEY }}"
        REGISTRATION_TOKEN: "{{ .REGISTRATION_TOKEN }}"
  dataFrom:
    - extract:
        key: crowdsec
    - extract:
        key: pushover
