---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: crowdsec
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.20.1
    digest: sha256:473941a39bc3f1b93d8cbf656358af2001361ca29b6f85979e2aea314806956b
  url: oci://ghcr.io/home-operations/charts-mirror/crowdsec
