apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-secret
type: Opaque
stringData:
  CROWDSEC_LAPI_SECRET: ENC[AES256_GCM,data:70mKl2m7EjI=,iv:rAohj/ZJO9F7wDyFTREvTQUpTZNWYvZ+9lCSGQH9bn8=,tag:tCAy367Eh00t6M3JDY6/0w==,type:str]
  DB_HOST: ENC[AES256_GCM,data:M15yqrCTR8vfFob7behCKbnKSGXAIsSqL7Pc9ocZssL+eALE3eO9,iv:6iy3yHZ8LcqfzpJ4NX1h9k5tPjvKlwJp7QIFTSwY+9Y=,tag:azZ9qMXKxrWDfHkrBAT1+w==,type:str]
  DB_NAME: ENC[AES256_GCM,data:5LfKrxipeBo=,iv:G52WKrJ4zP//fwT0QdxrtQsQAYuSKtqZ5LAC10SHbko=,tag:qEcmriLVbIxFZIFeZu05wg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:brHp81V5DmU=,iv:llLG3LxrU09JKdmoTFqAsZML6ARTYTKGSciOFWbrd3w=,tag:++CeWJcVRmpluq+eH9xhOQ==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:wjsVLqvXv7s=,iv:w2dYwJbTc++TCgDgKp4BWoXpZxN2w54u0uuI2JwEm0U=,tag:/ZhZUH1+oRdjKRR9ujV6rg==,type:str]
  ENROLL_KEY: ENC[AES256_GCM,data:/YFpBlcGaYS6+NusQm1P3X0SfvvLkBOcYg==,iv:DIs7LojdehrDcHY5m7DMi+vY/tUwCfvvGmdV1B16qQo=,tag:W2ALBKhU21S3d9cqmcR3qg==,type:str]
  REGISTRATION_TOKEN: ENC[AES256_GCM,data:5bTsLRWlMbB4AJZUZtQzMyi9dFcRCdfewA==,iv:oVZGmGwGViOLe0I5MQvH7RwooyLhsAcOxGMnQRIJojo=,tag:p8SceYxgoQXYnkIaMst08g==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:LwX87KH1PQ4=,iv:h7T2lXKA/Wvhvsxxpc62NS4GKVHRJ9ya/4FbJhjJKGU=,tag:99H7Bf4B1ik4ceJecrHvnw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+oCeY4xeqNsjRwTbItIIeYRFuG7YHMtYHd5NW9SHnldh6tsXc5JY,iv:Wj6gwpkZceLKUiJx94vzOO4nI78FUPxNr+oNDdRwaE0=,tag:6VowqYUxTjt5hP3iR44pDw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZzPbK9B0dog=,iv:BXiE21vlqv2T1KRFHKZvrxTq86rN638wAvMPMadamO0=,tag:BMtOxcoH98T28SN8fZA93Q==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dczgoq/WYHc=,iv:0CZ7kGkYSVdls0YS7s2uN/JI/yOVjjJ8n3EO7jeRuqg=,tag:s9SL25XjMZ3g0n2bKMXRXQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:iTFxPIa4Gh0=,iv:pGYI0BH/7gGDr0cOO318nG8BQOFqKOBplb1dnFWNV1c=,tag:aFQW7uCnVCtfZw0GYUYRWw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHppTTByWVVt
        aHJ3MkxTZnA2L0srYSt2UGVCem5HTk5MZEtuOGxrKzNhS2x2MGE4QkxPbEpTNWpJ
        NTNOTE9TT0txeFZyNUZ5NkZGYU1IUkQ4VEhvYUc4UXJITlFvRXBhRDZSU29hZ2du
        RG9ZOHd2empVZXRPT0V4L1ljanFFUHJTTG1tQjdZMVkvOXpXZDl5aXJlRlkzRFlE
        QXp4ZlRaZlo5RDBlWENuTmw0L0hBaXl4UkdraXlJWUlraERaejB1VHp0OUxyOFc1
        SHN5OTNOSERVNmNyclRJajBnVGxLYUxveGhrVEhVV1liSTZlVWNqd3FPSUFReHhO
        QXRvbjZ4OGx1WHZwMitScEtaNmkyN1U2TzZkbDFkamhXWlVKV3R1RkFsMzJtbC9p
        c1VhTDFtTVdoOGtqbWZKZHNITnExdkVSdEhUZjlXMmFudXBhRWtLS2NnbDhSSitr
        eDZtUks0ZVUxZXZSZVNVZ00vN0JneXhOUGFoTDlnRDUxTStaek52d2dUL005ajFi
        a0VLbTU3ekRMNjJKcWc1N1Y3SlR2RGNOU28wWE5YREpQWnVITjQxWmxvS28zckpP
        Zmlac3MrTGNOSUY0a0djTjNpUWFZc2F3YkVNYXZJdGtLMkhDdFhJYXY5SFNPcStY
        d2pnZzVaVjJGNDRUMTU3WStORXZRMjNQdGdJSjNIZ242UmxSU3VSR2lpUUlDK1Ar
        RG80c3lYV015YVNxMWRrdkNCNGdPTWJtRnNXUlBaWG1PQUNXVzAxVmdqRUE4SUhW
        VUdhdnA5ZVBndzljMmxMWk91dFJQeGdLemR3OWZGN2NXNEh0YnRZWkpiQ09wQzk3
        T1NEeXRwMktTSE4wR3BjaEJrZEg3cE1uWmtHUkNtOVJNVGNURnpwMzM4UDJ0N3lU
        YmRHdDJpMVZCWUhIYWJ4WTZ3VlZEUnMwYVMwSWpJQWZybk5DSHY1dDF4ajQzNVFG
        RjFPRHlVTk1NdWluUHNZVS9iVFZmL25zMXVYNi9rYnFQaFJ3bDk1bjloM1B3dFNH
        UXdUaC9sOHpGRXJ5RURIRzRzZVFRTUdIUXpuMGhyQ0xHUDlwWGlQcTFYUkdmbXR1
        L1JlZ09JRUJzT1NEMHZ2MXhIWC9MSHJBYng5Qm1qQXBLb3BqY0xNbjZUMWpSU2Yy
        TDFhYVBsUG9nY3JPS1ZBWFo3RmJZOWFhTnEwMURYbDhaMDcydHNnUWw2V1JDZ200
        RkxWai90Q2ZFSHh1UTd6cUlRSk5DeHdNbU1IY2l5RW5iaWRuOUVwQ09DUm5LT21Q
        T3I0QS8rUE1wdmFqNUJ6Ky9jSk9TaDRVTFZWdDJ1dVd4SzNqd0Y3MjFuVjFoZlhm
        SW9XcXUrMDlnOGFBWXNocnBHY243YXI4R2pyMHlQZHNaOWlSRWRhVzZQUzBtNnA5
        N29pRWhObTdIb05pTjBNMFRhVXEvTHh1bWI3RWZVYTBSY1ExbXNURUtvblJ4SzI1
        N3ZybmUrZVUzc3VoYktrOFpYVTVqQjRvanpzcnVKRng5eHU0YS9qbEFVcUZ2TXBm
        dk9pVGxxbTlVQ2oxeG1FRTQwWVFkNDFEbVpsdWNCbmlyN0Roem1IcjhQbUw1cDZv
        bnZTSzl4YVdFbjRtRzYvZG1xMG9QLzlCZFNJeEYzVEY1SE5YYVExRFJ3Q25jdFJV
        Znh4Um9IK0YyNDQ0RldNMWVlT1BDSjlPb0ZPWFlMdzJlQmNYYVF4YlJDM0ZZMVN4
        TlRHTmVwTmJlTlpBQVBRVVZwQ3RiRUFicDZGUTZZRmtvbGhCMXd5S2xyOUxSTjJZ
        Ym9ESzFsVTRHSWwvWjJSeEF6K0ZscXRRWFNjRFFJby9FY2xQcmo1QllRNG85TzIy
        SVN2Qnc3Y3JOZjlKcXBKK0JjM2x4UDJ3WnU1bWh0czNMSXdRdWs4dkh0cDVyYVZR
        M3JIVTlncXJXdGF6dWJMank3Vy96c1FTa0ZyUEI2VG1jcGdEalJQVTZ5cUZDUQpS
        OXBCSFJrVWx6MUxYZHlMQkt2c2RrRWQ3QWxxTTVFUDNvVFR5M3lKdjlrCi0tLSA2
        RHlhdDJSVk1BTUh4Mm9naXNDQVcyS3lOcW8zMFY1ZlpIc3NmT3Bnd0s0Ck7IfxQk
        uXhjx5SbeVOpQ62yFWrsHNuLBl+FLZEmKW/j+LM0Pm4EmDjeNlkujtdb/VBv410T
        oGuohdi6xhSjNFk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-21T19:15:12Z"
  mac: ENC[AES256_GCM,data:PQiL4mvVeSRXYgvsHcrCTtSgIIjT3IAGPmuH8+YUCfrOWGLxOrNdTNL9rnZ1tNhczxvdq+NZhVPcAtJ7QhXn19BFut4Uf0519imc1GfKDiDIE5SGg7X85NE0bn9riqTKQE/+87xNrHsA0CNccur+5XFfF36LgOuPiPkfRSsNBrQ=,iv:MfOm27N6blS0KOy0ayAZgkSRbSaMfRnG005jRKvDwa0=,tag:2XiakZJ/mkEeLgByyYpWQA==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
