apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-secret
type: Opaque
stringData:
  CROWDSEC_LAPI_SECRET: ENC[AES256_GCM,data:70mKl2m7EjI=,iv:rAohj/ZJO9F7wDyFTREvTQUpTZNWYvZ+9lCSGQH9bn8=,tag:tCAy367Eh00t6M3JDY6/0w==,type:str]
  DB_HOST: ENC[AES256_GCM,data:M15yqrCTR8vfFob7behCKbnKSGXAIsSqL7Pc9ocZssL+eALE3eO9,iv:6iy3yHZ8LcqfzpJ4NX1h9k5tPjvKlwJp7QIFTSwY+9Y=,tag:azZ9qMXKxrWDfHkrBAT1+w==,type:str]
  DB_NAME: ENC[AES256_GCM,data:5LfKrxipeBo=,iv:G52WKrJ4zP//fwT0QdxrtQsQAYuSKtqZ5LAC10SHbko=,tag:qEcmriLVbIxFZIFeZu05wg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:brHp81V5DmU=,iv:llLG3LxrU09JKdmoTFqAsZML6ARTYTKGSciOFWbrd3w=,tag:++CeWJcVRmpluq+eH9xhOQ==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:wjsVLqvXv7s=,iv:w2dYwJbTc++TCgDgKp4BWoXpZxN2w54u0uuI2JwEm0U=,tag:/ZhZUH1+oRdjKRR9ujV6rg==,type:str]
  ENROLL_KEY: ENC[AES256_GCM,data:/YFpBlcGaYS6+NusQm1P3X0SfvvLkBOcYg==,iv:DIs7LojdehrDcHY5m7DMi+vY/tUwCfvvGmdV1B16qQo=,tag:W2ALBKhU21S3d9cqmcR3qg==,type:str]
  REGISTRATION_TOKEN: ENC[AES256_GCM,data:5bTsLRWlMbB4AJZUZtQzMyi9dFcRCdfewA==,iv:oVZGmGwGViOLe0I5MQvH7RwooyLhsAcOxGMnQRIJojo=,tag:p8SceYxgoQXYnkIaMst08g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZlBSNVVSMFJXZG5wNXFH
        Zi82YUdod2hJektDaUw3MlVrVjlsaDM1MkNFCjlRTjZNSHFDb3pJSUhWZTRNRHU3
        MHBCdmNJYnVZakJzSlVocDdRS1ZEWkkKLS0tIHZqaWp0NGU3NnhqVlREWjY5L09Z
        MkFESG5DSmIyK0RBcTArT0VPYnlNamcKKbki53ao3rSxFuqgaiv227gj+j/O0Td9
        XsMT0vre6B0GdzVd0BFWGy1QNunDFaJ9QZigf+p7X+zjswmjKOIKzg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T23:10:35Z"
  mac: ENC[AES256_GCM,data:/KeAmnPxL2RuhbXTLoaP4eDo9XA8o9PuS42z56J2ssRSQb5hVhIx67PAm5nAiNvmQH/vaisAI/q7FTzg8yDPhU2QBKJfDZ1fMOtKJaF4/E0VvSUvJWSX4iBjSMobVEHTY2EaoSPT0dmBzkA4qFF4+742pK+P+QT1xgjPKXTUZBI=,iv:IIgXznQAlJ7omYN/yN/4kgj4pd6Qafl0Pr89lq8iEgA=,tag:Y3bmkV2c7+IXrob67IWl+Q==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
