apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-secret
type: Opaque
stringData:
    CROWDSEC_LAPI_SECRET: ENC[AES256_GCM,data:70mKl2m7EjI=,iv:rAohj/ZJO9F7wDyFTREvTQUpTZNWYvZ+9lCSGQH9bn8=,tag:tCAy367Eh00t6M3JDY6/0w==,type:str]
    DB_HOST: ENC[AES256_GCM,data:M15yqrCTR8vfFob7behCKbnKSGXAIsSqL7Pc9ocZssL+eALE3eO9,iv:6iy3yHZ8LcqfzpJ4NX1h9k5tPjvKlwJp7QIFTSwY+9Y=,tag:azZ9qMXKxrWDfHkrBAT1+w==,type:str]
    DB_NAME: ENC[AES256_GCM,data:5LfKrxipeBo=,iv:G52WKrJ4zP//fwT0QdxrtQsQAYuSKtqZ5LAC10SHbko=,tag:qEcmriLVbIxFZIFeZu05wg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:brHp81V5DmU=,iv:llLG3LxrU09JKdmoTFqAsZML6ARTYTKGSciOFWbrd3w=,tag:++CeWJcVRmpluq+eH9xhOQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:wjsVLqvXv7s=,iv:w2dYwJbTc++TCgDgKp4BWoXpZxN2w54u0uuI2JwEm0U=,tag:/ZhZUH1+oRdjKRR9ujV6rg==,type:str]
    ENROLL_KEY: ENC[AES256_GCM,data:/YFpBlcGaYS6+NusQm1P3X0SfvvLkBOcYg==,iv:DIs7LojdehrDcHY5m7DMi+vY/tUwCfvvGmdV1B16qQo=,tag:W2ALBKhU21S3d9cqmcR3qg==,type:str]
    REGISTRATION_TOKEN: ENC[AES256_GCM,data:5bTsLRWlMbB4AJZUZtQzMyi9dFcRCdfewA==,iv:oVZGmGwGViOLe0I5MQvH7RwooyLhsAcOxGMnQRIJojo=,tag:p8SceYxgoQXYnkIaMst08g==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:LwX87KH1PQ4=,iv:h7T2lXKA/Wvhvsxxpc62NS4GKVHRJ9ya/4FbJhjJKGU=,tag:99H7Bf4B1ik4ceJecrHvnw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+oCeY4xeqNsjRwTbItIIeYRFuG7YHMtYHd5NW9SHnldh6tsXc5JY,iv:Wj6gwpkZceLKUiJx94vzOO4nI78FUPxNr+oNDdRwaE0=,tag:6VowqYUxTjt5hP3iR44pDw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZzPbK9B0dog=,iv:BXiE21vlqv2T1KRFHKZvrxTq86rN638wAvMPMadamO0=,tag:BMtOxcoH98T28SN8fZA93Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dczgoq/WYHc=,iv:0CZ7kGkYSVdls0YS7s2uN/JI/yOVjjJ8n3EO7jeRuqg=,tag:s9SL25XjMZ3g0n2bKMXRXQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:iTFxPIa4Gh0=,iv:pGYI0BH/7gGDr0cOO318nG8BQOFqKOBplb1dnFWNV1c=,tag:aFQW7uCnVCtfZw0GYUYRWw==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZlBSNVVSMFJXZG5wNXFH
            Zi82YUdod2hJektDaUw3MlVrVjlsaDM1MkNFCjlRTjZNSHFDb3pJSUhWZTRNRHU3
            MHBCdmNJYnVZakJzSlVocDdRS1ZEWkkKLS0tIHZqaWp0NGU3NnhqVlREWjY5L09Z
            MkFESG5DSmIyK0RBcTArT0VPYnlNamcKKbki53ao3rSxFuqgaiv227gj+j/O0Td9
            XsMT0vre6B0GdzVd0BFWGy1QNunDFaJ9QZigf+p7X+zjswmjKOIKzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T19:15:12Z"
    mac: ENC[AES256_GCM,data:PQiL4mvVeSRXYgvsHcrCTtSgIIjT3IAGPmuH8+YUCfrOWGLxOrNdTNL9rnZ1tNhczxvdq+NZhVPcAtJ7QhXn19BFut4Uf0519imc1GfKDiDIE5SGg7X85NE0bn9riqTKQE/+87xNrHsA0CNccur+5XFfF36LgOuPiPkfRSsNBrQ=,iv:MfOm27N6blS0KOy0ayAZgkSRbSaMfRnG005jRKvDwa0=,tag:2XiakZJ/mkEeLgByyYpWQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
