---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 83.0.2
    digest: sha256:165bc2a7ba9e1cf1c5fdff2cf162416444efa89fe4074070246bf42ab57b0391
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
