apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-exporter-secret
  namespace: observability
type: Opaque
stringData:
  NEXTCLOUD_AUTH_TOKEN: ENC[AES256_GCM,data:fYrbOPf8sAfM8yC8aNFvB7/dfFPMfblfnZ1QH4SNKaDmjBtXU0lU5e6V9e2Sdke0mPE7iLYhoYuXnEJQCBWxqA==,iv:bQbroZGfFgvfQj5peNNc3GFS2t08ZmOZgOLCgnP6gHI=,tag:TQZcos5gyynv9zhvDtBe4g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTDdSSmJtSWdIYkR4L0hE
        TjBiYVFNZElJTEdVRkVlOGVSeE1ZNUNMNDBrCjFycitZczRJVkxTdWpYZE1FWFBV
        eXlwUVJqZW8wNEpyL0M0SHQ2RTUySFUKLS0tIFpnY3dCMDBLeXpic2dZbkN0SVBD
        eVFHOTRianFTa1J5RjRhS0JQa1RNVEUKlnu+ULu5LF+pPawZsJSKT4MTRTZTbMGu
        rvy+osh8lihiebuabSLkBdQOxCwvEGLZRUqh4CSou9RhHD962EBTxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHg0eWxtZE1W
        UXRwajJyd1VRN2FTQkd1cnpLbjdCMk10eU5tdFR3TkE4OElGOXZQeWsvcXZGbTJB
        UCs4SHNNRlFWZkxndGNLV1RJMW5nNWpjNnd6YWFzNUtGUEh1M2pLSVhWZkRmeHNk
        akZMR3YxdXNKL3A0c0NlNTBoZFRHZDlUT2N3Y3BjS2IwQUJNUFpCcytZYjlZRG9h
        UFo3ZWtMOS8wWmN3TCtmQlRwQlNSNVh5cWJ1S0J4VXMvdnNEQlkxOFBEQlUzUmdl
        QkViMCtxd3BHUCtDZk9Cb0E5R293VXc3bDhUU1ZnVTFHVEYyNGFnVExwSUFDRjRB
        YmFyUGdUY1lBT2JHQU1jamtHR3BrQ1NsNk1qMzViMEVZR3JQSlc0MTJwVkZ3WjBN
        NEZCOWtETmZvWEtGNWJreUx0UHBKaHJEYmFQdjBUanZuQUp6N2txMTFITmVvb2x3
        c3VhTVV6SWNhVUdFbWJleGN1aXRxWE9xbnI1Mk9xNDdxOTVMOVZvVzVjbUF5WHFy
        L1NnVFRPRFlHWHV0NkJldFBIZVRYRG8wbGcvME1reTZOekk2UDBGWFM1M25GVWZt
        bGxsMGxlYU1TeVpaVzZIT0VPYllCblV6L3I2aFdlSlBZaXB3NXVjamV0Qkt0QVFD
        dkgvOGVjWkJoanFESElYRG1VZHpHZ0tPZWVVMk5hMXVwQ0E0d2wrODlQNHkvQWlS
        clFSakRMNUpCNkhwdUdlWFhRUG5pWVA0cmdGd0VuRnByWXR4UVErWDhrd3JrakRT
        bE53RkVDRWtYeTMxamJqdkZaMnZGUmNKekVUQmFqa1IyWnVYQzVoQ2FPTTFoVDh2
        UFNBNnhnMHV4UEc3MGlwWTJIMitGK0JiQlMrRkFjQjc3ekZTVU8yNUVROVFPUVl6
        T0huaUFFbk1BU2hpb21nWHdTaG1KMmk1SktnN0pkdHZsSHVUaEVYeEdOUjNLeFl6
        UUVhRFROZzlIK3VrdWVCZUszNjFGcTlIR21CM3Iza042WitCZTlIRG1JM2RDOTRK
        cjFaUS9Ra1RURFhUekNjaTFsYy93UkQ3QVFYalRTdlh5YkpUWVR5L0xJcDJiL0Fp
        YjBaazduS0V2RjdaN20ra1lUZGZMdURaQ2t4MWJQdTVweUl0SE43Z1ppVGJzaTNk
        YURHMkFoZXVvSmdVa1FNV0hGZGZWTGJNN1E1MjJ4aUxJK2Fyc2trSjJLV2VsVXRR
        bXNGSy8wV0lsZTl3VGZhTjRnYlFqNlBZbnl5REJJckpUMWpVY0F2bk96MkZ3bDdD
        ZE82S1kyTWdyY0FKSUZpTk5sUzJDL1o4MHFZWjYrRytBaFk4ck56cUNsRnR4UnRz
        WFZpZXlXUk50cWJ5WXd2dWhXcVJtOUlvYmpHZmU3VTF1RFVNMWZJSFplSlRpMldI
        SEc0citkSnRaSm12YytQSkRVWHlpeWU2VklWdVo3NHpsaDl6ZUIzTDZkOGxxZTMx
        dFNjWi85dDdKeEVINUtIN2trYnREbGlweEMrZmYxOVozZ0RFdDVrbGg3QXc1dHV3
        Z010djkvTmdlcDc4N3BRSGJta3RoOE9qR29SckhwZWl5WHZtNnVHcVJJLzdQZ2hM
        eWNNcDMrNFBVa2tWM2g1QTZRNmRFNVQxUmR5WVh2dmJyN2pBYkErVUxncE1MNExR
        K0ZWcjRSdmUvNlRmTWo2eXFJSk1mMEZRcm9Vd01MMDU4Tk5qd0dYRXFmQVlRSUk3
        NmM2VjkxQ1E1Tlkydmw1U1pIYlRoYzl0RlpPTjZuRkEyVGl0eElHU1c3Yi94YVRz
        MG9WK1RvOFRZRi9EWXh4NHAwNVNHVHRwTGdTRjVQRitkbHlFRTJVRHROU240M3VV
        RDl6VkRRV3BnVnNoeXVoWW01U3lOdnpsaEVOdjljbnZEc3dWREdBS1NQZlp1Q2pv
        dUw0c2RBT0JQN3d6cWdxeGxKT2hXZGw3NnliU2Vjdk1tY1NVTUtWMU0zTFdaUQpM
        Y3FpTktoY3BVL093aHRQd1Vjay9zaEZTMk1qZC9XVHF0VmgxdnptRFBzCi0tLSBI
        alNFajNKZkw4b0JBNXl6U29KQVJzelhoaXcybnp6QXV0eDJ4RVd6SVRjCkCsMNYI
        Ct97e95zpLHSh7VMg84hUWjlDLimCdS5aZy+XDu4apKu3/ADrMKTJK9JCUykRmju
        WrsH4lPq60dd41s=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-02T11:23:48Z"
  mac: ENC[AES256_GCM,data:G9bIXnU2yh2cvKqEWYmz/42i3/OZ5fNuckd1mljeSdSkeq3gSF5VokZq44NiY4bjObHLXWwT45/ScRhLv/NyMA4XUYW7071ivQhId82WmfFnD1g8GqO/hflt9PsWvOApK5dnkK6mC8Nlxku6ZyigHYRqbXEFALuhGLmjFqHCu/U=,iv:CXpraCsLU6o6Nc8Cy1c4jqrlwUNLMlr03xXeoXLvMiw=,tag:9FDXSxX6UfVDiX5MoFk2EA==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
