apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-exporter-secret
  namespace: observability
type: Opaque
stringData:
  NEXTCLOUD_AUTH_TOKEN: ENC[AES256_GCM,data:fYrbOPf8sAfM8yC8aNFvB7/dfFPMfblfnZ1QH4SNKaDmjBtXU0lU5e6V9e2Sdke0mPE7iLYhoYuXnEJQCBWxqA==,iv:bQbroZGfFgvfQj5peNNc3GFS2t08ZmOZgOLCgnP6gHI=,tag:TQZcos5gyynv9zhvDtBe4g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHpQL2NvcWVH
        cW4xZ3RBSDVOUEUrRVowRmNvdFhTeFAzaE8vSkV6MjZPWUgwdTF2NW9WaUo2TDJB
        TS9NeksxYnYvZytTVDQ2aENVRGU5L1llZW9ORmFseHdFcFQ4ci9qZW15NjUwTjFO
        M3I1SXQ2RWpFYk5GM2w0eVpIVnEvWlhRMlFla1h5ZWRCcGlqc1ZJWDRtRnFoSk9K
        b21oaXBxNFZINlA4YjJxWWkwS1ZxZVJ0dXljd292MXlUWnlBTlFIVEovRm1OZWtV
        ajg3MXNxVW1hTExoMnhteEtHcHp1YXo5c0lBbklFdW9abEVQeURJM0xXTEpIUzdF
        L0gzc0l1M2NEc1dQODFObjRrWmtENkk5TDdjQk9tQkkzb2hNMnNUd0tUNi9VWjdR
        ZXByanU5aFR3bnlHL3NreWIxUFExaGlDUnNVRG9pbWZaSkxpV1NXazRNU1Z4UW41
        VmpSQ3RYd2hXR1UvRmxkd2Irb1EvTXp1dktmMWJkeGRQVG9zejI5NnVkSXhLeENR
        SHZ4YlE3ckRORXVRTURtNTRITU5Wc1JhbW95TnZvN0t1QWNTSGwyNmc2Y05zTHk4
        ZC9UMEp4M1NkK2Z4RnpzTE1PZHBrMTNWOHlubmdXK1IwR0lROE5mWTVHWHpDLzZ4
        VzI3REdHajhZTlZXaXZ0Vms5bnJUWFhOdHdzSXRrcGZtY2Z6N24rejI2cEl4L0Ru
        SUpXR0tiVlRDMDBTdnFsd1YyMm5jRlNsbEluc2N5R0o0Z1VSWTBjckpjR2lGNHRm
        SDlvTnlUYlFVY21FeThmM3gwbjdoMGt5UEZ5bjNnSGoxSXNOS202N1VXcEx0OWlj
        R2YvMGliTFRtdk9LT0VnZTJwcG5NRzV3NGxiVUVaZUdUZjdTa1cxMElIc1oxR2Qy
        ckpEOEJIQjYzWDZHOE9ndDFyQ3dxOFVOcmttb3hNclQxdStMLzlqbDV1WUZpdFhn
        cDIwKzVWVDZWMlE4SDhNQWJGdzl0UWlySFlSdENnVTJXN2c3Tkc3bDM1Nkp1Z1dp
        dlhaa1pTc3FFOWhCcVlRZmpHMGJsUjE5RkoxTHNvQ1pCTlJBT2pqWFgzVlNjNlZJ
        MVhqY0pRVXJwMWhXSDRDUEZYN1dUbmhEd2lqNElQdGt5Nm8yamN1Nnc2RmNHSWFm
        UUxuTXJNMXgxRnJsSngwVzQyUy9idUxhdS9QTWVFckNTM2dvcXVKWkRrMUo1R2Yz
        OXBpOUpQMEhyazF6NW5EL09RZy83ZjgxQyt2aWtPeld5WmVSV2hsUjQzR21QcWdw
        MzFwWkdKUWdNMjgrV200NHpOQzk2dEFpMzh2UC9IVjIyZDFRcCtoK2NESkxGR25y
        ejQxVEJxNFVzdTRqS2JJVE8zRUJXN2tLeWxpZndaSWxnV29HRVdtNit5ZjJlYlVK
        QVFEUmtCK1RqUmpveE1EUEF3YUszYWc0ckFNLzJ2L3p5a3J0N1VmRitaZ1B5TlFB
        TjN6aVJhT1ZZdWhCVU11SWVJTlNtS0o3V1FRcWlHcEFHU1ZtVUtXNjdUVTdoVEZx
        M0MzWWloUjVNWjZxKy9kTEc4alhUeVJyckFqMENLRUJwZi9yUENJV2tlaVRxQnFo
        d3FmWVo5WTFmM2RJS0xCdUlDbEVld1U2ZytHbm5tS2hYT3RtTGZZa0NFRElscEZ6
        NlBiUmZRcXJCTUhaakdKRnRaSWI2UytPL2lKbzUyMVV2ZjljYzRYSDJKY3RqMXV6
        UEtRUFBzWGppNGpZWHp5VWFlQTRHRE1meTU3RFZCbThqL001b2pZVXc2cHZFNVRs
        SXdqRTdVSVF3bVFpZWFsemtyTlpuQS9JekhFZHdXM0lFY09ucEFXVENIa1VFN0kz
        QjFjZnpyMFZVdnZRNnpVM0FrUVowNHl4TXBabWdxVnNQN2YzMWtxd3dOVTJKa0wy
        VXB4SitMd2thZ0RXelhUVU85WkMzUHJjbDhZRTRPQUkxR2w4d3psbFpGU0hCQQpy
        a1NzMHE2MmltZFhkMGJKRk5rVEorOU1XMURYWks1VzVTd1FJN29wQjdzCi0tLSBG
        azdGRmZyMjFRM2lBaTNYeDB1VHFsK00yVGFOZUtmNkNBa3FhT1VYanlVCuyw4S+F
        j6k4ZZpaY3HF1hK9McF4Rhv8KnrWgkg9tV//UVOCio5AhhjRAzuOXfRyM8D5wKf2
        XifZ4rn43bIw51Q=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-02T11:23:48Z"
  mac: ENC[AES256_GCM,data:G9bIXnU2yh2cvKqEWYmz/42i3/OZ5fNuckd1mljeSdSkeq3gSF5VokZq44NiY4bjObHLXWwT45/ScRhLv/NyMA4XUYW7071ivQhId82WmfFnD1g8GqO/hflt9PsWvOApK5dnkK6mC8Nlxku6ZyigHYRqbXEFALuhGLmjFqHCu/U=,iv:CXpraCsLU6o6Nc8Cy1c4jqrlwUNLMlr03xXeoXLvMiw=,tag:9FDXSxX6UfVDiX5MoFk2EA==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
