---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: k8s-gateway
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - network
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-gateway
