---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gpu.rules
spec:
  groups:
    - name: drm-exporter
      rules:
        - alert: HighGpuUsage
          expr: |
            max by (node) (drm_engine_utilization_ratio{engine="gfx"}) > 0.85
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "High GPU usage on node {{ $labels.node }} for 15 minutes"
            description: "GPU usage on node {{ $labels.node }} has been above 85% for over 15 minutes"
