---
apiVersion: v1
kind: ConfigMap
metadata:
  name: affinity-control-1
data:
  values.yaml: |
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - control-1
