---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llama-embeddings
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: llama-embeddings
      app.kubernetes.io/instance: llama-embeddings
  endpoints:
    - port: http
      path: /metrics
      params:
        model:
          - qwen3-embedding
      relabelings:
        - sourceLabels: [__param_model]
          targetLabel: model
      scrapeTimeout: 10s
