apiVersion: v1
kind: Secret
metadata:
    name: kguardian-db-credentials
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:9KYHq2Ud2EYrrLBHKwwnzYMy9XQqhYD9e+aZ4dseYOgCNbEcvhyd94fDVEJ+Xoh9liIeSBNX/FhjXtSgfrdfTQ==,iv:Xe2wek+8qdD0x51BZkUf8ai0GZ0S+wD1B6yQIrRa8uc=,tag:DZ9e7VX8jowr0Goo1MWisQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDErNnA4MDdN
            WVh4ZUYwZDQyb2tJWWVFc3lMS1lSVzhyMlM0Tm1FNlREZFM3V2tNbEczSWVOczZi
            U1ZoSG0xd3hTNTdSTWdDVmhuK0hYRmZFRThPK3JyckEwVC96cHlURkMzZkhCSkFO
            dGZRblE0SWVpQzR1Z3lFbTJSRlZxQXgrdzhQYlcwTEhHZTFPL0RXWEhMMFlod0pv
            dnQ3VHFKN3hMSTRYS0N3UEZ4Q1VocFNIK0FVNk0rMDNWd1h6dWkyQmc2eHZTOU9l
            U253aEJySEdUTUppYW9SMUJMTlJQdDBNcEU4S2FaR28yU0VSUVJ0bTJWYUZZVEFJ
            UFZyK1MvWkxnbEdQdmZBOG85WDQ3bDBUbjRDV1UvakNBNXhweFNIbDJNYVJiYU9a
            UmtwK0JMeWtBZTh3L1doSDJYNHFKSmw3cldTMkVQeUMxOUtuRyttbGlqRkhIay90
            U1FaM0M3TnhHQjVHY1FiRVBIUXN4c2d5ejV5bnlTek82bXlmaWJQWjdHbE03Uy95
            c1h4aUtmSHFQaVJUVEZtL1F6WnFvY3QxUnRaRUFJOUZrVVNyV2ZrMDVMMHpVZEZ5
            aXcvd3NBVVVUU0gzcFlYWW52Z3BlRkp1djJBTnN0RnRMUktpQXphWjE0ZytINFNK
            UW51aTM3ZDdwU2pHTEJJYW1QRHE1WEJDV2NjbGUxQUZWM3ZvcERmc2NIZDlGQnhD
            U1NUL1lzRzdNWkNLY3l3NGNvWlEydzhadWRKajY1elIzRXptMnowczVndjFVZ0RD
            Tm9ENjduclQxaDVVUlNIbUZQVUtyVVd4cEdud3FLa0dLQis1U2xHWjR5WjBiODBt
            MlhOT1g4bWwvTE4yd2NFMzVpRkJFMEhOKzgrZ0NqOFFac3NKY3RYOC9pV2JBN0pj
            MTc3RHg2R3oyWnoyRHRFMVQ1SUwvYXk1K3luaXd6TzZlSi9mYTc0eDdKRmozRUVt
            cHZxekdkV1UrYW42QUFUU0dMQlUzYVhHQTRDcGlXVmxiWjQ5RWNoVU9JTTRCMTVw
            bFdiNDVEbkcwZXNOYTNzdmpjb21GNW5DOTZyeXdXUXd3VWxhNHhVNHB2ZHU2Zno3
            TDM1b0ZycTBwcXBLYVBPQ0hRamxJV3QzZE5zVFhvVjhhbk9iZS9Vd1pGL1JNWE9S
            THhCbmpoRll0eC9MRG91L09QSHhqUXpkTVBxZ3BoVWNVNG5IcDUxTU5SdFRqTk8z
            bFpENVFpRHE2NGRLTDNiR3A2OUkrd2JhNzJzRTEwSEhSb25RamtBeU96ZFlsMlRW
            WTRHMWJHSCs3MEFEc21HMzlDS1QxUWlzQ2JzMHJjd0NSTWFaSDRrNzYzd2VFL3d3
            eUNOTWRBMlRKSmJGb0lXRnRuNUI1SmxXYy9EMjFMWHM4bVZyaFhkKytvSDBsazlj
            dmtmNHdhQVhodGFqOTZwaWJtbSs1NjBUcmxtUTV2SGtjZ0ZtdmdOaXVycWhsUlQz
            cU9IVU11Q1c5c2ViSEluL0VNWmJqWjYzQmR2TzhZVGVSSVE4aFBBMExuZ0NoY204
            ZWwyM2w1Zk1rNFhKYjV0RVl1eVR3cU1aY1k1V2tEV3ZKaDk2b0I4TFcvZHE0NWs2
            Z2xGdDJpWHNOdkpZN21HaXdkeW1kblBoSUpMNzdmeDE1d21iU3FKNzRqWlY5c1RN
            SjhNK05Vb0tJTDV0ZFRsMmlVaDhuWk5BMHpjSzhROWdiNXhocWtXdXREMUFkOHRJ
            aGtXbmI5cllqTFRQNlNiYk5NeE9YNWV1VXJhRkc3U2lNZVVEQTVJL2ZNT0toQXVK
            UDNlZTNVMFdIOThXTnFhMFc5clVsbkplb3F2K1J6dkRFQzAwQlVkb3AvNThLWCth
            dzloQkFFa01qK2dHZVRQaG45cUxxMGFhSHMyL0lvVkEvbjlVTTNsSGZIVzZFNFRL
            amZ0SDNhSkNqbXBmUGdzWVd5cDFhNDZ1YjgweXFpa3Ntam5pV29RVXB1MmxHUQpk
            d1lrdjJVa3BRR00zTVdLTHN4cEFaZ1JQVU1DRjFLdlRpcUF6WmVnTWRJCi0tLSBl
            alZVbzU0cWZtWjZ0dXRlQjNWMnhDZ1Z4bStnRlpwY1RTK1F0TUo1UjJ3CoMqetIk
            LiwE3yWP8LwV/Tkf78GDNHc4ZVuuL4Y7F/iWKmaQGpFCjaMJM7fa8H4d7MkuR+W4
            QNF0nvU7iF+ktU4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T20:40:56Z"
    mac: ENC[AES256_GCM,data:24IyHAC1P8mZhGvg0dgxpama5At0OMgDAITfBniLZvAEUSJtykKD2VbBAW/HtQ3kkzTLlv/RUtgM4FkJKttDLg7cu0UdQD5SBWMFEDEiEp4kOktq0MaIk8VXR3eFAChf+PmN0g3QwT5JGhc6HD2av1HBXFGQ9DDPoC6LRFUWW4o=,iv:NAQZHukTAcEq8OfWfCcVtOkHTJXF/mcfB9nq4gKycJg=,tag:Rx3k3W22LiMFqUiwOBQdFg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: kguardian-mcp-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:1BdFmkJYwHwKKqDnpFEZi318HHX2y/FIvEKjdnOTCPv7cVb9qG+LqUZtE7480oHh6nVk+nIux8Jn/vohipf+xQ==,iv:vSgg0lnUKvYfQDLP8m80erU8kvhe9cQCAjS1GsxY9Ug=,tag:zkzGdrpiWNxUwFDvjn5RBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDErNnA4MDdN
            WVh4ZUYwZDQyb2tJWWVFc3lMS1lSVzhyMlM0Tm1FNlREZFM3V2tNbEczSWVOczZi
            U1ZoSG0xd3hTNTdSTWdDVmhuK0hYRmZFRThPK3JyckEwVC96cHlURkMzZkhCSkFO
            dGZRblE0SWVpQzR1Z3lFbTJSRlZxQXgrdzhQYlcwTEhHZTFPL0RXWEhMMFlod0pv
            dnQ3VHFKN3hMSTRYS0N3UEZ4Q1VocFNIK0FVNk0rMDNWd1h6dWkyQmc2eHZTOU9l
            U253aEJySEdUTUppYW9SMUJMTlJQdDBNcEU4S2FaR28yU0VSUVJ0bTJWYUZZVEFJ
            UFZyK1MvWkxnbEdQdmZBOG85WDQ3bDBUbjRDV1UvakNBNXhweFNIbDJNYVJiYU9a
            UmtwK0JMeWtBZTh3L1doSDJYNHFKSmw3cldTMkVQeUMxOUtuRyttbGlqRkhIay90
            U1FaM0M3TnhHQjVHY1FiRVBIUXN4c2d5ejV5bnlTek82bXlmaWJQWjdHbE03Uy95
            c1h4aUtmSHFQaVJUVEZtL1F6WnFvY3QxUnRaRUFJOUZrVVNyV2ZrMDVMMHpVZEZ5
            aXcvd3NBVVVUU0gzcFlYWW52Z3BlRkp1djJBTnN0RnRMUktpQXphWjE0ZytINFNK
            UW51aTM3ZDdwU2pHTEJJYW1QRHE1WEJDV2NjbGUxQUZWM3ZvcERmc2NIZDlGQnhD
            U1NUL1lzRzdNWkNLY3l3NGNvWlEydzhadWRKajY1elIzRXptMnowczVndjFVZ0RD
            Tm9ENjduclQxaDVVUlNIbUZQVUtyVVd4cEdud3FLa0dLQis1U2xHWjR5WjBiODBt
            MlhOT1g4bWwvTE4yd2NFMzVpRkJFMEhOKzgrZ0NqOFFac3NKY3RYOC9pV2JBN0pj
            MTc3RHg2R3oyWnoyRHRFMVQ1SUwvYXk1K3luaXd6TzZlSi9mYTc0eDdKRmozRUVt
            cHZxekdkV1UrYW42QUFUU0dMQlUzYVhHQTRDcGlXVmxiWjQ5RWNoVU9JTTRCMTVw
            bFdiNDVEbkcwZXNOYTNzdmpjb21GNW5DOTZyeXdXUXd3VWxhNHhVNHB2ZHU2Zno3
            TDM1b0ZycTBwcXBLYVBPQ0hRamxJV3QzZE5zVFhvVjhhbk9iZS9Vd1pGL1JNWE9S
            THhCbmpoRll0eC9MRG91L09QSHhqUXpkTVBxZ3BoVWNVNG5IcDUxTU5SdFRqTk8z
            bFpENVFpRHE2NGRLTDNiR3A2OUkrd2JhNzJzRTEwSEhSb25RamtBeU96ZFlsMlRW
            WTRHMWJHSCs3MEFEc21HMzlDS1QxUWlzQ2JzMHJjd0NSTWFaSDRrNzYzd2VFL3d3
            eUNOTWRBMlRKSmJGb0lXRnRuNUI1SmxXYy9EMjFMWHM4bVZyaFhkKytvSDBsazlj
            dmtmNHdhQVhodGFqOTZwaWJtbSs1NjBUcmxtUTV2SGtjZ0ZtdmdOaXVycWhsUlQz
            cU9IVU11Q1c5c2ViSEluL0VNWmJqWjYzQmR2TzhZVGVSSVE4aFBBMExuZ0NoY204
            ZWwyM2w1Zk1rNFhKYjV0RVl1eVR3cU1aY1k1V2tEV3ZKaDk2b0I4TFcvZHE0NWs2
            Z2xGdDJpWHNOdkpZN21HaXdkeW1kblBoSUpMNzdmeDE1d21iU3FKNzRqWlY5c1RN
            SjhNK05Vb0tJTDV0ZFRsMmlVaDhuWk5BMHpjSzhROWdiNXhocWtXdXREMUFkOHRJ
            aGtXbmI5cllqTFRQNlNiYk5NeE9YNWV1VXJhRkc3U2lNZVVEQTVJL2ZNT0toQXVK
            UDNlZTNVMFdIOThXTnFhMFc5clVsbkplb3F2K1J6dkRFQzAwQlVkb3AvNThLWCth
            dzloQkFFa01qK2dHZVRQaG45cUxxMGFhSHMyL0lvVkEvbjlVTTNsSGZIVzZFNFRL
            amZ0SDNhSkNqbXBmUGdzWVd5cDFhNDZ1YjgweXFpa3Ntam5pV29RVXB1MmxHUQpk
            d1lrdjJVa3BRR00zTVdLTHN4cEFaZ1JQVU1DRjFLdlRpcUF6WmVnTWRJCi0tLSBl
            alZVbzU0cWZtWjZ0dXRlQjNWMnhDZ1Z4bStnRlpwY1RTK1F0TUo1UjJ3CoMqetIk
            LiwE3yWP8LwV/Tkf78GDNHc4ZVuuL4Y7F/iWKmaQGpFCjaMJM7fa8H4d7MkuR+W4
            QNF0nvU7iF+ktU4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T20:40:56Z"
    mac: ENC[AES256_GCM,data:24IyHAC1P8mZhGvg0dgxpama5At0OMgDAITfBniLZvAEUSJtykKD2VbBAW/HtQ3kkzTLlv/RUtgM4FkJKttDLg7cu0UdQD5SBWMFEDEiEp4kOktq0MaIk8VXR3eFAChf+PmN0g3QwT5JGhc6HD2av1HBXFGQ9DDPoC6LRFUWW4o=,iv:NAQZHukTAcEq8OfWfCcVtOkHTJXF/mcfB9nq4gKycJg=,tag:Rx3k3W22LiMFqUiwOBQdFg==,type:str]
    version: 3.13.3
