# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - context7.yaml
  - flux-operator.yaml
  - flux-schema.yaml
  - ghostfolio.yaml
  - github.yaml
  - grafana.yaml
  - homeassistant.yaml
  - karakeep.yaml
  - kguardian.yaml
  - konflate.yaml
  - kubesearch.yaml
  - mcpgroups.yaml
  - memini.yaml
  - searxng.yaml
  - talos-mcp.yaml
  - truenas.yaml
  - victorialogs-mcp.yaml
  - virtualmcpservers.yaml
