---
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: shared-dgpu
spec:
  devices:
    requests:
      - name: gpu
        exactly:
          deviceClassName: gpu.amd.com
          allocationMode: ExactCount
          count: 1
          selectors:
            - cel:
                expression: device.attributes["gpu.amd.com"].type == "amdgpu"
