apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
type: Opaque
stringData:
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:+1epyD4tFJvMkl6vJmS1JdmUgGUH6D9LD4aBkvf9iCfRcpZS9cQPJgwnj88LlJofNl2zOBqEax2PzhAsaVYkwuBLeA==,iv:XdOvxKbWHP5fR1JJsPiFUvUtMFjMRF5SpDiWNLe8oOQ=,tag:BKcG04+O5SZQD3BhwxRpiA==,type:str]
  LITELLM_SALT_KEY: ENC[AES256_GCM,data:Jtr4DzHFLeTVQXn6z2q3zwyHq6tAPpwN1LeBcoBVRHtHInz6/VKbHY9U/s+m+fMYdPEoOm7PhlA2jD9Y4vuwLuVVsg==,iv:ZinaPN9u1DdJuj+gOiHfneydiWoOq6uUM6VptNUBwZY=,tag:euFxDzJYMyJHZZ8FJbLeEg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:leCAwkGv6ul9GLtDShO7oNCBaf6rQfQF1hVarnQYoWc8BenSeLohcwum1h82vSpfNIP6owuI3BQ59Z+c/wFjrUHjGTNSzO0b/kB9r+6pxF18B0khj7FN70X+azNhfRwCnpx0fTaiWQ==,iv:nufpZqeu76if0JCvUP1p34twOasJglAOvCPbT9d/z0E=,tag:lcHLzND3OpHJkZ6GeER2JA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHdxa3VMNlM5
        aERTVDlEaVB2Z2lTZjF2SUNoNUFjamNZRHV5K3lQcDY3bm54VHB0QXc5SkZZL2l3
        R05yWnRkcnA2cTR3dU84TkRKbVh5K2FzRHcvbHc3cWtOWFBLTGxvcjN0RkszQmxr
        QkdMVm1VQmtXZEJDczd5dENVME1wcTZIcHRXdUVQRUx1U2pmVU9XR2g2eWlEc1M3
        cndVL3pDbEd6VStwSFhybUR4MFhYVE13dTNWRWVQajA5UEpCdlF3ZWE4L0w0RUIz
        cmowbmxYRTh1NDNheHc4Z25SakQvSzhVSFZSR0gvYUZQakgrdGpDRlUxS01lMTlm
        WmVKeXl1STlhVWVZMWd3eWZnMEp6bStqT1hGTGVZK3lBQnd6bkJ1Z3VPWHo3eFBT
        eHR4OElGekJlUjF3NXVwTGRJRW5PUXlyeHlpYWxqdlFwbWlDYlNDQTlxcmdBQXJY
        R0VuT29Pb1h1bmZuNmtUUjZ5d2MwbjYrbnpoNDhFVmRZYzAyMnljWTM0Vm94UUxO
        ZElVcGZqRUxTOUFveXFqVTVVWS9tUGFmS1hsUURPSjNObzVZMVlKY09Ccjh1cjNU
        ck1PeTBjRjZ0R1k0R01QVlVKQ1dmRnlEOWp4VHE3SUVGOGtaM01uU01SQ2YveFJ1
        dkNvNm0rZjFtUmR6VHBXNHc3Q3hGc3Fqa0I2ckFiUjJIUlk1WURteXNzMXVISERm
        R2dDZnpjdjlaU09FQjNqVk81MGt1TktSTkNWQmVZOUh0MmdwV3J4azFwRUxMVU9C
        UDU1QXk0bXhtcXpicTZUcDhqcm0zQjhVVWFid3JLQWJHQXIvZTlFRHB4TnAwSEt2
        eFFQUjI2L0NhN1RaRHN1bFFsZHBFM0JJdXNIdUJRRTYwYXI2WU96dDBZQ3hPblNo
        dXBYaXRUS2VJNDc5eHdEMzNWV05ZditmM05oNUNheTRsb1hkOENVZFVsZWd1ZUMz
        S0N5dCt2NmxiVmdCR085UExVTzgzaGlZc3lvMTFzZGJtd1VDSXExSk9Jbk9RZ3NS
        bkZVZ1dnTkxRRTlCUDdGcHl1ZnV4V0x1bkpYRVdic3ZHL1piUUhhb0VVekt6SzNO
        WXBaMEx5bXprZzlaWEJWUWd3UkE4a0tuaCs3VHJmSEdoUmt2ZTVRYVd4QUd4ZUtH
        aGJzTnpCdHlWSkxKS0tVV3ZTb0Ntek4vcURxdE1pU0tBSG9jNVNsbGdWblJiV01j
        SjhPSUdRbE4vUnFBK21hVUtRVjdKZGtRazVCQTFDVStyR243a3BwM3lhTlRWeXIr
        Wm9Ka0kvWkpQNnU5ZGVKWGNCZ2Q1d1JCVXJVdFNHTmExOC9rTEhjYk55RS9VcS8x
        UXVaSkh0clBQM295dnovTksxSXhualExcUhJK1dUZFJUOXQwUktPS1FvNndxb255
        T2NudkhDQjl6S2I1OXl2TGpvbkVnd3JNd3pueEFHVVhsTjRHbStlbGd6MUZZWlkz
        YmE3N1pKSnh5RXN6NHY2WDFRVEJoYjk5dmlZMTltYlRRZGYzVU5HOGFuNUp1MjZO
        b2swU2t5TUVlczUxeTdpYWpPSDg5eElYcDQvU28ybWVTRVcrMG1ScjhOV0l4eDhJ
        akFDYWl4T0pVdmpZaUc2Z3FrQmozYVFPZllBcFpvZ0VNTTEzcDRHcHlDNW9kZERi
        eTZGeFFiTnI5TnNsYWhDQno3RlNGSU5MaS9ocTBNV1RiL2hQSFJOV3plbUV2eDhC
        OTExOEsvUW5GZFVuTGUxR3o0VVF3QjlDdnNUVVpGTyt4dllkVzVTdENYWjNMeFNL
        eGJKMWdmbXlqWWg1WnQrazVjQ0RWZ2o5WVk5am9GOHRNS3NEL01OUkcwaVJKUVdN
        dWZUZW8wemZtRW9kTmNnQUR4MURBSjJKQ0dHTjRKTEQ3aHRtbGQ1d0Vla2xHYWdL
        QktickZqOXBFdHdPUHRrZENHSDVoSHlKVHZHYndKUkdRSkF2T3ZIT1BwajJGZwpU
        VkEzWUo2TGVpYkl6WklORVc2RFAxOTcvMy9UOXFYTFA1dExUZVJEWm9BCi0tLSBL
        OUVpS2laRmF4Q3BGeEdQTDd0c3RleWhZNk9McVFpOXd6R1pCQllDSkQ0CgMlM8vv
        2FCqd10+h8eVyXjubkvfZu53ywVQUpXxcZDZg17m7rmj7IVaEVHSg/tPgTlF01HF
        ivg0a/b9HIJErQU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T13:39:40Z"
  mac: ENC[AES256_GCM,data:UDnFIPu1u439Kd5S2Ip4atULmh6+ZiQ6HzGAjYLgUQJGzPxcquSq5NJlqjpoPQJ6GPn+SJhCqK3Zl12UwG/Byk1OwLqXjpAe/3U29BxPJ3qeI2AUUvpBFCHIz31NrS2xZ9OnQCT+iRSU8SPDz4y4Is1ignI3Ipe0uFiPzdk7maI=,iv:7KhNasfIzt7PRT5ab3Y4Gki7Z8jZmO9OpTlw1OtuP3I=,tag:sCNIcavIrxWb9RUOHw2HWw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
