apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
type: Opaque
stringData:
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:+1epyD4tFJvMkl6vJmS1JdmUgGUH6D9LD4aBkvf9iCfRcpZS9cQPJgwnj88LlJofNl2zOBqEax2PzhAsaVYkwuBLeA==,iv:XdOvxKbWHP5fR1JJsPiFUvUtMFjMRF5SpDiWNLe8oOQ=,tag:BKcG04+O5SZQD3BhwxRpiA==,type:str]
  LITELLM_SALT_KEY: ENC[AES256_GCM,data:Jtr4DzHFLeTVQXn6z2q3zwyHq6tAPpwN1LeBcoBVRHtHInz6/VKbHY9U/s+m+fMYdPEoOm7PhlA2jD9Y4vuwLuVVsg==,iv:ZinaPN9u1DdJuj+gOiHfneydiWoOq6uUM6VptNUBwZY=,tag:euFxDzJYMyJHZZ8FJbLeEg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:td7uFqKV6eWij3b4SnzvvrZAGnpbRc+e85sdyUoGl0cIBFqkN1omUN6EcCgL9yMUGKRH5F6tzayF8EDA/wGMfsrNXZMfqPHNr+MkjFxGbyQ=,iv:Qkgty80n0J681VkNFNhiE2hcNVthotZhlu3fHLE63FM=,tag:x1v6bsvKKzkTPkos6xheUA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWkRNZGRya1VaNFdYUjN3
        ZllHMnZSWldURnpqVXR2UDcyRWYwaEY0RkFZCmhrN0Z1OFROekpQS09TbWZyQVBE
        VDFHN3E3NVdGZGUzSHdPSHhNSHVKMlkKLS0tIE96Uk9DdTZYMk1rS3JRTmhjQWhX
        cHJrVFlSa1p6OStWS3ZrTXlqRlF2b1UKouEhn0yUaZUJUVkIm44s2t+0LbzA96rd
        4wuSb9feXVlqJziz4pkzWg4oezm2KiwDviYfhyBnMcWuKCT6lkcZog==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T21:01:31Z"
  mac: ENC[AES256_GCM,data:bCQQB0v1iZsaFWeAqohe6oLfaPS9JSlvMPA3uTxOe16ojahW71zkQGvHdm4eXYZGKzw40Jo1cuiIwDR/zaXoVQUz8D1d7yI3zpJeTdFEi4M6deM73XisS4fd60EqCFpMNeR9XLKERUBnauf1pyb3DUQxMCVpQCtk7VMxBCK+Mk4=,iv:AHWd9hwpwE1ycJCd9bNwGhWWIw9q54LlVqG5MKmGbOo=,tag:09xd+XAi8hNbAizY1Fmdww==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
