apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
type: Opaque
stringData:
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:+1epyD4tFJvMkl6vJmS1JdmUgGUH6D9LD4aBkvf9iCfRcpZS9cQPJgwnj88LlJofNl2zOBqEax2PzhAsaVYkwuBLeA==,iv:XdOvxKbWHP5fR1JJsPiFUvUtMFjMRF5SpDiWNLe8oOQ=,tag:BKcG04+O5SZQD3BhwxRpiA==,type:str]
  LITELLM_SALT_KEY: ENC[AES256_GCM,data:Jtr4DzHFLeTVQXn6z2q3zwyHq6tAPpwN1LeBcoBVRHtHInz6/VKbHY9U/s+m+fMYdPEoOm7PhlA2jD9Y4vuwLuVVsg==,iv:ZinaPN9u1DdJuj+gOiHfneydiWoOq6uUM6VptNUBwZY=,tag:euFxDzJYMyJHZZ8FJbLeEg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:leCAwkGv6ul9GLtDShO7oNCBaf6rQfQF1hVarnQYoWc8BenSeLohcwum1h82vSpfNIP6owuI3BQ59Z+c/wFjrUHjGTNSzO0b/kB9r+6pxF18B0khj7FN70X+azNhfRwCnpx0fTaiWQ==,iv:nufpZqeu76if0JCvUP1p34twOasJglAOvCPbT9d/z0E=,tag:lcHLzND3OpHJkZ6GeER2JA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMDR6R2MzdmluY1NZUi9a
        QVZYZkVMMm9ZUnA1N3FEcVdDeHFRejNOT2hnClFxTGdrTjZoQXNCdU1DWUNYTW03
        NS9oL0hIUWRkU09JQ1h6a2lMSFp1bUUKLS0tIDFqY0hlV0xDc3YzTnROZ25aRVRL
        UzV4eWYwWTRnUWJLVm9BWmYzL3lTdlUKy8YGb6WPCagt0FFZmula5vCaI+NWN5Nc
        BfEuOqtKPhiqpBOlee5z3nlyQaJDn55hNaVtTrt4EgARB+MxfpowZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDk3NHNwcEtM
        ZjNzeWpjWnNLMGNycGVjSVd5amZOSGRsTWFOUHRUTktXUWZKNjNIUXlLdURtd0dt
        Qjh0SXNROTZ6dlJvd29aNTMrK3VhRDZrZGpPMFFSSENLQzAyaFo4VHhlNjRQbUNW
        bitsWVRXYk9peFl0azEzWWV1QnBVWnVsNEwxUlExMVhJVm54RnprZjNYNFV3NTFr
        dDJ5eUlLVmxzbmZYZHZzUTZpUi96OU01SCtMb1Z1K3BwMm5JT1pFMlRpZXRPaEs0
        ZytLQ2QwZXJMMXhuVEs5NzNDK0NDcU84Qi9laGtNOUdjdENENTdrTUx4anBCc0xm
        VzQ2RWlJZkFyYktpR0E4OENYSGs3NnhKSkU4RTljZzBrYWlHakFzc1NxeXBPUHVD
        aURMajM5bTNvSWtnaFJCT2IrbTRWeFFud1Q1MjZlMFJPZnkxMmR1R2xnOGNBWnhX
        MU1GZkFHKzBZNUwxbWwyYUppY0I2cWhsU1VSU3pTR3oyVTRpNm9HeUk3emp6K0gx
        Nis5U2tFaVd0Z2pvZE1qRmVkcTVWc2k4dHdCelluVElsc2MxQURwN01aOGZ0TitB
        SmlHNTlhNHp0WER6QjRJc0RQSUs0SUFNS2lRaVg4V2dmdmI0QmsydXNPb01oUjRM
        SUNTS1p5eDJpdktEcTRobGNvRGZ0dk9HbEoraThCcHJGdVViS01TN0RrejhEcXk4
        dzlpZ0trdXd6aExTc0t4QkVqdE4rbUtZSFNpZXBrRUlVKzBaa2xEOEZaeXVvdVlT
        QUhISHFMd2JFWEJCN1p1L2plbFpHV05PYkhuODBYejNReit0ZmMyWEZ2bFFSTE4x
        TGJFa3FjM3hsY2VIelNCY0dqRkZLM3JnbGdsc2UzU1FILzU2dGZlMmw0ZWhCbHhQ
        MlR4SkJ6MFV3citMOGtDSWtxb3pMOHhuSVBLcFh2RWU5UmVKdjYreStaTzFaOUR6
        MFBZZmxiTjZZSUVNbFFBVjBFYjJVZUNmQmNtb2tNbVFSWm1RMWhpcHVKRDc5V3hY
        VEhjc0EybUpNdm9xMXZPQXpBVXJRaXVRa082QkpxT200bmRFNWZHR01QODZqR0xQ
        eWJVak9YQjB0U2cwRU8va0dpeW9LcFRHbnlaSEJqQ2dSellrZi9RdE1uWkdMZkx5
        TVZTcjNsOUd6MVZBVzM1UlBMS2ZvL2dsRDJMaEhpaFk0bjBrcSsyN05TcVVsWDA0
        U1VqdU9IeDBKbEZvVm81QjlpRjVQenNEYTFTL3pOd1ZQbE5HMVZzeEdhMWR0dDcv
        S1hWbTRzYWUrQ2R4UnhHTkJralZhOTlEWGlwODBBeUNWdCthNFlQcHNuU21FSjlN
        SUI4UVNkQ0dieUdZaWxVallQcFhjaWdVUXZ1T3VMeEZUSHUxMVFncllKMWxqZjM0
        ckpyS0FBTmlGSTd0WE00cDFBc1V3ZWJOMmFZZWo4WlhlNEw2UTZxdzRNTXJjZjJT
        V1BBSTgvY0JuNDh0L1U0V2VJSUhURlZSdThmWFc4YVFQdkRvNkdkMDlLSnBiVVlS
        NXBmQ2pLMmFCNWxzSUxsSC9iN0p5MGtKOW1tK3lhWUVYOVJFN1ZZNmE2YXZ3TTBl
        UVBkZjZmbHp5WGtoSzRkaGpIV1d3cHJIN2IxSXVHem5NNlBLdWRQMnRPL0dKTEhi
        TWE0VklqNnFCRzFzdDVtUkc3OFg4RE9kRERRRWwxeVFwZGZENXMzRi81K0w5SUY4
        WGdPNUVCUTdxd296T05RRmp1MWRiRmZ4MitDQ1V3OVphVkluME55MFR2Rm1PY0Jv
        UnBEUUVGYUs5dFFmV2xGZlhoUXM2aGFWVnFlMmlJblIrNFAzMW1yellkcy9pVXk0
        Mm9lNGQwbDVCeHlIL1RsMkdLN3g1S0lRWG05ZWhJZk9LK3dHMXJ0U3NMdGRFM0xy
        dlJLQ2xGRjRyQ2FrL1kvejBtclZuUTlrTkdualhsT1gzSDFESkRPNS8xMVlVQQph
        WWE4eXY2RDA0RjlvNEpyUFBWbVFtWFR5ekV3cWlxRVkzZVl2RGp0b05vCi0tLSBP
        THlIa0pmNkxnanRPNitsOW1qd2Z1WXZ2UFcvTU0rczZjN0dRKy9mTzA4CtDsTzPb
        cbz9no693CBz38DehB2Fb+rtZEf2OXz2lpO2v5CD4aYIPCPsowwgBiV4Jw9tjoEO
        DE45yr5gf2Hv19E=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T13:39:40Z"
  mac: ENC[AES256_GCM,data:UDnFIPu1u439Kd5S2Ip4atULmh6+ZiQ6HzGAjYLgUQJGzPxcquSq5NJlqjpoPQJ6GPn+SJhCqK3Zl12UwG/Byk1OwLqXjpAe/3U29BxPJ3qeI2AUUvpBFCHIz31NrS2xZ9OnQCT+iRSU8SPDz4y4Is1ignI3Ipe0uFiPzdk7maI=,iv:7KhNasfIzt7PRT5ab3Y4Gki7Z8jZmO9OpTlw1OtuP3I=,tag:sCNIcavIrxWb9RUOHw2HWw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
