---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sglang
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sglang
      app.kubernetes.io/instance: sglang
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
      scrapeTimeout: 30s
