apiVersion: v1
kind: Secret
metadata:
  name: dumbassets-secret
stringData:
  DUMBASSETS_PIN: ENC[AES256_GCM,data:QLd+mA==,iv:BJn6OTMiwsVmUDQFfqDGNqmSKfh+4Ac9zXWsKxfNwqg=,tag:ngdpDubQTIZ8LaOfOboZDA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEM4MGpycGhi
        d3BjWWxsOWt1UWhsNGNtZkZROG1GN0haSEc4dFZ5NVNJY05oOGJ6UERXV0ZwUjVK
        UFJOQXQ1bHFPQ0FqRnhSVXdnNHMwRUxQZzRiYWgwRTFJdzNwNzNleldsUHBmZmVX
        cWNRRXRqU09YS1VvWnpENXlROWRkak4yNDg1NGJUNHB3ZmR0bk9EZkYxNjNMM0dJ
        aEYvM2NxYkFXWW1qc1M0djlETHRjR3luYy9Xejk2VU9Yc0hxNklPWFFrWkEyVEhU
        ZFhjVUU3UUlub3FiT1hPQUJwaDk1Y3lSbGw1YUhZQXphYzdrMTF6azMwZ092SE5a
        M1B3djY0MDM4ZHRCKzRveUtTQTRyb0NwdFZLdnNTRzh3cHNmMEV6ZXViRHZGOTdP
        N3gvM3p0YmJzOWMzbXUxeFRoM2tEQXVLQm42b2o3RzNPd2pteXkrOVl2MVd6OUx1
        NFJhdFkvVkVTclBTMEkxZStldVBNVWxnOWlVZ1ZmNEc4ekRaSDBkdjJZMHpsR0R0
        ejJDWUgyTzFJUTduKzFYanhuMEJJNytmSi9uYnEraGt4QTRseEdXZXpRLy9qNWov
        UWxaMXFRZ0YxRkxPaHg3TlUvQWxzTkY0YnZGeFBUUU1CRGdmRWF6VUZxUlh5MlRL
        dEY5VUx3TWtZWk1kVVZTS21oUFdUVVloWGdKUmFUT0tQMWFFWEVEQXRJNm5vamxF
        bXhFTG5zZXA2MWo3a2Zzc3puU2JEeTFmQW1YVlJ4M3ZNdVdFbXY5ZStPd1pSR0Jr
        Z3h2WFVSR2xTOHhFNHNrRUtROUd2Mk9ZcDgwbGhhL0ZBZmhJcy9FbjEwek9lNTdC
        YUY2NElEUmFPeDFia3dSSlJ1Zi9wcVFLODVEZEk5MmtIZ0ZoN01xaDdmK3h6WC9R
        OWlzQStMYU9jS2hqOVRrUDVRZDZMTkFkSk9vdk1CQXVLZ0RRMmcrSjFZMzR1UXZu
        a3FhSjYveFZrcGFxbGE4VzFjd2RYMXphVFAyR2Zjb2h2dkZlRkhYb1JPSENTcFZO
        dDNoTXZjT042dHJieDFQdWtFVWZKSVhnL3ZGaEUzR3IwWWRsRFhIVk56Q2c5ajho
        UXB5K3VXbmxUTUd4U09md3k4dmhraFpuelJOWDNWRjdvbnBzYUFTb0ZEQW1VRlNa
        cTlPanBZRHRrN3ZuYWFzSzYwZGtpVG5pNmNucEE4ZlN6dEhrNi9xdEdsMldIblE2
        WVZ6VGdhakloM1hULytCcnV1dHplWWRZeE4ybURaTE1Wc3dNV1RWenkvNmphSERW
        S2kwaFFrU3FPVUdJQlkxcGZjamJxaHoxMXI4VTg4cTkvTUZDZFhuNGlsVUJjckVi
        a2pDLzdXUkk1TFZuSWVUOHQ5NmJXOVB0Mkdwc2hpOTE1RnorWHdoZGhiYXpFREZZ
        S0JyMHIvWm9FaGw1cHNGcG5nY0QzSWV0MWd6dmdRdVBHQThXOEdWOXA0OVVhVll0
        bjdRM1Bla3E3MGQzbTZFUVp1aDUyY0dwelVra3VDZkljT3U3QmlWU3RJVWZ2U1da
        WWRzNGNUYk05VGc3Ynk5V2c1OUdaRTNaZjBzVnBuWjVJbVNFbmlsbmNTR0VCQTV4
        bCsveU1RYWdpQ21UN2xwcXZkNXN6cDJMS1ErUDU3eC8xWngxUURPVTEwK2x5RG41
        RVQwS1Nhc0luMTZNRFUxbmNUR3dleUhHaHR3L0s1cTdFemgrVmdPSnpZOTRRcFhL
        VVJPMEpZdlErSnNuNlVXRWkrNVVTMG9mYmNubCtaSjBIWFQ2eWtCSE1LM3VLY1hC
        MVR6bEFaeHNuMU01RUI0NXA3a0NUbHE3a21nRGVlQkpHdVYwMVc4M2VjcVJ2RXF2
        TWx1SVpzNWZzdzRYcDFTTmpaQ251NE96Vm9lV2pIMC9JR0Yva1pETU5NT2Zjb2xU
        Z2NpWmpJVm8wUmFTOFdiQWRnOCtQcVdrOXp6cStCQUViWlN1ZUF6V0ZSQzhWUQpM
        aGp1azRqcWNtc0RYcW4ycjNQcnFndExYY2hUSmg5WDhzQTRlTUVJQ0MwCi0tLSBs
        Z2syV2JmZ1cyaHZSYWVVQm96YzF3MzBBZHU3MWR6c3pMaTlsUnRjZnBBCugrmDTJ
        F7ZaXjSEWK9EMl2YPP2pXr1SzB5wy6dRhzBeIcHHU8Y1DFV6Bm06taTQ8rwszGOW
        LsaNhMUl4IESoKA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-04T20:17:43Z"
  mac: ENC[AES256_GCM,data:aaadqivGIozecgC6SwH3MWHiH6aVdC0kki5poJGU0o7ii6mESgh41+Na0Qzc8m9n53n/ttCvte/JG81dRVkXq5L4GRo689Btqhw8hG5Csbofov//i2HfxV8tL0mPcoaxxNJzcs9I6uq2raVievSA18oMjQYtvz+zUPQhbdiNwlg=,iv:B2l0gMr8wnGmp2F0gGD8HWZ7Of2JHIWuog4oFg6rocQ=,tag:Jdl87LcPnIUU5GgU4dvPcQ==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
