---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gpu-operator

components:
  - ../../components/common

resources:
  - ./gpu-operator/ks.yaml
