---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app searxng
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template

  values:
    controllers:
      app:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2026.6.2-e964708c0@sha256:0872beb1d495d41f2dda73d7aea83746657afdd2be3010eb1b11f5a541555c9e
            env:
              FORCE_OWNERSHIP: "false"
              GRANIAN_HOST: "::"
              GRANIAN_PORT: "8080"
              SEARXNG_BASE_URL: https://search.${SECRET_DOMAIN}
              SEARXNG_PORT: "8080"
              SEARXNG_SETTINGS_PATH: /etc/searxng/settings.yml
            envFrom:
              - secretRef:
                  name: searxng-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                    httpHeaders: &probeHeaders
                      - name: X-Real-IP
                        value: 127.0.0.1
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                    httpHeaders: *probeHeaders
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              runAsUser: 977
              runAsGroup: 977
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              seccompProfile: { type: RuntimeDefault }
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
                  - DAC_OVERRIDE
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 1Gi
    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        fsGroup: 977
        fsGroupChangePolicy: OnRootMismatch
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    service:
      app:
        controller: app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - search.${SECRET_DOMAIN}
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        type: configMap
        name: searxng-configmap
        advancedMounts:
          app:
            app:
              - path: /etc/searxng/settings.yml
                subPath: settings.yml
                readOnly: true
              - path: /etc/searxng/limiter.toml
                subPath: limiter.toml
                readOnly: true
      tmp:
        type: emptyDir
        medium: Memory
        advancedMounts:
          app:
            app:
              - path: /tmp
      cache:
        type: emptyDir
        advancedMounts:
          app:
            app:
              - path: /var/cache/searxng
