apiVersion: v1
kind: Secret
metadata:
  name: searxng-secret
type: Opaque
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:ZY6HB17HFzI=,iv:Oi0AiaXW9ofRx4eLkcd4XxpUoSIPc+Glz6AdLz4SAVA=,tag:Tt28HULsxD5kf5HhspOufQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLV2xobDBSK3NhWllzaXlP
        R3A0U0lUQktrbHVoazNqdGpwVjljMzc2WGlRCk4vSWtlNC9OaFhPL1phdElDZmRZ
        MTRYUVNvTnpQamFIL2FpQi9FeVEzWE0KLS0tIG13V3B0SHlEa0IwcXdUdFVnUjZX
        TWRKL2htYittamoyTkVsK2ljOG5vUm8K55M6JSjeSfI+l2uEBuI0KhjMUBVpiC38
        HESvrJOdydA4kHy5DCLEa7Tk+a9ssm/xsBTyaoQ7jhjPBnm9IuWSOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFRaQTkrZFUx
        ZHFJNHVwM2FyRmgvWmpoek1UZnRGT290RkJoTERxa1R1YysxMzZON2Nid3BNZGJX
        QSttd0pIOXlJeHUyekhzZzRxQzZmclRpV0pvR2VJc2tIRzR5eHh3c29QTE00aFVO
        OVgvMjNMS013bUtRdHVhMjZ0T2JGVDA1U2ZQQWYwSUY0R1NSWjk0ZHF4KzlUU1BE
        Yk85dm8xaHhSK0o5MXM0R2hUUTU2cGVTckc1L1NBcldaOWlnTjhUZ244Sk5GZEY3
        eGRGb3hYQTZxRDByQnI5Z1BpTmlNdGJwYWtoR21MNGEyOW8vNnJLblRibndJQWVU
        Zll4MEs5RFBhMGhrM3hKcmhqZ01CNnNzT2NpUlliQlExSCsrMXBlU245VXE4WEpi
        WkF3S1JWSmxtMURJbFhOTlg2azVhNERlTi96UERramNoTlQ4TFBrazI3YWhSSGRk
        RWhuVVJTOHE1dTdpS3FtRnBnVFVOOVhTMHk2eGRvZWNEbEVGWTdGek5LTnhncWlm
        aUlFNDRORFoyTVJKWGE2ek5xcmdDaFRKVXRKOThnOXJOL1hCZi9ET0FqdGVyVUJK
        QmJORVVRQ2EwbXdERmpWeU1XTndKaGs0cS8vSlpCVCt3VnVDZjdsQVJ2bEZiSHJ0
        L0Z1NFJBL0dyNTlYWlhINWJsUHNMWWw2QVF3bDQwTkt4L2grYVhVNWdzclpGeFJj
        Q3ZhanJucnpGWlc3K0JnNU1MMml1bE41VmpMNUljSTcxekpGeEhDRmJhMVZYSlR1
        SWdUb2NBeTJHWVFRczBVK2pDcWJoU2RlakJ3bWJ2aTZkSkRQUkEzR2swNXFYbnll
        SDl2MWpnMk5HRUxORy92ZHp5NnNYY1ZWNmpIU29DNk1nbWplTG9iMTZvVkhTNXI0
        c2Q1bWpuYmNLdHhOeUJZZ3dhT0U5blBWMjQ2bXhEVWRrRXgzUE5PdncyZUpGM0Rr
        WFIxYWhYUDU0ektpNFFCWENsOUNMSUh4cnVIUE82amxGMHhVWTk1ZGl6dm0vd0hN
        bVhQM2hlQkpZVXR4WS90MHUzK3ZVYzBuVkQrSVV4cUF3OXJhN21vSitwTkI0eXR0
        SjN1eTNRdnh6STlpWGZENjU4MGVUb1NybmRsQUYxS0tXbTR6UGpvQWdPUUF4RFlS
        azBpaml4U2FXdGhTQUVTNUNDODNEV3oxTkJVOE9LMjBQYksvMHNZeGpLWGVqVjE1
        cHZXNVV4cWxlcThWTVRvMzFmb21sRExYaWRFanhRakJxZUxuSWx6dUlZVEE2YTM1
        NmdPYlZvQ3VRRURPRW8xcGozVzhMSVBNc0NKQVVBUXYyanlKU29HWGpneGU0bHU1
        ZUFKeVBZMmdhcTZtNE1tQzNYOGdxRW5PSlMxUTlaeEsxWUhBRkdhTjhFU3NsZmI0
        OC9UM0FDSmcwRlIvTjNmQlVvclNheU5lbUtsTndlUlpLa1FhTEVSbGtLSXM4dWdF
        UkFnS0xvY1NHZ0lIRStENmc1NFRoem5IM2Q4cy9KazRIZUtVOUdZTnVRcnZMMEtz
        aXk0RURBNW5nN3ZxanNndUlJbGhrd2lqRmVpcnRpU0tyeTRKdnNpTU0zbkszR3FE
        VmdvTUNXVVF4aTFhbUVkWEp2QnBnRXNNeWhTcXIvZ2cvTURLY1hKZUkwamxLL3No
        RkREOFg4N0pONm44MkZhYVJKMmdyaEplQ3laZExtTW41QVVIbUt5aHlWWWJTWmwy
        Z1JJeWdTdzJZamdTZmhKaU1HRXNOYUx1WEZJamdoKzFuNjA2OGtPc0RLaVpnZXdN
        L1NORlU1enlhaFovazJQWVNvdWxscmRhbTg0QklCcHo5ekVFQmRzbldzb0RjaU03
        dUh2L0tNUjFSdjZjMU1ZMlVJMlRzdWFvUmdsZVFSZFlOL2FuUVZRcmFrM21yU2lM
        ZlJZTnV5SnRudFIxUDVna1dqckZxYUJaQ1BBRHJ4b0Z4RWoyTHFUWEtMQWFOdwps
        WElWc2VPTm0wWVdzRWZCSi9MMURURVRVcVRRU3NQUnZGV2l4RWkxWkRvCi0tLSB4
        RjFOTmJIK0xmajhLNENDekJsR1RLdUNrd29WcDFDNHBQbVdnK2lmWXIwCq3HfQ3N
        h+D7HzTjEs8VZRJPB7YSLQRboXkAafuHrqxZoFCfg1JRZsZ/j3yWo/pmPx7vJbui
        eAsRbGCSoGO3QDQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-06-28T12:28:25Z"
  mac: ENC[AES256_GCM,data:J2vsE/MDkwNMKr4PkNFmOuqiSUcBm9DvLlRW0cCw59hc9AJfxNs9UGhFmurG/JFFG3LlEL1i2379uUHH9Gs038oQ5rkgYMoUiK3NoPfyUOVumSS++Dc13Q+SKwup+OMq5AKspMZDaTT4kxnZBXiTSKLkLuAvVtxMPD/YPDtcQDQ=,iv:cdDTwUB1Xk/aL3pdJl/TsjJhhj988PR6sXHSE5aJS8I=,tag:NDo2Fccubv668LAW+0kn/A==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
