apiVersion: v1
kind: Secret
metadata:
  name: searxng-secret
type: Opaque
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:ZY6HB17HFzI=,iv:Oi0AiaXW9ofRx4eLkcd4XxpUoSIPc+Glz6AdLz4SAVA=,tag:Tt28HULsxD5kf5HhspOufQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEhiY2NwNjdj
        dTIxTElyRHBQVElMVUtTYzIwTGRXcjlMeDFERDdLNm5SbytSMTZwSFY3eStUQW5D
        RzVFa1czdUc2NGR5SGZ3emJXNlVZOFB5dDJpaUVkYlhxaDN2S1ZlUkM5T0NQNVQx
        K29xenhveW9jN0lrNGNjaDZCeE5XVTgzMy9yaW03MjZQR1lZcmNUMXB4SjJ3Nmgr
        VFVTanhBMVFYRlVJeGJqSXNWaEpnTCt1S1dDQWpORWNlSVc2V3I1dnJQaDg1SHhw
        QlFLNkRDVEh4c3plUk1xQTNUSGwxTEVQU0UwWVByK3BrOHo4clVHc1lTLzIwODRm
        S1Vhd3ZHVlkxK1lsYmthVlNTV2pkRlcwSnloQit0T1ZVaFIvcVFIeTEvL29zcVZ6
        U2dpMVRzdFVxWlkzSCt6NzNkWVQyQ1JmOTBCN2I5VThCTklQSEdaclVSYnM5Wjcx
        WUkrcWZBVGQ2ZXMzbHFCSWlFOWFjZEc5YmdSV1NOcnkrNjdxWHhDRTZqRSthc3J5
        bFlUK2UwVEwvL1d6Sy9KbGhVemVETXU3THkyRmo5QnBNQzhMKzk0ckYvczF2d2lq
        RUo5eWRNdGkzdkxaay84dHZLem1SR2VJTFUzRDdJYWNNVWd4c0tWM3Q0ZnMxbE9z
        ME1WZmxMSlFwdjY2YzYrcHcyNHBHZjdUdE1rU2ovYTA1cXN5YVFVVzZUUmpZY0E1
        WEJsbDBaZDNUSTBiN3NpYjVCNjlmbklta0JHRXpXc3JxNk85VktwT2JCVXBacWhP
        ZkQxSVdYRUlzRnpjN3B3ZldxamNCMGFOV01pa0VYbGw0emlnOTA1dENnR2dUSkJH
        RDZyUi9zM0JaVlRmbWZyNERvUU5iRHBseU53eUh6SjJISTlwUmxOTlZwWU83NEFR
        cTBUWnpBZUQzck9TT2V4STU4SytiQXB5OHBmZy9LaWlRcTR0Mk9DbmViUDRMSXlh
        WnlEWlo3RnUyQXUxZE1SRFhySEtHUzkvNUR0b1R3MDcwRnF1cVZmVjhnNGd3SzFE
        b0RISS9QK1BSRUdBK3RMQmtSK05VWnlvS0hDZHJ6Snh3dWZGYU9SL2d1d3ByMGEx
        MFIyQ29uTzhybUU5SEpleHlIUU9waGRtdzQxNU01NHc0Sy83ZUtLQU9WMzNRTjUz
        aDc0UXQxZ29UcHlEWDF2OHRwUitiTEZDZSs4akdhdVZGWXpNUlJjUndXVlV1d3hU
        Z0RVa3h5OGhTN0ZxTEhGdFV2VWJpZ1VhNXkvMksxQ004Ri9vVElIZ2tEbEZVS3F0
        cncvZnVodHpXaytySFNjOGJvWkVXOVJDWVQ1c2ZSbUk1amdsakw1MVlzcDMrV1Y0
        N3VBMWViSDVYMUczUnN3aWljM0ZXZkw2S2xWQTIrQjVoRHcybkE5V3lYTlZpYS9k
        cEt5L0VGbjBTdENXNXFoWGI5ZHdzUUY4N1htMkwrYWpQM1JoZStWRnFQWkRuN2ZS
        d3loMnZzRGFFZ2FxdzRMdGd6VjBlN0RGWEZRa3Nsejhkc2k2M3JtdWE2RWJDUU5P
        Z0JpYzNRYXhOMVlBamFodFN6WUswRFNSQ25ZTUw5T3N3Z2tEZjFsVkwwVG9mYUpm
        VGsyd3EvaUpDQm9vTXl1T0VJSEVyVU1ZNGxQbjhiVGtGNDNUMTAwR09aeTRpOHJx
        K0RBbC9vR2diVS9kYVBiSFR3dXRoV2ZRWllzWXRsWGdFZ0dYSU5JeVY0UnRQUW1h
        dzNkNDM2K0pyWHVRK3lhUVgyL2RwRnRUQmNjd2w5MjJaM1hvWkY1Q0VUOU43QUNO
        ZlFUUDFQQjRNdWJOdy82TjBnbUFTeTRFc2doTnMrMUZUdVVFWm15SUx1dmJCN2VW
        OHorLzdzQzlPSjlVV1ZvZ2QySFJyOUlZQ3RqZ21udjVHUmU0S2Q0eUJ4M0N4WWtT
        TjNhSEdaOXc3djdGVEEwdzNZTUpEZzBvWFJVaUNZc2dRQVR0eTZLZTFCeUlQQQpu
        b0cyMktQcC9GWVNQVU5ERlVTVDd2U2V2V2JmUXF0K0QybzRYN2NqM293Ci0tLSBM
        dFRMd1RmMmw1TkkwUzJNcVV4RkhRbmZBYTF2djczOS9PdTM5bjBKMnJNCi1UZIiD
        6XyNPJns5zQSYl+Ndpgjdg2IFNRx9cPaiRma2zfm2yL8pteA638jpNlaOPme9lhc
        93pE476xSRRXgo4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-06-28T12:28:25Z"
  mac: ENC[AES256_GCM,data:J2vsE/MDkwNMKr4PkNFmOuqiSUcBm9DvLlRW0cCw59hc9AJfxNs9UGhFmurG/JFFG3LlEL1i2379uUHH9Gs038oQ5rkgYMoUiK3NoPfyUOVumSS++Dc13Q+SKwup+OMq5AKspMZDaTT4kxnZBXiTSKLkLuAvVtxMPD/YPDtcQDQ=,iv:cdDTwUB1Xk/aL3pdJl/TsjJhhj988PR6sXHSE5aJS8I=,tag:NDo2Fccubv668LAW+0kn/A==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
