apiVersion: v1
kind: Secret
metadata:
  name: paperclip-secret
stringData:
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:hwXaOyrCbZxXsFYoV99w94NPsR2IjmbflXIUW/XzZoddzspHVAWjFkC8HA6wz87wjttdzhIBUPHy66/LgsoKCA==,iv:aAsZBhtTKd4kiIelyCOesttQcvKUyPuwP1+8DA9bRMs=,tag:y44KBmEbGHUL4OxP9NT9Dg==,type:str]
  #ENC[AES256_GCM,data:kkDaXmruhutRk9615aeYvlKJZu+qWzo4+6JLW63M7jnmWhaZ1i4LyKl5aFmUobve5K+KpPSeK4bpvRJ+0HaixoRzuwZ7B3bhTs0dBIeGlJyxnJq2,iv:1j4/REyjg0mHTgHG97iPg/q6wqEtdKXO/o4dAIDVBOc=,tag:jgC9fjmEfm22m0FD8l1kOQ==,type:comment]
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:4ocz80CuRbAZ9u5J4A/WsN+O,iv:yx2AcqVyXKOJH++q4E5fjSF64BzK28b35pL661Yxzgw=,tag:SzPN7l32b0rlQh9X10oKAw==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:QeSxG+l2nHEU+whRa0ZUpUKz,iv:1NupijJHIUg5MX6xncuzlWKlCdYn2xEd3wqJUPBrGn8=,tag:cDYOlGO6JL9D5HFsMchaDw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEI5YlEvdEN3
        SzFtdFkxU0dKVE5nNTZ3MEIxYVc5OUxnYkNsMk4rMDl0Y2hhVFRjT1p4ZUlyeFc5
        SzZIbzV3OW9yeGliWlhSNVhnUEw5TGxnY2NtUTN0V3M1MHZDTDdlQkRoWnVRUEw5
        cHJONmtmbCt2SzQrZHl6cENRLy8vMHBLNUpGN0xLYjBBL09sZ21abDFEdy9HRWJ1
        RmdoRCtyRnhaY2pQNktZMmlhK3FsQ1pqNTVQdkpYUHFvM09HWFByQ0FmQlZvMzR5
        TS90WHdXc1hJcGhJVnVsZ1pkTU9HZ2VZZkRqdVRMZ09sb1NKckVMRWF6dEQwa0lw
        c0NENy9qT293VEVsQlA1NTQ4TUhXMmREeSs3dmNLK2d2R1BvYk9DVC9xLzd6d21h
        Z1JkakdUL01IWitLek11L2NMQWo3cy9sVVh2ZzlSbElSSWFMV1ZHcHc3K2FrUFNN
        Sk43SlpPLzlIM1pBNWppWkFBa2dRRmEyeUQ3aGdORHorT3gwSmwxSWpzWHMyRnFX
        c2IwVk4wZldURHNLMjJVL3FQTnJaTHBySVlvQkdPalBLWVdTOVRsVFRKaWhnT1RV
        a0o2THJSMkdIMi94bkxQQStPUmtGTjJLQTRaUFUwbXhiLytEd2l2TGtKL0puQU9p
        bkk2QzVxQWlmbnh5M2VzRGNUNFE3czM3YjR6RUxqSWhIK1JIdzl0UEhkMUFBNFlx
        dHZVajdjL29CUzRNZWNUb2Vxdk1pRlN5L212VnNBQTArdldTTzFlK21hZ2MwQWJW
        ZE44c2ZsS3JhMDJRaVZveFV4eThqNlQydzRaZ3Nvcld2S0NTeTZ3dEd5cElqWkFZ
        NVBscVdhdkJpSmQxSzh4UVdDMVIrS2d0TWNEckxhSmFqZCtGWnJ1cHl4NnhuTDhm
        L2FzdlFjV1RmcXVNdTdYWmJqQUppTFRydU1wanhyZUlzaWFRMmt5R1dIQmxPWnNR
        WHZrVWVsa2VzK1AzYmhzRFhUYW5UMGFTV0lCOFNnbDZyaGNaNHlxUWxaakRoak9L
        MzF0QytYV2NkeTUybitZZUEzTTZ5WmZNTEE2dmR1bDY1TVlFZFZRYU5WaTdsVVZ4
        QnZQaWZ4c1N4WWczc0JxVjdXQXJxWG5sMzc5LzVic2tWUFFTSkhDWGlKTDdvZHFL
        SlBZK05iVmRmVDc5NDFIREdYNUFVVGNrMU41L0FEQjBNUFZDbEZBNERERklrNHps
        aGcwZ0JQU2UzUXN1Vk9NQ2NwbENUTHVMQlk1SFEvR2FkWjVXcnpyM2lCalF0VStQ
        VmlhRXZRWXMxNmtjV0pqUTQvNnpYK1pualRQbWorOEwvM1JLZ1AzTE0wSjNnOUZR
        UUk4WSthSkQxckpLWWJnSnVmYUxBK0NxWGhyN3dSbk9RbTR2R3FJQnI0b1NYZnVR
        VUhTcUZmUVZ4eWJCZjdMZnEwam9VR052NGNicHFDbXY3QWVhbGQ0TzF5TzB1TU03
        cmFxdDZiMUordzI5SUthcG5XWjkrZVZ3MDkrZHdKZzlsSHhOeE1xbEdHM05vaStm
        Nko2N0NlTDhSM0tqRDVVRUI1WElPMUJVT0tsZkFFbGlIVnZxYjFQakNjYjhka25N
        LzMvRnZTTlRpczFudzdvUlRQcXFuOWdjY21qZGNiYUNjcFpnUkdydlFubVpzVDJh
        L1JXdnMwbHdHQUx0UXh0a0R6SE8xM1prNlI2ZzRGTUJ1OGdtVk0wcHRyckptTUsr
        a1VSYTA3ZDZraEFBSlVmK3FzNC9nOXFCOE5BbTEzckVDaHRVWS9EQmxoNXROY1k2
        RFh0cTQ2dThiZzZPazNFQWZiV0lQTWs0UTRQaVZCOGVnK3RrUDBMTmJSazU3YWhm
        bzhsQVY0WngvTmZJdWprMkZvL1JSVmgvaCthZ1F5QU9lVk5jWEZLK1YydmM1bE1Z
        Q01CaUpxSzZDWVJ5RDVMREdaTUV4RTFVMEpObnRjUUF3a2FocGR4ZWZ5eHNIdwo0
        QWg0Y0JrVGh0c0U5UkN0RFhJZ1Y3QytXbVUrVkxtMm5nazhHMFRHR2dzCi0tLSBP
        cDYzcWdzamxKTXhtek1Ock5oczhySlE2OFIzRHN4TVUvekJiTGFrbmt3CkNK3Bm+
        7BU/l+wmc7qEeuVwba3pWKHDO5v3tXW43J5/+jqao9Jzmly5mf4TKYQ4kI/g9CfQ
        Le4RIbUFrWqvUiY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T21:05:29Z"
  mac: ENC[AES256_GCM,data:eFdrqeoPtka32Z6q8eMcC8Nt6C7oINlmtdUVsqlWGE/ZgNGLi4twqBsUQPRNk+kV+qjG9YU7lnUyXfif787h0pKpotdQ+Wr85ekbSWfYVvK2YfgJ+4fjl6DVu5vZysQyj/vd87heq6I8kZBce+pD/bY66Kl9lH8p7Iob89Hhxdk=,iv:OaRbDR7y10kFtXj1fEONQKytp47CMMpKtL7jLyEhBmQ=,tag:yU/aVkPjyg+ClBwKutOWYA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
