apiVersion: v1
kind: Secret
metadata:
  name: paperclip-auth
  namespace: ai
stringData:
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:BmttMT58CYMGP6/Kn3bs0a4WoAJbX/vU3KOugS7dW8sZ+tSjoS1hLL9g5dQgxoWxv7jaOMmnv0KZVOoZlgH+Dg==,iv:EhVz5SkdZYcAM8b8XW2hzdvjHaYJZlPggTZmg5/x6fM=,tag:WhGwQk+YUKWuV7eDo0UfwA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICtISG1xd2Ew
        VDZmeDk4bENkNFplaXE1OFNPSUE4ZDNDdS83bHRPZ0tzU1RXbXlzdjhleVRGYk0y
        QXFiYWwrUFA2eE9YL0dRVjFPZnArU2orTlg2WkRaa1EvdkQwd1VRdFBCMXRiZjll
        VXVCQ3M4OEdDcXJmU0ZKMFM5NGd2UTFmdkd6UmFsMUp6VFQxYzJqcWZ2U3B3TUpD
        Y0FWeFpwWjhBZmNQODdKNklLZG5DN054K0thMHRTZ0V4U3dRNWxtRkxxd2R0OFZP
        ZFBWNHBmamQ4SHZTL2FrV2hEVkhOM3AyWEZrcWNFZGhyQ1dLTUF0bWNVNlUwRnVH
        WVozWDMrbUZReitMQS9qZ29hQ1ZKRUtGeHlJb08xMENteFFxQ1hHd2o5K0E0WE9N
        YzYxL3M3LzZQanNjdGVOTjdYTEMyQ3NQNk5QQTFXRHhDTnpkV1lueUlJeVNQcFgx
        cDFSVENvVXI0MTd0Z3BJSkp5MEFhQ1p3a1FHQ2pEbDJKVWp4NFhreS9tYkNLZWow
        dnI3K05lY2R3TU5kN05vQjJZeUtmbHVZSVlZbXBzem9jbDQ4WDhMbW1VNFdLVGdL
        czZ4L1JrUGc3eHVRNFJXa25RV2gwZnlWNmhtUGRNTFRaNkdaK3ZUdmJCb3d5cDh0
        ZjY3R2FQMzRCbjE1b2wvRFliRjhaSjk5MkI0aDhjc256ZEMyc3VDdk9kWWxkRUlv
        TDEyUVJDTW4xOUJTZ1FoYVluSm9KcWZsRFVpelY3RnpKaGEvRjhXM1ZTaU0xWGlk
        MWh4cWhlNEZiViszUW1GbDVETTAzMkorUWlmYnZrQmhRY2sxRHJncC9UZVlHZk9w
        L2VqbnREWlE1MVl5ejFlMC83bkJmRGN2Z3FiYStKQXRBK0xUNXcyZVZNL0NSRU9X
        YWxnSURjLzI3SmgzTzAxcG1LS0NJdnVKSzNFTnlrWWdaK2ZtbkpGelZiQ0YyeDVv
        ZU9mcjZRcjV6QTcyeXBGckUxTENaem9kVnpjQ041OXRLMVhOTjRNZXV2cHoxRlMr
        UlRwdWZVWnZGSWdlVDNxWWVxNTJuUkk3Z3g0SXZRNzZJRkgvdVp1dGFmSFZDM0Yy
        THlwV2pBc3l1NUtCU3hiWW15VmlhVVpvU0NUUzJoVkowQVFJZ3h6NUVvMWxncjkx
        ZktEYUFIRUxzWi9ubDU0NHhXelk4SzJocHhlZk12Rjk2b1BrSW45RDFKRDhGTXZk
        RXN1Z2h4RlB4UzlOOFNJeDVLSDgyYVlWU0xHZmJ6RnJOaW5OQm0yU0w3V0xVMUxG
        MTVJQW5DRm1iK3pSOHdOYVZKQWx5Zncremk3bkJUWW5TQ1BPSTdSTm1tQ1lxSnlH
        Z1JiZTBvT044d1d3Mm9xWXRpWG5yZmIxbzlaUjBCQnlpdTM3R2RMOWJsY2dqZHNQ
        YWQ5U2xOdUg1THo5M0dIOWxVNXRuTmIrdHBocjhOSEJicnVtY1NXSThWL0NFbzlU
        dDVLcll5VWRJVUZtSUlSSHFPZ05pQUpNUlJtRlVVNlFPdUZkTjIrVGVzM2lxRlUv
        bTFxL0x0VDV2eklzSjltZ3I0aWlGMGtsaFBnaTZyYXJsbm5PWk1SSHpIdWFlcXow
        UWtjaFljazF2cmNta0pMWFdwNnE2YXpqdkpqN05OdjZ4b3pmOHJ2cFdSd2JYbkpj
        dVRjQmdDN3E4Y2NsWWNRay9XamlhN2Vob0xZMGZpdStGMGRuWnZENWJwajJmMTR6
        ajJ4aU92ZmxPdkFSUmtrOGNVS1o4dHhyUnN0eFAxNUk2dzZWZEw5eHFIamluNUUv
        UytiKzZST21NcS90T0hIOTN1VkU3b2lXRGJyMlpRZk1LYUZhMitYcDF3WmlSRElD
        bE9ndmUxVE0rMXpvU0pXWkRLTUhmTjBjMFlTZjQyOWtoT2RSVUFqWlp2STNnejBx
        c1gwT3hVNDQ3Y2VGUG5wSVVZUERKcGsvdkVpeVgwTW5zYldHVmFpUit4Q0VSdwpQ
        Yko4WDRVT3V6SEhETXpXd2E1cldrRnlkbm56V2FDM3JzQWdjbVQram9jCi0tLSBC
        eXBNZVkybktvM2JxUmFTMTNnMityWFlTbWNvWGdxbEVwaXhSY1RITjdFCquS2e5Q
        mMNvC90IrrLYMYoXy8P32GDvAJwRHr8ibIYT5kbF2jk37ljcBjJErT/Mu05bYick
        7JU0LtgqHQMKurc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T20:04:38Z"
  mac: ENC[AES256_GCM,data:9CV/kzQHSURuNvZN0dvJ0MvH+6RsiS8nrjVJSMo6WdOhMJsHo0BlNnv7T8fp1GBPSkASciM8ccmImQN3nM9AYAhGoCgZSgm4XC+KBhszx2LzditZSXdTyYX1SGNqxxqWwRgWdfeQ0s0s5RIw2s3c2iRJnA5IdR2SxQTybZzUOUM=,iv:7tmp+pkE6r01Lr46BEps6hQMZXdPWpurWXHNlRx+VRs=,tag:Ll2xYT3lkBzqi/2Ax7vR9Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
