apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    RELAY_USERNAME: ENC[AES256_GCM,data:ZmDmoMwePKLNZjlq6/T/t+XMSHidMzc+rSXHje8=,iv:ZJnUS0XyiZbCSKU8GmwN0mTPD1AXRI8QvOHfTEWkGY0=,tag:8np4mFlp6ceZxHKnXGlkUg==,type:str]
    RELAY_PASSWORD: ENC[AES256_GCM,data:Y68uIFVqCJpbs//MWNPdkZPwJg==,iv:AvSaKi8nj5AcKzCyoCwHioG54xZ8fRFlnpizL2Qo+X4=,tag:yDDvWDL4tJAFlfjYzhKhLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVkdhRm4zWCtGSWJybmgv
            MFNySVdBRnZacXJGNzh1Q2t0UnJnci9XTG5BCjI0ZkU0dnkzMkw5dTB4ajJpT0VM
            dk9VUE1UcUpyNVI0VmhtYk1aaTBBL2cKLS0tIG14dzE2TEt0TDBVVzBJRkJsS2pn
            NWh2QW96elhjMC9iVDNxTGJxYzEvbTAKbd1ij4B/oySTM2NWuK0zog+WfuojRGX5
            6XSD6RWCUEn2blOJ6OHL3jf4mXBQBS+MVCwzRSmHrv1inHmcxUZZhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T20:14:55Z"
    mac: ENC[AES256_GCM,data:/kfujl2OT42QvRnff3Ca0rrrTGI5EAI2dmsFLEGLnh5p2YMICiClP5O5GN2CWbWqs1K+IM3jWrLF1Ld58pmwzS1j70uXyd3qLQZQc5hLAZrnNmMJYGfHdc63QBz4Vj/WPlvsPzZHNjivXwDdFFkTo441apKhJYMcw8k3xSATEe0=,iv:1Tc2nouB3a3PA63wA/ufaq8gy6iq1551x6v6JgayWQA=,tag:X5watFCFthBzS7zHe55VZQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
