apiVersion: v1
kind: Secret
metadata:
  name: smtp-relay-secret
stringData:
  RELAY_USERNAME: ENC[AES256_GCM,data:ZmDmoMwePKLNZjlq6/T/t+XMSHidMzc+rSXHje8=,iv:ZJnUS0XyiZbCSKU8GmwN0mTPD1AXRI8QvOHfTEWkGY0=,tag:8np4mFlp6ceZxHKnXGlkUg==,type:str]
  RELAY_PASSWORD: ENC[AES256_GCM,data:Y68uIFVqCJpbs//MWNPdkZPwJg==,iv:AvSaKi8nj5AcKzCyoCwHioG54xZ8fRFlnpizL2Qo+X4=,tag:yDDvWDL4tJAFlfjYzhKhLA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFRwMmxpZ3ZE
        a1VtbUxHbXpGNGFvYUlRY1BXNmVsaVVFRjlQSjJkOXozREZlSk11MnF6R0p0VGFo
        NWl2L3Z1ZFZRZDA0aVdudytZN3BWMnZzbnc1b2JVSFBZOVlrWGF4V0hBaVR4MGZi
        SDVTNHpLUjFydjFWNTQvQTBxMis5aS80NnZLaUQ5MllwKzhud1R2bHhaT1JxUXUy
        MWNHcWpabld0U1g2TTlVcnA5UnFISndodzRTVEFZRUlPR1hPSWdvTldjVXp0SHhN
        dmxZS0hzbFRYVkd2MFBKc280ZWNCdkF6bWNVdGltbWNHOFJpOGUxYmVPMWpVdWJO
        cFBzZnB0TEcxVitzcHhUWHExS0ZIekdqZW1EY1d3ZUNSZGhFaTlmN0tHSEQxYkVW
        L3Nwa1Q3ZzhLQ0F4M1Q3UnBGRUZJVWd3ZUh5UDdpUkRZTWh6aTh3TGxHNEdpM1FQ
        OVVKckRmUTk0anNDNGdtMm91dGZOV0xXWjJaSVhGMWtYcmw0RWc2TzRTQkhWWUw1
        U0hJMnUwb3VuVE5IWlNCM2M1clZjbm42djdsWGxUeGxVV2ZPbTd6WHpqNUpYQ1Nz
        RlVxbU9GMFBzV2Jqd285UWFYSHprbk1IcW5WYytZL3prdzNCNWJsVVVOaW16ZExo
        VzlEM3VFWHg0RXBMMW82djdlOEtQZE1OVHJCd3VOUXRLd21PaGs3U21rOFVLblk0
        cmtGSkRxNVEzU2lNYnllY1lGNDh3MjlOZUw3YXJQb3EyTlVNb2U2MmsxaWpLMnhP
        VVR1Y1JEcmlnajBwSVczcXVTenNtakVUWWplODFtTFkxTFNKd1dZNjRWeEFwK0Vp
        ZzIwbUdSTTVIMHd2NnJKQXFzcXVjckR1WHNBdG94NkxscktiSGphK1pJd2J6Wjdt
        TVFVOUhCbDI5ZU9hQmNqSkFKdGozN1ZpbisyaUZVS2N6NmViaExQU3pyK2Yxa1pP
        MGQ1UjB3MVNJby9KL25BTVlkalZxRVo3bTloTEFHdnF6UEYyNUZFZVIzK1pBbUlZ
        c011ekNMMHlhaWNHbW9rWndCOWlPUzNVMnJONXA0Wkl3cmVVbFBrV2lqRWdwdis3
        TjRyeTZiSjAwVUQrbTFrSGdrSTR1Q28vYnhTcVFlcURQeVdMcmdZWDE1RlVGR2hI
        bDc4SlJ2S2hvOHpsdFV4ZFpRaUx4K1FHMXdCK2JuSUJLZFdrNGdUdDB2dldWQW9a
        N3RHRDBpb0tOT2hsMWthWktMVzlBZDg4bnZCZGpjNmJTMlJqbHpKK1BEaUJFSm1p
        aDJlTzcydjRicUtacTdRc3BDL1YrZi9YUnRoekdYa2UzK25URVBldms3NnhnTmlJ
        M0xmd203QWVBbGdIYVNKRUEzSVVTR2IrTTd2aHVUdzZUMFMwakJHNVVyK2Znbjdm
        VVFPRFFKVlVtai9Tc0RtYmpGejBaamtHUDQwa25uVklhZnN5YnRRRlp1a2E5dVJy
        WEt1c1ZtUEowNjkrTjlQUUNqM24wREU3ME04NzlvWEMzelBKVGlyNDVkRzJURmE2
        eFF4cnZTMDV3dEgxWmQxaWVjWWRaSDN6eU5vdjUrYVo0OGdDZVFuNXc0eGVzeUdj
        Qjg0ZHFNSVJGcW9LQWNVRHlybzd3L2FQU2pHNy9DenRBOEdpalFGeTdLNnBGS1VZ
        dXh5bGd2ZnU1M0JyWkRiMzlLeHpvQXlvV0JnV2txaytkZjhLd3hJd0lUclpHSVYx
        RDNVTFpNMW1BUlVnSEZrWW90SUxoaGpnZE9EM2NyaDZTVVpIeXd3Q1c5N0g0Q1Rw
        ZGJ4bFVzVUQ2OXh2eXhsaG1LMk8yUVJUWVJ3a1hiM01YZTlhcTdFQ3AzQ2V4eENZ
        L1VTNzFBNHcvSXkvM0pGblk3cFRXY0QvR3QzS2pJdmhpV2dyVjA2SDdXZTBnZTIw
        eEgyazBmeTgzRUFsak1lbExqajBkWHZwKytFclRHbERxNERkRU02RTlGMnJkdwpj
        OFg2a1M0c3l1Q2JjTVZEQVo0VEl6d1RPcW1KWis5UWMrOHRnMFVBdTZJCi0tLSBF
        NEhGa1FNUWNRUDhROEFaWUJuQzR2NGRyTXluTXBkZ082Q1VXa3dhZmhVCv7wXeV/
        mogBavSElM2wLVshLPNu48HGg99G963bLj7qq0XJ8vyhtVGmvbUydQGRy6aZKyoY
        YZe4vDSpLyJTV34=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T20:14:55Z"
  mac: ENC[AES256_GCM,data:/kfujl2OT42QvRnff3Ca0rrrTGI5EAI2dmsFLEGLnh5p2YMICiClP5O5GN2CWbWqs1K+IM3jWrLF1Ld58pmwzS1j70uXyd3qLQZQc5hLAZrnNmMJYGfHdc63QBz4Vj/WPlvsPzZHNjivXwDdFFkTo441apKhJYMcw8k3xSATEe0=,iv:1Tc2nouB3a3PA63wA/ufaq8gy6iq1551x6v6JgayWQA=,tag:X5watFCFthBzS7zHe55VZQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
