{
 "title": "LiteLLM",
 "description": "LiteLLM Prometheus Metrics",
 "tags": [
  "ai",
  "litellm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(litellm_proxy_total_requests_metric_total,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(litellm_proxy_total_requests_metric_total,instance)"
    }
   },
   {
    "name": "model",
    "query": {
     "query": "label_values(litellm_deployment_state{job=~\"$job\", instance=~\"$instance\"},litellm_model_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Models Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LLM Deployment Analytics $model",
   "type": "stat",
   "description": "The state of the deployment: 0 = healthy, 1 = partial outage, 2 = complete outage",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "repeat": "model",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "litellm_deployment_state{job=~\"$job\", instance=~\"$instance\", litellm_model_name=~\"$model\"}",
     "legendFormat": "{{litellm_model_name}}"
    }
   ]
  },
  { "title": "Top 10", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total Spend per Team",
   "type": "bargauge",
   "description": "Total spend on LLM requests",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (team, team_alias) (litellm_spend_metric_total{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}))",
     "legendFormat": "{{team_alias}} {{team}}"
    }
   ]
  },
  {
   "title": "Total Spend per User",
   "type": "bargauge",
   "description": "Total spend on LLM requests",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (user, user_email) (litellm_spend_metric_total{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}))",
     "legendFormat": "{{user_email}} {{user}}"
    }
   ]
  },
  {
   "title": "Total Spend per Model",
   "type": "bargauge",
   "description": "Total spend on LLM requests",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (model) (litellm_spend_metric_total{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Total Spend per User Agent",
   "type": "bargauge",
   "description": "Total spend on LLM requests",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (user_agent) (litellm_spend_metric_total{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}))",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Models Latency",
   "type": "timeseries",
   "description": "Total latency for a models LLM API call",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (model, le) (\n    rate(litellm_llm_api_latency_metric_bucket{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{model}} - p50"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (model, le) (\n    rate(litellm_llm_api_latency_metric_bucket{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{model}} - p90"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (model, le) (\n    rate(litellm_llm_api_latency_metric_bucket{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{model}} - p95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (model, le) (\n    rate(litellm_llm_api_latency_metric_bucket{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{model}} - p99"
    }
   ]
  },
  {
   "title": "Models Time To First Byte Latency",
   "type": "timeseries",
   "description": "Time to first token for a models LLM API call",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (model, le) (\n    rate(litellm_llm_api_time_to_first_token_metric_bucket{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{model}} - p50"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (model, le) (\n    rate(litellm_llm_api_time_to_first_token_metric_bucket{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{model}} - p90"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (model, le) (\n    rate(litellm_llm_api_time_to_first_token_metric_bucket{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{model}} - p95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (model, le) (\n    rate(litellm_llm_api_time_to_first_token_metric_bucket{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{model}} - p99"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "description": "Total number of requests made to the proxy server - track number of client side requests",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (route, requested_model, team, team_alias, user, user_email) (rate(litellm_proxy_total_requests_metric_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{route}} {{requested_model}} {{user_email}} {{team_alias}} {{user}} {{team}}"
    }
   ]
  },
  {
   "title": "Spend Rate",
   "type": "timeseries",
   "description": "Spend on LLM requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (model, team, team_alias, user, user_email) (rate(litellm_spend_metric_total{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}[$__rate_interval]))",
     "legendFormat": "{{model}} {{user_email}} {{team_alias}} {{user}} {{team}}"
    }
   ]
  },
  {
   "title": "Tokens Rate",
   "type": "timeseries",
   "description": "Rate of input/output tokens from LLM requests",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model, team, team_alias, user, user_email) (rate(litellm_input_tokens_metric_total{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}[$__rate_interval]))",
     "legendFormat": "INPUT {{model}} {{user_email}} {{team_alias}} {{user}} {{team}}"
    },
    {
     "expr": "sum by (model, team, team_alias, user, user_email) (rate(litellm_output_tokens_metric_total{job=~\"$job\", instance=~\"$instance\", model=~\"$model\"}[$__rate_interval]))",
     "legendFormat": "OUTPUT {{model}} {{user_email}} {{team_alias}} {{user}} {{team}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Failed Requests (top 10)",
   "type": "table",
   "description": "Total number of failed responses from proxy - the client did not get a success response from litellm proxy",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "litellm_proxy_failed_requests_metric_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Fallbacks (top 10)",
   "type": "table",
   "description": "Number of failed fallback requests from primary model -> fallback model",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "litellm_deployment_failed_fallbacks_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Requests (Last 25)",
   "type": "table",
   "description": "Total number of failed responses from proxy - the client did not get a success response from litellm proxy",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "litellm_proxy_failed_requests_metric_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Fallbacks (Last 25)",
   "type": "table",
   "description": "Number of failed fallback requests from primary model -> fallback model",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "litellm_deployment_failed_fallbacks_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}