---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellystat
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template

  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: cyfershepard/jellystat
              tag: 1.1.11@sha256:c4e2dfa8bddf8d5ac3a675d7202f71a54dcfe3540cc186899d9201e0fe701fa5

            env:
              TZ: ${TIMEZONE}

            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                cpu: 1
                memory: 2Gi

            envFrom:
              - secretRef:
                  name: jellystat-secret

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      main:
        controller: main
        ports:
          http:
            port: 3000

    route:
      main:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Jellystat
          gethomepage.dev/description: Jellyfin usage statistics
          gethomepage.dev/group: Library
          gethomepage.dev/icon: jellystat.png
          gethomepage.dev/widget.type: jellystat
          gethomepage.dev/widget.url: http://jellystat.media.svc.cluster.local:3000
          gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_JELLYSTAT_API_KEY}}`}}"
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      backup:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /app/backend/backup-data
