apiVersion: v1
kind: Secret
metadata:
  name: jellystat-secret
  namespace: media
type: Opaque
stringData:
  #ENC[AES256_GCM,data:4j6UYw==,iv:8EHk9ucMA6JTPLqHXJ4yWocoiL+SdQ0LjjG1IXAactI=,tag:tn4IwkVwJ4o/2bvYemC0/A==,type:comment]
  #ENC[AES256_GCM,data:Vn0sgaMbd+aftsF+pIDQ0tMO5DZdemyhJoAjJQUlHCU=,iv:jzeXN3SYhWuijP+dITx6/h9S+QDe9JMoHxERvSVOvCU=,tag:PSrF7iWfDvW5suJbJeuh4w==,type:comment]
  JWT_SECRET: ENC[AES256_GCM,data:P/WNByLNxqmqCXhGYRw3giFDKgc5h8Y+EDJllNDCVJnKqz1WPKdtn/nQAw==,iv:tqkqy0cKummXz1wqAUjugn/CVpnJSf57vkpr5gt9LXo=,tag:yToUQMpB0BmYXpnhPhWQ8A==,type:str]
  POSTGRES_IP: ENC[AES256_GCM,data:kGpgQj4W9QUWV7LQFtzOB4P3/ynugGbNkRol2BSW8OBF10l6qdcW,iv:Vaq0VVOPeVTjlsAXsV1aPLZI0LTwJt8t4j8SMOdCXgs=,tag:amJhZB3lGsq3CB7O3Ff7kQ==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:HXXjYA==,iv:28t9U6Y7hmMZmpmlZXA+bAzthHqSnP31Tc4ixxoDuHc=,tag:lrl86wzJ3pagFy3+9cjndA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:0nVin2H5,iv:Bm/IqaZhItzjwu9NmbATpA9YXQbsa2Ly+Tw5QouOO6A=,tag:eoVfFBu+Zx3y+ky3Ze7qWg==,type:str]
  #ENC[AES256_GCM,data:O9gTzW4X3w4Pr/2hcB9uQYAfKcZ1K+t7Gq4cb6iN04gB,iv:dBGhCudnQBqaI6vZi3kUhfXiLscrAyjijEw6cTyd39g=,tag:CdQbgqL650TxjKweeen1+A==,type:comment]
  POSTGRES_USER: ENC[AES256_GCM,data:AGQeuzoCRHgn,iv:jCCJBL0BWFdZT1MAW5e9F88NXGyrvOs74wheBrweCGI=,tag:5sc9QJBjPuARmppx9Hxspw==,type:str]
  #ENC[AES256_GCM,data:H+HVRmaiycfUFTp78F4c5c/Y9NTfCGdSEw==,iv:/H1q6K47dLFDOoHWH2mNbU1KdX3yF14XAKoeH/m01Ag=,tag:lHor8NW+CIKlRNq2uOXI2g==,type:comment]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:H++CjGaWC5Q=,iv:nx23Dgfxq1dSBLFd/J6Bc2u9FPdH8NJnP2z8pG6q/Cg=,tag:ly0BHQQOyfd2ApQHbk2hsA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZWJQQ1FEa3o2RDBZbzZD
        Y0UyOUh4L1RjZXJZOWRXb25lckFXZDF6YW5jCnRRSFUvdFJLTGhOU0ZYVVdjenlC
        QXJCVzFjN2ladHNPdVJiUEF2ZnVPOWsKLS0tIEVCMjNpSlEvTGZkY1psVWR4NHpW
        Yi9ncDFRK1dqamFwbG55b211UkJiOVkKsGUrMZZEFeYOnhonlF4G/vd0+8aeWiti
        yVsfeM/8KqvNiLp+W7atuKHdVO6AkEhHNs4qA2R1p4tfveVqrPQKDg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T22:27:18Z"
  mac: ENC[AES256_GCM,data:kw4Myqd0j959efnOiOQrNmNBYwSif9vpcBmvoK7UNX3s6s0/z3RN51eRE1BfdvQ1dWXDfBrKQOvELShruBFBEyn0/9z4HTQYdAlHQlqU+OoYWu23rDC8/xtoSmCEOjY+yVMDesht4M/z0w3MFoZE4IjRDznc7qk9Ombcoc4Wa3k=,iv:LZxUjhLe/yxzpBGtgKtmDcNRM4xvKFkFgpf3KWigm6s=,tag:iabWFkJMMAI+zX2Ycm/pxQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
