apiVersion: v1
kind: Secret
metadata:
  name: jellystat-secret
  namespace: media
type: Opaque
stringData:
  #ENC[AES256_GCM,data:8r1ssg==,iv:qEftgyefyrZVNbTHJukOYhlGglcZabmbO8gLqYmNXWE=,tag:bew/54DheTRgpq660b7Jcw==,type:comment]
  #ENC[AES256_GCM,data:qwUgDScTRd3uMWzQgcvF1AQmzlRSt7iGkgdmWoY1in0=,iv:i3w8f1zOBBz6BBtLUzBdEU052XnA96XW+RK4d5iM6D0=,tag:VSc6ZVAUSwEbwn2Fxpp0Ig==,type:comment]
  JWT_SECRET: ENC[AES256_GCM,data:VaKuxZz9u3yhQmhwt3pFmUYu1vYXbAPOvMETkGa1E0C3PiCfj7RrDqSiOA==,iv:4Romsz584KpvdccqaXe2SpKwsNvB8R9uSgbSKUf5BU4=,tag:d9qQtx49j7nVWkD8ahRBjQ==,type:str]
  POSTGRES_IP: ENC[AES256_GCM,data:w9xA1PKhlTc1z9lpd3RnShSBmt2/M+1a4izu1U8TeAyZpKFGpnsX,iv:efPLsW4GXnsb1KtZWsj23kN4v6l0Dvw5yE7WadBVzro=,tag:RTuKlz75brMd8amJm//z+A==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:gkjXkA==,iv:IoM+H2AlNs02P20go+2jRAPOURIgx2xRU5WaIJSTQGw=,tag:a/msSbKaEoKwYQd+lml58Q==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:V8GXli2o,iv:fxiGdEEzNdW3aAmGOF+27KcmYrUjSLwMU/hCeiI7HHU=,tag:M59Of1Fhkq5T88k4bmDRjQ==,type:str]
  #ENC[AES256_GCM,data:kV5uym5y4gmHXOMa5ZUIB1Cd3v7ax2gye2M0ZUX7WLNe,iv:gjdsaXxyhYaCUQuAde7YBh8q1bjC9XN+kw5N802DEjw=,tag:2CNOIDpDcE63efAIuj553w==,type:comment]
  POSTGRES_USER: ENC[AES256_GCM,data:xc6xo0Tx4tGc,iv:UARpuvzFdgGVbIeH6cgzIQyes0OMWH9gz0LCp8gIdHk=,tag:GuNeWPK60GEkeybdqJANwg==,type:str]
  #ENC[AES256_GCM,data:yBHV3tz0wx8rmmY516Q8KpNOMpMMetKDhw==,iv:4fE1q8sSA1MMYZVVL7muW1083UOkj7png6IrTBedcxk=,tag:vux2UJQIna6U5tZuqzEg4g==,type:comment]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:AxZq+tqqPmQ=,iv:xVZiEnfleGV3bf+f2QTAUBV5Fg2tK3Ey4AJihdai6HA=,tag:qEnHuxPtCy6+CV71JpuKDA==,type:str]
  #ENC[AES256_GCM,data:pAFhX7gEpZJ+1MfHMXI=,iv:I4cec79ndWOqhJTjjq3dQH7iplyk7ut3J1AogyjMYtQ=,tag:qj1REYJh+3Ocw+uhkXJ9bw==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:3kMr4sEx,iv:r1gAD91GNgay1VC5OUlsWYZcbSsH/+C4OLvM7D7Ys8g=,tag:rQL1kWqLg9kB7AwWegbS+w==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:rl3rzkxHpKWmTkpwiXHBJR/K1ajhTboA4AqS2yPB4OQ7dEsgk+48,iv:4ngQREk0JxP7CudfYK9DJNH7gPT3du8a6SjQ/9XOhwQ=,tag:mcjGIOS6kVoGxA/J9b6l5g==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:N98BEZzwYo+o,iv:K7P6yTKTR3/DCFvmEHepJzP2xu5nWT5l722Q+qOl/Ag=,tag:y4Qpdr/jJcG0e61m/OQJzA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:gfSo4/0OUzo=,iv:L+0uFSUD40eoO4Y9P3dOA2Jwg6hmL3zwV0cMuupilj8=,tag:FmPuLN84I1cmIXaUoTFjEg==,type:str]
  #ENC[AES256_GCM,data:J77T9JqsrNkwxrHDitBlpu1a8KzUYVQ9lmmVI1x4L6rG,iv:FmFjT+j7Ec5Ixjed7Dx0qHDOrZyj73Za48iTUtZ3Apw=,tag:13m//R1NJEmrpbi9V/1jhw==,type:comment]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:5BXg1hc2N7w=,iv:HD5qFQOAZzPm8Mq4Z4/sHHCiF00ZnwzzA3v+PBBZbzQ=,tag:tMMWghMkPu8yFOIsWt8fAg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG92OFBvRW5Z
        Q2JLc2wyQjZVT1NvaHZmSDFJeWtvRGJFcFFiZUhLeGNjNFg5SC9ZalY0Rzd5UUNa
        MGFiWDIyNCtxZ3JLRDFjUlJicEFEd2ZFeEFrRDZKaVZWanVRMFpyUXBYdm9mNmQ5
        ekNlOVNqV3FrdVM1ZXhYbi93UGNzbWtUZjdGZEtEam5LQmhFNWF2aUx5UnVWMGxu
        RFhxMTlKdnlRLzRTZVpTVmNGWDBlKzZDQ1BERld1NVdTNFd1OW40WGF1WFBNblhh
        aXJOWUl5dEpJM2tzY280WXRobEVqZ2pCbnBxbWJKQzBONWRjUFlRZ3NITTlWMEx1
        Vy9HU1B4SGtBK1B2SFIzMWpVOWNtVEgrSXZvejl0RVdQRGNnNURhVklzaXZvcTZi
        Y2J2ZUpkY3NzZy9qQWwvZVlvQk1ZQ3RFcjBWazA3Nyt4eVJZVlYwbTdpRzF2ZmJD
        RjJnaU55UVVsb3ZlN1FTVm9xSCtpU29VdytESTNCeitweEp3VlJyQVFyaDYwaEkr
        c1hIaHlIMDFHU1F5dVVaRWVpbjRIU2szNjlXdmN2UEQzZk9wbkwyU3J5WWNPT25y
        ZFphOHVHNEV0dDIyRDc1QzVuUWs0aTVvK2hzUTA1emlRYmV0azlEYzlwZzNhR1BT
        TlBmMlB3TE9pdmJKTm1GY3kvM3FkM2dVTGhoSlhGZE82UzhldjRPZDhZQUhQMkU0
        QW1nZWFPMzlqMktlMFhmU3NHY1RKejFZQTdyMkdiaXM2TlFnYTVVVXk5a2tvak4z
        UlFPTWRKREpuNjBPQmZ4YjFxWkN3K0xZNzdDdzdrRTRPTXFNQWxpVkY2cmtFcWNy
        bVZ3SnRjS2hSbGdqL2g4YVlITEQvTS9hMjE4MUJJTEZNMnc5S0x5TzZXVTExdUY1
        aGFYdjRCaEhNbkJyVGd5aG9ONHRaYkwrVjhLTjR1Y0drVGR5cFRRZlBudlRYWlN3
        UWhmYUdHZDQ0a05CVFZvRUZPYXRpZitDbDZ2WUh0LzZGWmpPTkhBaHRDM0cyUS9n
        bGo4VU5SNEd2QW9zSUx0VlBwcVdKMVo4S2ZHRllpdG50dWZzSmxxWElRWHFCOXNh
        TTU3YUNyYnVERmY2Y09NNi9LdGlPU05LM0FCbmloYlhtWmdvSklKc0I0Tyt3MVYw
        YldSSWNDUERFM2FiQ045dHJTdDRvL2trZ1VyTkloUlc1Rk8xdUk1dEJTTmtFOXJB
        alVsem9nbkVDa1RvUG92RVFOek1ad3JtVGE3WHk0RnNZdHAra1lYajM2SUYvYnBB
        czdCdDV2cjBKYzcvRmZ4QXYrc3BrUDVNMExFY09INEpPN3k3U2xMWEtyRXlsMVJk
        SFhOQ21odmJtc0h6OVBaL3VLbDlwa1ZqVi9VVW9yZkNMUTE0U3lralBRZkF2SVhh
        b1pEaGsxbTN4SEpNd2VacVBTRHdFWjNNbUVSY1ZVMUphSi96TlJpc1NVZmk3MXJy
        WGVIcU0yYm9zQnVsQzBjeVQweWNxRmtzZnpQL21EV0UzR3d5RG5KTUVNQndwbFls
        MU9SVWl1d2F4UlVJYWpxZ3lvQndtZ2ZHbkVzWjlpL1ZKaGthQXQremhTU3dGc1dV
        akl3ZjVNVnRMaFd3UFh3VVZuWEo3MnE3U01nVXpQckxwVEwvR0RDMDI1R05JODZU
        dWhlVXptY2xmWkpGREEwWTl4dWkzS2tVVHRLb2JyRW5EeUp1ZnF1Z0YvdkZUVEM4
        MFIwbEl3NEFiNFJTdDFJYzVZZUlRbFlzVFVwMkc4SEd0NlZFK1B3TWUzVUJaY2ti
        QkZ5b2JjcXV4U0w3NWZwTFBJb29OMm1rNDlLdUtCMnp0NVZKVU1EVnlyNFRJdUhD
        T29CWGpDSnZLcjRYVHBuWEYxdG51THJRRExSaHZEeXB2Z0N5VUo4Wnk0aFEwRWs2
        RWRGb3Y3Yy9YbzdUd1Z2R0dPN3NtVEFqbE5HL2tJck9SeStsQmNVM25JNExXQQpZ
        U2NCL2dQaHlyNWh5STllbENKN2REVFdqdVhQeE9ISVJQTE1HSllqU0JRCi0tLSBH
        WjkyOUVKZmV1RklzaG1sUGNrWUpVR2tPNUZhbVBMRWRSM0ZPQnFBQ1BVCnTQQyqh
        oSUGcYlQ/OyLX2BUPjU+dBiioKhKmOS2kxnDczBoUdNKhokbVkU5N36Gz0kB1H28
        fdQA+VK/BzRnFu8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-21T19:14:22Z"
  mac: ENC[AES256_GCM,data:nEMtjKNpy/Wjt/hDnaynxqQXoGf4gHY+6W9CnPbmU6Cn1Qcekxs0wWQpZXUB8MTSt4aM2TebWbdErqDejXITXsXQqoRMTAuk2+0kc7v7ysUCPalNLGiMZARrNLHD6XVajsyNGxNFMsHQh5xSUq4FrE39sUlGVK7EM5Myc9WCZ+Y=,iv:LFM+JHv2JlWrIg7cl7mDBhlIyN5aYfBvRl6Q47bunGE=,tag:piN74mVe4EhCjY62WDFocQ==,type:str]
  version: 3.12.2
