---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nextcloud
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 9.0.4
    digest: sha256:f7d6e0c7981b46d318529e12a997a6512e3252f466b2b536878ee16e6d659d15
  url: oci://ghcr.io/nextcloud/helm/nextcloud
