apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: default
stringData:
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:wYeTpnGSQEG/smACH7JAkMN9fkA=,iv:G2SbHwnM9dG43Wc3rjFoA4orPrgMg7VcPfXQPNS2CW4=,tag:ZrKd9fLvEsMJY3hp+tF8KA==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:jiV/ySPm3GBShCgnpsNh,iv:niQ5RI50Tm/8w3yGs1znDd4I6tGFreABob44MQg3u7E=,tag:owhtlgy6wBS3wH9eIqN5kw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:fwU5E/rPk/olYmGV7Rv9sea/CJ0K3rCixHlGSyc=,iv:wnT9+/aiarWsFip4RH7Ew3IAODLwlxJLqJkmfEcYDdo=,tag:ltnko5QVQp49cmmo0NUAcQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:R5+XHpgBkb4=,iv:W9R8/xHQrvEnfOntfRdpW9Rmwrd7L6ePHTyca3Gi7j8=,tag:rPYeoCs9dlHMsDDjL2mh9g==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:pQRFpleBDIGcmWDJcqo=,iv:AcucEk3HZPhDy8P2A0hh9ZAiXSs/QizjUy+kMIszNLU=,tag:90/AEiBFAEds3/3HTnkh7Q==,type:str]
  FROM_ADDRESS: ENC[AES256_GCM,data:IbnpRogDqNaa9SO4FZe7D/FQCQ==,iv:BCo1YhdDEdzq2/I7QOv+SpxXHmIJ9fNGb/JsrhFkK7w=,tag:+diMpCJRbPuEbx6hzPkYhQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:SkMlfoJvruoM,iv:h3ru6PPcCrqbLa/B20+gxLBcUzWSS/03Ga7DdOd1Nd8=,tag:arAIWPDjBh2yPZ0Sc22VzQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:LfHl7PutvFRa8lJzBnFLoHoQo7ru35N2faeWy5X3LcBJ67MiakmO,iv:LLPRf6BSDkyKx2vNtd/DkP44wS7RC+KbAMYY1/MpOk8=,tag:G0+NbEpSxV5qJRD8L3X3sQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Tfj44gXzF24W,iv:HSSqrUuTo6HPhMOYR4NZ30yFhuOx8CVrFizJrYTVB3w=,tag:wcddSf/JaJzndPjL8GD+1Q==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:LGbrhnlYil8=,iv:DjDlqOaCuN78xDS/PfKCF62A2+il2oHLnHKpFc/koBI=,tag:HI175tfBJqFaP1znQQKOWQ==,type:str]
  replica.config.php: ENC[AES256_GCM,data:yyFon/rGNuEvSRPp69F81bvpKoZstpA1kAKHnlO9r2tsuHPkM4mzIjNTiKDzs2JmKc5JB248s9sgQFl0mSO+ArKKUKrkL4ZJSzY9w652j9Ns89/crQlML5B1YJGpE56kpUfOEswelZdaZcI2cIqWB1bnLdU+6C02WgI1MEa12IteunbuixTrR7oZ3eQfCjvERrCrdhoLjR7VtM3SSMK4R3gj4M85ym+wDnn1KI8xz92QNinbJYicHi5mgb6Y0aBU2QJlvgs6Zk18z6uNpI5gUek3advBI5xWffaWDlcO8/mujOIAJ7sDiFyMspM6h2CzTJpJ1j7lQg==,iv:1gFi2GbaqsGZs3/xepjTNyjPHTvZk1LvNKwzrioZZjE=,tag:QLjPzMThuvKyKnGWfZ1mTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG9RMWFWUUpC
        TmZMWi9NUWpMZ0JZM2xjRWh2RU45bVFWUEVYRlhGczdjK0U3aDJ3bFdnN1o5MFU1
        eE1RZHdnazRxYWh2UDROZmlmQ3BUekYzT2lnN0dydUVHVzB3cDZXTXhKcFN3dWJr
        d2JCYzBkZXhzc2hEbUNTMmgrY1BoODM3bndYZ3F5ZkQzQnlMWDhjNGYrWFhGTXNs
        cTN5dEQya2t5bjZWNVcrYThvWU5YTmlBWC9GejRTN1RzRHpxbDJXVzh2eC9uZTN6
        Um0xQTYzTEJGdGoyM2h0Y3NVTFhrN2RNTi9iYitiaTZZWkNOcTdsQ3R6SzZpaTRN
        QlZmWmxhY0hVMk14MW4vWHlmZGJxaFBPL1g3SDdkMGRBdzBIcmtEaUVLNmY4SVhO
        T2VUaG9jMjV4UnBSZmxodnFQRDlnVWwzZzNMY3VLakdJcDIwTHhiWHhjL0dYd25v
        SWNXRTlRVVBuL0xseExadnV0V0VxdUxCbGtrc0NOcS9ULzdOdG5OZGdZdXgySTBZ
        ZDI0TlVFSWdQSEsvcWk4dlh6OFM5ZDUweHFrNTl1OWFTaVlnZ3crcGRwNmkwSUpW
        My95eDRzT2NsTGQ4UFR1NDZnalJtays0UUNRQ1I2R2F4YmxnMW55cmd5S0dzSkxD
        bFBtSDlpcTYyYTRpVzRtK1VDNytKM3EwWmtXWVZ1RDNyd1FMWEVjdnkwZTQ0Nmc3
        MDlyWTNxeXFoN2Qyc0tua0QvelIzRVY4ZnFySDFtTnBjQWxjbkI4TEF3K3VJWDJa
        QXpXOTZkUGJ5VVJoVHgvY3Nrb2lNa2llWDYzN2FnYkJBWDBNa3dJY1N3aDlzTnhq
        anVIYVVDOG9KTXVkZ2lSTndKbzhlR2ZRa3pGbFhBM29mZ0dhLzVDTUpFS0lySi9p
        NnhZWUNiNEZEaGFab1VQRmVNY2lCc09UVzZVWUUzbmpCVDBocVdManRaQWd6anR6
        SGY1a2VOVkUwRmNiRFpybVBpcG5Gdy9nVEVDMHV4SmRBM3RHeG9MUUUvdjVZV3No
        RmJUcDdoSHdFeExrRU5mRGdqaVg3K1NNK2sySTJLOEF6eVErZk1VMkhJalExTDhK
        UmRpdW95b3liYVpPbUVzVzZBdkh2QlFpaGJPdHpabVE3dGJSdEQ5QUd0dEtjQ0Y4
        TlNSQ0FlUXdDRkxobE4rcGxLV0tsS3lUYTdGdWlCWEFJSUJmZjJFUmpQZXYrTUtV
        TmF1bHB6dnkxNVAzckJDNHdwaGJSSlA3QnErNTlTYktOSFJCRUZQS1VKVmtjbXJl
        UE9VelBRMCtvdVJmUzFYV1VNN3ZGSW1qL3lMeVVVcTVVMHNEMmZTUU9LdmJJclNB
        VWx2VW5GUExtRHc3M0FnREJYTTdWcDVMdEtDNnpsZVZ6cXYrVW9lYkswUEIwbjZ3
        OFBuYTlHNnRoM2o0Y25kWW1ucmVoZm5MWWpMT1RTREVtakpYRDhXSUhSeUlYbHU0
        TTVIRW5ybGxWOUJHU2NZYURIM0RMd0dpTUZKZ2szc09tSEd0Zmt0QUtyRm1uUFJi
        enBaS3BqL2ErWitGSEl5TWQ2dkg2NFA2Qm9Sb3hsZjZCOXMxWmJSV0o4ZHVva283
        ZzZxem5oSWxKZGhEWktKZ3d0ZVFnSjEyQVZwNGFyMytWcU56ZFpjbGUvQ2JBaEpF
        cmt1VUp6dkJYSHNvSnNQWno1VVZlcksyV0c3cXE4SGlITjFaK1RnWktHbzE5SnpV
        ajMwVWpRM09DSkNhaGFpUklYUTJzVEd4K0M3RHIyeVZKTUdVVTFFMTRlZHI0aHNK
        WlZUN0dNVkNtTElRd0JKTWoxeFJDdVpIcENJV3ltNEdMSkdQVUdLcUpOb3pHcDNU
        U2RVN2hrbEc5bTU4QW9Jd2RKRTAzTEsyZTdHaklRZVdYZ2FvSWxUaGRPV1V6Nmtr
        OVZ6bkdDS2ZRVzR6Ly9zc2RQNEZQSFhCWVA5Q2NneU1iMTlDMHNrTDFVeFhJZwo2
        bk11VWh6djdBaWVmWXptY0hKQWtheE5XeHBiK3hsWDN1MVBEZGprQTlvCi0tLSBC
        Y1FRQitnNGZmcmpxSmJDbEdxRmI2N1FmbkxRWmRseEtyQnVQUjRNd2ZNCurhtzj7
        pHenFRuHPmv8bvyL87HubEjNGmNXDUxle1sofEKi/ObVfSbnzmwMNFCcw3iRM75Y
        t7WoiOw5y5m9YfM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T14:41:37Z"
  mac: ENC[AES256_GCM,data:izTSf3xy5dg1mMaow82mv9sf5fxWTVwbMuKtgVupugvGhS7LYfQdBO51Vo8p3gjnBtffprEj/RtkuVWB1X8wK6UJQKF70eWdr8NiQRU1BAfL8LWltDCqma5Kdg0oo4lZZnBr+/UKs0R79TXxQ4U4rp+FSBDqXNXCMLwpYLaDZBw=,iv:DSDxTBLUToDeYwKFowqmUFFzdigboF4Jp9hWGTpuZ+o=,tag:+8YxGcE1DJc3H6l9ha7CPg==,type:str]
  version: 3.12.2
