apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: default
stringData:
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:wYeTpnGSQEG/smACH7JAkMN9fkA=,iv:G2SbHwnM9dG43Wc3rjFoA4orPrgMg7VcPfXQPNS2CW4=,tag:ZrKd9fLvEsMJY3hp+tF8KA==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:jiV/ySPm3GBShCgnpsNh,iv:niQ5RI50Tm/8w3yGs1znDd4I6tGFreABob44MQg3u7E=,tag:owhtlgy6wBS3wH9eIqN5kw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:fwU5E/rPk/olYmGV7Rv9sea/CJ0K3rCixHlGSyc=,iv:wnT9+/aiarWsFip4RH7Ew3IAODLwlxJLqJkmfEcYDdo=,tag:ltnko5QVQp49cmmo0NUAcQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:R5+XHpgBkb4=,iv:W9R8/xHQrvEnfOntfRdpW9Rmwrd7L6ePHTyca3Gi7j8=,tag:rPYeoCs9dlHMsDDjL2mh9g==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:pQRFpleBDIGcmWDJcqo=,iv:AcucEk3HZPhDy8P2A0hh9ZAiXSs/QizjUy+kMIszNLU=,tag:90/AEiBFAEds3/3HTnkh7Q==,type:str]
  FROM_ADDRESS: ENC[AES256_GCM,data:IbnpRogDqNaa9SO4FZe7D/FQCQ==,iv:BCo1YhdDEdzq2/I7QOv+SpxXHmIJ9fNGb/JsrhFkK7w=,tag:+diMpCJRbPuEbx6hzPkYhQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:SkMlfoJvruoM,iv:h3ru6PPcCrqbLa/B20+gxLBcUzWSS/03Ga7DdOd1Nd8=,tag:arAIWPDjBh2yPZ0Sc22VzQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:LfHl7PutvFRa8lJzBnFLoHoQo7ru35N2faeWy5X3LcBJ67MiakmO,iv:LLPRf6BSDkyKx2vNtd/DkP44wS7RC+KbAMYY1/MpOk8=,tag:G0+NbEpSxV5qJRD8L3X3sQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Tfj44gXzF24W,iv:HSSqrUuTo6HPhMOYR4NZ30yFhuOx8CVrFizJrYTVB3w=,tag:wcddSf/JaJzndPjL8GD+1Q==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:LGbrhnlYil8=,iv:DjDlqOaCuN78xDS/PfKCF62A2+il2oHLnHKpFc/koBI=,tag:HI175tfBJqFaP1znQQKOWQ==,type:str]
  replica.config.php: ENC[AES256_GCM,data:yyFon/rGNuEvSRPp69F81bvpKoZstpA1kAKHnlO9r2tsuHPkM4mzIjNTiKDzs2JmKc5JB248s9sgQFl0mSO+ArKKUKrkL4ZJSzY9w652j9Ns89/crQlML5B1YJGpE56kpUfOEswelZdaZcI2cIqWB1bnLdU+6C02WgI1MEa12IteunbuixTrR7oZ3eQfCjvERrCrdhoLjR7VtM3SSMK4R3gj4M85ym+wDnn1KI8xz92QNinbJYicHi5mgb6Y0aBU2QJlvgs6Zk18z6uNpI5gUek3advBI5xWffaWDlcO8/mujOIAJ7sDiFyMspM6h2CzTJpJ1j7lQg==,iv:1gFi2GbaqsGZs3/xepjTNyjPHTvZk1LvNKwzrioZZjE=,tag:QLjPzMThuvKyKnGWfZ1mTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicGpxcU5DZTlkTTdGQXlr
        TVNrekVIaTRCQkgwWi9rYnJacEt2U2llYVgwCkFBZ1hQeUxlTy9YQmJRUVpmcGNF
        UXYvcnBMRkhJdjRqT2JGNWZmc3RwbDgKLS0tIDhERHhSa2IwUC94SXliNm9yZ3BV
        VHJkVmhYM1JyejFHblkvZUxMTXF2SFEK66BrQg6quRA/u339aatlqKCL7jFJdS/6
        swg68gaHfFxKTTNgdsB4+2l3TmJtyH8RVs+vy5A/wyGX+h63Ge9aQA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IC9LcXVZano1
        WGExMWU5REZpYXJzUVNsTGZqblRPc1ZmMG9CdHFkZXd1cDFTakpST0hQUHp3WnZQ
        VEtoWGJsYmhrTlhXeHlvSVlKY1pRcDJZcmlqbFdmNVg0ekdUU1Q4SzVjSWgvVnox
        TTZ3S3N1eCtQdVd5Y2MwVlJiOTY3VWFyZ1ZZb3hjM3Y1dnJhQS9NOEg4Q3I4UHBT
        WDdxc2tEcHZQdFdJYzB2R0xUQmRrMHd0VmJzWlpWeTdnem5HeVF2NjVoaEtNaXIw
        YTkybk1jNkF6bktHNkhpVEEyYzhuUU9aUVN2Z1FzTFI2VjdLa2o1ZjdVZUljaVk5
        bXQ4cGNzN0ozbFVXRGROZHNIUVJOME5aUFRHMkV1WUtwM3RnTGxHeFVHYTZvUURq
        OWVqT3Q3TDZOTzYwcmZUempQdXkyZGN6YzA3QzN4TEhtWVh5SkxNYU96cXNpZDJU
        K25hR2RSUUpWb3BJQ2RSMTd4WWcvNTVYRmRXNXRRSFd2bmpsTzZIbHBFb01maVhx
        b2ZmV2NUUDlqbkFzWjVZRHEvbFNTd2tZZml6WDB2SmVxV3haQmUvRTBISkNQL2sv
        clRtZ3JzWGVTRzNxZWN5cUt3NUZMTEJXT2F3VHozTE1BV2wzVUoweTUzZDBvSnJw
        aHJ5MWVialY2UUtEdldFWFlWZHJLWlcxWFhtakhDZ2VNQUdiSm5pS0dSeE5TVlV4
        SDQza1NJNDJnTVl3WXVoNkxVa2c4TTNpK2VnT3VGVUs2YmRoelgrVUVDNUxCT1JJ
        aEJhdVAvclhLZFdKTTdmbS84TlhwVitSTldKczQ4Sis0RDRGbGhzbE9rQTlPWVZl
        cWJrT0hhUFhkbnNjVzFrYlBheHM1Mlo1SXoyTUJvdG8vbGhzVlo0aVlKS0NHQzZF
        WjNKRmU0RWlmelMrc09VMGN0KzU1d01IU0RKVlAvTFdLUVl2Z2VXeEdESlRKQlFT
        ZHRQTDFBZjcxb0FQOThFcno2KzY3VE1XVnhINXo3VEZxU0ZrK3cvcWE2N2x3cnNJ
        bzlTMHhoeWdsOFVJcUFMYzRrZ2FFeXB5cVovcHF4ZjR1YVN2NnVVZk1GQURvM2hP
        Y1U1TWw4ekREZi8yK0RJZEgvSkNQUldoYUhYZGdtS1VBRXdLb0RSUXFZVmNqbUFK
        WWprVUhwUlZaQ2RReko4NHptMGhCOGp6OHdPY1I5dm1uZk1XRDdWZk5kSUlNYjdr
        UWFpUUFLWE5KLzVnViswTVZxUkNsS1ZrTkoyWldwM0l5KytjWHUxanZHNExNTitB
        dWFsb1R1TnJnaG8xM0ttbWVKWnYwTnoxTW5Pek9kUGhwK3R0cUd5WnR4UmdMZE5m
        SnZTMVpwV1MyaGMvbFdTMGkxTWlCZUZCemloVG51VzZmTEpxK00zN3o0bmlpeFBJ
        NWF4YkwyNGNXZE8yNEhTbjNoZHJoM2tiVS91WlBmWUdKYUgwRkkxQm9rOUZMYWZ0
        OURyeVQwS1cxY1FUUGZVTHl6NzF2Wk1JT0dob2l6RVIxeDhERWV4ZnVQTUJiQzFx
        dlVYdzZVWDdoazdqV0FqVS9PT1pTOGNDbWJiWWZvWVUzNUZNbktkc2ZkMEtwM1g2
        bllkTVpKaGdlSWRsVWxkVTVrSTFpYUx0bVZRbXJ1N3A4REkxQkNGY1gxcFRqQnky
        UkdSSmU2N0hZR3psbHY3eU1waGJqRGtVWGJGSExPQW1Bemt5YWlBQXBINnFhdk1j
        L0gwMzlOMmkxbVdSOHhsM2ozT1B0ckpyQy9uQ2ZpVUVQNERYK1FnYzBuUTM1RWNS
        MHUwaDFuTjBkdGNxdkFNRmtoNmZnbXVLS1A0cnlVeG1JV0dVWEUrLzdkQ2Iwbjcv
        dFJLZ3BWbnpNYktWTHlvcmQ3aHpYWStDaHpsU0orZ0ZzY1VuMTlqYURxei8xZ25p
        U0tlcjZHTSs4SkdHbDlHQmNHZGZwNlFXQ3E2YWVpdE1QYkJUTzVnVW1SOXhkdwpF
        T3hUVE16N05ZbXhOT0w0aE1vYjd6UkhzdUdZdnNmcWRlZi9PZEkyMHpnCi0tLSBx
        SmtIb0x5NXNsNE16ZVM2OHVxOHZzeWdwVmVQcDF6RlhSNTlJUnJLay84Chlaps8/
        a7IZml1ZCzC6nhfZzWk1MfKHo+q1vzOlMkv9eCK22/uKU+RwyLWhzYpVzkLuZfry
        DuTuII8/BOQ2LCY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T14:41:37Z"
  mac: ENC[AES256_GCM,data:izTSf3xy5dg1mMaow82mv9sf5fxWTVwbMuKtgVupugvGhS7LYfQdBO51Vo8p3gjnBtffprEj/RtkuVWB1X8wK6UJQKF70eWdr8NiQRU1BAfL8LWltDCqma5Kdg0oo4lZZnBr+/UKs0R79TXxQ4U4rp+FSBDqXNXCMLwpYLaDZBw=,iv:DSDxTBLUToDeYwKFowqmUFFzdigboF4Jp9hWGTpuZ+o=,tag:+8YxGcE1DJc3H6l9ha7CPg==,type:str]
  version: 3.12.2
