---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm
  namespace: &namespace ai
spec:
  interval: 30m
  dependsOn:
    - name: litellm-operator
      namespace: *namespace
    - name: cloudnative-pg-databases
      namespace: database
  path: ./kubernetes/apps/ai/litellm/instance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm-operator
  namespace: &namespace ai
spec:
  targetNamespace: *namespace
  path: ./kubernetes/apps/ai/litellm/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  wait: true
  interval: 30m
