# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:PE3QAd0XVvEQe8ULDjSyIrMS2e/LQxhfo5ej1JMLFlV8Ssd+Xki4n+vhYtOQ+/fkjY/v4aHnzfcDSVK04GV9rZDD0YyYjR0mBdnFep4co5a8e1nqYh1dbilmH3TWfBm4yHLG8fxOln/bbvFNuRo1aYny2FbVmOK8Qec3nnBvY3VAgaCaHBMxMYw/Ce9ObXlkzV7NU0bY+vLlo0ayP1BAXTpd7ZThfongfAbSv0SSpCudDS0jLw==,iv:hv8OedXR+ayW5xLUdlkHBxgtkKEi1IjKIM3/PE7Io6A=,tag:DyKO7Zbwo2TGgegwzF1+iA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHpwT3c0aFhW
        d3llUE4yMjdOaFFDakZWZ1BjQSt2WTNSelhLRnNpczRPeHhLRVZOTG5mYWc0WUFS
        NUd0NmlpbUxxcCs4NVp3RXpOV01wRnkzc2tjRGhNc2h1SFVyYTJxR1ZlYzhzMG1x
        M1RzNmNROTVWcDNrS3RQU1M4R0pXRkpGM0ltaWRQSjU4Z1VUVlh5ZEFuc1VXTlVM
        bVYzME5QYUl5bTN0QXZTNU5kbHN3RVFkalNrb3ArUTVMbHFnR1hGK0FZOEppVUFS
        TUNUdDN0b1VFb1NDUUJ3Y3FnN1o2bjZpRm82NVpNT0lKa1Q1T0E0UGgwM3orU09t
        QzFRaDdVLy91L3RtUm9ZUUcycWNhTHgzb2s3T3pBV0FoZlR6ME93d2VLL2V4dkd0
        cG15cTBxK2RIMG55ZjdXMkNyM1Fwd0daVFJudzRjQ2F2SURmZG90MnBlWVp4dEdV
        ZGVSc1E3QzRxSFJnVHlGRlNKOWYyS0NMN1Bya2ZnaVoxem1TSzQ0KzVqRTU0M3p6
        OFIrVzBtQ1VIellmd3FhWERhTTQ1Ymo4Nk1hNHNvS3dNZUZ0OWFNWnRYb1VFdmVQ
        aHZid3QwTCtlZUJpWHZ6ZnJWeGo0bm9CVVd4bytlajF3TjZJWExmRm0rWlRHTkpD
        aFZTcE15NjFDeVo5UmRXWWoyMVV0VE4vV3FEWENNaG0rcWFNSTdmVWhYTjA2UXFn
        UlNtZS83WWZnaEVhSkxtMmF2M0ZLRUc0SlIyUVpOMytLRTlscXQrR3Q4L3lmTUhP
        bW50TmNFMnpCZWhadjRzNDNOYWowU3VxZk4rNlQ3cW4xcml1R3RabFNuVUV5NzUy
        REVwQk5DSHBYVjNTQnhsQnd5NlVMUzlQQTNzZEs3bTI0bmxmREZLd01nRENTWWZQ
        OTMxTktRYWlwZEpIRm5wWWdmeUgwK0dkU01CV2gzUnFlZVdhMHF2MThteXNHa2ZT
        dDI5NnFRbkdNWnJoSHBGcjc1cnFWNE9BeG1jUmxoM2ErcW42Qjdjb09tQ0xYSWZn
        U1FpUU9iV1psWDBTSmNPSmlyL3RYalM1SEduMDB6Y0xEWk5JUjBldlhPVENxRGZY
        azJLUUVDck9pSXJEWEpUaStDUzBUOGhScFRFalpnQmozcnpFN2xXWEk0K1Nsdlox
        WGEwNWkyelBGWC9jd3pJTllHaEpuZGFYdFRZVzR3LzZRcVhpSytlV0REQlc2WmVm
        SFJPKzdnNktzSE9YVHdNS1lLRExTazJyT3lTcUNoblkvYXdlN0tmbzdXOTc1NmZI
        L3VXUmhSK25uaTRkZ0RaT2t4bGxtOTZZNjdpMmJMTzBNWlBIYkcycnZnNG5QTTgv
        bEVaVUJSK04wQStQdzJnY0hDYU9reG8yeWJieUU2YnVsQnM2R25uWkU1L2NmZHRI
        ZVM5Tnh2b2kvd0VYcllscDFOUG02NTlmQkpNcVpiT04xZTBjdldvZ2k1VVRxN29z
        d2psUFFoUWhyYzdraEF1aThGUS9PT3JZS1pnQVNFTUpLMjhBUHRYVEJOOGQ3N0Zt
        dmwxbStyQ0Mxcjd4M2N2RGQydkl4eWc4L3RlME82elJ5ZjRWUEpVamsxMk9UcXRJ
        Y05iWmtJQmtKRlYxTzQwcUZvS0cyRklqZjR2a2lsMHN3MTZUNEhEMFpuNFRaNnV0
        d2VaSzhwbEVTVFRsOVB4KzZISXR2YVVDRklqK1NTUW9sRWFuMHhvRDR3NjYzK2po
        M3ZZbEtrMXhRanZIbmJQYTdYbTBFTUdVUE02TnBpZVhmMXdhNEZnWHNBbUJQa1Z4
        UmlEWTVRYW5FUjdMY01KbFNWQUFucnJNanNqTnRSZ3BRRStWOUZFTHlJMnpXV3Zu
        UmJKZThCVXBsYmorMDNXWVljbWtjYzJBcUJiQTJjT0RqMGs0OUErUXlmcVdaYmZF
        aE1xSnJkdE1nNzFqKzY0ZEZzcTFXS1g0dEJ0Y0ErSDR6alFmYkFoSzlLbEtGUQpR
        cFRBczBLRy9YNkR1cGw3YUJDQmxxeGZiUHh5bVNIeUNiMGFsbTRBekFrCi0tLSBU
        UmQ2NXdnZlBKMEcxRSt2RVU3VXpaVXJqRXZjZmMyeUxHbG1ManVsQWFJCuVGRPt2
        Dd+QVdZ035eIRfn/USjJ68bTdMwf6YQ4x0J3In+S6XmQWYplDnm17qkST+ojcB3K
        WVGML1fGIwu/IbE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-05-03T13:31:13Z"
  mac: ENC[AES256_GCM,data:bk72T32Mt9r1zkVSAyyI4OLRKROMMvNu2aJI4yQF1j2+gbWvldARQXY+uwL+nkb4XbR0PzgEiMsCaR/xF3Ikz2pCBYs53h9lekbzMGpfX9bBtJDEcMqmGipes9mcH0FGLQAljJQMhC5pxvfbBaJdpoqGuWHM3tiUDhMFkrrcKvE=,iv:Wy8NeP9kqHl7sQHkFAildRhfVwh4VkQIGnfszDR1hz4=,tag:SfF1ksKwwXKpo0PsDqfqrQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
