# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:PE3QAd0XVvEQe8ULDjSyIrMS2e/LQxhfo5ej1JMLFlV8Ssd+Xki4n+vhYtOQ+/fkjY/v4aHnzfcDSVK04GV9rZDD0YyYjR0mBdnFep4co5a8e1nqYh1dbilmH3TWfBm4yHLG8fxOln/bbvFNuRo1aYny2FbVmOK8Qec3nnBvY3VAgaCaHBMxMYw/Ce9ObXlkzV7NU0bY+vLlo0ayP1BAXTpd7ZThfongfAbSv0SSpCudDS0jLw==,iv:hv8OedXR+ayW5xLUdlkHBxgtkKEi1IjKIM3/PE7Io6A=,tag:DyKO7Zbwo2TGgegwzF1+iA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZjRzd2R4UW9vazJtWVR5
        bnUzYS9EaFZ2K05ZeDFRcVJneUYzU3lBNURVCndabngyT1RPbk5Wa2IzaENEMU9a
        NUdsRllBSC9PelNvTEhMQmtnaWg4V1kKLS0tIDZ1bExJOGJieW4vYWlHOEhYdWti
        dmo0ODBFdWNuSUNwenowMXVaSU41N1UKWCKNnQuiUEyQcqUOTL9mQ/GdYSUnyCxp
        lKqDwlQaFgtSxHDSMyl1bO8FyyueS+kltwe5J9CVceCIT/+cDSqHDg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEN6MXFGNERy
        Y2lWQ0tsU0FOaWhWVEViRlRTc3pxNStOc3l3UnlxUTNVcmkzRnZvZUFPU1M5Vytm
        YW9KRWZNdUdXb1p5eWlQOFBQWC9HSzFIMzhrRjI4L2NzdnJ0elZsQ2xQY0UrSmI5
        eXgvUHVtdXBMaEp4U1JCVnF4dGVNZWxuWjlxamhvVkFlc2h5NGw1SUhSUUs2djAz
        bkExTjFPaDQzbUN2V3ljNmhnZm5wQ3hEaDZWR1I2SjJxV2xQc09RdEZUZmVXWlZ1
        YXJLTnRSZnU5UkVJQW4yZUpFQ2E4SWN4NEQ0eEc2Zk9SM3krNWhyVGtJK1d4QjJG
        YzZVRkxmSkw2eUtDbHV0Nm05T09TWUJCemsrNzBLWUl2czUwNDgrZUJ0eXRmaXdS
        VllYM1IvUUxLMk5QbVVuYjM5RXVpZEUrVFJXUjAvWCtPNmN4YUhaU3BJR3hQRjE4
        QngreGt4RWhIRHFjL3ZCdmZXK1lOQ2MwaTJGeTlHdkdKWUtpUGY3VHRaWnd6YXF0
        TXhZOUY4d2VzZlNhUWY5WE5BWFZJbmI5YlYyY1NMU0ZIQUNoUTVFcE5KRXJ6OVFD
        eSs1aTN0bk9vUHIxN09OcjcyZHdBNHo5N0tzSktaZFdTdGJqc2svTVkvZmwzSU9o
        U1B1c1hnalo5MmNqdUE4R1ZSR25ET1FUeXV2bVpsT0RLbnUzSDJCdzd0UmRuZXBn
        d0tNTTVMZE5GSlhKS2dyMEVYTThMa2JZZEZtamhSVzFWQkpvY1AyTEp1NDZxVVNX
        VUxoZ2ZvZDNxdGxZSWxMOW1WbnVZbCt1cm5SNEpsci8xUElWV3Q4YWhrWG9qMHJU
        ZGtsOEROdTU0VDRZbnEvb1FJd0pCdTJhaktaMTltajdmUWU3Y0R4MDJ0ZWJJZFQx
        WXdYK3ZwT0pyTzFVTlFOQld5NWxHVGNjcTdmSnNTZkhZK3FXKzNtOGF3UXY4aEJF
        bkRzREhnWnBidWpWU1V5eUQ4RmQyWWh2Zkk0cXhpRGR0a3o4bEZSKzFSdEJKZGlw
        aEdOTmUrZFgxT2Q4QlppejhKZTF3M0NjNFJET2ZTa2R3c1lOWXEwbTR0bTFTdXRG
        aDR6WWpWRldURXJaeldBNGtKcjVYQWc2YjdTMkJQQ3ZHdllwamN6TU0yWnVLVDBU
        V21QdXF2eEVORUIrQStQYlB5eWN5OEdMWGxHbVBxOHludi9UYmhFVnJOSlJqNXcv
        NlhjcUhCSUsxaGdOZTJFRm9ENnFkQ2pFYnlaV3o5Q212VnpTZzM1aXJscmZ6ZXhN
        Vmg0anlkeENYeDVqa3IvWWlweTBMUjJaMDJncFh4c2MybGFiNXBhM1ZjTU43MHdn
        MWozdE9MeHRIODI4K1BGZEhmN3BtbFRUaGZ0cjIzNnFDdkhzMjJrNGFqajN3ZG9Z
        TUR6aDFPdkNkS2ZBR0JBdFUvOTJQU01mQ0VBbW1lN05vZkQ4bGE2Y3NDN0hycml1
        Z2cybGx4dXVSdmNIdFF1cmlJQjdGR0czNXhkNkF1ZVVFYWFWaU1lY3k4ZE9SNjVh
        TGR0bElQcWtlSTRCUzJibWx0R09nMjN3RGNMRTd1MXdMOEtQeFUxUGxTS2dsUGZY
        MkNNT0U2dVR0enNpVGRReldoQ2tXWTd1ZUl2c1RNNEgxQTRyYnFpM0NtRzRNNWIw
        KzVjZ09JalA0RE5YZmJ1Mm5xY3k1UGUweVB4bnUrTUpOL1gyZEVzeVJxclBSOGhh
        ZG9YTzNVYVpXamt4UWFObm1iV2ZyaFRFU1UxeXZ3UDNuUEFWUVVlUmd4QnJCcTdn
        L083c2paSHptQXRHK2xaOFNyTDM2ZStXNmVuREhjV1ZmVmo0ei96d2tyT2NkSDJN
        RjZmTTFtQW1ORDRTaEpwRS92TFFEaEZxWUFLVStDdWVpbG1oR2JzY0pEL2pKbGdY
        S1czQTB6Wjc5ZXZQemwzYWVkYnQ0M3FNZXR2WHNjL0dkaHY0WWtuMXpHUWVSZwpt
        T2VWdHlFWWZKL3cyS3gvWXVadm1POVo3MjNOTEJKajdYWFd6VVRlTndFCi0tLSBt
        NThrZzlaMDhsWmx2alRpQmVQM28rRWhJQk5ad1hobzhvZ2o3c1RtVHJZCsba5pBy
        ohSACXoHRyLzSLAlhaiv4dO5cyv+Q1kxUe1Xs0d5YKYdechC7gQPNDN+MqM3iEQx
        9d0fse/BSolvtrM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-05-03T13:31:13Z"
  mac: ENC[AES256_GCM,data:bk72T32Mt9r1zkVSAyyI4OLRKROMMvNu2aJI4yQF1j2+gbWvldARQXY+uwL+nkb4XbR0PzgEiMsCaR/xF3Ikz2pCBYs53h9lekbzMGpfX9bBtJDEcMqmGipes9mcH0FGLQAljJQMhC5pxvfbBaJdpoqGuWHM3tiUDhMFkrrcKvE=,iv:Wy8NeP9kqHl7sQHkFAildRhfVwh4VkQIGnfszDR1hz4=,tag:SfF1ksKwwXKpo0PsDqfqrQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
