apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:SzHKmuAp3Xw=,iv:y5SfzkhN55iOAbnWhnC4fhOJLM0zKA5h6gJxcYcTYaI=,tag:UaIWcRdKPdC2tdC/hHuEiw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:Kww5vdpMYtDAt5jugGc/3jGxubGy0qrZ1SxTmA==,iv:+XV00OYsUX97XxgwCt0AGDjF4Y2IZxnOAyG8XtayFMk=,tag:KT8YRdEKz9OSoiRU9gDTpA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcFV4SWs5dFpEV21CbzF5
        UjY0MW9PS1Bjdmt1WVZCeXhTZWg4L1FNVlJnCk42REVsbTAxa0s4enR0aGhNbGpx
        WDFlSVQyRVJ1RWRGcVlTUUxkL09vVU0KLS0tIEE0RnU4cStCSmE5SmZLT0FvaXFX
        VnFWUU1zTEdZQTcvYXhoVEpXQWxxYjgKjDfaQwEQQ7iZTbDcgsxrTCSMnzf7ZWgt
        3M/uY9u6+AEr4Hq25561Q17tQM7fnwUD83JTDXVoZph6uD04AhEwyg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEtmV0xaRGdt
        YjlZUDNvYm1ZcmhQNy96QWZSa1RzTWVUL2FzNHFyeFdlcXUwQTJYclRveUFKbHl4
        eEsxbk9BY0lzaGdwUU01SUlzUXNSTHBkYk9aZDRlSW9sNkVIYXpEWTRtVVhJeTJs
        VVY0K2R0WGF1d1NYNGk5ckt3T3BRbDJDazhXZEwyMlBzekdXM0pZRktHTnE1bmxL
        UGVKNVhnMVp0L3NXMHE0MzlMZldkb3FsY3U3cFZZZ1VqWFJRT3QxTEE3UEhoRkNu
        K2RUVEhnVVNLUUFvV1A0dFVSYzk4QW5Ya0NKblhlZHhLc0IwOFN2dGJwdGhnUHRu
        L0JwZ0MrY0xBK3RVM1p1THpQeUhQTFdHZTFXcFFDNlhZS1JlTVdvdThlRHY3UHZy
        bVhrTjVaL2xEVUpJa2U3QVdCK3VtV0F1d0tPays1NElEa0Z0UXBmTUZtQ0lIa1FM
        WHRyc3RiRWNuOGRoMTc5czlZWkd5bC9lM1BsZWJvR2w1aXN0QmpXQnUwSmVTVFRL
        QngweU1Ha09OWTV0a3BoT3FBc3h3MXhDbXpBYVU0aE1zeU9xYVMzUHpIOXBVdnRD
        UVR3eFo0S0g2S2c2NnNDbEdaMjVESTZLenVmQzFJUVdSbmVjYkd2VHZRSHhzNXgr
        ci9WMEExaHhoOVdYNjlwck1kNzArRlFSTld0aFM0QkozSkxvVDJLN296WWNmUEJO
        ZzA1cm5vSlloWXlzT3NqZlo0TFdNcjl3YWR2S2hRZ0oxMWJQRTBsQ3U5U2Vpenk4
        UnFOclVXNCthKzZXaG1ORkl2TC96cjA4MXF0cGdyT09OcFIxRjVIZmpzT2lZbmx6
        YzExSDE2WEpmams3NW1xTGFWNDNlSStyVzgrSTZCSVk3STEwMGFZazBvSzdmc0dR
        NVJncEwyVTFyRnQ4QS95ZUxueTJNd25Mb0F2MGtYc1VKL2pkd2VBcUV3KzdhOC9h
        aW5KYnN3OVdraHU5bGxVb1ZEOUg5RTE0U21YbGtqeU9DZzkveTBtN244KzZ4Q1pr
        czhnZTNONGd5djVNOUpiNWlVL0RWb3JkVElxcGl3UmRGWkNpRDNpcThHZ0JJbXFX
        SllvaEhiUktKNHJkdXFJVWN1Q0hjNUlyVlB1K0xpYTJjMnFnNDdUZHF4UTIrcm9v
        Y0c0K3o3bmxuaE1xYmdNQUZJa2craG1MQVNhQ25FQjZ1T0hjN1VZQ2gvd0NWM0tF
        eFF5WW85ZmxWVUFCU0dlTThLV0ZycmVrM2Rjc3J2OENlWjNRKzJBUXNyRFdWZmE5
        dURILzMwUjEyaFRFdkZhOUNNL2NiK0VuSUFXTW00TzhiREd2MStXaW1SWmN6Smpy
        aDNnMkZPZkZaUk1sUFE0d2ZzN1pZMW9FR3U5Tjg0Lzg5ZHdXUCtLNDhFbXNLdW1F
        aWJPc0EvRm1KY2JmZ2lIR3Q2UFlKV21PbTB5NGFqVFdzZ3ozUHVkeUhWVXNpNWFM
        a0d6bmFXTmI3RnB2WGtpVTR4aWZrV3N6SWh2eUI3eTQ1QVJseDhIM2hjbEFUMXZR
        S2FMSUtXNTFjVEtxLzFidGFWYnhMSlgvbGRnbTZGRmIvR1dodUwvKytIMzhKRGJo
        WUo2Zi9pM09pV1VsTmlZOVBjVFEyemt2bFUrM0FzVGI1dVQ3bkRxd0Y0MEdNS1N1
        NHMvYjZDNDY4dWo0T0NENWhrb0QySkNwaFN0YnpxdUY0OTgvYmFLVUNHYWRjU1FP
        RVdYWlM0VmtFdnd3aHYzTHVUUks1bmduTmxZWFUrdUJsNy9ZR0pidjM2ZGo2dHBB
        TDIrRXpTT1RlVXF4VVBmcUFXZ3NXZE9QMkN4SmhaZ0s0ZW9Vdk9icjVNb3hzT1FT
        RW1hTk45UmxaWXk0dUdVL1A5TU9sbXY5OWRLVm9Oc29WRk90UzdFbGFsQ3EzWVg1
        SjBjcUZUZmkxd2lVVG1kU2NEbVZyVy9OVTVTNXZkSnliWlRpa1BYNTA2cXZQUQpN
        bU4xSDB4WVg1R1RKeE81U2EvNHoya2VFNVlYZEIyM0xMT3BVRFVVUmhjCi0tLSBr
        M2hvaFRqLy9MY3ZUMTlvM0MyanZXZmdValFBSXViQmJxZmszRXVDcGhBCmZhDEtu
        exUz7P3IQb29sYgRGzVK9t2SrqyI2ooupfLQplRldSRr9KxFMQEuScXXJsmjj26t
        PwmWg0rPhtHP+WY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-03-17T21:30:37Z"
  mac: ENC[AES256_GCM,data:/iwfbMfLVhNmvXdDodt18c7BDPv2MU5KxY8V1kNVmpQgbJsRYiDAbO/P3Ds42+YEqg9so36brKOQXhTmnRjjPpL/5hvfvXbsEYp3E+E28Txx5SJb1ZYfOmzvFPiI6nFeD6btV/5cjB/gGYtWa2lRxidMkTqSmWW0/GQ9/V9Nkhs=,iv:kTQI8k5vz6WfLfD7jm2hb2Jdw4ouMSXuFsBelKpxjdk=,tag:/PbuIfYcLWqh0Wx1z/p9fg==,type:str]
  version: 3.12.1
