apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
type: Opaque
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:8T3HVVJSOZgJxAc=,iv:0mZsWx1I/+FPvpuGkzvHuKjXsWvQxkjuti+6ZMjceUA=,tag:EZY02bG9pe2M2RqjrvkiqQ==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:SzHKmuAp3Xw=,iv:y5SfzkhN55iOAbnWhnC4fhOJLM0zKA5h6gJxcYcTYaI=,tag:UaIWcRdKPdC2tdC/hHuEiw==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:Kww5vdpMYtDAt5jugGc/3jGxubGy0qrZ1SxTmA==,iv:+XV00OYsUX97XxgwCt0AGDjF4Y2IZxnOAyG8XtayFMk=,tag:KT8YRdEKz9OSoiRU9gDTpA==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcHRCemJiTHdyZWFxODVI
            b2ZpeEFINko4N2FOd3loQkNWS2VzVDNDTEE0CjlVOTlsaFlXS2N6VlVGMHdFS2pF
            a0dJbDRqalJGQm9QelJrQjI3eS9TYjAKLS0tIFd6RkFNejBrekJXQjAreTMzYUl6
            R0JCNTJybk9yQWt3SFo3NXg0cDZ1aFEKewD3K2im66SLFhVhUBbIj69dvrsWvphZ
            c9ZORmLdDON3Argdorql1MfEGIV7y4E9HF62VVeJvzgsv156kxxP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:17:59Z"
    mac: ENC[AES256_GCM,data:CE/dq45G0kHJFxmzNtGjaltZ0yp9Tp2tnQQWIjpgpCFXYWuqekcXHABK6nlZiGeiP92puN1LZv9QWa29Qr5r5meSO3hS7RgSHqj4R5Y6Yv+pn8u6HypV54NtIYUDswjfBkHyk6S3bdVQGZu3kHpxUouASUKyJ4VtQw+3FksoGGM=,iv:8Az7+c4EiKl8WAE6DnxIKxA+AHFZ4Owiv7HBIHmDb04=,tag:kZOsCBFByJHklCTORhqNpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
