apiVersion: v1
kind: Secret
metadata:
  name: facerecognition-secret
  namespace: default
stringData:
  FACERECOGNITION_API_KEY: ENC[AES256_GCM,data:qpmLK4YPi7CdSvfrO1ng/Wbf/DMpdXjcYmeZz9Q5H2DBDXR8f+xXsNXTQwk=,iv:sUJYZw0iV5nPN/8bKlWQNjtY7KE83PTA/Q5Sq8fuM0M=,tag:9Zl+VKXAgLUET7D7DUnVgQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Uk5IakpjajljNFpsb1VX
        cTdWNFV4SmJqbHhPVi9zYkhOMUpmYlF1Yms0CnJJUWVVakhPUXFVWDNndndKMTRi
        VjAzbzFqT1Fydk00UVNvWVE5WWduNnMKLS0tIDZmNWM0aE9kZ2VxdHBadGdseGVN
        aFpqczM1UzVKZi9pU0h1WFdJdkRESkkKxLvXQPuBr7YMAz997QnfCOkWcTaTQDJN
        LcYe2ZPlsVmpIVUm4RX5ta5piyrS6QtBcYAzWsoSS2+d/Ymstcnr7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFVoTG9wUkJm
        RGdERVhKaDV2VWY0MzhvK2ZLWjArdUpWSUllRW9UQUpkMXQvRVV4d3pmdnF5dURl
        SGlvMjUvY3QwZTdOeExibXExWjRjZWJ3NVNsOTNvSnBKanM5cnRRNDdubmJrK2J0
        emJjcWlOTlQzTElydDB3K21XVWhPaW5GUmdlb0FON1Q5dEVKMExYQWJwODRCUmlW
        d2hpK2tKYW4vejV0YlN0VzBPakJjWGltNFFBVDkzWHVlSjQ2UzZZTGNseE5uZER5
        bTlFclNESUplZER2Wkk1Ylp3V0tMaG5uakpMYzN2Qk9xbUpUV2ZqK2lCTEt3Qmwy
        YmFOVVBIL2VpOGt3N0dKQUo4bGFzRzMzUWV1T3duNlhsWHZBMzQzc1BMbjdKWnpr
        WnJQaEwvNmpEaExGMnVYZ3hybnMzV1BwbmhwUFgxelJLdkVlenVUeDZuQXFYU0VD
        WTU4aThONXAzMzFiNmx1ZGtFSHYwa2I2ZUdZbFNjdXBGOGs2cVBoSC9wOS9iczV3
        S2tyZ0pubnM2MFVOK3hGeEVDdXZnTlExNHdXT2M4UmowdlBRUWQvenA1SU0yQS85
        R1VRTXU2ZHNIcGRHbEZTaEd1d3BkZnZFNlV5L05tSGIyM3V5MlJVREJNZGdNaGhJ
        cCtycGFWcFRaZkp5RFc0WFhrSy9MaFJsWVlwem1UYkh2bWNnbDJpWFJKSjA1dFRE
        eTNKSUVCZHBhQkNNNGRwTi9NTk5KYmI1SHdhelJWdnQ5UTBNV1piNWhydFlMWEFD
        V0V6RDRhVVc5OSt0cU0zRWlhb2ordE9LZzRXTTdUYUUwRG1tSFVRZllyUTRnc29H
        cGdTK0R5T2VUNCtRcVBIVGJieEVlTUUrdUxPcW5GTVBkQ2d4YlFxNkdSdzdIbjBy
        MEkzeFZVNFpvZGRyNkpyZzRtZjFWUmwvcmhJcDdVNEdJUEdRT2ZBYUVaSDVxQ3Zv
        eEJNUzJpRWhnTVJlcmwzeFE3b3JQZkZUNjlTWEphaElPZEJsc0t2QXVsaWZrcW1r
        eE5iYUd1V01LYlFtUFJDMjcvdTlzTU95T3N3OWZPYmJPWVBYeGJxb3JhVVozR1Fp
        TGowcElUMUFiVTFEVTBGbDBTRVhZdERLM2k0d0ZiRGc3djNLV3d6bEZJampyWTJV
        ZG1scTRRUmpvTmNCN0E0UXBjTnl1R255TXdheE9OSzlzQVVHUmw0bit2VTRZM21s
        NUZiT2l4bVBEYStrem53YlFFVmovdXRxMWhlQjRSTGFMYXVUcTMrY25RY3lMbXhp
        RDFWbERYaEk4enp3S2o2N0hJYjhZYkdCSFBsdnNvd2FUenRQQ05ROFV2dXhOUUtI
        QUNmby80RGRiZDl5cmVLRkZtNzA2Y2JZWXNLQWVab3JEZTBRSVdJWXdXREh1cDlW
        bERVY1BXUHJxWkU2N25hQzVGdXU2dldoMlkzQ0h2TERHZkdzcERKZ3c2SzBnNW5Y
        R2VucExkVUZvcjhLVnVidU5VUmpOQyswejJYNTRjWW00VUtUSWt0MVJYU1E2cXZl
        WW1LQzBLMkdWNU5EZC9LSklFb3orYlhYOUR3V1VOeXg4WnFYaDJRN0NDM1YvMncr
        YzcrY2xsZmN0cW1hOW91cnQ3Q1Y1RmZGZThtc3hFVU9iYWl1ZkRMdEVjWmhDNUxp
        am5sU2Jyc0p6a2EvK0VtVGJlaU5XVzVDVXhyemMwblVNTUV2amRiUTVOZDhEZUho
        MnNSWVRBZ0VSWld0dXc1U1JBYkV5dGZLdkJPTFl6VmNiVDNuUWY3Y1libGxacEJT
        R1RDeDFMMVBJZWxHUjFreitWYkd3VWI4YnVrbkd6VGxXdUJYdGJTTThGUnp4aEQ4
        aksvTlFPNndaTVJDMkRUcG5sUVpObE9wc0paRDNuZWkwTlpnNUhROURYT3N2aG5s
        bGpHNldIS3c3dDBJNUcwdEZlUTU0RnZIdU9mK3Q0cXZkckNFM3RCWkJpUmRKdwoz
        RnI2MTgvajRMajZJTXcrTFA0U3FuZ0piVkdmTFE2bHdJdXFlVmNWajBFCi0tLSBs
        UzF1bzZ6bWxqanAySkJPOFgxMENOcXZxUE8wcXNTbWlJblNmYkhQbTdZCu6niqPB
        PXJa6Gbs8bRaCAtevepIqVORC05chTNnxcLDYAhO3yLVS1j+5e90CIKFRJdkb5Lw
        W+SRKDmmkuvzNsw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-25T20:18:10Z"
  mac: ENC[AES256_GCM,data:Nme56VYPA/wAj1e1dOG0AM6KsYD8P+ue571Ftim+W+jQG4J4O6hbl99Sdpj1E/nwsKhlRS6JLSpU9f4xsDsO+gLxC8VSvty3sQ7qdvVPcCdIsq8gt3MBYXaLPvn1v1CZq4yKfubW7r68/jk84dnvxSH/NHsRDd6Thu0NFSD3AcU=,iv:V/GknOyER9PB4RJveIh/Xz/ZUhcko3Yh88xPDEV/sM4=,tag:LQuFJD59X5n+hKjEfqx/jg==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
