apiVersion: v1
kind: Secret
metadata:
  name: facerecognition-secret
  namespace: default
stringData:
  FACERECOGNITION_API_KEY: ENC[AES256_GCM,data:qpmLK4YPi7CdSvfrO1ng/Wbf/DMpdXjcYmeZz9Q5H2DBDXR8f+xXsNXTQwk=,iv:sUJYZw0iV5nPN/8bKlWQNjtY7KE83PTA/Q5Sq8fuM0M=,tag:9Zl+VKXAgLUET7D7DUnVgQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEJueEdvaFdT
        bURxc0dEeG1leTVnbWcweHpIL0c5MTVWOUxaTGY4RE5GUzM1WFR6K1EyKys4aS9G
        dzhjS1FvR2N5S0w0TVltTGxjd1RaQldaaFhaK1VYT0R1MEVaVjAyYnRtR0dpRGVU
        T09hejZKT3Y5V0QyZm5HMTFsdHp3aTk1eExIRlFFOXlXbWNWK3JPbHRDRkxodFJT
        SWZEa0dzTzFtVjQyNXB4SnR2STN1WDZSWmZFcS9xMmQ3dmNxcDZaZGI2SnhpUUtJ
        LzF6SXdncFB1KzhSYk1Fc0F6Skd2RXc2eXJCWGpHNFFFcUtocEFFMWEzZDlkaUVp
        MUV6Ym1kaDJKWUFCWFJ2YWlVV0xWZlNXYTBBNUlQa0dobmtVMUZvZXZYdE9PdUhE
        L1BQc1FHMFhveGJheWJxeVJSek9DTUt0cTVxd2g5eFVXUldLajBkR3NNMlZ5dXdG
        VXp4UUpiakpTNzBrTFpnNXA1UkVxYlN4STNDaDV6YXQ2M0tFZjJOZ1BSUmY3VWlF
        OGI2WHNyTHk3QWRYTVA2KzBBaDZpdUdjWElkTTI4cWF0NjZiOERWY3dvamhpd002
        NFpmNGNTcTFhREhLVElaL0dka2QveUZMNmVZNU9ubER3M2NueHdYZ0lLeXZjU3No
        OEdKTGRURTJ0ci9CYWdvQ1daVElDS3NEMUs4dnIvMkZMZFRXN1N3RDZjYnEyTTNU
        bmtPaUxmM3I5cmNMVSt6L0dycmJ1NkdnMjNhQW1xWDNJbFZ1ZC9jaHd3MmlXZzJ5
        dVBLRDlqdXI2SkFUWDdBU000T1hwRXU4VlJvdXpqMkZRd0h3SytwR3VRbDY2NUZs
        NTdLT0Z3bVllYTVPMDExUG5ZL3BlRkR0bXFoazBORlU5YnI1QUhibDB5b3lWU3Er
        S0g5VUJQQmU1a04vWkxZZE1KcE16TjJLMFRVU0ZCU2FVcGdsdHMxVVJzMERLRVdo
        aVg5V1dZTnh5YWU4c0FXaDFjVG9CY1YvZ0NucXFjeWg3TlpFeG9TK2h5MTFWRzdU
        OFdtNlY4QUp6YVQvanV1NXhZMFM0blFmQVNQWUNvZ29TaUVGRmk5MmVxcGpEUU1v
        ZmJnYlR1S2lnZTIyRTBtT1dYSFZ3RDNlbjNnZDZTRmluWjVtbiszbnpYRTUxZ05B
        eU95dWt5Uzdza3cyVEtXM2l0Zk8wSGF2ME93UDRkVDJodVlodkR6MDhHWkZGTW13
        Wm52QWR6bEhXQlRYb1gxNnkzNVpuOUZvWldzRXVRYnd1SVpIdmpLZGc1Q2NQK3JC
        TUJDVzl6L0lKNVBOaHBnN1VtaEpNR01pWFVTUFlaYnBrL2JtYS9SbGhGWVhHK1pV
        WXNoWDhHZXpDWVlOL1ZGazJCUWRaRTJGanVNNzk2VUdWV0tPaUxuNFA0OXhxK0Rq
        dTRmZUt2NHczNG55aFlRa05VQlB3ZVBaUzNhWHVVRW5rRTc0anREdVg5MExRb3FF
        b1N5RW5wZTNSWFRpQW5vU0tJRjVaZXI2R2hYS3J2TjFXcE0wZ3RSWEMxZTR3TGF3
        S2wyTnhNcXJYR0ZteXkwNDV3amdhL3NlZEYxdk53NzNidDIxTkxYMkdSNE1KMzJZ
        N29oM1h1bFNWeEpLUDNWVXcrbGVudzB3NVFJMXFIZ0QrdXRXblArNHdZem9mSkk3
        OTUrYXhXZ1NIOEw2ekFLdzRuOU5OcWxFTWc3KzJDOWZxQlpnalBpUjhwOXczSnBY
        dGl5ZDVKL3gxd2V1Zjg0WnA0LzFJMmJCa2hwbmxuR3U5QlErZFJhZjdDRVIxSzEr
        M2h5VVVpT204bGs1a0NNbGFmWEV2SyswOGxyYlhrTmpraXZ3VEx6bmNaVmdFdVEz
        UWlFS0EzV1crNXRQaEV2cU80RGVMb05UM1AyR3JEVVFZSm91YVRBa3B6V3RpVTZX
        V3NUZ2xubmRJZVUyM2t5SCtySWxKank1bURKejdDUnFGN1JlZTN6dWk4VmZJUQpp
        bkljMThpZXVsVGQ0TXk1SVFLNlE5NjAwckhJcWNjd3QxS3djVGxSdEQ0Ci0tLSBE
        V09BRjcyTjNiQTNJYlB1YTFFK1E3TE9mQjVCNVNtcy82cFhBejUvZG00CimtaIK5
        +Y9DT7FGSwwnaxbv+gonPuFaVhHvcDInlb2PzbTLH5qcT2ZfP7cvQZjFYc9YDt+r
        C54LLrvIvP7L23E=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-25T20:18:10Z"
  mac: ENC[AES256_GCM,data:Nme56VYPA/wAj1e1dOG0AM6KsYD8P+ue571Ftim+W+jQG4J4O6hbl99Sdpj1E/nwsKhlRS6JLSpU9f4xsDsO+gLxC8VSvty3sQ7qdvVPcCdIsq8gt3MBYXaLPvn1v1CZq4yKfubW7r68/jk84dnvxSH/NHsRDd6Thu0NFSD3AcU=,iv:V/GknOyER9PB4RJveIh/Xz/ZUhcko3Yh88xPDEV/sM4=,tag:LQuFJD59X5n+hKjEfqx/jg==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
