---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: toolhive-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.15.0
    digest: sha256:a10dbc2044466651f2e283b7ac6b70c54a5bc6ab7ee4db1fb90e04d6d329aaf3
  url: oci://ghcr.io/stacklok/toolhive/toolhive-operator
