apiVersion: v1
kind: Secret
metadata:
    name: streamystats-secret
    namespace: media
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:sYD/LBZhsbywTQNLZyU3dgETSTeo734plZzL4BTPNyuxfUeCAFZZp+ofLKyqVfCbTXrkMmDrP7ZjNnlbMxd/krP1b6fCxiS0Cp8E4yfS4z70anIkIF1pawnHv/s=,iv:wX/kvLOsiz0J/10lkxMLhEkKf3zbimfNzeMj+0DOnfw=,tag:FYfqC7C1tkF8tcnWuqa1Qg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Fopz2MSSx1Vkq6xZ,iv:N59XhA2sxgL49LeJQQs1DvPZaDhmC0xGKBXc+uhxNwQ=,tag:/NahRDPBR92nb6HUSlmlgg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:J70cVEfJ0SGe/FY5SUAzwMbvgLPZjErLiU+VzSOOiywbARIksvwM,iv:5UNgzHOp5AmAKbkGX2zmocJApqcuFJ0nDP7vPFTZ/ZA=,tag:JMj6Ib+qaHPr8/ARJKlaJg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:KpEMs7d+8/qgaFP7,iv:Sz4hAtxNoHhvonm2uLFqYEGxgL1jiyg1b/CR6uflXdg=,tag:Dp3hvo0k/8dPGmubo8sNHg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:7THJwnTrrec=,iv:p5onXZOWIruZAiuF7MK0KzXtdWMq1LSWE2O3okEZcz4=,tag:WIa75zlR337VXmBgIu8fqA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:UR1MpMX44j8=,iv:ts8o98JA8+RA9sfDHSlReppzzYTagrdK82Ykd/OsqbI=,tag:ptlaZLg0layXXC4WKn7UEA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:aRfwJde0K2cxqJdvLjNidw==,iv:CMC6KOxrLxK0aYZCzR7yDIwcJ2Z2r6NhbUCrAbEFWbw=,tag:Zxq0BhGar82R/E1IBa3y8w==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTWFkUnZKaHhNOUpzb1BJ
            a3R4TUpsZDRrbTR0eDNGQmdDRXQ3bDZnbFdRCkZLRmNuUVhDSDIzSG90djhSVWQ5
            cjJyR3ZHcG9WanN4Skw4dUVJeGlJbmsKLS0tIHJyZTg1OVdqSHVaSzJLL3dYQWVX
            cXJETlJ2Si9CTFhKOVZscG52N0I2cm8K+AxX9+GQz3QAreS69wvQH5Lw743xrZvS
            A53gdIRwKNuTAk66i4otXEDcIIikDpktNfE3M1fAXqATh8gEr6AcAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T19:12:50Z"
    mac: ENC[AES256_GCM,data:BMpjAWn5g0bHJXIDVuO1Yebg4UsglOHwSBQbVgcIojjCUAM8yaaubCo8leZj0wbSiL9izqVBB6lx5OeFP0rNRlqeWEQVvfCW6xyENdNZOXe1yGEgq9krisAHIfVsIip+NuU3pcOtWd4zNyBhvC/I43S2eAvr76b9MhISy5vC5S4=,iv:+Dq2p5wdlUddRT7p1tbDIc0GU9W+JRlRz7CLm1IzwuU=,tag:r6DaJz6XXY8l/mwO6Yy+mw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
