---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: xmrig-guard
  namespace: &namespace web3
spec:
  path: ./kubernetes/apps/web3/xmrig-guard/app
  targetNamespace: *namespace
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
