apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  namespace: ai
stringData:
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:27kM1is1YTIfXkvYMrn4kQ3pAHFuw5CfPx0VNk4z1BSWRvNLkqVlZkS9rIdTPZQDY1V/9slS2Illbqlw34i5sw/i5A==,iv:7osd3VVWSOrXYp/0b6n2kkAzdiogxer599rH/5RZLc0=,tag:wGkEzszbOwSK6ScGpx2Yjg==,type:str]
  LITELLM_SALT_KEY: ENC[AES256_GCM,data:CEVOCmDO/KAyjID1WJy3zpoo2lIn7/9cynjZmbW/IvGzyz/hLhreIx7MWVl952UbFyNim6VZuiqZv+FcdmHKgaqEQA==,iv:LEhlPQD5g1ZJMVTzqpSWhoaYP53PDrVkIc1fPEcBaIo=,tag:c4ulSLJPCpyPvapLTGOExQ==,type:str]
  LLAMA_SERVER_API_KEY: ENC[AES256_GCM,data:t5tpsDY7rWEM39YE/AqI3drO,iv:MzQoZKdJUZJm7TRT7wrFhmQCShlCZO2gUJvtylTDzPc=,tag:XzayhUGu2ZiaC323rlZTew==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc25iaVMvckhiYXdENGpB
        djJUemdQVWZxVm5aK2dyUUR1d0JpQXRRdlRvCmhzRzVNcmc2RXgxRURsQnkwZTdk
        ckYwdEY3Zlp5L1RTUkoxeXVxckczbzQKLS0tIGd6anJNZllKam1wQ0Z5UStLd08w
        dVp2dWp5RmVEUEkybG9lc012bm9pN2MKQzL4hBSj+oQbG2JyyCzfFwqrwxKH9oTB
        cSGkFf320joidySkQWlo6HIZBGg84dVkceMcJg5Gprx1kjBWy2Bj7Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-03T19:16:41Z"
  mac: ENC[AES256_GCM,data:QIRAn07rRZ+jUmhS+Oz8PL24qlFYD5pWY6bBkppjuYFIoTuPmc0c/2bZrpccF9WAWLvnoY4czxOhAqjodQwaIpzk3sHRen3KobGR/4Q0B0bROJOnqJ5IkqJfVkbqHm1+5Sx/RZ8mt9fS3L4ZiIq+7YavJMaU7UsAKJDpawY8t0k=,iv:L1VpNT3lGfScbJyIFDQoHgEm0ouSIBRdg/r9MB9H3+8=,tag:2GCrzruxSZ2jf+GYRv1L0w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
