---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: litellm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: litellm
      app.kubernetes.io/instance: litellm
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
      authorization:
        credentials:
          name: litellm-secret
          key: LITELLM_MASTER_KEY
