apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
stringData:
  encryption_key: ENC[AES256_GCM,data:i0P3gNOaPdsfDcHjfPjedil2SA==,iv:OopkM7i4od3OoWfGlvENMD1Tx5O9O+JXeR4F7k+rqGE=,tag:YhRNUUKStBjNLNgDHUPXzA==,type:str]
  meilisearch_master_key: ENC[AES256_GCM,data:sqxcVOWXE3g=,iv:x124Lkxfxo/N530pUk5JzstVQeuJX/N5VTL1l1ApGrU=,tag:Fp6QshF0dOu9q917g+MOvw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEtncHh5NWxF
        Q2tReDhtMlBLd1pkK01KOGMvZ1psQlNRK0MrM0MvRGpRTGRzajBKSkNPYnJRTCsr
        YTl6Q2dJWDNsWURPRUF3aERQUCtuVUtkZ2x2cHUzUWdmMHQ4eEI2Z0xCVm9iV1l5
        RXkvWEppWmNFMlZpK3lhZytIbXhFb094MjdocWxtcXR5eUpFN2lmaXNFeTdGK1hx
        YnFvZUdoTCtOR0V3VjBPTVhIZ1B1dndWRTh3UmNaejdzOGs2MWhPajk4ajNFeHdS
        QjNLSHBveHA3MGg5eW05RFBlMkdQVkZpZWwwYUpZM2N6Y2FHTkk2dkswRkd5YS8w
        THB3WmlHQVVNYlByNDJQYkh5NGx5alZVU01SS2N4RUhQOS9YamJYc3VQMmFuNkwz
        L0U2RVcxblVLcFdZc0YrZjdjdUNLdURVcGlVLy9lOWRoeGVWRStaMFBiZHExSUdP
        VjNJd3FaOFhsbHpxQ0RvQ1FEVWJnRjB2eHZVTDlTT1AyM0xzODNHdVNCUW1mOG84
        NlVmRGFDSlZQZG1GTzY2MHN1MzNlQ2E1d3hPdUZQcG54WWxhU1pMUldlTFlZN3ha
        bGJBVDV0cVlpUTFZQzZtRVJZQUQzUDNsVVRCd0xPM2FjMWdLanJtY0dCbGtLUklX
        UVpkU1Z1djZTNnpUVllPeXlMM3orZkhvdUtzUFZRQXpQRnlpVTBmdmUvaldOTito
        Sjk0NkVkTkdMbDhYWThRbVF6eEZIOWlqTEhWb1Zrc2tldHdBdUhVbG5KUGpmNnpG
        WkNzYWJFUUJyVkNqSksvc2xFQ1liY1ZMM3psYzFaSExCM1l2T21DODNVcVowMTB3
        QkxZS2xmV2pjbzlPRTFrb3BQWndxTm9ZSTNtK1pmN3FhMFNxTytxQnVzQW1UaHg4
        U1ROeERXOVoxeENaNzduNE16TkNRYkduaUNQb3IxZm5sZytjY3gyU1BadFFiN1Zi
        cHJZRmtERngxOUZ5Q3A0RTFPdmdaUFZqTVlIOC9Tb3llQ2t6ZXlJZWNjZTc1c1FF
        MWY2SU1VTkptYnN5RXk5bG9FWFhCRkFyQStEOTJKSGROT2Nxc0RYSWQvOERlUHVT
        T0RwUzN0Y2tqRzdnbHJPWEJWK1JNbWYzVG9xbDZxQnNUejVoMlpyeXdBQWlZcE5U
        UnZsYXFVL3RZQmFyVEdud1lHRGI5M1BrYW5INkhtcXV5M1pXcEJBR3RLejF3MmRO
        Rmk5OVR6WldqcVRTVnJaRVUwMDgyem1ib1RuajVXWUtuSDFWd1RHeUxIekhLQ2Ir
        YWJzczJZQkg1S0l5bW9hZTI1NVprdUJaUHBQMlZhOEl0K3JJSFU1TWpsanpkVklW
        MW9TTkxlcEpWWGdwZ0hkS2txL2x1NE90blFnM1ZrMG5mdzBmYW5tSXZhdFg3WEx3
        VFVaSFFSNjUzdDdUWW1nOXBaallDdVdTaUZsNDFpdlR1c29Tc1U4Wko0NWJnaW9X
        S2JFaVJLN0NIa3dWeW9CQ2RqQkNGSGxmSEZyMUNiWWlEaXY4K2NPdk1ZRXVYWk5B
        NERZdHd1dkx5SlZTSnNEZENnY3hNd2FYQmZpTkRiM0IvSXZyRy9iUitGMS9QUEVl
        OUZDVGZhRzlYUmJZbm92MjdBdks1N1lLZUVuLzJTSHA5MDBIcDQvM2ZZblRESXhS
        TnVvSmJlc0RqZnQ1WS9QTTFGZmdJdVJ4eW4zMUg2Zk04Y0w1TFpUR2JRbEtuckV5
        dmJLcUtNMkdIMFlvamsveXc2dmd5L2p6WXRoY0FvbHVhWUVUWWhYRXR3b08vZkd0
        ODBJSDJVNThNNWFIWTZUeWlZSkNQaGpVU25udTNTWjFJT1JsaFlxMXlCS3ZrK0Y4
        UytCWmo5Z29QSXRSYXJiTEVoQnM2ektlN244SlQxUjh2a0sxVSs1NEpzSzdwckFL
        c0MvOHdZdmZjSi9DNklSMXFaRjkyaUx3TTFob2hxS1N1U1FON1ZMNjZVdWRJUQp2
        b2JaWG13T0dTT3l1STA4dDJwMWx4WFE3VWJYOEZJNi9ORi9DQ2JXNi9NCi0tLSBP
        ckc5SWw5TVp2N1ZWNm9hRkNpV3dTYjRsajFUSGZaVFJmc1pjZWFJak9FClocOcRt
        VAiHbgjH6wnlTTCukcdaCAT2QxnTWa4GyoQU6NHkr3am4FZ3mjuQnaTcJ05U92EB
        rDTz3/ei9uGJMFA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-22T15:11:29Z"
  mac: ENC[AES256_GCM,data:YFD0DcPCQj3F9eCU9nCHH4K9dHWP9xSZrW+o+MypcmzdEnarRdYL01G14HjzzbujqHV3wtOfNRsfzrAt6lnuCgnoice+0euN4P6OmONvyYgXn39e3L1T8Z742mhAEUVPQO6K/SPH79jF1wb8AGq2nQu7GFP8oHiqeOFaLEQ53bw=,iv:Tz6m2qtn4vrAtRS3SISBtVSflhOAgdhMve0kEhZMTDo=,tag:D9l8hDerCFeSU41ZOroaTQ==,type:str]
  mac_only_encrypted: true
  version: 3.12.1
