apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
stringData:
  encryption_key: ENC[AES256_GCM,data:i0P3gNOaPdsfDcHjfPjedil2SA==,iv:OopkM7i4od3OoWfGlvENMD1Tx5O9O+JXeR4F7k+rqGE=,tag:YhRNUUKStBjNLNgDHUPXzA==,type:str]
  meilisearch_master_key: ENC[AES256_GCM,data:sqxcVOWXE3g=,iv:x124Lkxfxo/N530pUk5JzstVQeuJX/N5VTL1l1ApGrU=,tag:Fp6QshF0dOu9q917g+MOvw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSERDY0doWXJ1ajF5aGZL
        U1FVUU82NnBXZVQrY2o4MmdwY29wemtwS1JBCkpMS1Z0WGRxNXpibFB3UmhjTitm
        QS9IWUhhdzRIUUdLV21nYUs5UXpZYVUKLS0tIGsyMnMrMlpaYzFzWUxDVW5mcUk0
        S01CZFVLLzk3L05aRm91Sm1FL05TQkUKAnX2XE4e3OTYWlxL3eLX5XBOLKaQAa5l
        jkXBzignxDprZkYN0mWVyQqP5Omk4nkArQZmWIULFuidCLBBCOYbWw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IC80ZUVZRWI0
        SC8yMU1DQ05lTEFmREhBL0M4V0U0NEFOTnpmSG1ZYVE4b2VHS0dHNWM5dGo1QUVw
        bkdjZ05mWSt2N0lXbTZsUEJlNU9vc0VBL3IxTXFPTlVuRkhseVFBS0Y0bjBTdFdv
        Qmt0RmJmSG9hZ1ZPR1VLL2FmWmc3QUozeXdINVl3OWQzRGsveDYrS01qVnVxR3FZ
        cTBRcmx0ZFhZMStvT0pIbE9lanlpc1hJMzZyc0VVOVpXVEtrUUVIbGlyS0ZORC80
        eUF5YXlJc0I2anJVTXVHaDJuc2t3Qm1VTDlKaGZWcmJuRnpTbGFkYlJMV3FXN2xn
        YW5vcGpPSkRpZWV1SDJMdDI4R2ovUzBESjBlVm94cXowaTFrWng5a3VUT2srUHps
        K2ZqUERYVUI3S2Z5S1J5QThNZWlTNnFoRVUvS1lDWm9OdVhJeW4yd1d2Mnk0akN3
        ZFM5L1FJdm1ydkpUVVdHWEhSU2t1cmN1VWwwdWZqL0FGcEE2S1JCUURvazNLVmRD
        V3I0dktHZWVQNUg1a0hyMkQ0aTRFV3RaVnhseVVqWHk3ZC9yaWFLd2NQVEVkd2cx
        UlN2c2ZyUXgwelBzcXRUWXdXbzVINUl4VjFOMFFKUUJNVENPUlJJajJBUTlLVnF3
        VGI0dmc3Y3A4VG1OaWRWK00vdEpsWXd3bFMyeFo0L1NLNXN1MnNEaUlPOUdjaGJT
        ZkNHVk4vZDI2ZU5tU1BFOG9KNjcxb0YzcG9lSE5SK1ArenBGQ0RRa1FRYVdKc0VV
        Sm96RHZoTzV5eTRwa0RiUktyVkNQY2hvdUdYTFVvYm0xNFhkcXZacUF2ajZvVTFZ
        d1dOa2JnN1hocGRvUWFtWUhpdDFId1hYdE9GajB1NGx2SDVSQ2c3Y0tXd09iWmdH
        amFucFBtM2MzZGt6b1h3VktGbGg5UGRScHoyUjZFSGFwSHVzWHp6dVNUeHRpNWVr
        N1V0OEFJY2pZQWVlYXp6OTc3UFRMcS91TmlXUmN1N2FFV1NPSHVRQVh5S3FCVVNK
        alp2ZXF4WE9ZZ2d0alF6U3BzQlFublVlN3FTTjBLa0tTSnJYSUhvLzY3TzNMUXlo
        b0o0MG5NSFk4OFM2YmorU3pCeVk3bGNRUlFSeERZTTBWUEhPczZIRjJCQnh6cE03
        cncvMmJyMGlzRk42QnlMaFZhUkIySWQvMGc1aE1FU29mL2l4ODlFQStYZjJPQ0di
        amdrQUl1U3Z2WkFCN0xiemd1Tm1pMmhQN055M0o1T050Nmd2QzBZQUVJU29FbUVI
        Ynh6WHJwS0VFSlhlbUZoZWpBQ004eWI3L3RmaDgyR3h0bzdQbkkzaTF5TzhNdFRL
        SUxCblk0SVFvbDRobTJlMEFFYVV3RnR4Q0p6NlMveUd4TEFMRy9Gd2hFbkw4QmFH
        d01QckhnOHdEOGg3c1YvRFJPcHdJRTJGVFVlWmVPU2lMRGY2Mkd5U2dMMklzV0pr
        UkRhdksrR2c0Zlh0V1ZDQW1XYklaaXp5SFNjRHpNbTdwRTlBU1Y2UkgyUFFySUNt
        S1c0NGVHRG1oUlVQS0hqTStoS0dFSndyMHg3eUovS0tpOU50dVIySUFLTGFNSmZV
        UkJKaXgrWlZIS2cvbDhlek5MV2JvMTJsSng0d2U1ek15YXoxMjNtMm04SHd4cmtj
        dWZaSUpIUzYzZFA3dWo0dlZaM3dtdHV6UHZrcEpMNm9KZi9ocldOV2tsSXR1bnFW
        RUwzMGVxaHpWcDRZdkJadHFFL1RPS1psV2R6RG5YVUd0UjF2bWVUWWwxbVFJN2Rv
        cFZUNUFVbGcvN2V0b1hrY25JdlA2ZTJLODV3V3ZQb2FkQ3lVaTV2N2U2a0VPTnlU
        WDQyQW01RWVtbURTWm9iM09Jc05BeERWVDNoYlhPUGQxOU93ZllXS1NYNGw5eXZE
        QUZSVXNGc3RyWnZCU25YL3V3MFFqNzJ0WnBOMmxjeGZBTTkyY1BvVzVkbGRSUQpE
        WFpkSnF4QXBnNzRVN1NURWxzUk9uY05MYnBTVlpsOVNZUllKUXp2YlJnCi0tLSAx
        N3B0MG9xcXRsSkw0QThCakdKaHR5bnNyaXlrc0l0eDcxb3NBOTBEQk4wCti0t57g
        x5RhCmLlSz/SkCQ8S8hXQrkNCCAnG/HRNdN3Q4HEeSFQra0jOapIdCm7wXfgus3X
        fTHgnTK5stdMAzI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-22T15:11:29Z"
  mac: ENC[AES256_GCM,data:YFD0DcPCQj3F9eCU9nCHH4K9dHWP9xSZrW+o+MypcmzdEnarRdYL01G14HjzzbujqHV3wtOfNRsfzrAt6lnuCgnoice+0euN4P6OmONvyYgXn39e3L1T8Z742mhAEUVPQO6K/SPH79jF1wb8AGq2nQu7GFP8oHiqeOFaLEQ53bw=,iv:Tz6m2qtn4vrAtRS3SISBtVSflhOAgdhMve0kEhZMTDo=,tag:D9l8hDerCFeSU41ZOroaTQ==,type:str]
  mac_only_encrypted: true
  version: 3.12.1
