---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-instance
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.46.0
    digest: sha256:cf0045bea89d79056c3e1bb1043237a1081c1abe1751fba493e546cf1039959a
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-instance
