---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-centauri-carbon
  labels:
    kubernetes.io/service-name: external-centauri-carbon
addressType: IPv4
endpoints:
  - addresses:
      - ${CENTAURI_CARBON_IP}
ports:
  - port: 80
    name: http
    protocol: TCP
