---
# yaml-language-server: $schema=https://raw.githubusercontent.com/home-operations/kromgo/main/config.schema.json

gallery:
  enabled: true

cache:
  enabled: true
  maxAge: 300

defaults:
  badge:
    font: dejavu-sans
    size: 11
    style: flat-square
    labelColor: "#374151"
  graph:
    maxDuration: 7d
    width: 800
    height: 240
    legend: true
    theme: catppuccin-mocha

badges:
  - id: talos_version
    title: Talos
    icon: mdi:server
    query: label_replace(node_os_info{name="Talos"}, "version_id", "$1", "version_id", "v(.+)")
    valueExpr: 'labels[?"version_id"].orValue("unknown")'

  - id: kubernetes_version
    title: Kubernetes
    icon: si:kubernetes
    query: label_replace(kubernetes_build_info{service="kubernetes"}, "git_version", "$1", "git_version", "v(.+)")
    valueExpr: 'labels[?"git_version"].orValue("unknown")'

  - id: flux_version
    title: Flux
    icon: mdi:sync
    query: label_replace(flux_instance_info, "revision", "$1", "revision", "v(.+)@sha256:.+")
    valueExpr: 'labels[?"revision"].orValue("unknown")'

  - id: cluster_node_count
    title: Nodes
    icon: mdi:server-network
    query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
    valueExpr: 'string(int(result))'
    colorExpr: 'result >= 1.0 ? "green" : "red"'

  - id: cluster_pod_count
    title: Pods
    icon: mdi:cube-outline
    query: sum(kube_pod_status_phase{phase="Running"})
    valueExpr: 'humanizeCommas(result)'
    colorExpr: 'result >= 1.0 ? "green" : "red"'

  - id: cluster_cpu_usage
    title: CPU
    icon: mdi:cpu-64-bit
    query: round(avg(instance:node_cpu_utilisation:rate5m{pod!=""}) * 100, 0.1)
    valueExpr: 'math.isNaN(result) ? "n/a" : humanizeFloat(result) + "%"'
    colorExpr: 'colorScale(result, [35.0, 75.0], ["green", "orange", "red"])'

  - id: cluster_memory_usage
    title: Memory
    icon: mdi:memory
    query: round(sum(node_memory_MemTotal_bytes{pod!=""} - node_memory_MemAvailable_bytes{pod!=""}) / sum(node_memory_MemTotal_bytes{pod!=""}) * 100, 0.1)
    valueExpr: 'math.isNaN(result) ? "n/a" : humanizeFloat(result) + "%"'
    colorExpr: 'colorScale(result, [35.0, 75.0], ["green", "orange", "red"])'

  - id: cluster_age_days
    title: Age
    icon: mdi:calendar-clock
    query: round((time() - min(kube_node_created) ) / 86400)
    valueExpr: 'humanizeFloat(result) + "d"'
    colorExpr: 'colorScale(result, [181.0, 361.0], ["green", "orange", "red"])'

  - id: cluster_uptime_days
    title: Uptime
    icon: mdi:timer-outline
    query: round(avg(node_time_seconds{pod!=""} - node_boot_time_seconds{pod!=""}) / 86400)
    valueExpr: 'humanizeFloat(result) + "d"'
    colorExpr: 'colorScale(result, [181.0, 361.0], ["green", "orange", "red"])'

  - id: cluster_alert_count
    title: Alerts
    icon: mdi:alert-outline
    query: clamp_min((max(alertmanager_alerts{state="active"}) or vector(0)) - 1, 0)
    valueExpr: 'math.isNaN(result) ? "0" : humanizeCommas(result)'
    colorExpr: 'result > 0.0 ? "red" : "green"'

graphs:
  - id: cluster_cpu_usage
    title: CPU
    query: round(avg(instance:node_cpu_utilisation:rate5m{pod!=""}) * 100, 0.1)
  - id: cluster_memory_usage
    title: Memory
    query: round(sum(node_memory_MemTotal_bytes{pod!=""} - node_memory_MemAvailable_bytes{pod!=""}) / sum(node_memory_MemTotal_bytes{pod!=""}) * 100, 0.1)
  - id: cluster_pod_count
    title: Pods
    query: sum(kube_pod_status_phase{phase="Running"})
  - id: cluster_alert_count
    title: Alerts
    query: clamp_min((max(alertmanager_alerts{state="active"}) or vector(0)) - 1, 0)
