---
# Control-plane-only documents. machine.type, the CAs, the service-account key and the
# apiserver/controller-manager/scheduler/proxy images all come from topf's generated base now
# and must NOT be repeated here -- each has a conflict validator.
machine:
  features:
    # Not auto-generated by topf (KubeTalosAPIAccessConfig only conflicts if written), so the
    # v1alpha1 block stands as-is.
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles: ["os:admin", "os:reader"]
      allowedKubernetesNamespaces: [actions-runner-system, system-upgrade, ai]
cluster:
  etcd:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
      # Keep the etcd database lean by compacting old revisions hourly; this
      # replaces the nightly defrag job (compaction prevents growth, defrag
      # only reclaims space the file already holds).
      auto-compaction-mode: periodic
      auto-compaction-retention: 1h
    advertisedSubnets: [{{ .Data.nodeCidr }}]
---
# Replaces cluster.allowSchedulingOnControlPlanes. topf's base taints every control-plane node
# NoSchedule; all three nodes here are also workers.
apiVersion: v1alpha1
kind: KubeNodeConfig
taints:
  node-role.kubernetes.io/control-plane:
    $patch: delete
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
certExtraSANs:
  - 127.0.0.1
  - {{ .Data.vip }}
extraArgs:
  # https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/
  enable-aggregator-routing: "true"
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
extraArgs:
  bind-address: 0.0.0.0
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
extraArgs:
  bind-address: 0.0.0.0
---
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeCoreDNSConfig
enabled: false
---
# Was cluster.network.cni.name: none. Cilium is installed by Flux.
apiVersion: v1alpha1
kind: KubeFlannelCNIConfig
$patch: delete
