---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/discovery.k8s.io/endpointslice_v1.json
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-homeassistant
  labels:
    kubernetes.io/service-name: external-homeassistant
addressType: IPv4
endpoints:
  - addresses:
      - ${HOME_ASSISTANT_IP}
ports:
  - port: 8123
    name: http
    protocol: TCP
