apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
  namespace: observability
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:tbHOb14O334=,iv:6mPkdlGkowBU3ZPhm9oKgCSO8sViYpoGhOzkgj3DObg=,tag:V/iUTD9yAc/IGPxlV+OaRg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UXByb3luMWdSQ3BDbHpI
        dXhHditpTEJ1WENxZVZYSWJNWi9KRXN1dVJRCmg0MkNkQW1iM3V5RURCTzhWTnBx
        a2JObWN3ZmEwN2xwTCtYcXdTTittMzQKLS0tIGl1WGV2M3o0dXdqWVBQUCt4dkdM
        Y2Q2bm5USjBNS3BkYkRXSnJFSlJDM2sKZBSjfc0VhLWNRZqhIQ4PkFEy6cukLoad
        0omwxCP+vWj/pfXz0P/vjuL4xUaZ/LozdfWWOIBZnkAqKAdfSxDpTw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFRMNHQ1bDNR
        WDVjeDY0UnZQUlJjV1pxMWJEQ3RkWFFSQkJiOGN5VjYzWGtvSWx2TXBEWVR1MzhD
        U3NPaTlReWJDUVc4VWJEWUliZ3BPUkRTWCtsRWw1ckRZZzNaR2Q1czdGNk9lcHFQ
        K1B0NUxUdHZTN2JHYTBXQ2VDNlBOdlhsRCs5cytuVUlQUlY4eno1TWp1MlVIMVlK
        SWlBNDRRTmQ4RjZHY0QvN2N5S2FxQ2lJbG0wbVZrOTdEOGJnQmNtait6MW9ueTll
        UElleDRMQ2ppUTFOMTJJVFgvYy9aQmljbitPdmhuUmZhd3BsSFlibTdMaW1rWkFW
        L3lCZGZ5NDlEU1paNWhLVmJCcEwrdTZlZldObW9YN0Y2NzQvTFdnZnRlTHVtVHFM
        L3NEVjFrMkpmd3BQT08yWFRJRGZZY0x6Q2kvdEFaV1M5a3o5ZEhHaG1GaWZtYnFR
        UVJjYnZXdVhBSjBzSy91dEUrUlJQV0xYc0RiTDdoQjRrbU5FNldXalVLRnhRdDE2
        KzRwczl1ZWtkT3J3YWlmemVDTS9mUG1KamMvRDRXdFlRVmZUVTkxYk5sZmtNNGRD
        blNqNksvazNrQVFpa3d0d3pEL0pIaVF5Y2xNTnY0MDNnUlI3aVJNZUZWVWtWelFo
        UVhYcndKSEdncDhjbWdKM0NISzhjdW9Oc2YzVUF5TlY0UU9XK2hzTVVkY0NZS2N2
        Y2E4YzJZUHlUTGYyYldLU0JGaUlBM2VnZ1BzamJPNDBoUjRJZUFrcmdGNGVnaWZT
        djlnOUhmVEZEYnVkbzFQbFNIT3Fhd1NRZ25udWQrZzVaQWNSNVVaaWdndlBuREpJ
        QzYySVRwM1c2VUF2d3JpNVJWQU9mTjQyazNXT1JTMzRKMzBNdHo0WmliNTdKbTRo
        RlBKWHIrazYrNEhIQ0NzYjVEV3lhRWZIMDlOaDh0aERXajJ3dTliOHQzOWl2TmFB
        V000ajl5a2NjTDNndlB2TnU1V2dGUVZCeEdZbitISk5xSzZmM1V0OFROQXZqOVRz
        SWpzNG9kbXF5S0pwOTF1SEpBMkIwaFNENEtKbWlBQk85QUU4WVppTGMzcmRIYzNF
        dTV3eXZJb04yUVNlZjJCckFYdnkyOFdTdmlvMGFNem55cGQvamZ5a0FEUjJwdGtS
        eTgrM3h0ajN0aDRCNWhZMGNlL1RsTS95K3N5dW51L0FZMWFLUitXWVdiUngxNHAx
        VEhmNzhYMVFPWVA2ZFU0QTE5b1hSQlRsZWEreTR2WFM4SXN2NHlCQnBLNTFwTkEw
        SDFYZjhQellxRys3TGVRVWF4QXZ5SHppNXI3UUgzbW1GZHdwNGxSalduajQrN21P
        MnR4UHJSOTFzUXlGRm9SWEFSYW5uMEd5NDhCdXhPNTVnbTVYcjVyc25hb0YralhE
        dEo5OGJNcW5aS3B1Q3pJTkZrTXI4UWxPeFJPbDd1M3d6Zi9SbE1haGpRUloyTjVt
        TGhDdmI2NXJZdlZlTCtqS3hWSzBGRFRXSDM1VWxISS82VDhUTDJadHdzSVhGQUVq
        RHVQK3JaWlRRR0xGNHYzMTlhZ1pwUjJoWTVsWXNoWm1IV2FUdi9UbFgzaGFOZTlW
        MTcyeTdPQ3FGUEhUYlVBNFVrYzlqS2E2MENlYlRxYnQ0SzlQci9XUFhFZktBamhn
        RjVxRmQyd1o3VHBhaTViMGlyUGxFTGVSMFptMXVzV2UxVUlxaUs2eHdDZGRMbHdt
        YWpEb3QwTFA5NjE5RE1UV1NIYWUyWTliOEJaTk5HSFJ5aERUUm5yREtSN0dDRmpk
        b3RzcHFBMjF2a2sxQXdPMTRZLzFZOEpYZi9KMlUwQmdnRzRVZmNlNndEWlNiaWtU
        VTZVZTV2cUczVHlNRnBUWm43QllMK2lsRGJBcjFXZjdNcEUxaXJQSmpxV242MThX
        WWNlNzV2M0g1MEZuRXRZb3RvNDd4alNtOHdNZkVlTFNKRXZVVlNmRXBUS2lYZwpp
        QVhjSmFONlczcCsxRWh2RWhlUUoyUENKaGUyMGtRRjhGRmVZK050SS9BCi0tLSBX
        a0dOMjFkSHhVYUpyUzRuMWhqcEdGYlBJVGEyaXlIdTBaa3VrelF5UFRFCvJ61a6O
        1AxVejTcmrQe6zrKOBmFJg9Vg8vgG8bUn4JJgraLprMQOmov5LzJwa8reCDTktY4
        UmxtTFRyvrFrfFA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-01T21:18:07Z"
  mac: ENC[AES256_GCM,data:u6lf9br2R1aqTycVPQaMusHZzz149CIKCiJkI9AZ87ZXLM8XWrY7bDqpJ1+oqgan3XwkbrHRXYP/UGGqkJV6jjMHJP2ayfwGmVS0af+h2+IfKryGpvXZEYLKvFA/Ji5VwkvdrJIDYZn9jsv6M5p1OxWl7lp0e2m2Wip2UOQrCpY=,iv:QxjsTWLxP69ildwGI3Bb3NtXEjuIreMshxhtz1UeDxI=,tag:/RyzwK24sikwMkky6sWJ7g==,type:str]
  version: 3.11.0
