apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
  namespace: media
type: Opaque
stringData:
  SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:8FhpeWFMxBJy/T2o2EI4vIUh9vjpiKdK4wxI4aBPWyrVaEsK5o+C,iv:5P+6CmwyZ3cJWFvScty49jfMjWzAs6vAVNpcYmkR5rc=,tag:rIKKwKeRO9ywDFOCL7HeSw==,type:str]
  SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:XVgHdA==,iv:2Ym90/+g2tkt2MF1NDmSIob9vcgRwH1GtNFVFBxBq6s=,tag:e0WL8pBB9CRgwjvUcFRcOQ==,type:str]
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:+qMzNCf1,iv:eCMKa0Cr1dXGRG3ZP+56qI4OEbnQ3KWjqzzyXmKPKTg=,tag:9Ada/UP19ZOtwwvP4ex38Q==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:p2CPqSLLdRY=,iv:CyfC/3n2nxaXevUyRB2ovOwQPoXL1fIoZ852lJkJFxg=,tag:8Rfs94r3sUi9mBDjGVie3w==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:WoUG/SVi,iv:yCEC/ay6TDvmuNWHJYAhdFaqPvYUm4u9ypocMr2A2YM=,tag:WgBovC2egTCUoCzVgaillg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM0syZnJPc1k2d2JRL1Nu
        QUcxU3BJaEoyMGVLbEJzSitvNEgvb1h6N0ZNCldXK1RTZU9QTTFWaXR2UjFyT0JN
        MENCUENUTTRKdjZwZGpmckVENHpCclkKLS0tIGd5NHN6dEkyN2xNUVF5S2cxbWxi
        YmkzUHVUNjloSTcyTWZ3R3JBbnVMR1UKF4hGCYkGeBFSuO2pOHFHhM6DGWUVW4yY
        tq0Thgve54/cFOEAANreA3DAla3xnTxOaZXB0yAnyhTMvnFD+2Yb7A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T22:59:24Z"
  mac: ENC[AES256_GCM,data:LBRAGAMgHyu4I7bHq8veFETp0CxCDtdbJJVKgIPPRvIAoTc/pbMvxCoJTPFbj6+6lJ6WLDksXiUy5oP/Up5u1/WE3KQYLQuMlebAt6doeTept81bpKiiqFqKwlaIpTEm/WRHYehaiRg0Xtg3z5EZKLzeF3n/qiycv1Nm6sPJ5/o=,iv:0yTUimX1olmNt7FUTaSTkmIaGiNyAV1WCsrsdSbRmaU=,tag:iNgAGcJrJ7yEiaTE3Fb7gA==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
