apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
  namespace: media
type: Opaque
stringData:
  SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:8FhpeWFMxBJy/T2o2EI4vIUh9vjpiKdK4wxI4aBPWyrVaEsK5o+C,iv:5P+6CmwyZ3cJWFvScty49jfMjWzAs6vAVNpcYmkR5rc=,tag:rIKKwKeRO9ywDFOCL7HeSw==,type:str]
  SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:XVgHdA==,iv:2Ym90/+g2tkt2MF1NDmSIob9vcgRwH1GtNFVFBxBq6s=,tag:e0WL8pBB9CRgwjvUcFRcOQ==,type:str]
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:+qMzNCf1,iv:eCMKa0Cr1dXGRG3ZP+56qI4OEbnQ3KWjqzzyXmKPKTg=,tag:9Ada/UP19ZOtwwvP4ex38Q==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:p2CPqSLLdRY=,iv:CyfC/3n2nxaXevUyRB2ovOwQPoXL1fIoZ852lJkJFxg=,tag:8Rfs94r3sUi9mBDjGVie3w==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:WoUG/SVi,iv:yCEC/ay6TDvmuNWHJYAhdFaqPvYUm4u9ypocMr2A2YM=,tag:WgBovC2egTCUoCzVgaillg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aFZWZnlJV2RQK0c4OWpr
        SUFsYURtbTVnaGZPUXZRc2xSN0o0eEE3SFMwCm5zWFh2NTBTbGs4dzVscFdCeWdr
        ckxRNkZWSytEd0p1azRnMnlLWnF4c28KLS0tIEd0NUkwTDJTR24rbks3OFl3bXR0
        bFFvNlVHRjd6R2RuczVJYnFaT2M5Q1EKiIC+2gXIXQLL4bFqdI3CrR8IGqwo7IWm
        F4fX/dPYpILSOX2LqW0UNjHJSzEO8gmZjgt8MaggyM5dh52D+x4fWw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEFLNzROK25C
        YTFDanF0cmpzV1BIR1ZONGdkMkw1d3IvUWxFS2VmQndNSmdHY2VvTWRkVEs1cDc0
        ZENmeXZoOG41Wnp2aExhZTZrRE16OEtjajJJNDg5Sk9zSTd5a2JrRVNqaWppYXl0
        S2tJQytBMUZaM0ExZGUrY0lKdnJBNTFRNTA2QW9BaXlLemNpSWttbk1YSkNZY3Bk
        MUJlMUlYaE11MXVKSUNiM0t2Ny9DK0ZheVUrN0JoN2NsUlNYMHJVYXV5UHNZWnIy
        Wm02Zy9Fa2dzZURsUEpoT1RDQjJJSkVGVDN1V1Z0T09WOFJWSTdGY2YvQjJPY2tY
        TXNXM2svdFV4RXUzSmpiemllbDFoZENqbXBqb0pzbmx3WWp3a2VGM0dmM1Y2bXVs
        UWRNZTNZb2JUWERVMlhUZ2M5aFN1eGJ6YjJjQ2dTTzdZa210NzR3QmRrUk5pY0My
        amNCelF4SGFlb3o2RjRyUTRlZ1c4dWd3RWhWSTRtVk1OSmNYcnBnamNJVXZTeGh5
        M2Z1c0JNV2xRSTlFdm9TVzNOSjYrMllwN3JqQU92cVNZZGs0U1RyZFhtaEVnczVm
        Y2lzVnlSVldkakljZUxKc2tmSmcyZGMxdGwyS0p0UzUvUEdjMkVtUENWbTBZK2Vs
        NE41S2MwTXNVODVZdlRRMFZoV1kxeXEweldIZW5DWk1nd1BYeGhpd0pVUFdLM1E1
        UVMrbkFpQWxIaE93cHlxQ0dmZjc0dmhST09wL2NnT1ppbXpHcmgwQmFxVUFKSEx4
        OW56R0tkWUVLT2QvTmNqeXkzLzVGa24yZGp2cE4xWTBtRm9sRGpMMmFKYlRWNVEw
        cHhSQ3JFSS9CcmZvM0RJQjFyK2VOYmhRV2NxVE8zQVprQmpvWWhGOVJkdDBWdlN3
        Q1pabEQzdWV1akJQc25TZ3J2aTJvMHZUb2wxenR1VmxWYU5YY3h6Sm1ZOUY2cmpJ
        R2tQQXZkSlNjdTBBd0gvSGtxZWlLOE4yUGx3Zm1NSUkwNTk0bUhpZHc5U2ZRNmhy
        YnkzRTViZzhRMUNrbFJUTERXUExNSWd6QThyWG1LR0lTUmxJd09ybGo2d1pFNFZs
        VmlDeVJYMDB1alNENEtkaGZKSDdSR2hONnF2TzYvN3pXV2Q4VTBjZ0VSL3RhaWlm
        Yms0aVNQUTdHeFE2NXBlODNFUDZjU2VkMTlrTWdMMTRVK2hvZXJZM050dllQbHEy
        bVZ4MVFQQzBEYkl6MjJlNkkrN2NqSmJuSHp5TzJXbGFuQVA1Yis4MmxMWmt3alFa
        RHhxS2pwL2hUcEt1UGNaUG4raVd1ZTFjUjAwckJGdnZkYkllVnFJdERuckFpbVNB
        SzN0RGtWTjRhSmNidzBnaGcrS0h6T09qb3VUbjZhTFVOODNHc2R3Nzg3VUR6OTRP
        blJ3cTVLZWJteTY0anhCaVVXMjVNUGZra0lESUFTcDB0YWZzSVVaTXBPK2JtQTg4
        ZHEwQXhSSlR1Q2ZnSC9QWDRnS3Jkc1RUeFpjNGRFdVZWN2dtNCt0REgwS0pObFdY
        RWMyNkRGcE1ndHlxNERuaEEzMGRVQTdFL1pRWUxKb0FhV1RJayt6d2Nwb2R4RzJa
        SHJVTWlTSS83Y1htdjlqVURoUU02SUpoT3h4Z1hOTmVkWXZKdzQ1b2JnNklqVEYw
        RHVQQ2tQRnJQS0RQS3pic3ZTajJhVkFTY3kyT1RCU2JUMUIvUzNlcENNRmVaQStH
        ZXBIMVVTdjkwSkxWVkRmNlF4dzdFcllyRWhzSWtCWCtGQk1WQzgybnVxckFUUXNz
        QmJGZ21VWjFab0lVbzhrMDZ6MVdFWVR0MHZuQkl0eis5MmRTR0ZuYjkyRHRqOVI3
        cUEzM1pwczBtSFF2SVd3MmJPWWxyMHFabStBSWpzR1FNMUVDRVdTeGdYWlI2OG81
        dU9zK3EvdmVhVC9mcTJXRVJaakxISXBuUWJlaW1JdkduRG9Wcm9NZ2cxT3FBdwp1
        MFBGVmlZaURhbmVVc2k5eGlNYnY5R1p3UnN3WTBVOEw3MHlpQzNHQkV3Ci0tLSBY
        NkE1N1FWR2lKdldmRG9reHBLS2hMdnAxclZlN3UweEh0blB2OTg2RFlFCuMN3Fj0
        s0JJljHzJneBMqHI22pb1WL3Ee9wj9x/MSdgwrQ+cwrJgyAR5cOORIGGGp5kNHBa
        XPy+9O1lub1xcDM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T14:41:36Z"
  mac: ENC[AES256_GCM,data:8NGqo8hLJRKnlMnwiY2rW+zWJjnWMFc1iDE1+Q59/74eNwXwATnKvhe58GNl31kR+RiPzuE1QXP5mT7ofJaJlP2UaK6801F0OFkZEVRG3k7CLvlQ0rjJJmXd58Hjh4JetJ6CnUirIRiFM/U3mTKakPFQ86L+ptimkpM36Or7i18=,iv:j2fuq0ZC+1eumA34qWqPNAvdvuTTtKa/E1AqZ616cSQ=,tag:7N0dAgYlSCHIfQ7AAcxSJQ==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
