apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
  namespace: media
type: Opaque
stringData:
  SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:8FhpeWFMxBJy/T2o2EI4vIUh9vjpiKdK4wxI4aBPWyrVaEsK5o+C,iv:5P+6CmwyZ3cJWFvScty49jfMjWzAs6vAVNpcYmkR5rc=,tag:rIKKwKeRO9ywDFOCL7HeSw==,type:str]
  SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:XVgHdA==,iv:2Ym90/+g2tkt2MF1NDmSIob9vcgRwH1GtNFVFBxBq6s=,tag:e0WL8pBB9CRgwjvUcFRcOQ==,type:str]
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:+qMzNCf1,iv:eCMKa0Cr1dXGRG3ZP+56qI4OEbnQ3KWjqzzyXmKPKTg=,tag:9Ada/UP19ZOtwwvP4ex38Q==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:p2CPqSLLdRY=,iv:CyfC/3n2nxaXevUyRB2ovOwQPoXL1fIoZ852lJkJFxg=,tag:8Rfs94r3sUi9mBDjGVie3w==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:WoUG/SVi,iv:yCEC/ay6TDvmuNWHJYAhdFaqPvYUm4u9ypocMr2A2YM=,tag:WgBovC2egTCUoCzVgaillg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDhNaFRXa09p
        bTUrd3FuNXRzT1FEbDI4NWFPdzRQYXF6WkdycW5kUlNvQWFLWEcvMFpnS1NQR0c5
        SHJkYk5HM3I1S1pQbEhlYkFONXVWTDhGdy9KUjZ0dENLZ2grU0ZYYzluaW0welNF
        cW1iRXhTRkJBNzJ2dGFEUE4vQ2htdkhLVHRxUkJ0dzlDYXZzQStJU0UwTjFWM25w
        QmZ4N05QOHZFUU5IK1lIS0NWWnU2SVVGbXhCeDQ3Nm8reEVlcW5VRzJuZ0pFL3lM
        VkpraCs5eTZqWDNLV2dkendtOTBwYk5WK3FQMWpMcGpSeXBKdlRuWGhpZFoyOXhH
        UXV0U1BuSkxkY0JPVU5wTFpWVDJSUVM1NmlCeWJiV3d4azgxTGUzeEsxUlFuSUxO
        ZkdhdUVFYlRDd1lLQkZxYy9RbFVHaXRXemlWRHRQR2hNTHRGUi9ZR0FSeVlHNUF3
        MXNrNUxaeGt0ZzNqdzh4cFhzeFZ1QXE4bCtPVjFFZmkxWXVEYUtLTlMyVVJ6bGNX
        RmtxLzg2RThmUkNvZ2FFemNOWlFna1NIRUl5U2V1S284Vk5mand5cVZBMk5uYUFm
        VFY5MUxvQU55OWk1YkR2aWNCL0NXbCtZSUhaek5ITnVYSFVWbjRGQ2daZjBZWUJz
        cUxtSk5lbnE0L0xBeEVaOWJOSmlVU2pIYm8xS3dJa2RuZ0lWOWpscW9yRVFiaWs1
        SDE1YkZQaFR6Nk9GS252bnR5anlCcG9Jd3N0b09VWC9uWWZrSmNnVThtejgvOHBn
        ZlpWYnp5UlJZOXBTQjRJYmlwUG5rSnhXVnFkS3J2anJueDNLby82bUpCZTY5eWx4
        YTdYUklGQmVFR3A4UFdSMzN1aE5telFnNHM5R2tjbHNXb1JrN2ZZUHJBT1BOOWp2
        RjdtRGNOdjFyWndSdkcwVkpjNzgyZGZ6bXRsd29DcUk1aE5TWCs0WUExL2lvcEN1
        Y1ZXWHM5R1o3Ty81RWtWVVhNcXl6eVRoVS81ZmxHelZacTZiVkczRklRdE1xSER2
        N1F5cVB6a21YcnZpR2R1YVRzT21xemFBU2d6M2FmdGFNaytxMXY4Q3FzQXVJTG9X
        Vm1RUXFxRGg4UVR0a3U0NEttNlJyOTZ4eHpNYkJWbTZ6d2FOUzc2cVp2OW9HdDNz
        TjZDd2tFcVFsSno5dHlRVjdjWHpiQWI4N0F1TmZTdHlTSlFiVHBJU1hYTVRzaFlz
        cDRDaFFTUWFlWFpjR3c5VUZOSG5KQzQyN2M3QzE0b0lzeStiUEVLam1qNHZRQTRU
        SnllNXpYYXB5TU1IdXFLOXJPblFSeisxUDRqTko0NXZnNGNDVGQ2bG84ZzI1NG9F
        eXFTT01mRDMrekNkSUh1bm1aS1czZ21mYWNwNFJFVEFwYUdzNTg1em1aYU1yb3k4
        M2U2Rkp5WFNlZllMcGthNGtMRHcraXhpS0lUMjFwdUhVZDZTRVl1N2d4Uk96eU14
        SEFBYjhhYlMzcU00elBZTlJ2bWdzUGlINHBEek9PaEZyWEJDTU5kb3l1bWduUkVR
        MjRDSUFTVjVXSkpGUDJCRUFJTXBnenlucHlWNjFmN3JwUURwOTBncTZqN0ZGUDJZ
        a0s3Q1NMM01JOCtMK2lzZjliYzVvNS9mak92RVRtQ3pjNmVIZXhIRVJla21FZDIz
        S0JnSll6WUJ6b1huUjBPWmZ3U2s5VXhkamxJU0xKbkhpaUh6UndxWXFqK3U5K01I
        a3BKUlUreE52SngvbytvQlM3TG1FckhqS3FaaThEZlNRbWh3Snh1UEJ1dFZvUkw4
        SGZ0UlY0aWJ3THRkQU1TanNMK0s3bkZSb0Z4bm1VV2trZFFLZ0pOOTRmYndicUJG
        V29rbWU2TlVnM1FpYVY3OGw4TEVFYXdrbHVZc2hrcm5TQnl2NUovZnN6K0FoNUFG
        a2ZiNDNaQVM4KzU3U3V3ZkxMVnRmcTBBK1hHbUxjRmlTTGpsVFE0Rm9pREdZZwpJ
        WVlqYk9Wd1VLejhOSkMwRzdpbllCYTRpQU5uSUdxU1dTcEc2UmJXV3lvCi0tLSBt
        MVpxWGNWdkwvYnF0Y1hNNU9OMi9zSGplK2FVakFNcDYzRGJSdVBheFRZCml2Tp8i
        50BXjA5PI5oSW1AHWWi7o2by0cUQS9MxzNdxFc7W9uj64b6NU4zkrVSv1fpBiscV
        Yz9OGBGFpEg1aBM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T14:41:36Z"
  mac: ENC[AES256_GCM,data:8NGqo8hLJRKnlMnwiY2rW+zWJjnWMFc1iDE1+Q59/74eNwXwATnKvhe58GNl31kR+RiPzuE1QXP5mT7ofJaJlP2UaK6801F0OFkZEVRG3k7CLvlQ0rjJJmXd58Hjh4JetJ6CnUirIRiFM/U3mTKakPFQ86L+ptimkpM36Or7i18=,iv:j2fuq0ZC+1eumA34qWqPNAvdvuTTtKa/E1AqZ616cSQ=,tag:7N0dAgYlSCHIfQ7AAcxSJQ==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
