apiVersion: v1
kind: Secret
metadata:
  name: memini-secret
stringData:
  MEMINI_POSTGRES_DSN: ENC[AES256_GCM,data:xUjESeMAWCv1cYaLpNwF4/ck7paOId4v/zQJ7hn64qnpQxA79duOwivGlGj4uP4Ly4SDR9u2jz4c73/17/ISwxmdfOuJXtoc9EJ+3SfO7gDIavaaYjVr0OwpWlUK3A==,iv:E7WjMOAAk2joUGJAkaZRSXE28pURsln8VL1el2HufAA=,tag:Fm02Cz76UmGwWv5tkhoX3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMWZRalV5US9URkRtYjJp
        Rm1aSlNDTzRENDZLakIvRWtCcVJhelB2TzFJCkVWWUM1czNNK1ZIZEhqbWlYdTk0
        aFFybE5YS2w1elRrQ3pmbDE3YklBbncKLS0tIEo2bWEzNkVNTjVPczV6ZitrNjZ1
        d0pJM2lacHkrRVF6L3BSZUJBL25sa00KsRd6xtnrVsIL7pU0bycFr3u96BpyQfJy
        mAUQZedrufF1sEcHXOdVp9Vc6OhHVrzJlG7C6YWObTVpGRc1t/r1hg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHpTeEg2Q1Jv
        bHlqclRheU9VbXFvYmhGdjRrNzUvUFVQLy9qR0p1ekhoVW5ZQ2FKcC9qdUJMOHov
        eWx3MWhWdkJiN1gxL0RpZGUvOWlQN0lEbHpnRGVESkVvbFpiWXJ5cThCcUxyYmR0
        amU4SjJhWDFBVFJKVExpM1R1RElBaW92MVpVclU0QUY5eXpWeWNRNDYrbnpaTE12
        d0Q0c2g2S1ZJdFRTRkd4bWxnUCtONmF6MDZ4b2JSeFJWOUMvdk50SHdSdUo3Qitu
        UVBlUHdkZ3dVM1lCRnRaT25UaUQwWXlFTmRJeU9xY0ZkdjBzL281cjFWYjVYUlNX
        NFhXMjJockYyZkFnTVFkTjhva2JyTUFWbGVoK3p0dnhYL2sxL1BNUkhoU0dSeVJQ
        akdlemRnN2hKY0dnTGZoY2dUWk0wU1ozcXcvTEhvcmdmVkZNcXkycEQ2RS9TSWx5
        YjBnWFl0Mi9yWk10NElEYWtJdWFLWE5YZUV6dTZoQTEvUHFHaHVDUlRJeHFrT3N6
        aitUNXBxWVJVaXVXRGllM0pmMVRjRFE5bkJibzJTb05sREhkVmQvUTlOR1RqQjB3
        cnBkYUtXSmQvc1YzbEUrWXg3UzJFYThOVGU5RGVNSVNiYW1WeWxzYy9IWmN4VmlB
        VDZjVXl5K0ZaRkw4YkVwbGdnbDlCam54RVFzc3ZySUNPYkRadE5xcTZrRzBVamR6
        QWdrZnVVRFNwZ042MldXWDBIMkRXMEJEaEFwTHpxV0h3MmN3R2MvdndEQ0pEemlp
        T2VvZWpybFBQY0E3c0hsQUdQdXdXd3RYM0FqN2hrYnI4R0JETzBJV2xMc1N3UDVH
        M1ZsNnNSTWl4d1RPNm5QSHF1dXFBNjZhYmJ2dDNZUTRBL2laMVZPa2Z4K3paT0o4
        Q3dmdkx6QjQvRFZONm1nZ1RXeHVwcnBKMnJUc1BwbHFUVHRNL1VKc0kxeEs0Y3ZF
        L0x0Wk4wd0trVmZGUTBYcGlkK1dpbENqL243WTFjNFZpbXpvK3VTVUExcGNPV09y
        Q0JwQ2xzY3cvMExwQ3VMUnZkYXNUbU1PK2JDdUtxelNPTmV0Q0tqV25TdU9uVjFM
        eDltOGxBSHJzek9heXpOSlA4d01BOWcyVlFnZS95Tlg3eFBUaEtJSzdoMllhM0Uv
        eURWeEUwOFh1TkRqMVk4SFpCN1RYRkxPT3VTZVpkSmpOcE03RXhrdFNsQ0FDajlN
        a2lvT0FRdWpsNjBNRkUzQUw4Qng4QjUxbytmUGk5UjNUdjlNSmlmaHMrY0xuRnVz
        eTg4U2JLc3lUWXFFTTlvLzVaSkdncmJzcWthbi8rSHFUV1F6OEZVUHVoR1ZLM2ZC
        eVlNdTRjRnY1d0N4bUZxckxjdkQ5aFNTTXRncGt6MFpGVGVEQzU4N3NRVGp3YVA4
        c2FQZnNzOGI3eXAwZndZc0sxNWVlUkZFTGowWU4xMnRURDk3Vk80RXlDY2dvdEMy
        RzduYzErNkFwcUlOQ2hPdnhzWm5QUmprNFRoNms4dW5oR1VDcXlIQ0FPVFp2V3Uw
        dm96NnFDQmZPS09QSGNUL25ZQ1NBOGY5NkM0NUNhQ24veUpsZVVrVklKcUtvRWZj
        MjNDZWhkVVJjUWovbnU1WDhrTldZVGQxcUFIT3I4akRPOFgybG9XQkRDbEhPS0c1
        b1ZMbHZNeUdENDc4NlRxQWlUa3Q0Mzc0VGVLOTV6UjBCbmtHdmpvSkRkc2ZtQm9q
        UHB4NjFqZXRaMGtWYVlDMHBKL21PaFF0V2lnN2R0eTl4NUZTMFk3UGNKU3VhNkdP
        bFp3TDNxc2dZWkdNRjNQRUpYTFladmwwbWhuNURHZnRYYlpqZExtU0UrNmFnVWdj
        YXoxT3RZUGZUZThwZlU2Q1ZVNTVVWnlPNGFYdXJSamsvcjU0RGVDbHJCVlVTN09q
        ajNOQTdkOW5uclFoTmFWWkk2N3pVRkZxWDRuOWhySm10YXg5RjBKRW5GS1NlQQoz
        Tm1od3FkR29va3lzYkxneXAyRldqNitmL05XWjM2WFVnandIVko2R2FRCi0tLSA1
        T0lJZU1FU3BFM3IrOHUwVHNmUUhzcjZqWU9zUXluRzNJMlJHYmJyOTRrCuLRIz+J
        3/c1Mn7CIr0WlCzMuuEVDzU7Pr3sinZ1+5n1LREo5+TnD61RjMoCd5pprrC+xIlu
        WWSiVt8YxPQckgE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T14:41:36Z"
  mac: ENC[AES256_GCM,data:L6WATEFqU+qYyFU04X7wnzk3gXKxPq5wdXuZZaTpw2YBxmi8OTZWSuXosLI4YJ3k7dHKikz5+nXUcyh0eRWzAOG7PdtId+VwRkTTW3F6x3n9TeTRGXeE9Yg2n3q+j51+YKlLzZoqLc6DxoNFHKAxJtGT4Y+kPNoMa4MKvqRLxuY=,iv:CvF38eqtKg+0hWQ3X24nV6shUfzmF8KuibFlFN6V8nU=,tag:mUtHwQvfZoxuJkqvYgDbUA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
