apiVersion: v1
kind: Secret
metadata:
    name: memini-secret
stringData:
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:w9VOyIWmplw=,iv:1+QNZJMFHvXtrxigtWlAUbRaSOCygjOCuXJIAt9EpaI=,tag:7OL/2GGSI45i+gNB6PYSUw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:bIz1UWQ9,iv:gTC5yIg8QVviHEi9wmS6+hHeQrQnFFmyoJcxg3tuWYM=,tag:6Ox9JvNIoDEwNQQOT7gUGA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dYEB1znVPT8=,iv:jTRBKmHhRDAkEs9xz7flsjiEm45hWpIHzsIfrtSvUc0=,tag:6MxJI16OEbhfEYP6RJPYCA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+sAK515gOtTjPyXpQJV46mIdkHOcyOI0+Cq8TERJJZxujWyspPsG,iv:wLX2lDXxwifdwl/9uYipg/CZxCGAGSizyV3HbnnDorc=,tag:ErVW/5pspGAjiuJpfEipcA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:irylD58X,iv:vLe22O8wDhsMmRVVH1LknGt0igJqVc4S66N41AsY+os=,tag:3kTqhQTzPgtopudMSJejmw==,type:str]
    MEMINI_POSTGRES_DSN: ENC[AES256_GCM,data:xUjESeMAWCv1cYaLpNwF4/ck7paOId4v/zQJ7hn64qnpQxA79duOwivGlGj4uP4Ly4SDR9u2jz4c73/17/ISwxmdfOuJXtoc9EJ+3SfO7gDIavaaYjVr0OwpWlUK3A==,iv:E7WjMOAAk2joUGJAkaZRSXE28pURsln8VL1el2HufAA=,tag:Fm02Cz76UmGwWv5tkhoX3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6L09TSWg2UndIbWFDeCtW
            ajcyMHU1N2p4ZlRKZTVDcjIrTloxQmVkc3dnCjUwR0pNZnJ2MDNsRHhGMDlwNm5K
            ZHBiWmU2UFhGZ2ZrM2lZTld4T3h3ZW8KLS0tIHZic2hPbUNqUURqdkt5V3ZoYWxa
            V3UzeXVRQXZUOEd5UU90WHA0SmhHT1EKaH9nTGz5QMsESuVAQuoNeAC36MR0wWH5
            0aIXBGl9lJoPz+j9eUMy39mNcjljJ49nyMXIz1UDC8EY0zLZfy0RMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T20:29:52Z"
    mac: ENC[AES256_GCM,data:B78LDbhabWy7/qbb7yeDRvvNwIaoXFtAIr1qIhv20ox7kWqDy+DzpLX7V+2ZAUPPSh6AHyP2KrkU62NpNpNjCfMS9dEinp9aP4ow8UOmnHVQqBsQti1t5n8vX56anTXLZ3bKNX0TGUU+Vqa9PxAoAb8hAfCf0Vb3nfWdxsP3wk0=,iv:YVIB+J4TLVhkeDBeV29RpPg9YxM4X4Mt5PtFhBVdkK0=,tag:Bqb7qyqV84+UdPICLGHqhg==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
