apiVersion: v1
kind: Secret
metadata:
  name: memini-secret
stringData:
  MEMINI_POSTGRES_DSN: ENC[AES256_GCM,data:xUjESeMAWCv1cYaLpNwF4/ck7paOId4v/zQJ7hn64qnpQxA79duOwivGlGj4uP4Ly4SDR9u2jz4c73/17/ISwxmdfOuJXtoc9EJ+3SfO7gDIavaaYjVr0OwpWlUK3A==,iv:E7WjMOAAk2joUGJAkaZRSXE28pURsln8VL1el2HufAA=,tag:Fm02Cz76UmGwWv5tkhoX3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6L09TSWg2UndIbWFDeCtW
        ajcyMHU1N2p4ZlRKZTVDcjIrTloxQmVkc3dnCjUwR0pNZnJ2MDNsRHhGMDlwNm5K
        ZHBiWmU2UFhGZ2ZrM2lZTld4T3h3ZW8KLS0tIHZic2hPbUNqUURqdkt5V3ZoYWxa
        V3UzeXVRQXZUOEd5UU90WHA0SmhHT1EKaH9nTGz5QMsESuVAQuoNeAC36MR0wWH5
        0aIXBGl9lJoPz+j9eUMy39mNcjljJ49nyMXIz1UDC8EY0zLZfy0RMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T23:05:32Z"
  mac: ENC[AES256_GCM,data:C3wlpC0LWI2Q9wQEg86739nFmFSNYJ5AA7dfc37ikx2VEXViwkulz+UZ5iFXUK4+qToodZLAibl84m5G5BMIQjq+NVvIpldD1LGWsRBZ6yOnD0KcliBjcDk3RcxHNSB5Uar19DiP1TPS2deCrRp14b1apehuEk/kSV67Cb9p44s=,iv:INaXXmiAKf1H56b2/pdvFUskRK3qX/UzIbL3UStvuQ0=,tag:ISSuMNUMQr+Nfg8qUzY+PA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
