apiVersion: v1
kind: Secret
metadata:
  name: headroom-secret
type: Opaque
stringData:
  HEADROOM_PROXY_TOKEN: ENC[AES256_GCM,data:DqEa8CkwDsli7z3sQzAN/zlPGz0C4/0I+oO6/W6T2E6yls6ljkg3TftMX3GoVB7PyXQP667LU4dRF0rGGwGnEA==,iv:j8dNO88fn93skXIAeY4qnc8jx2vDn78H2E7LeRrIy1I=,tag:vhP+jN64d9iW9g8mtTBdOg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICt1MDhzWW5h
        WGZOcUN6N0Rxa3VqVjJDbU02bDBaeVEwcEJoZHJpYW5jL0NodGZ6YjFvYnExemJR
        eG80RFI5MGRjTWFPRmR2bnI3NlZlTHdOdVR0bUJtWS9YYmJCZG1ZMkhNVWxvaFVG
        T3MwNUl6Z09jdjk2Yko1Rmkwbkdxb0dLVFcxMEJGR0l1V3BGZUZKeGtNOE82YnBS
        U1d6dHBuZGVXWFRIamdZN2VVT1JCZm5PQ1o3eG9zeWE4aGxKVUh1V2YxSmN5VVJR
        MXBBcWErbEM0aHdYUnN6TkVLZGQ2VGxMNHpEamV0VHFmSUE2QUZyUFIvckI2bHNj
        VEdXVWlHbVJSUXJ4VDBSZzJ0WEVMV2E5N1EwY08xYitLZW1lNTIweUFiUDhpSWFx
        RFpzRUx3R0ltNDByQXd5TXJRUE04cGVJR1h3NS9DejhSY1RsTys5ZjNEb1hSRUt3
        Sm1HWmdsV242SlBZZnk5c3hkb1lnNUc2dFAxSG5aYW1aT0luUXl5cWJHYS85S2VE
        Tmt4N3lIQVd6d3BiMVNhTkM5Q0Nzci9zRGFYKzQzU1U3RVk1S0JqSS9wOTNyUDNY
        QlBqMWZXbElEYW8xMXY4L1BjZlBjbS9JdU85cDIwZ0xsL3FpZ2R1aDA0bDl5N1B3
        ZXZwSEtGZDVsOFFFbktJaWdUYzVQd2JQU1lpNmF5YWFhY1plRFlkb21WNE1DdzNa
        aWJwbWxKV28wUHRRNmtGSnNVZFpkYnlGQUsvREFKNjFoT3hGRE16ek5iUlRHQVFN
        Qks0S2UwdWQvUXV5bDBKYXFnSVYxTXFFUkRRMEM1dktvY0MrUmdGTnVJS2s2ODdl
        K25xU1JOanV3TVNCeHlBblRZNHBad2xoZVZwTmNVWUdraWlSTk1JTVVHRkJkK2Yz
        Qy9KdHVZUFg4WTBNYjhVZGhydmpielNqUDZzdE5ZU0wvMk5YTktIdE9rMytpYzFt
        amZsdERSV3oxVkJNOXlkUEhreXA0V0FSZVRsNnhSOXRvV1EvekVYKytQTll5bW9K
        UXoyQWQzM0xoOTVtZkdzTHl6S3ZkK1hCMWZ4VDRtd0h6Z1NHM2RaUE9rTlJVNktu
        OXk0dVhNKzZJaEJtL3pCaDFrUjU5TkVGSEVoZVlWeGIyWUo5dWc4OU5kTTdGYXFr
        ZXI5cWFObnlaTkJvLzdmaFV1dGNQc1ZGRldvRWl3eUw1NUNHVzZGVmFlazB1RHJ0
        TVRqTGNBdjdPZUJENkRMbkE5bEJqeUtJcit0UVhLeURyS2FNVUkwUTlDaVFPMUZN
        TTBaaVNaRWxPblpXWTIrMjk3NE5GZXI3YUxGM0RVRnhHdnRlOEM5ZFZXWk1JREx0
        RFFZYVRVK3VHelJybllPc2pXWGsreitRMHJ3UU51c3p1MnFEWm9MRzhOM0VkUFZt
        aHdkQ3JFNzBMTWFuNlNKeWtWZHlQUVVPOWtSalFhWVhzZXppRTlTajhrdHNVMWty
        V3MrQzhlSU9yL2ZtK1VScXlBWnBtZzdSOWVqRzh0N1NON1JGS1laZTFldDZTZG1E
        NkpEeEFiWjU2UjJHRmVHNlFEVC9lUjJQeUhlR2c0NXl2OVB1Q1Bma3JhcDkxb2tR
        N3k2VGwvTHlqSmUwL29PaW9SK3V2aVBzY1ZQQmdhMExiSEpEMWczdncwUTNhaXkv
        WkVlKzV6TW9rZGdHZkRzUnpnWjRZWWtFUU1qRGJDWHNEUW1vbFpJWi9NU05mSHdQ
        QURSQTY3MDNmQm5uQW9FempPdjd1WXFMaXpUMWQ2MFpyM0thOWxMdkdhdDl5TzVv
        VmZzNkNBWThxU2ZCS0l3RHJadURGalkrMDIvdXBBSWxUMWZFVE1SOTk2VFlJQWtn
        VkFoT2dQUFFZMGFzNUg5MW11WFFpMGxkaHZjZCtvTjBzYUE3NEoxTmhFVitMZXBC
        bzUrTXlmTHJVNlRVZTJkZ3c1Y3ByOTNtNXlTRndLVU1iUHo5VFJXRStUN2tBUQpq
        RldzRmZzWlhIbEl3RFlQTEQxOFNaemx2aXBRdVFZNzFLdFhoSi9sYW1JCi0tLSBp
        aTZSV01STkhRcTRpSFI3STREdlpNUTBtT29BTmFhL016eFZHOWd5Rm8wCmQSHPPU
        S8YeiTL/ePaMXiJ+0jwsfeJMoDJIfdvusD1OcStghWaeFyErpfbD7cwUTEs5ECVP
        bQg7N4nw58NXjQk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T20:06:08Z"
  mac: ENC[AES256_GCM,data:iHZyz8iMnIASNFHKuWCXEbl+XIaUHfpU3SJVcaCRyZlYBPpVWjKEEIkgg9YlN5IMHk2q1oxuI0JOnZLy99C7qxCNoTtOeESlHkYvcCdZmoioL+4ptvY1WV570//58shF3+qsupv1nAXo0ZVyyqjRXa3VUkE+IgVtp1ohJ4A9Ffc=,iv:Yp8wnQN1wn3OswLqigth2oUMdAkAD4uXXHR9k4uY28I=,tag:pqQhfQqFYAI1TOTW8Qkxfw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
