apiVersion: v1
kind: Secret
metadata:
  name: renovate-webhook
  labels:
    renovate-operator.mogenius.com/allow-ref: "true"
stringData:
  token: ENC[AES256_GCM,data:ASqFAqnMvnqUcni4vpGyPH7koJlqXST8tdx+RjK314mEr/a53AEG5Ay1i8SFGI95D7kMdcQKRKoBl5/QvX+Sig==,iv:Dgj8SHOg0IhyZrYREtRIwZbrb7h/OANiqg9PcN6B7+c=,tag:i5dUckHTa0ESF1mxRSfrUg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDZVNWwxZUp3
        T3o5MVVzcGx3dzNCd2JUZkQvcy9aTE8wT09ySlJRaE8waDJqNWFBVWFsUDJpTERV
        K1FoZmJGdzhyZzdNL09FRDdEU0hEbGpBTGloMk93YkhmUUIycWUwMWFKZ3RoQnhZ
        WXFWaGN5SDY5M2tMSlQra3IvQ1JzZUhuVkxDcjgrd0E4VjJpdWlPM0l5L2ZHUGVu
        aUx5M2p5QnZEVXE2QzY5VTRZUHh1ZCtOTEI3M0RkMVZHd1YvRDZhaWpRM3FLNlpB
        TENPRG9TV3ZWc3hRNWhYb3A2SFUxdTRGcUZwZkt4ZnV0bzhYOXQxVjhoR1dGOGNw
        YlhjVERWVlBkaWg3b1I3Z243SVhCMXNlS3JCQ0tWZWRlWlp4bDViejhCYjZnVWNz
        TzlMZGFqUVkzbjZOREpJdFZYVlJmdFNRS0hYL1ZlTDBvL2cvSmtST1d4TEhJK0l5
        L003ZmozZjdhMGIxWFg5WU90a3VCOUozemlxbjNDVno3ZWJ0ZTRjNTgwOHVndmln
        aDBxL1FUZVYzVUpHVmQrS3JZRzZuYkdFMkNLbVp3dUgybEJmRWl5K3VaMTU2Z2VR
        Mk9vSjlWbE5nV05uVWhiWURpRkxncnYxL3Q0eVViaC9yOXpkQ3RaY3pKN3pENkM2
        ZkNVamhVUGF1bTU3K2hyV0Y3UVJEdDVJTngyWkpLVWdXMG8xOHhtU3I0SFllTFNk
        SWYxMU1XUkI1bGRZdkxRUFpFWWpZSWhaM08rV2thWDlOMm9WZkp4VXpnaHlVdUg2
        VjVocEFTbEtsWHplUzFma29qYVg1c3NYSUxXRmZzWUw4bklFVSt0elFUSGJnNE56
        YUEybGp6Vi9hd2xBWVFGL3FleHYvQVRtSlhuMUNMb0pmbVMyUUduNDhFd1VJL2RQ
        WldHbFRsLzJkR1NzcGk2U1VSdmhmQkVNSlBXVXBGK3JyMndvelhMR3FESk1GVy8v
        aGp6RXJlT05GeXdkYU1vMlZPQWg1T3RKYlliQllHY05pZUFLMHRYdUpBcTdQcWo0
        WWxvanFSc2l0a2QyZnlRZjhSZ20yWkQwem10eFF4SWhnSk00NDBMc2NXVXNBbkNn
        RCtncUtLTXZ1aXpXTmRuYkc2bTVqU2pMTXc3VEhXbnhwY1pSM2FBZXM2V29EMnNq
        R2dBZno5NUtGakFOaFFUcVozV3pBRDFveWdYUUg4WU5sVk5wT2JQWTY0cXlxU1Nl
        aFQwTFE0YlRFNTFKKzlISnRoMzUrL2lRa29jUHlIdzdyVW5rQVJDYlZNOXE2clBB
        d1hNV3o0QUJkMXlpUEVDQ2oyeUhtTG4xdDU0aWlYWUpoSFlRQkIxU0RkTkdSaDRX
        bTlHc2JBMWdQR0ROaUh2enNqNXhkYlZjK2swZ0dWZVR3OXV2cnFjaHZWWmpKWlNU
        Zm94bXk0byttZTg5SFJLY25VM29LaWJack5uV0dDSHBMQ0p0VVhDVkpBanFPMGxR
        YmNIVFI3RmU3TE45UmVUMFFza2Qwd3RZRlRRV3VKSGI4blVYV1M3WUdLMkZRbUV4
        L2hieXQxUmFaMWxJbUg5QlZPTGFZZHpBTm00eUNTUS91ODNqTXdhWTdUOWFHOHhC
        V1ZzSnVGejZVVDZaUFlud2RSbkdZRVpKL3BWNUhPZURESnNGSU1CM2gyQWxVNXdV
        WmM4ZnZEOC9lYytOc0pvVU5IZWlIM0VLZzBCSTB6MHFvTUloTDViV1ZnSS82aFNs
        N0NRZk90SVZYSTVXZElPSFJBU2xJSnkyUmNmNkFySEpGaVQ5Y1dadFVYWE9Bazgz
        MlZBN01USVhEY3dLVTMzNDlvQ0VoUEJmcXBtQ28xOStGVzZ4ZWF1eE0zU2ljMTJZ
        czE1ZGZ0bFgwWVBTNm9WWE5Hc3grcCtJWmlZTm1GSUxsczcxTjJkbG5NMEFGZ3dz
        RFVUbUkvekhwUHZ0WVpITnRhQmtNZTdMazEybys1aUJVemM5ejBiVHlFLzZjdwpS
        V3prQU1xVkI1cTVleE1VK0wwejFRWUd4cTE1Z3FCbm1hVjFmOE9TZlo4Ci0tLSBk
        QnExRkhJVWhkNTBaVUJNcVJEVXhSNVNIRTd1algrNXI0Q21sNGtWRGQ4Cn4P8v0b
        bjh0hzyPhI42JaldsDxuvboVxndNI3kNB4l3C7g4sMmYW11D/Wu1sNQSVXRkSRsZ
        ewIBY+Vo4r+LuhE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-24T19:53:41Z"
  mac: ENC[AES256_GCM,data:5e2ZS7kexBkgDnwxX3eo3JpiinQztc4h6B2fomrUncUDEMP4AYXFg6pgejZ9u/BITHu7QcD00HWtjXtzkD0k3sD5qQcjZuIgngs2QPBBbBBOfKVxHL+mLv5/iaGa9qFVuTcw1B7smA4vWalBBvkkMvXufTpi6sIH37aj9M3sj0s=,iv:VR4pvwFZTIaKaedgn5Ms5w5pM9n7oGhMRKVBJ+ZTtzE=,tag:S5cyjfghp4/uM5ZNI32rPQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
