# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: flux-operator
spec:
  image: ghcr.io/controlplaneio-fluxcd/flux-operator-mcp:v0.59.0@sha256:ca1b36b93bb8fa22eb941af690c1788c5eddc12497eff645452f9710b2c389c0
  transport: stdio
  groupRef:
    name: all
  args:
    - serve
  env:
    - name: KUBECONFIG
      value: /kubeconfig/kubeconfig
  podTemplateSpec:
    spec:
      volumes:
        - name: kubeconfig
          secret:
            secretName: toolhive-secrets
            items:
              - key: KUBECONFIG
                path: kubeconfig
      containers:
        - name: mcp
          volumeMounts:
            - name: kubeconfig
              mountPath: /kubeconfig
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 256Mi
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 200Mi
