# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mcpgroups.yaml
  - mcpservers-optimizer-group.yaml
  - embeddingserver.yaml
  - virtualmcpservers.yaml
  - postgres-mcp.yaml
  - karakeep.yaml
  - searxng.yaml
  - homeassistant.yaml
  - flux-operator.yaml
  - grafana.yaml
  - github.yaml
  - sequentialthinking.yaml
  - context7.yaml
