---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: talos-mcp
spec:
  roles: ["os:reader"]
---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPToolConfig
metadata:
  name: talos-mcp
spec:
  toolsFilter: []
