apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
    namespace: observability
stringData:
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:KZCg8z4iez4iCW6DM+wyLslUkRgRRBXO4mxCRQHRcBHmFxifMFUK,iv:sjSWRlGKNaSob3/TrJUPoBEu23j3eS978cle23itEnc=,tag:KFoFlXa7nphq4Zlwagp70g==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:F4fxU2E=,iv:kIZ8cAk9P+CYSuRTAVHReWrj7meToU1PjLqFkNXN8KE=,tag:fCLPNaTgGPdmBUDC+RBDHg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:WkH8PYY=,iv:zN760dvWhOrMIk1ppY9AMMTYq2871pOPVIRU0JHz8Bg=,tag:WwotR0CeqtdwlRPCPID+uA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:caqOKNgbeTs=,iv:kGfT8Sn4HiU+csBpjfGwVngipw4r0Gd84uyJ+FRz0ic=,tag:SJa6grC51sjTOuRX8azv5g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:OJFihmZ4X58=,iv:aNhCONYqmwPXigbRDNOq9f72ptuEAWYaKF4rhQrI74E=,tag:WQAQ5L+LT2GW8pciB5oYGQ==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:429MPmHpkNbblWLx8LqLMKdQojXsthBMy0GSrBeeIdRIH0Ul725kDtbq65TS6CnXGI17uJkqMwNA4+sNCp/lbuMmyUVNy4zHG4z/qZB+ZhovoBlusCrJ+hphjGfYJ7mbkehHBVzdj7NkYMTrK8nP/vLgXTkGHnnOeA==,iv:o968amUxRwHdfCN/aUa7QpJgbx9JBaftIl2RwenV55k=,tag:EuhDmJN4BK0WNvZ10vgdNw==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd1p1SHJiQVRYWkRlQUUy
            YnRzNlFSQnluZ1NQdVk5Z0VmUkU0dk44Z0gwCnpHbEd1R21McTFkMzBrM0U1U2lq
            NmZKQ1RuVGFEdzJHdEw2MnN0Zm1PcjgKLS0tIGNCdkhDWVZoT3ZlVGUzd05CajVD
            OHlHOEE4QjlweDRLR1BTanFpNGcxZlkK+WWzdC5kwSbUpcsR9spN8G7V+9shxkdQ
            exKY5OmR73kEUkv5YuUgur7ZXWPqMptbp/7izAZqQ+Euf9yf/g1u0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T19:15:24Z"
    mac: ENC[AES256_GCM,data:3Eij13YrSqQrrgOA9a3NL8diozCb+LKcJebOAhRqJ0y99ByndDOIXpFhYhmgOh6pBP5ipNnMhJEMPLoFUBZ1k4bzby2ulYilZ5MXZYjLeA9p7VhoF4gyq/1875kTVI0daeRVXiqX95+ZDoOmqhYFO1nyREuxppU2GaWaS9kChjg=,iv:p+jBRu1Wjhs610n9aJ2X0XaopwFW+RSRkc6f/jU19b8=,tag:93K0qcRK2sACbtZolnjlwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
