apiVersion: v1
kind: Secret
metadata:
  name: gatus-secret
  namespace: observability
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:KZCg8z4iez4iCW6DM+wyLslUkRgRRBXO4mxCRQHRcBHmFxifMFUK,iv:sjSWRlGKNaSob3/TrJUPoBEu23j3eS978cle23itEnc=,tag:KFoFlXa7nphq4Zlwagp70g==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:F4fxU2E=,iv:kIZ8cAk9P+CYSuRTAVHReWrj7meToU1PjLqFkNXN8KE=,tag:fCLPNaTgGPdmBUDC+RBDHg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:WkH8PYY=,iv:zN760dvWhOrMIk1ppY9AMMTYq2871pOPVIRU0JHz8Bg=,tag:WwotR0CeqtdwlRPCPID+uA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:caqOKNgbeTs=,iv:kGfT8Sn4HiU+csBpjfGwVngipw4r0Gd84uyJ+FRz0ic=,tag:SJa6grC51sjTOuRX8azv5g==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:429MPmHpkNbblWLx8LqLMKdQojXsthBMy0GSrBeeIdRIH0Ul725kDtbq65TS6CnXGI17uJkqMwNA4+sNCp/lbuMmyUVNy4zHG4z/qZB+ZhovoBlusCrJ+hphjGfYJ7mbkehHBVzdj7NkYMTrK8nP/vLgXTkGHnnOeA==,iv:o968amUxRwHdfCN/aUa7QpJgbx9JBaftIl2RwenV55k=,tag:EuhDmJN4BK0WNvZ10vgdNw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZDVYQVpZNGgrYmNqM2Zn
        dnhhWmVTb3lQRGdFU1M2K05ReFEzajZJM0hzCmltYVp5SThIV0dMWG9mSjhhRy85
        R1ZxdTROWjhZaE9JVTkvWndZcTRHZmcKLS0tIDFMWmhyV2FUNWVzME1VRSt5Q3Rq
        U0ZNYWZxVGs3amk3d2htTlo3Y05CT28K/7v+d01G7NNs67dgf/WcfSNmxcf5Epul
        mgxDpDQNTqzlr5gBaDEhhtv4hrVUFnVbfZI6AV3T8xVoOjOtpaIdlA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG11V0QzTUta
        a2VrWFFLRjVDMTJuclgzV2lyU3QzRXJBaFJHNEl4eVAzaDd6YVdIRHlkNTczWEor
        NWJKNXFxNVZXR2ZzY2Q2ckVhVlhQZ1k4cm1OSTZuNmhTZ0RZbzEyM0FOYXk1b051
        OUxVWGRid2VlVGpCQlZzL3pORmV5WE1EcE5xcTVkOXdkbkU5WVczQlJHRlBpc0xi
        WW9lcHViVTJqZUgyOHhEazA0cU5UTWU0QjVtS0pUZFNPR2Vnc242NHAwTWFwdnhY
        UTZCbTBKUHZNaitzT1N1QnFyMTBncGdBcUFiazZISExyM3RqRml5UHBIWGdWUnl2
        bnh0UmFWajBKL1BkWGRaMnNMVlFRMWNkZEtuNnNORFRoSUl3OVBaZVhSTWdjaGZZ
        ZE1KQW1pL3A5aWNQbTFkK016UWFPUEJlVUdhQUlSVlp6ZUVZcmhqSEJnSGhPVlZO
        bitaY1VnTVUxQSt3ek1tcGhJdzlWWDR0M1lwU21UNHBtSmpsLzR6Q0huM1ZTUEJ2
        RTRyN2U3azFRbHhpeVlsdysxOGVIVnE4YVJZc2NQVXpDUjB3VFJjUjczNjJCZ1Zp
        MkFGV08veFJIaXhNT1htWDFqNnRaK0k4SzFpRlMyUUsyRzhHSUp1djY0ZnNnYTdW
        akd2d3dYbzhrVG5JVzZqdG1NZU5wOFBiZ1Y3QVo5eXI4Y1FrWkZlRHdvamt4TUlp
        VkUvbkN0bFd6bFNocEZURHYwaU45SUgzaEpaWXE0R0llTWplLzdqQmFHeGJvdWhP
        MlB5RXdmY0JSSEJ5ZVdUc2dxVXZMd0IvamZhci9KMWxsWFVEL1A3ei83YlZmR3VE
        SExNalFvcnA1YkZxZkRkU0c0OWFJSTAwV0o3N25xUlpLazBUQ1pYNnRXd0kwOHRQ
        bEFRTWRRMjFsblJJSFRUMndQbW5yOTQwZHB4YjcxbGlneDdYbE1jL09QSm5FN3Zn
        RG1UbUhvN2YvRzJORlhmajdnSWozVHFqQm5CTG9MYlVwT2ZEdlNZOTZYU2piTnlC
        emE2MWZxNjA5M3llSU10cXJYYXdJUDlYWkcwRGdCOW9EdEFxcElhU0xPQXR1cGYv
        anpvV0JsOVc4NWRRcDE5SzVOYUZaOWIrQVgzcElRN0dlaStLTmt2cmYxWi80Z2xj
        ZTFQUjc3eVJMMEZwK1RzMUJOdGpMd0hVS0lIV2ttcGdreHhtT2hmZlRKT3E0OTNX
        Q2JtS1VWTnRkOUFjcEpjS0pGL3dHZ3R4S1hCZ3RpNTNrUUxxMkYvWWhOYVY5ZFpi
        ZUNlMGM1a0JsblFvU25wSXBoK0svV2htVkt4VkU5VnJvRFg3ZWF1RjNWNDJId3M4
        eDA2aVA3YTN0MTFqN3pvdEZyMDJMRFcraUYxUzNxTUFacnlSbkZia2M1bitwTjlC
        U0hIWUlOK1RRL0RIcTREVDVIK3JJdEwwdmZObEZRQTNyenVhMnFxYVVYNGpKcEZz
        QnNCdENLYUVYNWZFakFQZjRRTU1mZDFicGoxelc1YXlvL3pzY29NNHA5USt0KzJz
        K3ZxZ25OR0JFaWJYdnEyek5pMTU5ckxHQ3lNYjBObUtQRi9WWW92SEdqL0NvLy9J
        bEpaMjRzNWpKdU8zTUFjNm56UWFpVWNGSSthSkpWdDVKOWg2dENyVVl1a0VIR2Vl
        STBXNW5ZN1U0UEJReGN0bWpKV2prU09KMlNNUE1lQWtKL1pkZWg0b0JLUE5qUHU5
        dnlsR0J2cXc1U3Q4QlhLSWZ3T2I5RGtjdXloNVZWR3hYeWV1N1FXZzg5Qmh1dWFB
        dVVTclpUVGt3TkJmdWFWYm8wQUh1S2hmV0FOb0wrNFJvVURvVXBMM0d6QlMzMjRR
        S1d2ZFlYeithM0FraXE1dGdmQ0tWSFlvWGVoWXB2QXpTcisyYUx0VElWV1cxZ1Qv
        clhZZTFDUkJWdHpUS2NOUFgwWHp2dXJZWDZhTFZoNnVvek5NcitCNmRXMEljdwpr
        QVlQcHMwS0d4WjBPNXFvSkZWSkFHSEVoMzdmV1FDaDJObUpTTWxzNTdjCi0tLSBr
        VHFMN0tMdkErZXZkWTNhNTdoK0hmZ2o2di83dGdFUklsZDdBbHFCUmJvCvCTueUO
        6HWlxuzSPzO95nj5PTmiTErh4/lFCsk3NbYJjqRh+gKNk/CdvLqReGdrr61G1gbK
        47k1Gy7VC0FKRaA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T14:41:37Z"
  mac: ENC[AES256_GCM,data:CDcAaGIB/PIvbgOUelY09MtkKmkP8jj2XP+GFqkHJj3H/vDW1HGQ9AeuRI3wosNXoQgZ4IP8JCpOuWkmMUO2pPZqFlqNCXSAIXX5KKH/tAv/wDcHsYcDmbUaMEcBkFb6X+z8i4OnVYIjiWHD5D2t8Rb0pxjMqO7igrEfZR+f9RU=,iv:ad7ll+jKnI0xF8H3F1Zny+mNl9mtozG5Vmp45xsFgrI=,tag:Iz2OFbrYXbKmofNWNAHmyw==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
