apiVersion: v1
kind: Secret
metadata:
  name: scraparr-secret
  namespace: observability
type: Opaque
stringData:
  BAZARR_API_KEY: ENC[AES256_GCM,data:TRV5QSkLwrHHkuYIooV5i+L4nNgqUfi76od/h9Zgyx0=,iv:59xt4aSz/Y+8ErkytJdwj5sBf4hqRTS5oEsbzQ4/mi4=,tag:/a/l7kEZYGfSOEyrMDfdlQ==,type:str]
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:e2iIU3BHLBM9sBGO+glXCrAaYnX2RGnuiva3Io4uZN0=,iv:BVl0JUZFyRLhtLNntx6OFxJOxo3Bef5vYUXKDKeHupE=,tag:Jd3XiPeC/5MbtArA8UOe4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSVcvWmRIU2hadEJENVJY
        eG9wSDYyZjRhTjNaU3pSZ0xMczAyU1VUMzBrCm9XSE1SbUVYWkF3a2d0RFJWL3Zh
        WWhmaytEbHlBRWdsWVhBNnd2WTRxYVkKLS0tIDdOakJjaGpidkdxclZrVGF5U2Rj
        MlVtUFloMmlwM2FaRDNUTGVCSnlsZk0KfgSxc23CAhgKIpi3OkfZzb8/Y50NrFCY
        tQYdRiKhHUnJy+Uv5xXHLFZmx1/XaoKvlGqmLQoOR6onmsfMon1c3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEt2VEkzQnlD
        MGlpS1ZyODlKSVc4blQxYUt6TTdBOGtUZUpNR29ZNWVoM05HRld0Q1lMS1RSKzM4
        NUtKcUhka3RaSGZiQWxpYWhWcE9HVHY3d2tOSkREYzNhVFAralJwUEMwUDE3aTZw
        STh1L3RGeDlibnN3NGF3b1JJUEJlT0QyZ2h1UUQwOWxkbXd2aDZDU2Jlek9VQ0xD
        MXdPenRxci96L3MrQ1FqQWxhSHhnSWtTZ2paNmJmYUg3ZUx0WjNncExJbG5EMkpv
        ZW52NGd1d2s1NzZ1eW0yVnNwQ2pUTDNrajVFVERVUGZ0cFJQeEtHZnAvamUvQURy
        SzR1NDQzc1BHQUY0WnBBRlhGVnZSMll4bUUvYmJWRXVpQUF1dHZuRVlIb1lpeTZY
        VGVFQkpjT1JNVTJqTTBIeW1rUGorNHB1WmRKNDFjQmhCWkxxSmZOWnJzQ3ZUMDdt
        NGc0OXB5b0FZb1FaUldnL2k3aGZWREkzVVJsZ2dGUk53ZGs5RFo0RGVBNGNmaVZ4
        MjIxQ1ZzeU1SdzljZU41WFVzZ3hSUXcyeXYrbktKM2E3YXlrcldiNWI0aldKWW1p
        TFBKWEY1RW83Yk5rRnFqSmpieTFPekZOUzNFdUN6WFJSZmg1YTljeTI4S0dEZHNQ
        OExQRjZNVDlmcWdvR1NpN1Z6Z0tzNUtsc1NacHN4TXA3RGE2RVkrb1NieTU5cCs4
        UFh2Z0I0ckRmc2srWHl5ckFHQzVxVkgrUC9WYTN3RHVuVkc3UmRhWEhyMkIxa3dU
        YjdWNWc0SUd3aFBjYUhwU1ZmditsczBCMzkyOG5WQVlFRml0RUtZNW9McmZWSGMz
        bWZONjRFcFk5T0N5UGEvSjFHbWNmaWZmQkR1cElGYmpWS0lSYUZJMmZOeCtMVCth
        R3Q0MUcwWnk3M0p3dG10TEh6NDF1UjN4cEtvRTEzK3dxaG1ZdXZET1BIKy9ORllL
        WlpSaDlCbmdNL1ZsWnc4ODA5Y2dqZHF6OVkyeDJQUkgxVm5aOTJCM0Rkd0tlS3Na
        ajU2RmNCTDM0ejBhUmdzSHZKK0cyaE1qdkFVU0taeVM2UXNsUWZqY0l2SHhPRzBM
        Wk1xTzZ5QnQrUStuNG42Vk1BTGFoMlNTMFRIMk1KdDhTbll2aVNLSWR2cUJSMHUy
        U2l5Q0FaNDJWMVlmaEFXZnRhTjQ1NUc4VVlRU2NmRWxRNlZSUjhqbVMzVWFsZTZt
        NFUxWGhvL2s1Sy9lbzhoaFJhMWc1L2ZSVmM4RnYralliSmdzWnBVODA5STVwWWNo
        bHRPdENuckZvRHJyOXFyaGpQL2RWWTJFaEdEQndxdnV0bDFORW1pNlgyWE1aa3Ji
        KzNtZTdzTDJ4YXd4bnRkclN3RWEwVXpGYXBFaDFKZ2hrTFQ1Y0FNTDNSNFYxendK
        YjMrSWZlb0IzWVB0aFpOMWFqMUszSW1jSDRCQTIzZUhVNENtNkNCM0RXYUdzUVlz
        YkVrcEdDUXNnOUhTQW9POFZHbTZEaktVOUFQbEdpelpoUzRWREEySTVZN3lQZkJR
        R1JVOG1MRHE2OFVBM3lPM1I2RVJIeFBYNVJ5SW1MYnJtVlRvWFNkZkNvU00vMFFP
        T1JIR1lxa2FyQlRrSkJaRTNOc1RCaFk0anZkYUVkU29wNjBVOFVGQllnZ2pXNWxh
        UE8xdC8wd2QyMEtPYjV3NUdxV2NpbENqb2xhb05QWjl3VGZBQ0ZocGpXYkN3bFBx
        VnpDdC90TmxWellsS2U2U3l3Sm9DVnRGNEkyWWl4ZzdtTEZlRkMrTlR1b2hpeVBU
        UXdtdjBRaFhHK0x3b3M1ZU8yMEY5NGhsM0Y3OXhIMkJNTDRkVTU4bkc2NkFDOEVx
        eGhjV0IyWDhjb213MitycmViMG16cjlHT2JLd2RIczhYd1U2OVNRNFlwMCtYR3lV
        Q3ZLZ3ZTa1lqbW1JNUZ3L3RiV0RpQm9mbkQ4TXNyRXRjNkp5cFFQVVpab1RHQQpK
        WlRVS25RMFcrQXU2Z1hhVWROSzhGK0l2eFJ1ZUROWXM0T3FtRnlHSnJRCi0tLSBs
        K3FKTU5xT05DQVdLbHI4UFFSQmNockpJc2tjLzY2QkJURTV4Nno1aDRjCg6Xc3rq
        xIMujjKisha0r0DEGuFJ9O4/xKVijxNtRDjd+EnE286k66cMFv1ys9vPtdlQGIBK
        VOxs/QYM6kvTSC0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-13T20:27:21Z"
  mac: ENC[AES256_GCM,data:AvTvU3DQCC+LIn4ASh+Jl/o2ihaMn/1lckBLcs8WpxHtCg9KnVEclAI2Ia7z8aqw7qV5XYMvc57FIIjvvTJ59V45zuIPRAweB1TBl887t5FJXmmcggyn8W/Z3RSCaemBo26QH503I0yDVcfUGcIxHkSJQkztB6Z4Hk7YGGUhcoY=,iv:QhgH+LakcLSOIcIDebZ/0BDhBiimr3igAxcayWg2yoU=,tag:Nic7a62B/Aio/LYiQI+D6Q==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
