apiVersion: v1
kind: Secret
metadata:
  name: scraparr-secret
  namespace: observability
type: Opaque
stringData:
  BAZARR_API_KEY: ENC[AES256_GCM,data:TRV5QSkLwrHHkuYIooV5i+L4nNgqUfi76od/h9Zgyx0=,iv:59xt4aSz/Y+8ErkytJdwj5sBf4hqRTS5oEsbzQ4/mi4=,tag:/a/l7kEZYGfSOEyrMDfdlQ==,type:str]
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:e2iIU3BHLBM9sBGO+glXCrAaYnX2RGnuiva3Io4uZN0=,iv:BVl0JUZFyRLhtLNntx6OFxJOxo3Bef5vYUXKDKeHupE=,tag:Jd3XiPeC/5MbtArA8UOe4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IExsWWhBaGhS
        RlIrU0p2MXlBZEtnQzc0bDBCa2JkaWt2dEk1SkFuZC92UVA2YmtRa05qSGQ4VnRJ
        bVFlZnJjeWF6UXFibHFXWlZHOThseXZ3MkFiVVhNNVdEREwydktsOUhCM0ZyMEM4
        SERzUWNwaU42aDk3NEJFTzk1YlMwZFN5RmJROWt2TDAxMzlLeGRwL3NXdnFaNU94
        UGUwbVRZNjR6L3B3Ty9YS1Zab0dKNUg1QW5oYVdzSnF5YWVXYnA1Y3U3MDRmRXFF
        eFdRdmxLYmxoaXEvUEZxRDhJSjdQZXE2TUdTYVU5Y1g2eVBUYk1Qa3Q2bDc1djZk
        WGhlcnRwKzl2WE9MWnBxOUVGMmZIUk1rdlFxNGRjNTRsTjNsQ1RwOTUrd0tsWUNa
        R2pURjlueEhXb3BaZGt6UEpGN2lIcy9ycGJlSGM3REs1cFRsN1VjbFpVZGw1dnUv
        a2g3Nkp6QWFoM0VXREg0NW1leGlOeWRoa3NWbkRrTTl2RFNvMk1Uc0l5d1Y3RFYr
        UDByRWNKSCtSbUZSVXJVWGVXZlVtRkQ2QTE3UjNlcXhEZzAycldTY1lzdGR5QjM5
        dEpoeit4UllFb1dheE5qNk5NbFBaRnozQjBwbCtkeERwdkVOTVJEWUNzdi9hNUlO
        YU5ockdOZXJTWEsyU2NITTRacDg1cGpUSEg5UEdVTjFsenFxRjJhTDRmRjBFbjAr
        dmx1T2doOXM3cU5mamR2VkZ5UEU2ZVo4cTRQM2xPMTBvWWdSNXZtMFRvLzdLY3A0
        U2tvWW11TU1VeE5Tckp5RjZSeFpPakl3ZGdGQTNEcU1vRlF0TzRlN0hIczZZT21t
        ZTcvM2I2N3ptUmVjMDJ6WmNTU2h0K1A5TEVZVmFwb2FHZmo0NFVaQndFeUM4UHZO
        RnBJRzRlUG1TNzRhZ09LdjBreHJmRDMrc1VRQmV4QkRjR2JVMUFrcEFTYVVUZWF5
        UTM2c0FJMVMyNU8yb3VRRFA0dkdGU1B3R0xIM01oV3V0T1lGU1Z6UkxBSUxlYzla
        UTJIVFJDRzIzZkptSEtvWCsrdGsvempwM3paTjVBUGx0TnRGSmVpcEN3ejEwVUps
        VjU1UDVwbWpjZU4yVG5YT01JVVV5NWhqaGtRcmVmRTZxV0NHUE1rclpGZHFIMWY2
        aS9DSmppeFU5ODVaOXN4OGdzeGJRbGVnZUY3L3JQaytOT3dLSkJGTnlNcTlxZGJQ
        OXN0UFY1a09uTWhOdzBGVzE5QnhxdDY2MnpEQld1aWpEcXJMcnV1ZjdHZjAzbXBz
        Vk5sTVR6cXBKWnhKOVdlWkFEWTdFT0FuM0JNL3JOUXdwZUpWZjRaRUFPcDZPK2ZX
        alNhWlJTRGxSWGRPd2x6RzJaakJ5V2VaWGRpNGxUZk93LzM2OXRCcDlLTmVjcDI2
        L0U1bnMrN3lUaGZwRHFXTytvZk1aenVjRWR1LzMwU1hIZ2pwTTUyUDFML0szeSs5
        WDJjMW8xekhOejloS21VMGhwYjI5bHRDS3VML3cvNFcyVUIzenFnSWVlZkJrR3Zw
        UWlST0NycFdXRGNVdnNOTlJYSWZaUmtTa3BaRGNUbnFMajBIMm1QaFluaHZiWXo2
        bDJTU1R2ODVvWjNwdWpUWEozcWVsMEMxb2hHZ0NXbzA1a2R0blpnNnF1b3ZyVThO
        bkJWd1RUL1g1ZENocmtpMSt1Q2pxRW5ka0FmcUw2bWlvaVNVZWprMWQvUjIvWXUz
        bWUvbUhkdm5RQTlIV21GMHpyOEtkbzhkem41OFhDOFlNdUF2RzNIc2xTTXpIaVM3
        NktGakhTUCthaHE0eHYzNWlNMlFOeVhBVWRDK0JzTjBQdWJaNThPS1lGUFk3U1Jq
        YStUc1NPaGltUVhnSERJR0hqRGF5OUgrS29USFRwcEFqR1hXSjRJbHg0d0IvR2VU
        cmYxTHdtRk5jSytHMjhtdThhZ3B5WEkxdVRUSzRBaGhlMEJGK0NtVEdmSGpBdwpC
        OUQyTUZMYk1tMndldlJaTkJxS2hac3RBQjQyenhsR3Z6ak5nWVNYMzFZCi0tLSBo
        S2hYNEY4S3orMDE4RUlMZTFTd2w3S3lSUTB6VGcvd1BYcndhK1ovOXVRCtftyCPt
        HMEC9qh/2d/DCwnaXQFu8nLBWDNQ6RzesfObePSv2STlFZgkCI3wL54TbABHXrX9
        m3v88DLgkVcyEow=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-13T20:27:21Z"
  mac: ENC[AES256_GCM,data:AvTvU3DQCC+LIn4ASh+Jl/o2ihaMn/1lckBLcs8WpxHtCg9KnVEclAI2Ia7z8aqw7qV5XYMvc57FIIjvvTJ59V45zuIPRAweB1TBl887t5FJXmmcggyn8W/Z3RSCaemBo26QH503I0yDVcfUGcIxHkSJQkztB6Z4Hk7YGGUhcoY=,iv:QhgH+LakcLSOIcIDebZ/0BDhBiimr3igAxcayWg2yoU=,tag:Nic7a62B/Aio/LYiQI+D6Q==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
