apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: media
type: Opaque
stringData:
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:jI9CHBGqkE9CHqbjP99rh7dD90g643JsBO511eYpJ29YrpPHHTPW,iv:ZqpKNy/N+vpLVYODqq2LOo8Q4PEva8sQgrDQgAM0ME8=,tag:J969N1JdVSpaxVtTQKYbuw==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:7QSdsA==,iv:j4Mec+DiCAMezaqBZEEewHtovTC9AEaR+Vc5fikZld4=,tag:isfT2jHPOURLBiUril/BbA==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:rBcZKeVQ,iv:vQX4HGXtWgpfiJMOqttpWm2nuOBdMoL6Buzmp8So/Jc=,tag:HRe21G7ov3PjnXbjxbqwhQ==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:Iz0IGuoHEAg=,iv:yZfYgn2HVPTwrf2FG7o2Kcvf0KkzD5118c6Gq2EQqEg=,tag:hqaRbFIpchMCW4zmsSuc6Q==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:tZpO9RQ2,iv:47VbmDvqP5A4H94VKZ5dWynsfks5AzFLUFscpn2L/gg=,tag:hM/FzQd71kRu6hz+aK3/rg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:StsYlPgW,iv:rFk9sXHUtRlnPwoVlQLrDylweIoewxFG2Zk5p6XBxeE=,tag:bBOkFTtBpPdaKAPCa0z5Ng==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:7juJIHxXibPUVsKSpsLjYI4nVPkSDMEAw4LW7JlKar3VD1FlGYb8,iv:y6gFLLclS7nyriYuQQX9ZMp0LKRlJF6vQEr5kTFx/YY=,tag:T7Qm71ilct64HwCpmLC3Zg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:S5iH5ipF,iv:ANm97UkcPXDcNPTgnmFP9qekjZBA5cA2cPiX9DR++QE=,tag:zBB3JuNu1aght0luq2nVLg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:nOcBNRXunxU=,iv:0CZYmCbSIwpi0TnV79XBKjO2/mVcxxevHrI78fu93Ds=,tag:hxh4x6at+uPvCrz2L0Ns9g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:k2wCZZLKduo=,iv:9J5d0QP+eevBh6Zh9RCwC74T1mcdex4fzUL1VFQxtek=,tag:CEIBhGF6J9DSq2qOtP1UMA==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleVU1d1FWVHVtTXd0NWZZ
            YzNiNmErcVExa2ZrQmxCeGFXMjNqOWpNcFVRCmhzNldzNmZBTHpOcEdLSzMxanVE
            TDhxMStNRk5LUW1adzBRT2F0aU5aZDQKLS0tIGdhb2YvV05DVjdZbUx2dFJtN1lz
            bE9DU0o1TUJNbi9DTnc2OEQ1YWw4clkKGfIgTBic6KcOIliVj+8c/mOTY9wCbo03
            fSu3V4MvITdAuXbzwLvKckaXRDCCXqbVg/X31LPhzKh8K46f7FLuvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T19:20:18Z"
    mac: ENC[AES256_GCM,data:dkepptbjTBKZTMIls9ZBzddzQUxCAZcjV/STDU6wnC0+Z2S9kgcncvILFSP1Uafqgq6fJicg+Vda/vGCrpKy+m1l+Y6ZRtIQxTE1dNJXygsSdXvAgGbgz4UKxiRvyOctZAf+drzj1IUuIagNFr3KDVS+ZxW+FSwZ0FsbzF9sw3Q=,iv:HFTWBXpR/nB5uxZfvJJSQwH6XEdNaoJkHQ5yxT+5XcU=,tag:42N36r28lHWMQeasoI6ReQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
