apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
  namespace: media
type: Opaque
stringData:
  RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:jI9CHBGqkE9CHqbjP99rh7dD90g643JsBO511eYpJ29YrpPHHTPW,iv:ZqpKNy/N+vpLVYODqq2LOo8Q4PEva8sQgrDQgAM0ME8=,tag:J969N1JdVSpaxVtTQKYbuw==,type:str]
  RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:7QSdsA==,iv:j4Mec+DiCAMezaqBZEEewHtovTC9AEaR+Vc5fikZld4=,tag:isfT2jHPOURLBiUril/BbA==,type:str]
  RADARR__POSTGRES__USER: ENC[AES256_GCM,data:rBcZKeVQ,iv:vQX4HGXtWgpfiJMOqttpWm2nuOBdMoL6Buzmp8So/Jc=,tag:HRe21G7ov3PjnXbjxbqwhQ==,type:str]
  RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:Iz0IGuoHEAg=,iv:yZfYgn2HVPTwrf2FG7o2Kcvf0KkzD5118c6Gq2EQqEg=,tag:hqaRbFIpchMCW4zmsSuc6Q==,type:str]
  RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:tZpO9RQ2,iv:47VbmDvqP5A4H94VKZ5dWynsfks5AzFLUFscpn2L/gg=,tag:hM/FzQd71kRu6hz+aK3/rg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:StsYlPgW,iv:rFk9sXHUtRlnPwoVlQLrDylweIoewxFG2Zk5p6XBxeE=,tag:bBOkFTtBpPdaKAPCa0z5Ng==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:7juJIHxXibPUVsKSpsLjYI4nVPkSDMEAw4LW7JlKar3VD1FlGYb8,iv:y6gFLLclS7nyriYuQQX9ZMp0LKRlJF6vQEr5kTFx/YY=,tag:T7Qm71ilct64HwCpmLC3Zg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:S5iH5ipF,iv:ANm97UkcPXDcNPTgnmFP9qekjZBA5cA2cPiX9DR++QE=,tag:zBB3JuNu1aght0luq2nVLg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:nOcBNRXunxU=,iv:0CZYmCbSIwpi0TnV79XBKjO2/mVcxxevHrI78fu93Ds=,tag:hxh4x6at+uPvCrz2L0Ns9g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:k2wCZZLKduo=,iv:9J5d0QP+eevBh6Zh9RCwC74T1mcdex4fzUL1VFQxtek=,tag:CEIBhGF6J9DSq2qOtP1UMA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNEFFbWl0ZEplTG9lSW1S
        LzYwYjJCZnBzaXhhVG9SWk1UY3ZZNnQ0cjFJCitadmUyRklXelY5MHB3RGlWQklP
        SGhjZ2tHam1zblI2dlBBbkl2ZWFZNmsKLS0tIGgzdHBuMVRiOXdQL3RWNCtGRFcw
        OEZrSGI5dmt3SzNlRzlZbHVOT1VXb0UKPM8a5cqXIkjiyV5rgaSAwvAqew3fP9pS
        CFS8oc6eNJjEZB5poj099kdhSR00Wfc9YyRB+YMBS8VQ3WiXU/vqkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHd2c0NnV3dF
        eDNWdENVSzlVUjB1aGVnU1ovcisyUDRlVm1sdHRBNmZwdngyV1dBbmhwakJ5b1JV
        cXo2K2JJSG5neDRPa0VGWUpxYnVCWXhRaWl0d1JvTWI4SmM0TmxzbmxKZVA2akYv
        WjFHR001NHlLS2UzWmI5UEFYL3lrR0Zoc1NuYnZSS2NCU3BheEJuSm5QaEF6alVp
        cnB2OVp1b0JNd2xCSlZid20rSUpwemYxaFdlS3oweThaUTdWY2JFZmlQTG1seFdp
        TTlybGR0RlRZTVhlcWltaEtEYWI3VmxDVGhjaXhnQjFTWE1DR0ZWcWN2UWRIVjM1
        V2R3V0dVY3J3Ymh5K3FKYVhWUEtEdmFXaWI3TGhEYWl3SlF5RHVhWldFQWJlVkVW
        NWFYVDZuenFvTFhtQUduV3N3bTl6U1lhQ2JGWVdrL25DVnEybFVHS0xLL1hNV1Fq
        RmU2U2NTbVo5QUR2dkJ1V3JLNDZTdldlb1ZIdnMra0F3cDA0ZVR3MVpvemVlbldF
        NHVONnpuK1FyQkM3SFZEMlpIeEpGY2dhbXl3RUVCS0ludHJQRHIxdU9DQk1aTkVX
        cEZpNDdycXNaTmR6OE9SekdTaFppamduT2kwRjZHYzBZNnA2SGpKdGVrVWxPRElT
        Y0EwRkluME9Jb0QrcDFnTzM1ZUJxWVFiNDNCT3FmRUZtQnJsZWExZUZKblEzM29j
        cW13bGJKcWg0OHVDaUdLNEc4QlFYTnpQdTB4Rk4yQy94U3J2WFNEMFJZN3NhSE8w
        cFluc1ZVWW1nKzBQdm5ua0czSWJlbW9WVG04aXcrUHMxNC9BbWV6UkJYOHNmRm5I
        cC9LRjQ1NEhiRTNvZzJadlBtREF5Q2JEcDF2R0pac3VDbFh3eHZjK09LYmdaNDE1
        N0ZYTWJoeGhSQWhCYXFIeC9Sc1JkcGtCbFNyeVVtRTRaS1gxM3dVOTA2U0RPLzZz
        MEcrNEdyWHM5QTF0ZlY5aE5DWmVsMkRhNlpNeTFCUWN5YWs3YVcybjlETnI5Q1NC
        bjE5OHExdUdXdTBBcy9vZkdkTEJyNERSR0tqMXNsQ08waUVUazI1SGRraDNDZzg5
        WTczV2w5MUVYWGg3OUNCZ1ZpSTNzYVpCR3NZMzNlNUNTUE8rTDBSRlJlMHFHalla
        eUFYNlQvcjQ1RXIvcWdUOStJeWovUGlpbjQzYzVONWl5YWJJNFpTejQxdkJSZ0o1
        SFNVZjF4dXloRUZmSTk1L2hXaGdKc09sL3JEc0FYcWE3TjQ3Tk0wb0IzZVFPQVNj
        d0dBdDlVSnd4WGRaWTk4ZllEOFE5SkJNNEhMaTR0bzZKMWRHcmZvSW1NaHpST3hv
        NERnS25XcUc3Mklob2o0VURrSGJaYlA4WTVHMUpUeWV2U1hsZ1ZxdVN6eEpteGc0
        U1BTY0RBMGNoTnNiWE1KSmhkUXQybEJ1U2VuMnZXeWJLTExQc0ZUNkVUSU9WSFN4
        VmRjT1Brb0ZLd3FHNXdJNEVnVFQ1a0ZtdEJJWVhDUnpCUHhaeEplandScHFLeFpv
        c3dNYlF5ZEd5TmdPWWVGejFhYVFxbGhJRFgxTHFSNmhLRjRERWpUSy9EMUxGZVBz
        WE11dnQvRmRVc3BFWWhNMk9NSW9HaEMyemlLZ0svdDhTcHhuZmxBaFVhZXZWMWRs
        VWxrZUxjRFAvN1BLaVllSUZKS3RtWVdueU1wNmZZditLZmxJT2hMY3pvd1ZpVXVk
        QXg0WkNEZHplNkpXUUZxRHpmOTRLQzVmT0trRjV3NElSTGdER0R6UkFSWUprKzdt
        VGUzaEltYWVuOHVOYjRrWG41Y3A5VGpZU1Z0ZDhha2t3Um1uL0pFRUpDVjVHOS9u
        VGpZbzIwRGVyVlN2eW9hbFU5VjlycExmRUhrN2hOWWRlZG9NaENId1Fkb0IyRjIv
        TERMQy9ady9IdjNVbUo5Qkc0ZXFycGtVRms3UGJkUko3SCtwV05iSm9wemNVUQpN
        QlhrN1dnZzQ3eDRYOHd4MzYwQW1Sb0FPOExseEFodXhKNGZuMFU4dnNZCi0tLSBa
        bHd3UktUMks4UXhvVUh0VHRvdnFrK0dIa240WXc5MDZoVzlWT1duU21ZCkE741Xb
        lRSJAQRnswvIY+tHld8mRpcfHOQUyclhwwPAiC4KV0bfWvMCQ+sveCjuiaslFqEG
        DF4YXt4MvFfS1bE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-21T19:20:18Z"
  mac: ENC[AES256_GCM,data:dkepptbjTBKZTMIls9ZBzddzQUxCAZcjV/STDU6wnC0+Z2S9kgcncvILFSP1Uafqgq6fJicg+Vda/vGCrpKy+m1l+Y6ZRtIQxTE1dNJXygsSdXvAgGbgz4UKxiRvyOctZAf+drzj1IUuIagNFr3KDVS+ZxW+FSwZ0FsbzF9sw3Q=,iv:HFTWBXpR/nB5uxZfvJJSQwH6XEdNaoJkHQ5yxT+5XcU=,tag:42N36r28lHWMQeasoI6ReQ==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
