---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}
spec:
  accessModes: ["${BACKUP_ACCESSMODES:=ReadWriteOnce}"]
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: ${APP}-restore
  resources:
    requests:
      storage: ${BACKUP_CAPACITY:=5Gi}
  storageClassName: ${BACKUP_STORAGECLASS:=ceph-block}
