apiVersion: v1
kind: Secret
metadata:
  name: downflate-secret
stringData:
  DOWNFLATE_TOKEN: ENC[AES256_GCM,data:TIVcgE1bE54fnx1swZX3aCC/sJUZaA==,iv:WuR2l7cDilwpvs2g7qhiXLyP2zXCGT/lHGGL7rutHrU=,tag:knZvSay/tBIhiHOGHFyqqg==,type:str]
  DOWNFLATE_WEBHOOK_SECRET: ENC[AES256_GCM,data:uDWZElPLHHwIVJeR/KbuxxIievmuvQ==,iv:1bSMnAIJ7lIcs4jN+MIiaTfcvgc9fGbMUQ6ZtglyYJQ=,tag:wkV+hcta2k2019DhelNFPg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Zjk1eDRCRXZja2ZJaGx2
        YjVnb3MxWGN2R203NHkvMG1xcFVUY05FcjF3CnZWWWl5V2svbmNrT2JTRnNmdHp2
        Y0JOTUJqKytqdUJBcElqOWN0VzJFaWcKLS0tIFVTRjNHZklOQlRHQ3pSektnTDhO
        T255RUFUOVR2WFdtNWtHeW9DYzFSencKZauC4fR0vQl3uaUiV9I9hdelrF2IaT4Y
        8PVXC8YuyJASpYlRXHiVeY/GoiPHArqg7qjgQGRtN04TC0oie/p9Nw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T18:55:52Z"
  mac: ENC[AES256_GCM,data:LMvpuCaTlzYQaS4pDiAbM+QXKd4PiCL3krJ4OuxUUIjPjqlOkjWPu8Gx7ondvXqm+40gleaG/AQJYep41lkGv0g21HJPwjUhoxCdUXN1m8GKxieI1hwd7neX31XO+SIEzXIhMpAr6np1lWuTxGi1zLztcgrnW+jbIa6PruQGvow=,iv:T3H2l4ZL+RB2220JZQLrRi+p98HC+PoQ/nVl+Cdr1SM=,tag:GttzrlMVTR/FkBiQ0sRUPg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
