apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:SrftPOuRDkE=,iv:cH30BeMrsIfoxeQV17Du4IVOXGkOejyXEHkQBmTIl6o=,tag:L85BhpN6rOWYjoragZPb0A==,type:str]
  TYPESENSE_API_KEY: ENC[AES256_GCM,data:oeGrUjlO5Uo=,iv:FOrcbt9Th7f7zVNBzeVBS6VjixMKqgHdlIl0PwgOjVU=,tag:+oitKaGZtloLRbjvwbmg1g==,type:str]
  URI: ENC[AES256_GCM,data:koC8kbIRha63KrqNjS1/CiLp7GQIaQyDh/4mca4FdM7jVchWpSYbSC5lOmoppS1hSKuCePsBcCOth3m3kQqBGje9FNvZ9fbXMoKye1rVZATSLLU=,iv:R771m2ye2K8FR70G4fGe4p6UTu9yvEGnGxWZL7GNWUI=,tag:9i+sKIJ3eiUkpwT2WRe0vw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:J4QK3re8,iv:kcdyFg3jKXS8T15C6zsQTBipTQXgr3/7KQ2FxLxktoU=,tag:HdVHf2pdVqv7VaNudFCAUw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:T86RAviIvOUUZtBg41IK5H4FGlx14qNa9FropvRFqKP00c94+E2lHsm9etQ=,iv:ukDcpg2mtuNlQbQNRDV/eprtQyhWT8q13FM5QXV7Mnw=,tag:mBsJbD5BlnY0xclrXf6XFg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:baAyYW3V,iv:dByFG24IS1MstekUVzjGc9U3f3yv77+EwGOI33NiyQI=,tag:+GO6I+KGOsC4NEqTr1jivg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:5hrR5Pk8lqA=,iv:0gxtmpxy3wd9mnCsjg7JA9nHH0P1wtffo3tjS3V5Eb4=,tag:qx6c2WRjVP4pDujj0J750w==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:BmH3kS+YvKc=,iv:1q6gG+muw88pWBWoMSRAW+5+qNqCCZYf5tL6VKtGkZU=,tag:Cc3k4LN3Npuplh45QhY9Jg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUnVteU9nOHV2Mm9MaDVa
        dHZETHA4dURQN3hjNy9rNCt0Z2ZRRk0zVEhVCm1jNnIveEFEdWRVaHpnaUxJcVFj
        MTIrK1YzLzUzcHl6R1pZaGVOc3F2eEEKLS0tIDA0WTEzOHZHMnhEbVZTaE54UEZ3
        aFAwRmdWVkdPTU9HQlRDUlY0NVI4eWMKpkHWgqiHjA4hHNy4p2cKbzjiNNu7HDqw
        oNpRccd5QBLUJDWkhDx+pmL2uJoJ4d0Bfcu1ZKiyG087nW/A07wZ1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGYzWlNMbFlH
        TTNRREV4aUcydGVxRVJsUlRLMzk3cXI2cFJCYXNFYVZ6WExOWjhKUVNYVE9vUTJB
        dXF2akVyQm4xNlhsdnZEMC81bDhhWFprSEdjM0FwbHZRdy9WRy8xbFdGUEJUSVFO
        dU8zUWZ0eVZvQzJab0ZPWEtvSGp4UkUxcVFubWZyVGxkWTNuWXJqUEFCNlA4WDd2
        ZFhScjZGVXEwMzY4NmN4NlVRYm1aaGc4bTFXYndaR1hESTdwNW85NVZUaWtWRXU4
        Zyt3bVhrRy9Zb2g3UGJybm8xbFhEblJydm5yVnJCOVFxeGxlREN4QkNTMElFeHFW
        RnpTbmJ0ODZvbFl2SWVINHRQY1Y0WGZvZUpwbG9WWGxVeFNCbEZxWUQyMnV4RGNm
        YU9yb3FJaURid1FpR1FVdVpuWjl0WjRVbzdyV0FLNHlDazVHRWxLZVo0ZGtLeGN5
        R2diZWRaNHhQUjNUNmhKeTMxRUFBM1hxa3VmU3RyVGRuWHRiTGJEcHFlTUlLVm9m
        Qk5EdFQ1R2xxcytwaTN5Nyt6RGUwbE5LMkRVMHJPUXRUenAzc2NweTZLdURKQzA4
        TVM1eC9iTE1kblFDMStTVVFqN2pHN1dNcUhGaHlFUmsrTlJCSjBJYTFjdVN2ekNh
        emVIdXR2RkJCdE05ZWRheTIveUxZVytZYllVMEJCV3RudThFdTVDdmg2ZCsvMVRD
        VWEvSkMwMEdSME9Ydlo5b0REdDVIaGFhMDlyT01qb09hR0JpTC82TFR4ck1hT0pD
        TVJaSHlGSGFxRFB0TnA1RURrdXVnWlN1RnFoVmMxZGFFTzd5eXBVVml1TC9Qb3lW
        K2dLRWdJNHJhWi90MWZJTGVSdVUyK0E1TjcraTg0ZXViZEpaYkkzMnp2ellQVXhT
        WE9UUHZqMzJ2REJ0ZFQxdTB3ZmUzS3d6d0VZVzR3a1pnQ3kxOWlTR1drbUpma3hF
        bW83M08wYlNFK2V0VXR5QTlNTDRKblRkR1hiMElBMU9xUnFjL0ljaU5Zb081aEpY
        Ylk5T1hNYmt0YmNjUmR4VExYem5seW5BN0FYVWJLeEhBdzJqQWt0TXp6VG1uZWRO
        SkJxNVFiZkZ5S2RnQ1d0dzl1MTBHeU4xaHpGMTJHVmZ0VlR0V2FkMWVDbEFpcVM5
        N015Y2JGdW5kc2RLZTN3MHZsMGYwdG95MllkMm11aVd6cWxSdlhpSm8rZTNNNWNh
        RWxQWHozSUFibTVjMjdYdm1KUUx3aUhNYTJrY0VpMmRYZFVBVFFqby85SVdNNjB5
        M1ZPZDlDVnFueUtTVnFqZ1BNME0zTE15RmpHWFBlM1FEVWF1WGw5L1lkZ1MzdU5r
        MUcwbTIzbGV2NzM1ZWk0QXRKTnpOU2FyczNJUkUwUEVhQzNGWlV5YUo0Z1hmZWt2
        T1pvTlJtMnlRSGgyeTRxdk9oQmhWOGJWanptZU1tamp6MWx4VzJYNU9LRW43bzBy
        M1lwZGl5a3U5UjB3NTE4R1hYSjdmN3JQdUJPZi9QSGJWRW9lMDNQWkpFUjgwY0Zm
        TUdWdjg2b3dlSWxlWnNyZngxOHRBQ3hQWUIrcWVyVkRUdmtDbFNHNHgvampvVEt4
        RlNUbVIvbDFGZEV5dVE2K0xIN2s4bWJsN1BMdTI4SnlnZWJZaGl6cE5tTndXbGNY
        WGdnMjVqaVZHYjVVM0VOOU5Cb0puMGVKcVhyWFIxY0sxQUFQZk5wOEhpaU1GRWNC
        dm03RFBYS2FrYjlQUmxZQ1g1UytZeWRsSUVWaDJqVDlQd2U4NndYb0cwaDR4TWp0
        MlZxOVJHaXZVTWw0K0poaXUvTW8xWFlZNUVtOU8vZ2txN2prcGduYlY1Szd2aFF6
        V055WEtMV2Q3d05vSjE0c2l4Y09qc0ZHZjJzKzRqWisydEJFeDYzclRlSk9FWUFp
        bEIxTU9ra0lpS1B0ZWQ3VjFNR2R1NTRibjdXQ2x3TU9RQlRubUw0ZzlsWEpiZwpU
        b3lsUTdjOWdhSTlJN2hHSUtGZld6RisrOXpHL3ZxZHZBODBSUHlwaVpzCi0tLSAz
        Q2JNY3RwdG9JbmFEa0FiQnpSYm9KLzArcGcvQ3QrVlFRTENKMVE2N2tZCnSk0ypZ
        FOC0GknFZ+NrHavYjQkZMr0Q1OVBn8uydiOiaFUC0FjC5YBE8/yOHG99McaihEQW
        zfTUPhF4lnvmrAo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-21T19:56:34Z"
  mac: ENC[AES256_GCM,data:Seh89CvrHCLrZgXcSRhfj0uK0yNha+k4vBCr+LDyv70NXzDQGyvdzcxodFh/bdi6uPfmXoSfc4XJdIItiZAwd4Vo6VpJGTyKxadAegvA4NRDImxyaFn5cIkeQFAi8iJvU1zpa2plPoulI8gwbErQd4BWeViyldn7tvnW9jFgKGo=,iv:98s9UVUt/9NZLAde8wbE6/9UtutwHlfxeA7RV9gY4tw=,tag:rg5WZO2mPCwAC7w4CkGJlQ==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
