apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:SrftPOuRDkE=,iv:cH30BeMrsIfoxeQV17Du4IVOXGkOejyXEHkQBmTIl6o=,tag:L85BhpN6rOWYjoragZPb0A==,type:str]
  TYPESENSE_API_KEY: ENC[AES256_GCM,data:oeGrUjlO5Uo=,iv:FOrcbt9Th7f7zVNBzeVBS6VjixMKqgHdlIl0PwgOjVU=,tag:+oitKaGZtloLRbjvwbmg1g==,type:str]
  URI: ENC[AES256_GCM,data:koC8kbIRha63KrqNjS1/CiLp7GQIaQyDh/4mca4FdM7jVchWpSYbSC5lOmoppS1hSKuCePsBcCOth3m3kQqBGje9FNvZ9fbXMoKye1rVZATSLLU=,iv:R771m2ye2K8FR70G4fGe4p6UTu9yvEGnGxWZL7GNWUI=,tag:9i+sKIJ3eiUkpwT2WRe0vw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:J4QK3re8,iv:kcdyFg3jKXS8T15C6zsQTBipTQXgr3/7KQ2FxLxktoU=,tag:HdVHf2pdVqv7VaNudFCAUw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:T86RAviIvOUUZtBg41IK5H4FGlx14qNa9FropvRFqKP00c94+E2lHsm9etQ=,iv:ukDcpg2mtuNlQbQNRDV/eprtQyhWT8q13FM5QXV7Mnw=,tag:mBsJbD5BlnY0xclrXf6XFg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:baAyYW3V,iv:dByFG24IS1MstekUVzjGc9U3f3yv77+EwGOI33NiyQI=,tag:+GO6I+KGOsC4NEqTr1jivg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:5hrR5Pk8lqA=,iv:0gxtmpxy3wd9mnCsjg7JA9nHH0P1wtffo3tjS3V5Eb4=,tag:qx6c2WRjVP4pDujj0J750w==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:BmH3kS+YvKc=,iv:1q6gG+muw88pWBWoMSRAW+5+qNqCCZYf5tL6VKtGkZU=,tag:Cc3k4LN3Npuplh45QhY9Jg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJvY2IrZHBq
        THo2d3NqbjhyZmFndkErekJ2cHFkek5VWkU5WjhUQ0JETy9YTDcxeGhKMFRpb0Vy
        azk4N3RWNkVaMURkTVJMakdZeTh0YmgrM0tIbXpoemYwMmtFQ3RwZ2RnbkNJZzYy
        Rld5eTdhbExEZUtiSndMMDZ2ZW9pY0ZEazQ3Uk5YSmRkcllaS1FYL2FHbTg4TFF6
        WnBacFhyRVFyY0FOOFF6RU9adms2WDlDRzZieFh3Z3cyR2VKYVBCR2dmWnphR2hl
        bDBRZCtvNkdMSWdUYmhmVDZnYjhGVjdpaHFWVGI3ekdzekIwWndGV2RrSDdROU1h
        Z1VIQ2Uvb054SHdSY3AvTWhoMFNuNXd3OGhyVnFYaEt0blVRUzFjS2JveHdCczZW
        Slk2RHNZZDBkai80bE4veDRrZkRkQW4wWHBwMmkrVmlqQnVwWlNvWDBDbGVNc25V
        OFhsR29iRlJZZzZ1SWIzWmhWTkhOdmozUGp5VUhrMGc1bGFYVndyUE5lYTIvOExV
        MGtCaGNvd3hsN3BrYWwwVXlXQUdteDg5T0k5VHRLd2RZRFZRMW1hcmpLT3A2M0JW
        TnFFbFBmcEhnMGt6MEV4TmxoSU1WYzI0a0k2dEtER3IxZFgramlwQ3d1ekR3UmtC
        UzRGaytRM2U1OVR4UjNWb0pWSGpSNmZwYXJ0TTVEYVIrOVl2blcwSGNSb0Q0OFZJ
        bnh1aVFjc25jS3QvOEF6dUs1cG1qb1h1VVBxUUpDNHhtNm04Q2daYWs2QmJybXM2
        NEJpWVl1dW00cjJBNzQrbkdtcGpmQ3ZGNHpFelIvU0ZOZTAvdmgwYVZZTnFNMkxU
        SEpJRzc4Z2x0VjJlcTZXaXAzRXc0M0FSaldyU3VDQmk2RWM5cW9BaFp3b1preEtO
        eVlMbzduSEFmUmx5OU5jOE1HbFQxUTZwNUtjUFNjdHpscUFyM2pocVl1TXlkempH
        Tmt4VGV1NzdVdHFGbUkrdEduS3pLREN0RHI5SE1pSlZoYnppTkVJU0JQTTRsWitC
        Y2VyYXJJQjJxaTZEc1BlYjNuZyswTU0zamJrMmNUdVFIVXVqRmthRit0Wnp3Wldp
        ZTlldVZwcFVDRHlDeUtSZmludlB6TzkzVkYwNzRTL1VoSlhwOW9od2VaaGMyMzVG
        TWl2emU2NU0xU1dyeFJ5UHJGS1FhZmhydVhwNmcyY202L3RWYlRrU2NiMHRHd25i
        d2pWcEMyL0VnaEpLY1Q5RCttc2xMUmdYalR2T0hlUWpZeWE4OS9TQk1hbTk4SWta
        Y1pqdEc4bWpCNzE2dGc0S09iZGtlaC9XcHc2VzNOSmNUV2cyWWpla0NsS3dlS2Vh
        S1M1SSt2WlN2cWJBdzZoRnFoSnZyTWZkd2hlRGJOVm1oTk1BMmNWcHM5ckFTVFE3
        YUhrUkc1TFBocXNweVlRL2Fsc0NKejNKR3lNdXk3c2h1Tjl5Z0NEbGVSOW5IU3Jm
        dHJEeHBIQWo5SWFtL2NHbVppWEV3YnJxTkZhejM4R2dYNXprT1FTSWNMcUdDcklL
        eEtHRDFOUWVQYTBGaTBJWnRid2ZKNW9Fc1VWNFBjSFVJZ3hxN0RVamNsRFYxRUh4
        dExQM0YwVFdVVDcxT1FiaE1tUnVqY2pnc2N5S29SM1I4NnVpZVJaQktrK2RCT3Bo
        U24wVU1kcEJucXBEZXlieGRXVndqdXpDOU83MEN4dVhxUCtJR1JJNlhVQ2ZUeTdG
        Lzd0VnZtaWFFamxFd0ZyVzFQWndHMVMyZ2xoSnVEcUVRQW1OZlRsbmltbDlCekQy
        OE11V1ZGV0krUkM0Q1U2UVA5eXU4WWhjSzFFQUtyYmplVzlzcldaUkhtMXNLeWE2
        cklrbUtHL2FaM0JJOVBKRUhlczUrekdIV0s5T0daeGpFUlYyUGxPaEc5bFpHbDBt
        V1V5S0kxSlM0VWx0RUkyM0F6RWxGdE0xdVZBOTI3TjlET1JIdC9RcllVQzRZQQpI
        MGxXajRnTU84RGlHSXEwZUlSckxYVFVQQzFWS1lvMTh3dW1xWHViUkVFCi0tLSBj
        TW9UZzRRUWkzZXFsajJ6a3FuTk9xWks0UzQ2aGdpK1J5THA0Y0VONzY0Ct+Z6H3f
        32EWBsTm2595ncwTKhPJ1Nmbq7qS8VYLe6NSLUBmB7Y0sYx83K6GXR+I362aMeYA
        sHRh80G7dEE3RoE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-21T19:56:34Z"
  mac: ENC[AES256_GCM,data:Seh89CvrHCLrZgXcSRhfj0uK0yNha+k4vBCr+LDyv70NXzDQGyvdzcxodFh/bdi6uPfmXoSfc4XJdIItiZAwd4Vo6VpJGTyKxadAegvA4NRDImxyaFn5cIkeQFAi8iJvU1zpa2plPoulI8gwbErQd4BWeViyldn7tvnW9jFgKGo=,iv:98s9UVUt/9NZLAde8wbE6/9UtutwHlfxeA7RV9gY4tw=,tag:rg5WZO2mPCwAC7w4CkGJlQ==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
