apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:SrftPOuRDkE=,iv:cH30BeMrsIfoxeQV17Du4IVOXGkOejyXEHkQBmTIl6o=,tag:L85BhpN6rOWYjoragZPb0A==,type:str]
  TYPESENSE_API_KEY: ENC[AES256_GCM,data:oeGrUjlO5Uo=,iv:FOrcbt9Th7f7zVNBzeVBS6VjixMKqgHdlIl0PwgOjVU=,tag:+oitKaGZtloLRbjvwbmg1g==,type:str]
  URI: ENC[AES256_GCM,data:koC8kbIRha63KrqNjS1/CiLp7GQIaQyDh/4mca4FdM7jVchWpSYbSC5lOmoppS1hSKuCePsBcCOth3m3kQqBGje9FNvZ9fbXMoKye1rVZATSLLU=,iv:R771m2ye2K8FR70G4fGe4p6UTu9yvEGnGxWZL7GNWUI=,tag:9i+sKIJ3eiUkpwT2WRe0vw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:J4QK3re8,iv:kcdyFg3jKXS8T15C6zsQTBipTQXgr3/7KQ2FxLxktoU=,tag:HdVHf2pdVqv7VaNudFCAUw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:T86RAviIvOUUZtBg41IK5H4FGlx14qNa9FropvRFqKP00c94+E2lHsm9etQ=,iv:ukDcpg2mtuNlQbQNRDV/eprtQyhWT8q13FM5QXV7Mnw=,tag:mBsJbD5BlnY0xclrXf6XFg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:baAyYW3V,iv:dByFG24IS1MstekUVzjGc9U3f3yv77+EwGOI33NiyQI=,tag:+GO6I+KGOsC4NEqTr1jivg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:5hrR5Pk8lqA=,iv:0gxtmpxy3wd9mnCsjg7JA9nHH0P1wtffo3tjS3V5Eb4=,tag:qx6c2WRjVP4pDujj0J750w==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:BmH3kS+YvKc=,iv:1q6gG+muw88pWBWoMSRAW+5+qNqCCZYf5tL6VKtGkZU=,tag:Cc3k4LN3Npuplh45QhY9Jg==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTnZaWDRTMHUzQUp1YmZj
        Vlo3dFBsaDN0U1Z5ektRNEtmMXJIOEpDUkJZCnJQMHRteEhkcTVPdGtJdjF6cWN1
        a3FVd3BVOTZ4SUxnbHdma3l6TGw4cm8KLS0tIG9aamZNY0hZdjkrbEdZQjVFbHAx
        RStDeU1xd3c2QkRPdlYxaC9LN0Zad00KQzdGE+ONxLBlnbdppqbrCmFBhusO/ION
        7pHdoP8TQ9IKm+neOGkpZY38vf0acA6DyGUv6qIZOYmcyxiFpbn5nA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T19:56:34Z"
  mac: ENC[AES256_GCM,data:Seh89CvrHCLrZgXcSRhfj0uK0yNha+k4vBCr+LDyv70NXzDQGyvdzcxodFh/bdi6uPfmXoSfc4XJdIItiZAwd4Vo6VpJGTyKxadAegvA4NRDImxyaFn5cIkeQFAi8iJvU1zpa2plPoulI8gwbErQd4BWeViyldn7tvnW9jFgKGo=,iv:98s9UVUt/9NZLAde8wbE6/9UtutwHlfxeA7RV9gY4tw=,tag:rg5WZO2mPCwAC7w4CkGJlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
