---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/maintenance_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Maintenance
metadata:
  name: kopia-nas
spec:
  repository:
    kind: ClusterRepository
    name: kopia-nas
  schedule:
    quick:
      cron: "H */6 * * *"
      jitter: 30m
    full:
      cron: "H 3 * * 0"
      jitter: 1h
    timezone: ${TIMEZONE}
  ownership:
    owner: kopiur/kopia-nas
    takeoverPolicy: PromptCondition
