apiVersion: v1
kind: Secret
metadata:
    name: omniroute-secret
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:PuqUvXJR826enHwvq6p3kiiIfu3Dt+nZICJIhU2lokxZFlbbgZYVgu947WYB2Ga3/Pcf4bHOcnc4e1axjpg+tw==,iv:f202RHk5uB4juwaro49gGh5RZ4HtDl5Q04/QuiVF2Jg=,tag:Vrm3IVzPuf/t6ERKHBSK4Q==,type:str]
    API_KEY_SECRET: ENC[AES256_GCM,data:DGPkNnb8+6VUM00DWjodfC5nNzQPfkDh3a+QN2HGI+b2Pw3c+ayXb0xet+Rnxjp29BBKT7vphLk4j6KvgODh4Q==,iv:7nJgUysktjzK9Zi5h31XCJdmHz2vzF8GFIeYj4ke5/Y=,tag:sMTsMHl9/4gddabxVEcyfQ==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:vfRAcHIT83vqqRgVgG5yeb3E8Z+ulBAtiPpMB8wRnvaWaGAtLaB8cMFWVov/XBYaP7gBFq3kzgArNQpmBTkq7Q==,iv:LuRX31HZM28AD52yRBZ/Nc/JBxRd5UtMrg0AScWjxPs=,tag:RpBvyIiKU2mbY6M8QvFTrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFRXRWFHcUFS
            THUxR00zK3F5WmdoVkxiMGsvcW5wZUMxQkR2NDV6b3MvdzJTV1gxS2h4QmNSanRq
            a0U0RTBKVlJrL3FnQ2QzeE54aTZOQWE5OU4vOFhtMWgzZnl3Y1BzNzV6NkJKTEtw
            dmthRGhoVytoQmV6SUQ2b2hzaGNHbWpYNmtCZDNmNGp6RHpjSjdQQm5zbTFSTHpj
            cFJLbE05TEZXSGdPbDJwcHpVa0QvcUVaRjFOOU9NazVLTkpXZlljQ09QRkFHalZW
            MC9TQVoyTFFCcnRMQml5OTBMd0tBTk9BbWZJSDh4TWFvMGFwWTFqQTJGZDRKQlpR
            MXNRTGVLczRsRldhbjhQVEZPZ0N0bXlqUmRxTUpFRGZJQzZ4Y2ZYejc3SHNCZmhr
            VUVkS1ZpT0tHYXFTencxcUFHUnpDdUtlbWM3OU1ZSTdISEdxakFrK21vL3NZNGVp
            aWh6dzhlOWxhcXNMRXc2Y1dXRXd3eVpKbGFzMmpFV1pTRDduZDR6OSsxd0ZUT3Fa
            a21kamdXMDhXV1dpYkU2RG9nQWs0TkhMbFZFNnBVRmRvREEyZTlTTXQxbkphbUJF
            YmRPcUtwZ2FjRHExODF4U2lrUWNrSFpXc1B1K0FzczREVU8rTVlwSkpxNnZISnZQ
            MHI0a0piVzRHZzlvZjlsZVRoYnl0Q0Jva29kWU11Y3pUa2xjRDVDWktPNCtTc1dX
            Mkx6ZGxLMDEzb0RySE11MDArMTRub0lXbXFZT3M3eko2ZTZBbHhKS2VneVVkellW
            NzhFbDJKTWU5Zzd3WE5RdERaT09KRGhqRFpQWHM2VHlEZHZZaWYvVkdqUUt4UnZU
            SFR6VzRTRXVwaklSdnIvZmdWUDZZbVdGK1dhMkx6ZjNFeVFFWEt1cDdmaWw2bnhE
            dVZlYkNtQms0NVVNSk1yZXV2YjhyOUxoZUlRM1A1M2JYSlFwOE55QWtHRkhxcEUz
            ZUcvSEV5dVB5eFZnL0VYaE1xWjVJcytUVUdVd2xPcWlTdXpNUFprUFFob09xUUll
            WmdjU2tjWGJsQ25CS2JvSm1YOG44UUtWSTBKR1VJWlFsZjFJV21BZ2V3UGdUb05H
            YnIyck5yaDlmbHJ3Z1pubWNYcitOWlpsMnhwcDFuNkxxQUg5a1plbFF2SDVHWHF4
            YnJDbk9FdHkwaVdTR3ZpSmpNanRxd05xYTFvWlEwdXdPL0hDc0lyWXptZXc1U2hh
            N0pVNmtMMGcvVTlTOUM0d2d2Rk5vS0ZaOVNMV0d2OVE5Q3RvM0RCeTFHRThrZ1BC
            UlRRM1FIS0RDRlNmNFhZQWpSQkxiN2xPKzVSa2xLUitLY2hRQ1hFVHMxR3lIakM4
            cTVyMHZGM1hDZUNXNjB5dTQwSWlCMjNtZ2VkRkRCL3RDNVNPK20zTEcwVG5RV1Rr
            NVlpeCt4V0dhTnR3Ty91SGoycmVISkJtSnJxbU8vWjZ2RkxFSlJ3aEpYWEN1YnBq
            RkRJTGU2ZmFBekU5akd3WjNSWU9xa3pIWXdCN0NQUkJaN0QvcjFPSmxmc0ZtTjU0
            U0VwOXJ4dVp0K1Azd25VZjcvWk96RVdhMWZ3OFcxeCtTUHBzZEVLYTNuOFlXQ0xM
            QmIxenhnQS9QS1FBVWlWSkQzY0Q2ZUFHOUIzeXg0RGt1VmFnZWdRSzRualFDS1d3
            a3BTRmtxMnFTMHdnZktZdmRjeFRvWTM4UnkyMHNhRHRVWVJtdlBsWGEzYk5ydUR2
            c2pxTmUxcGZCQng3YmFNN3BvbUhnUHVHbCtlZTc5WGpGaXFjMlA1TnRBcG5QVERq
            eWpWY0hwSk00bkY1NWNZaFhDd09JejdSSlRvOTlKV3VpOG1EL0p0b2lTcHQ2NzAz
            VGZPQmZUbGV4UTNhMTg0RWFnNFNyL3VwMkkwQjZtLzUvTWRtR3oxN3J1T1NaRzhx
            ZmsyR002d01jYU9CODhpMklxK0lVUXNPNERtUkp1N1BudEtXdVE1OG5OODZTZwpN
            Mnh5cUtNSklWY253QUNEalFvMWUwc09GTUxsU201K0lScTJTMS9iUEE0Ci0tLSBJ
            bXczNk5GRFM5OTl4V3JBVVFqT1FQUzJhWGFxOElKdURab1c0Y3REZU0wCjq/Ivan
            zOBDrjzpDCROKQVE/vyV47BqjyZC95ZYPA3Ck8piQjaghMig4sLSjWN/cS0pCXGs
            WvGB5ZsS5Z0kP1s=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T20:09:16Z"
    mac: ENC[AES256_GCM,data:Mok8MmVYvViqpxRBoRksphyPD9vmfzTfKAqhZLmQPXX76XU12GGcicBt1BjB/rUEbtu6hzfutOqsd0M61QTv1QLp93qlT1oHBaVsdGt2bT6LKtS8TLFKT3mRVBTMtafnhiaMaXVsRc9d6ZEGUpKTp1sbdw17H2X8DFdBhE64QHw=,iv:YnYzp4Q1JlbQe2lNbBOF3VKoxSI40MFulOelleGWkxE=,tag:RXRgCoR2yfeg7nXJeSFtlQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
