apiVersion: v1
kind: Secret
metadata:
  name: bazarr-secret
  namespace: media
type: Opaque
stringData:
  POSTGRES_HOST: ENC[AES256_GCM,data:S5ATnvkYesvXxTto1tmKAGvenuCefGncTPbH2FJFASJsyKcXaVJF,iv:9OooTJ/uDgNS4krg6mf6cMgK2oM+kVhOLytyaIuVTjE=,tag:YKzxyfBvPTamuey5KwvAcQ==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:pryhgQ==,iv:iwyq+iaMJclKnzujpgRjzRb4eXuNuhHK5FF9zx1AQKg=,tag:zh94umI56qZU9Z3Nwp5hpw==,type:str]
  POSTGRES_DATABASE: ENC[AES256_GCM,data:EpgXtz8F,iv:3qR+ylJkUtpucVgM86vo8mNMlgCOlMbq1JQvJDjhxiU=,tag:eO31JqFS/LiSRRTMW3YcRw==,type:str]
  POSTGRES_USERNAME: ENC[AES256_GCM,data:ApxdukaF,iv:HZznlrOvFQUeNcEAdlPzqjzgvJVba+nSsHwpUw2tDcA=,tag:gaBLL/NW0GyJFTtvR6XEuA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:uM3zusLjob4=,iv:RQYHhLh7FjcrgVCMypIv6f8eQ7i44qlQqgdL+AwY9ok=,tag:h6JwlwF5snbdVB5y5TtraQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:jCR7ti5E,iv:hCH+egP7Xq9x/LJFzMbQTgTlBC0LNqNss9lxnlbRbSY=,tag:YgfXBhwO3TGioyQmhkJfEg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ZaRPhBWwyKaGXoi/TQQ0QbtmQBfYAHnRm1kUybMpBZKgTnr3Mdh9,iv:xIPhpjrArx0FPUas9Aj+YKRpn+mKzQEwEWvdM7Ebchc=,tag:58KhoAYzPt8jrtKptBbNhw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:xbdwJ9zL,iv:xXNttyvPTO3X1WlBd8q1mG2LtSXwEN6Jpg8qcK8BGn4=,tag:YzfsZ+y7+jiPZivOf/0k9A==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:zwB0CIq/dI4=,iv:JUtUT3ALsXLp1V27baxWpt3hx8Ib2X27yD5kSTdhL4A=,tag:YNpR4cNKZprmjpx8yC+C5g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:SDRovI7vN94=,iv:Arr5Q3SReBzTFq05m0epOcp+xzsG3PXKx40ckjRk5sI=,tag:NED12hT97EDJomQr7ilUPA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYlY0bmFQWUZ0a0JBR053
        c1V1Nis0d1pGN2ZTOGVzb2NvZjkxTWtjUGxjCjhNSU56VzNzZFFaNE9nQTF3SGsx
        MDdmbFZReVRSTXBnYnlEOHZmRjNzRE0KLS0tIDg2S0RQRXQ4dDY1bWI2WWZyRlpH
        TTBFQkQ4eHppcERZTkIwRHVsS1FNRUEKocUbQpCyDhO7S/b0AZv7KTpvQOWvdQRX
        9PF5RGqFBcbTs9UlRvqZ/T75Hp0mhPSNOHrCiqM/AwXQadU0qDSUmw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDRPYUZYWHo2
        bmk4OE1uMGp1V0Y2VVpJOURLVm94VXpiRVRnYStLdU8xeVpBeE51ZGIzU2FhRWJj
        d0JVMGVwSjJ1djFSdU1sTW1SY2wxTGFaV2Qwem45ODJuSkhtbWxXUzVPL1g4VTZo
        KzNqRmxSeVg2UEk1V2pFMmlQSDJEcmhYOTFNd2NXRmxzSm1wRThQUUpVQ0VRN0hv
        b1BNeWx5YkQ1YXROai9oSUNVRkZndWtSaHlLelptRDRqQVk0L0tlMUNmYUc4eVY1
        VW41eEkyQU1iTytBRk1DaUY5eVpFV0FqSFo4MHNCUE5uMDRJQm8wekdIczFibmRx
        Q2tFNzQ1SUIwRi9WUDhzRlRVRmg2WENZcDg4OVZVc21CRmw3WG1NMHdOaWJYQXpR
        QVpKeURDSjR6OTJBQnltVkU5VGhnejRtTFF0Nk5SUHdBbllySHZQUzFqSmFZaWNU
        Q0R1bWxyMzIwSVlmdVR1QjR0WElzTERZd3lVbVpjbmw1MnBSNWozeVh0dWo5ZGFu
        YTFXNm5rU3dudTFOYmpzSU9CV3RiNFhORGNDRHdkZVByODdQUW8rNERsYWp3dlQz
        bDE1RnhtbWkyd1gxK05yajVuRDVhclFRZUNWeU9CaCs3TmFUQVg4WUtrRjlZNVFy
        cGdVTXB3d1F0bFo4Q2JPb1dnampVZmNjY1hvTnI0Qk1OMjZZRjZBZ29GamR1b2FM
        UXMyb1J2ZnNpRjhrL0dURVJRbFB5RkxiOFplU1dpNWxVMHp5ZVFmRDJMR3lacVJF
        N2VLUTNORkFHSFo4ampkWWc2TURJb1JjcjhVZVZ3N2s4bi9UUDFwR0I3c2RXd0pV
        U1BpamN3Mkt4OVVTMDRTZnJaT0pYSWkzaDJGTVYyemtNSGw4MXpucTAwWDJMWFpZ
        RlA2U3pwQnBGVU1odGZkdTZDWE9aVkdJbXdyQXpoSzdzbHRvQ296SHNDQjhkenhl
        S2t5bTlkeUN2bisyZmYxM3BvNG5Ib3Z1NU1LSHVoSXZ0UDNVaFNVZ3lSYjBvYjV3
        RnVqd0ZGQUExSjFHdFN1SCtyM3FqOW9nUFFuTmJLbllYNjBqcGFpNmZuNzFaUEEr
        V2NtcnFwaVVidFNkbkJMdFBvWnJyWHBEalJ1U1k4cU1kY0I1SkJlejM3WEpUWkFz
        Wmdab0cxYnpocWtqWWFlWTA1VGRaQWV2VWZGZytqNVZTMmo2UUpDZ2dKb2dwRnZH
        NzVGUkRZdDdLY1JOWFpzVTlad0FIT3dIeGZXYzBWa05nMTFUdnV4a3FraWJNWnN5
        OFhoeTlUSmNmVVpGMk1FbkFXd1VGOVorZW5DbnRMc0tMYk9URm9lRFZxV1VNZ2Rl
        cXowa1lFVUk3Y1IzZ3l3VWdUb2MrV1Nvd3NSUkYrcFIrbFJPZEhNdHhKWVljMU9r
        ZUNkN2ZGMGdyYmRmM2JNSTR6Nlh6RGFZYUsyQ21GT2pCREV6TURZYU9vampJNmJE
        c1RkTjVxanlHeDFYaEpuWldKdHZKQTdIeTg4Z0dSWCsxN2VzalAySkk5eXpROXRC
        T1l4MHI4eThVTGxhdURWMlhyYlp2Ui9sTE5JaDR0OGNabjNHKzY1eUYvTlk5c3RE
        WVFINlVGODhNazI2SWszaGJ3bmp0bS9OMGZ0U2hTR25GOGVYczVWakwxckZHUDhJ
        UU5WTFBCR3BkSW9Ncm1XUWlCc3duT1dZTk5NTytzZU9DTS8vV1JsYzhPQWZuay9k
        WEZMRjd6K3haa1UraHVrMHJ1TjJCK1E4am9WcFNuS1VPemlscTZ0aXNoNlVYbHVS
        SjdNVFNVWjY1enI3R2dmbExaUlhVRW1hR0VVaU5pOUkxRFZnZStsYzJ6STVGcHUy
        ZFRQcEFBa1pZK3dGTFF4QjVRR2hNUGVub1hYa0RHODhmNGhVTFJ2NGVDK3FwY3k4
        L1hnVFkrb2FDOHpvL1M0QUhKU0FUSHVNL3VYWllnSmZMNVh3OHJSM0l6SDhJdwpT
        dkh0ejYvYWNNbEhSNHoxT2h0dmphbFdkbXpibFMzZkcrU096NSsxdFBzCi0tLSB1
        b0lva202VVlMM2ZyR1VkU2hvUzlDSUpqRXExaERka3VlM2djOGNGcXdNCskoppXx
        t4+39nkUODMZIC3UxSmIsBh3zxocfsA95tJuWftowS4sBP1VKocHyDUlRnpuQBsD
        fSI8BvL9+7OYlkQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-21T19:14:48Z"
  mac: ENC[AES256_GCM,data:5kLUCYp6LcoXms7pk9VMsgbzR/JwcTqTWS3QXW+xK3cW5reeH2a3BqhI0NLnhFhKXdQXVtM4uX2js+elkG5ZrISYfShpV1IiEnDiyFV9hDPqj9tbAS+ahtkVF3SSNzK08vDTtlLg8CroDDRUGXxnwtbhx2FrQsZpgtgc1HGpowM=,iv:OC6eVteUmhSqUN27WN+ACwLXLu2xLxxOP9Gx3Xnwns8=,tag:59zg3kCAf4aLUCeOdRHOjA==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
