apiVersion: v1
kind: Secret
metadata:
  name: bazarr-secret
  namespace: media
type: Opaque
stringData:
  POSTGRES_HOST: ENC[AES256_GCM,data:S5ATnvkYesvXxTto1tmKAGvenuCefGncTPbH2FJFASJsyKcXaVJF,iv:9OooTJ/uDgNS4krg6mf6cMgK2oM+kVhOLytyaIuVTjE=,tag:YKzxyfBvPTamuey5KwvAcQ==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:pryhgQ==,iv:iwyq+iaMJclKnzujpgRjzRb4eXuNuhHK5FF9zx1AQKg=,tag:zh94umI56qZU9Z3Nwp5hpw==,type:str]
  POSTGRES_DATABASE: ENC[AES256_GCM,data:EpgXtz8F,iv:3qR+ylJkUtpucVgM86vo8mNMlgCOlMbq1JQvJDjhxiU=,tag:eO31JqFS/LiSRRTMW3YcRw==,type:str]
  POSTGRES_USERNAME: ENC[AES256_GCM,data:ApxdukaF,iv:HZznlrOvFQUeNcEAdlPzqjzgvJVba+nSsHwpUw2tDcA=,tag:gaBLL/NW0GyJFTtvR6XEuA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:uM3zusLjob4=,iv:RQYHhLh7FjcrgVCMypIv6f8eQ7i44qlQqgdL+AwY9ok=,tag:h6JwlwF5snbdVB5y5TtraQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WFdYWWZzYTVTY0hkcDRm
        dTZQOVZ5eFZTK0NxVERVSG9oL1NyT05ZL1JzCm1ZV2tmeUNsQVZydWtvVkZodmVV
        cTlXRTlieTE0em85YlBYcGN0STVxMlEKLS0tIGlSbnVYVHE5RURUbisxVDdlV3ZQ
        RjRYUTVWS2ZSK1pENzFvOS9WTFhBUjgKupk0EeHRErfpG8lrYkksr9OmgOTalXJb
        b966I64pWQdG7Urb4pNIOyHpJMBe6DX1vvqQ8aszXNi8UKV6ktoJfw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T22:58:18Z"
  mac: ENC[AES256_GCM,data:hM96tzVg3q202yhqBkKxPUvMYoAFzma7lPuC8+ViF4eJnvm0zV9yeLe4bR/Foq25UR1qkbfpkMn5MQbUzQA01Z7Ajob2Yah218uUWJcwyy9ujsiqt2LzoUeLW+uCE95eZ2X4PuHUxSxrZsNiZSQ+H0t3gJRldhER6iKEhnKxOR0=,iv:DQTabh+kg7FfmQvJRfsPPyLXwEX7gyRAw0nLMd33wZg=,tag:f4pmEQoztWQm+krH6l2dUw==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
