apiVersion: v1
kind: Secret
metadata:
  name: bazarr-secret
  namespace: media
type: Opaque
stringData:
  POSTGRES_HOST: ENC[AES256_GCM,data:S5ATnvkYesvXxTto1tmKAGvenuCefGncTPbH2FJFASJsyKcXaVJF,iv:9OooTJ/uDgNS4krg6mf6cMgK2oM+kVhOLytyaIuVTjE=,tag:YKzxyfBvPTamuey5KwvAcQ==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:pryhgQ==,iv:iwyq+iaMJclKnzujpgRjzRb4eXuNuhHK5FF9zx1AQKg=,tag:zh94umI56qZU9Z3Nwp5hpw==,type:str]
  POSTGRES_DATABASE: ENC[AES256_GCM,data:EpgXtz8F,iv:3qR+ylJkUtpucVgM86vo8mNMlgCOlMbq1JQvJDjhxiU=,tag:eO31JqFS/LiSRRTMW3YcRw==,type:str]
  POSTGRES_USERNAME: ENC[AES256_GCM,data:ApxdukaF,iv:HZznlrOvFQUeNcEAdlPzqjzgvJVba+nSsHwpUw2tDcA=,tag:gaBLL/NW0GyJFTtvR6XEuA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:uM3zusLjob4=,iv:RQYHhLh7FjcrgVCMypIv6f8eQ7i44qlQqgdL+AwY9ok=,tag:h6JwlwF5snbdVB5y5TtraQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:jCR7ti5E,iv:hCH+egP7Xq9x/LJFzMbQTgTlBC0LNqNss9lxnlbRbSY=,tag:YgfXBhwO3TGioyQmhkJfEg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ZaRPhBWwyKaGXoi/TQQ0QbtmQBfYAHnRm1kUybMpBZKgTnr3Mdh9,iv:xIPhpjrArx0FPUas9Aj+YKRpn+mKzQEwEWvdM7Ebchc=,tag:58KhoAYzPt8jrtKptBbNhw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:xbdwJ9zL,iv:xXNttyvPTO3X1WlBd8q1mG2LtSXwEN6Jpg8qcK8BGn4=,tag:YzfsZ+y7+jiPZivOf/0k9A==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:zwB0CIq/dI4=,iv:JUtUT3ALsXLp1V27baxWpt3hx8Ib2X27yD5kSTdhL4A=,tag:YNpR4cNKZprmjpx8yC+C5g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:SDRovI7vN94=,iv:Arr5Q3SReBzTFq05m0epOcp+xzsG3PXKx40ckjRk5sI=,tag:NED12hT97EDJomQr7ilUPA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHhFSEoyRk1C
        Ynh3MVp0T1VrUXlsREJGWllVVjJkc0txV0xuVzVvbm9aemp1TFhLTS9XODBtRGpP
        Q1lTZmNZcmdzeDgzMXRhZ0FRVDJ0V2o4WEJLSXQ2STl6enZqQ2lzQUsvbWxIRXVz
        UXVmbUpRbitheHRzeWE0U3g2WmJCTUVHZnd0MEtGTDFZNzVOUFBuWVJNNWtNVkxn
        OThqRER6aDNDK1hGY0NrU3dxOURHTUlMR29JN0I0d094VHNCZCt3QTRqMXhtS0tO
        ampRNjVaNUJpdGlLTFhDNGtpQjZ0dTlYVUcxUWJ6QTgwY1kwaUloYWNaVmpVTFpT
        L0hjZXdka21PbjkvekJCaStUM052Wm9QK0dUR0ZnZlhuZXpQZk5MT2hDNTVrcHpm
        akJHY2NsSHZUOVEyUEZqUm1QMVU0LzRkaGJVTmtkS1JYYVNPdXlCeTZXaERQRHVt
        UXlVUk9NQWk1MHhscWNSOWhnZDdaQ1NhbEpBY1ZOWUxZYmN4ektQYi9lOGFUbFgv
        WURNSGcwY2YxM1JkS1duMGVDUVlDWm5rS3NUTnYweEM1VUZiTUVBWDlVaWl6bkw0
        Nks5M0M3dy9MaEZINHRsNEErcXFBNjlyTWVtSkdCVXVzc1haUGc0dmk1NnVSMFdk
        akFGeCtNMmFnZk5tL2tzeFNxWDRhUDJKajFqdklGRDh3N2puaEVSbWpPdDByeHRu
        bXc4NlZQaGUyU2djRmN5d3Rjd1ZPTXBJM0JZOXgrdzgwZ2lkRlcvcEFTQUhiNDlO
        V1J6QjJ3VkRrMFlySUQ4Sm5BY242clFHeU9mNmFIbEtCODVocXZhNUFjQ3NVeXUw
        a2VKckl6ZzJJK3JDMy9DZktCRUhpUzlqcjQzUjZsclRlVk1kaUI5aytxSGJxNEFj
        c3VkSjJyR3VOcTJvVXFRMzRuVnl3WEdLbkRTbmhQOUU1bUtNY3MrZ3piL2dGUUM4
        THQ5UlJvUGRMVWY4YmpsYnplQS9RUHpyZGpYSU02TnJPNXJwSEdGZUdKK1I4VHNT
        VEhxeHFyM0NZR09BQmZBNjI4L3VqTmh5ZFE3MEd1eDZhbitOQURUVWwvbU9HK3VV
        MGJJNWw0T2ZoMjdZbWloUkJteERGbDd4RVVkMTZPL3gvN0JCR09uNDYwN2ZzQ3o2
        aHg2cUNXZWd6d0RXNFUrdlBEZlFUSHhWRTVnUTZldUE5N2tPVDhIUUlkVFRaa3kr
        UUtVU2NkblJoV1g4dytYejVvK0ptdmdwaVMxaDdTeDlqTlRCY1hLMmJXSmFVc2VF
        QTFpeFNvSlcyVHo5ckcwZXRxNUdFZmxFS005WWd0cEMyNWtOalkza25nRlUzMDlj
        a000dHgwM2R5MThPQzNyTUVvNHZrb2ZBeE1wVHhYR2M5N1lNVWtqQm40Ym9Hdmdu
        Q1pCUGR4ZXNEWTdiY0RUM3pYajdlbnZKbHhuQ2ZvaUZXbjN4bVErcWIveTJtSitJ
        QXhlcGlOUFUxSFRDd2ptbWdCVk0ray9BWmtKUVE4U1F1TllRZHA4YllXMTAzNDVy
        c1JoQk04Nlo2TEdRZkY2cVZOWTduYkFhUVl1YXdhQStJRHZoVTNZQ3NUSGViZ3dP
        SmxReFRhZFlNR2ptQS9UcHhRem5YejQxWHFmUzJ3cGhCcXZ4NzhkYUhkcGhGNCtN
        YmF4b3FmTWttWW1IYit6bGVRbTg1VFkwWmdScFNWRzlucTZzSmdQL0xkN1J2ZU95
        dXQ3QlR0RnMvQUY4bFZHYWRzNXhucUoyc0EzekNwOHA5ODFSVVVwNkM4ampMeHN4
        WDVwWHBGTTVpR3VmYmtheWxueWU2NVB6dVpoN2xLQVpFcFhFT3dFWnZhekltdUU0
        MVpzZlh1eTk5ekE5K2x3V24vVEhjU2xxMHJLYkt1NXhQNmVUczZqN3VSdEd3WHBo
        eTdXWSs0R0lqN1dNQVBoN0ljMDJ3MmZlaDRyL09temFqQVJrUjc1VklEVzJYdwpK
        S0VzQ3R5a3JRcDErRHdleXdiVXFQcTVrUm9wWW1IMzNFdVQvOWtLOG5JCi0tLSBB
        UFRNbUFnTkFmV1hvNW5WZ2Q3ditkR3JuRitrNllkNHV0OGlabFNCSVhVCgPwFG7b
        auM9mfVhlxSU1sKFnAnQZdl+wU6rEj+1QjP2BX7diWeuRlR8n0qcqXMyI8vv5ujo
        w81wTj4yLiFtqB0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-21T19:14:48Z"
  mac: ENC[AES256_GCM,data:5kLUCYp6LcoXms7pk9VMsgbzR/JwcTqTWS3QXW+xK3cW5reeH2a3BqhI0NLnhFhKXdQXVtM4uX2js+elkG5ZrISYfShpV1IiEnDiyFV9hDPqj9tbAS+ahtkVF3SSNzK08vDTtlLg8CroDDRUGXxnwtbhx2FrQsZpgtgc1HGpowM=,iv:OC6eVteUmhSqUN27WN+ACwLXLu2xLxxOP9Gx3Xnwns8=,tag:59zg3kCAf4aLUCeOdRHOjA==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
