apiVersion: v1
kind: Secret
metadata:
  name: p2pool-wallet
stringData:
  address: ENC[AES256_GCM,data:Vb4PIQ5eN8PprK2p3PRP+21512hjU+bHB3HANgW48UR8tD1/wLKFSClHy19p/Tg5aOdGtZLGgee2MtevQqgloBKlyh6pnMkz6rmcwtu2gcQdqORwprU9+0V8RNwlJvM=,iv:il+5GF6FYSGAbHApPuVuZT954qMFoqZkcV0JUC3m1Vc=,tag:JDNhrQzNe/KDWiOucGfn7w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJZTXVUbFA4
        bzgrY2IrS2xwTnVwY0laN0dRQU9CYTBmLzV3MHcrOXFvK3VIemRzT0w2VUdqWVJJ
        LzRib09kSU9hNmtIbU5yRGw0dkM3WjZQdFg2Z3Fyb1p0RlpWMlBOUHdPaUZZWnlB
        bmdkOTE3bXhVNE1XcHI4UTI0anJuWkFpd1ViR3Jqc3VYdFFia1IvUWZ6RndMYzdM
        YnZUcDJURDM4OUE3Z3hGYzlmK1Z5MkxFbGIzaVRVOXpaei9Ja2w5U2s5Zk9TTUhl
        ZFRONStVNk5tTERnM01DaFI3Z1J4WjFkRThYaDFCbWRGUnF3bXpxWXByK0JlK0NG
        STNPa0F1UmkzOCsrN3lZMlhnZ3BDLzdoSnVPN2NUQzdSNnZiWEZWcWpTUjhTMHpD
        N2tCTXBwUDhyWUtBTmF4R1ZaK2N6Y0I2UGZac2d6cFF2OWMwSXVZa1F4c2NiR2hh
        VUZqaTRkbnNVR2g4OEMvYlkrQzVTVWNhcmMxYkNKOCtIMVZZWG1nRmp4eHc3WXds
        MlNMeDVLS2J3U3phSkZuOHltVjJTUWkxeW5vN1BkQ2tjOVZjU3owQW1zNXU5c1Rx
        enNsWWRzbHlXVW8ydG5NUVAyeGFEbDQrb3YwdU5STEVOKyt0K2VmQWdvOHJTMUs1
        NzBxdW5sc1BEa2JwUkFzNU54SjNkMjdqM1I5eDRGWFNuaUxZVnQxKzNDUlhwNkxI
        RXpsbmRaSDd2d0syMmZUZ3BxVmtlTFYxcTRmYysrQUFiT29iUmFmQ3Fkek4vV0pP
        ZVlMNzdqeTM3eXpMeUhFUWpCVnZ4bnEwanNBQTJJK1dtVHFlNFhhRG14cnNhb3FC
        cWFzUzNadXA4ckhsNUxRWEY3SStYU3paT3RJZmVZWUtmamFNNm9BeWowUTdqamth
        UnU0TkdHT0pGbXh3T3hkTVp5OC9yS0dhUDIrdENGbldwaDdNQ1pqV3BBWEtpYkE4
        ZjI5K0dCenZrMllUMG9jVFZlemZ3K3EzOHVPelBTOTEvWG9MM0tDYytkc1dNQTdo
        UmJNQlpEYm9TdmFsdXdTQ2dTenluenV1SDJjc1VXRXNnSEdFUkJFRkROL1l4U0lF
        U3o5Q0VPemRLVjNON3FYdlB5YUNnZ3c2d0U3bzF2SVdOaDk3TFo0eGRISlBoMTJ3
        cXdpOUtFelVTR3lXUmxBRldZSllUL2RhUUc4b3RZdVB3MkE5bndFbFdub3FIOWhY
        a2VFdHJMYmZlMk80MU1aRnArYWk0MXV1ZUorZnc3V3BubW5UMzhVWER3ajA5VDJh
        QUxFWFgrMUtrQkQ5dWhSd043TWhleEVKbHMwbldzUnBRQUhSa0lmOWp0TkxmYk9O
        N2hpWHF4NGdELzhZTVhFYWZDQXF3M2l0UCtWcTliQVMyM3RtRXA1ditwUEVoQXVV
        Zms4dVlmNGk3OEJQYTh6dGVYcDNubnVUa0JaNVB1UFZJeWtvUnVUSitDek9xNEpl
        S29sTjBOYVQ3eVdrZ2QweEZ1YW1ORE9vdW4rai9MRDhzc21JRmtOaHNtVXNHODFF
        d3BnZWVvaEo0TGsyMnJxNEJPUEpkdWlwMWJlSGIyc0tzTVVIK2pGb3V1L1gwZ1Ra
        WDBySVEvOEQ4dm01U3Q2TzdDWU5CWmNYdzVzcFM0Vmh2TTRYbVFXdFByeFVseTZ6
        eThCQStiTk5ESGtvWEVRTW9TdmpGOFZEM203YndXRFArSkdWTTIxMWU4NHRXZ25L
        UWtBNE84KzRJdzVzaHJnWVZCNXNmblhzQlk4L0o0eDQ5cStkRi9CNkRmN2l3Qksy
        U1pmR3huQXpzV1Zlb293R0sydmZKM2ZWazNKOENCMXhpUHEvNEh3Z2x0djJlTUYr
        RUg2amRZMkZvY1lndGpmQXBMTmwyTEtXTk4yaHpNaWtYa21IelRtTGVKVUVaNkJu
        T3ZxVTBYUHBubDNlQzJPNkR1RUZqWlZmT3FOSUJOc2NzNVZoeHdxWFN5OHlXZwp0
        ckhnc1o5RU1ScUl2Y1NIWGtLMnpvV0x4VzdCd0xlUWM0TEozM21Ya3dvCi0tLSB1
        ZWhKWnYrSnhrZFJrYXpMOEJIZ2FCU0VkeHN0azhVZ20rZFJVeDFmazRZCsdtGue+
        +83glNUoVTHfyuh1dLBurbwJFZBrZrFoUDdJ/JsX8x9k8hI8KUvAFOWQVEEFh7+5
        UvbkoMnw8lfqKD8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-12-20T11:58:15Z"
  mac: ENC[AES256_GCM,data:ISIfIFwhBxfM6a3W32cBsLYrRM6FgwAGOUWDvmWIGPPMzvF2qXhLroIzFn5hm0ayw924DQ76kiON/XPs8JpV2Tt8AUamDgsGWelihEPdSmX2gmgSDnx3rH+dqGUxzGQZe6otL3/cfcyfC5p4Z83CYZDm33zhTUwnSzVveX/i38A=,iv:DWLPVKDqqJFq6F62qS7cMHoWUAY8uif1ao4dN/v0wPc=,tag:b+4FLkGM6Nl4QGGVSFbQaQ==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
