---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gha-runner-scale-set
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.14.0
    digest: sha256:12cf327bba7c865d369524c06f63b26e1c5b876446a1c4f7c7c462f3d44ffb2a
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
