---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-runner
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: cluster-runner
spec:
  # Only use is 'talosctl image pull' in image-pull.yaml.
  roles: ["os:reader"]
