---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  TIMEZONE: "Europe/Brussels"
  OPNSENSE_IP: 192.168.0.1
  K8S_GATEWAY_IP: 192.168.0.3
  ENVOY_INTERNAL_IP: 192.168.0.4
  P2POOL_IP: 192.168.0.5
  ENVOY_EXTERNAL_IP: 192.168.0.6
  ENVOY_INTERNAL_TLS_IP: 192.168.0.7
  MONEROD_IP: 192.168.0.8
  CLUSTER_NODE_1_IP: 192.168.0.11
  CLUSTER_NODE_2_IP: 192.168.0.12
  CLUSTER_NODE_3_IP: 192.168.0.13
  HOME_ASSISTANT_IP: 192.168.0.16
  TRUENAS_IP: 192.168.0.27
  IPMI_IP: 192.168.0.45
  CENTAURI_CARBON_IP: 192.168.0.95
  AVR_IP: 192.168.0.106
  LAN_CIDR: "192.168.0.0/24"
  POD_CIDR: "10.42.0.0/16"
  COREDNS_IP: "10.43.0.10"
  # NFS exports on TrueNAS (${TRUENAS_IP})
  MEDIA_NFS_PATH: /mnt/BIGHDDZ1/Media
  BACKUP_NFS_PATH: /mnt/TanguilleServer/VolsyncKopia
