apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Cm8ajV0NJfoLSQL4bjc=,iv:KVhpP+u4EC4BsLOMnbfVJBH8Y22Wqvr6KkCvpYPl0jc=,tag:gFWLCvFd3Uuf6PljkifTAA==,type:str]
  SECRET_R2_HOST: ENC[AES256_GCM,data:UV6DLto3bI46ZSYYdraHHYcexU2sTeG3Q6ERAi5uLBUdehs4TVySuVpOR+nEvgh+alfNswtzYewJRCHltMEz5v0=,iv:yBDztVgfp+prxKSsejiQc4RVhffF898nXI7llMsPfio=,tag:k9SXtSnqUAK2UxmQbhR1Nw==,type:str]
  #ENC[AES256_GCM,data:ATO14DaX,iv:O0bedo9/F6wfkZJyuA3v08GikQue4jAIKINRL373aLc=,tag:OEqy1osoxxOZjw6z43QxMQ==,type:comment]
  PROWLARR_API_KEY: ENC[AES256_GCM,data:Tc4QeODIBwo1vXP6piMJbokmLQkmL3mYuAv+5glgE0k=,iv:943lJulBQ5A7BmYlO2lIrxcKVW4+5oIoRElP+HeQ3kY=,tag:fiVL5QNNpcOga3K2JVTLBw==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:+c/5fgBMjv3IPYIBhBMI8/wa89r+LJWvecN5TDjpsKk=,iv:IlRjawRiddHUZKUPHaZ06plz1dlUc0xyubFxeP4Ql5Q=,tag:NrnNlohmTNsav+Cwi4mpeQ==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:fh3IdlFimeoDpnMfUgPkn/K4F0usCou0N9OGlMHMjB0=,iv:nJQ7RylzyIuONmuOJDNSox4iC4Ea15YRk6sA7r/xWoA=,tag:DhuI0IAlQZVB8YIIOf7HVg==,type:str]
  QBITTORRENT_USER: ENC[AES256_GCM,data:qYAbnAyohYkZ,iv:Ojpj1LYl5T3MwXxuaY+NqrcVj7rLQWPOZPmvtFHxQ30=,tag:Kv0uB5nWgw4X3Dgw4f3zUQ==,type:str]
  QBITTORRENT_PWD: ENC[AES256_GCM,data:O5xloyDQYHw=,iv:8aJB68LqEBGBke0TViOaG4oU0jzv5X93so27+hI+HCA=,tag:8JAPUibieAaTlMIFNj6msg==,type:str]
  JELLYSEERR_API_KEY: ENC[AES256_GCM,data:QyRFw5d4RCoyCYa2eP+X69a3km5riKm0wvv/fWdgxDYDPspCxVd4yE9KfwgBVG76UEwLFR5lGcQiW5G+xU/U4+izmVU=,iv:Ttc+LafseP8sUK95ksKTt4b1tTezHPlCwFsw75PB/d0=,tag:jLhd9u0oViBB1o5uw0xq3Q==,type:str]
  #ENC[AES256_GCM,data:f09m,iv:9VjIiiQgJ0QWjJTLP65cTX+apUbs/aGJhTKrVbVJ6gk=,tag:nbBUbyUyrGfF8w5vkaeGvQ==,type:comment]
  LITELLM_API_KEY: ENC[AES256_GCM,data:jBfTb/yTn32mmq1hQ4b+7gckavBWvLLJZCyfGk3/rg0tfI/y3GLpgTxxvLdCG9uPoDwpL9r/wNEUG1h9OpOF6WF7uw==,iv:DiiXCw2NiAmoM5AiUkGdIaFIJoqC0g999iXNUuXR/fY=,tag:NRHtyuYkqaraEUhYzJLqGA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG9WclBtUEpr
        UHJLbHdyTjdjVkJJN25xZlVwWVNwbit3d04raVVOWHpCTWJBWmJVbmF3RXNiRUlv
        SUVBY2s2RnpONUVZNEJ0THpYTEtMd0JXUmFSYkY1VHZqZlBVbkpMSTBwUDk4cnZ0
        cHF4Vmx0R0JrVURKSXlZMUZIeXhvdngwaUl5RGpJMHkyZ0M5R3BXSEpXSjJocTkz
        R2RwbWw5UGJWR0xXcGM1UmZtR3ZZK201aVY1dkVTbmpLdTFEYVMrZ2c0d24rYzg3
        emZ5QTlaRW9TNE94RFdNWDJVcklYM3c2U09IeE1aOVgzTHVUcEROSEw2WkxJRkdq
        WGlzcVdxTjB0OUFkcjA2MlQrVFd2UXhpRnlDRkZwRVBHOG5GTXdQbkN5a0JhQTBC
        TEJpYUVhVWI5Y1l2OGplaHNNckNJNzVEQVA4ZXU0a2wwUHgyWjI0QlhGMUNTMnZB
        UWw5eUprNHR1dzh2VDRla1lnckxDQStvZHJYdVo3eHB6cUptQWFseXk4cnd6WnNv
        d0ZtSWtPRitERFhzWU9jYlBTNmU4d3p3MFpHN0hmeUVTMjdoNG5YQTVaWURJTUZZ
        UnBTZFI5UjMzWEc4dkkxMGZhTWlNbGFVTjBDQUpoSDJWakk5TGk5YkZVL3BKdys1
        R0p3cUpMUnhNLzByUExWVXpMRkc5TWpvVG82NU42blM2RG1WVXYzUHQ0MFZZenFB
        QURCS1JBZ2x6eUR3WnRWTnlqNHQrUlpzYzJTL2hwNng5RlZKMDFJVVBZQlRaZkhQ
        WTFSRWFEMU9VTlRnV0IvU0RVWEpFU2J4THJKUHRJdlN4bWxFVHRWVXlrcmhlem5X
        YmR1TEZvTFpDZXpNM0IyMDFXL2VEaG9QWGxzeGE1K2E5YVpIZkt0dEk2dkNkWUUy
        cUxST0ZNTGdpL09sZ3dGVUYyMTJNYXZ1R1AyL1JUMXVCQVhsYXRtZDBVQUQ0V0dN
        YXo1UTNLcDVBRWhTYlZGb3NKdml1N0ZGcDZPdDFLWEZZeG1PMmJaTUsvQkVjT0RK
        UVNSdHNvek1xQzVzRXBVNnRpU01kSVBucG9PNUNCNnUxZjJTQ2ZyOERLV2xnT2w2
        Z1BIRHpYc2R4VTY3ajdQMWpkTC90eGoyT3U1K0ppMjd6bWNJLy9iM3RSbFBmOENT
        T25DSCt5RUtMbkFXRkFXSmVVM0hnamtaUDdiRjgvbnJwK005cWJFdUFwWmtnTUMv
        NHd5ZnBHdDhUeXdqZGFMZTdCWkdzWjI5cFJ3SGFsNnVJcENvTU1WNk52SDEwK3ZT
        N2tjZUhhUkVEMEprNjZtekNUTFJyZkJKeEw5aG9FQ2tWdWc0eTRQTlVsU1JQWkRo
        c1pTcHlLUHV6KzQ2UkN1UWZaaGRxUi9ML0UraVBCOFdQOTJtVC9XdjArUTJSNHRP
        Mk4zbVRlZXdFSE9yaDlsdWtHbWNsQkp6K01nUlRMQXFncVhaNjljd1FNWVBTQzhS
        WW9OM1Y1QWZKLzhYazJGcWM2YkRYSGlEQlZ1eXl5eHJiOTkzejZhSDVDMTlvTzBr
        RHRqdVRkcjA5U3pxbG0wclArWFYyMFRwTFJVZW9tZG5yTk9iaFg4cUVaZWI4UFRL
        ZkFvRllzbWtUaXBPazBaWHBwTk5iRXpNWTg2M2JMUkk5bFN4Z1JTQkIramVhTENQ
        ek8zdVN2ZjFyOXpJRDFGcjZMSzUrc0I0THNCWUc4dHpnMllxWXkzS3BlVjBiZm9y
        bXBqc2tjelFXaVhDcjVCNG1rVEU5aytiQkRORVhtTDJ3cTVOTTVMTFlMaS83S2dN
        Z1BsT2krUWo5cXAzaHo4WFNGOTBFRmFsbjQxWWx3cVRPMnFvK0lHMlJPU2dJb2RL
        bk1tWnhnSUlqSmRDVkhkblplRkNjRVNtRk8xazFseUJQMUZGTWNxS1RVRi9hYTV6
        V3E0OW5nVktyWkFXZUhGUjNjZ2QwY2ZraVl3emwrWUJpdmFQTndHZmQvSzJKQQpJ
        SUhrTllwREFrOG1NcFROZW9YNlRXc2V5U1dDTXU4QUV0ZjE2WGpoNVFJCi0tLSBv
        eTdqTEd2VnFGMVRYdUQrekhQd3JTa2lUYUFLTkc2b0dnZkdzMnM0WVdFCjZqSASR
        j5enlM0tXsCbB0Bugg7JSqoKLWVFZdgE2IApGq7SZryYPbxyERhm2RsmM+zzafzA
        5L2Q3a/WoV7R//8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-13T23:07:23Z"
  mac: ENC[AES256_GCM,data:oFnaqnoKUTFWPH+suhaGNBXo1yIDYZNGT0blV/65D+Y19VQF2KnWkSAaiZMt4uz/fR/lxURlT1WM4kmJdG1tPXMZnIvx2vPVOstw5DBb4VkoJvU9g5eCfGfbDGp1O4xf8K+yqVODWUEGMxsiwx5vTyejnRSNsx5pE/6hFN3+DHE=,iv:6faasnsKS8m8m4VD/Bn5zT2PWSL5bB0IK3UlfglX8LA=,tag:LePhzEwKnVnpysZkwfdmZg==,type:str]
  version: 3.13.1
