---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.20.1
    digest: sha256:98a9dd1a3ffa8dfc1d0a34d10de2f2ca9152fa1de3869e8ae8b68eafc9a1ddc1
  url: oci://quay.io/jetstack/charts/cert-manager
