# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Au5C1YaOAwcui/xX8pCDmV8ARBvm4TNwnYgR+GEVslfO9Tes5oIxwg==,iv:wdtvV9OWKPD2sRdKiN1BMUtEiLjZS25d1DsVIR5px44=,tag:ET2ztoMcbe+Ss93t04Ka0w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDhEei9tcThM
        Sk42RGpkZmNUU1FHNWt2SCtzc3c5NjcvcVR2SG5nakYxek13cmcyd256UnhOaWcx
        QkZtWWVXVFhxNHNxQU5yc3BUYTJZcHowR0JKaWEwVGowL1VHUzdYb1NXa1R6ZWV4
        ajhYMEZ6c0VJWW9SbXg4dnhoU1JrdmVLMkNienNwUXA5b1lYQ29pcWZsVDNvUlhS
        emRyTFRQL2lFT1FnOTQxZERiZXJLeDZHbmFuQmk1N21oK3dSRDlTemFqamdnUUxF
        NFpRVUFuU0ZWSm1Vb2w1WVpURHMvcnBFYVQ0SllXM0dtMWVicmNROGRhQlhsVHMv
        UXFjN0FxQUQyN3dqV2RnQ1FwejJ2VmRaTXE2aXV1R3ozQ08xQzRlNXVWQ2dwTWo5
        aHEzRDErM3JDTUZQWldrVUdSQUdRL3RxcEZiNTFTZ0tFZDdOMW52MjZkSzhyaTdW
        Q2xDQ3k3K1RveW5MZHpEa3ZvNkplcWN0aXFPb21VclZubEtSOTRYdHNxYzlwQ00z
        NzNHc3U5MWtHbmRDVFlOWU1FNnVjd0d6aWxxdVl0U0xnYjMzcWxlS0hBTzNvUEc2
        LzdHM1ZFb3N4L3J5dlhyNDVEVXJCSW1NZllmWXprR09FRnZIUUdXVzFpMnNwWHRB
        SEJ4TXRTR0xrdytmdFlQeEJGMWdxK0dra21MQStQdkYvSEJka2ZoRURqYTFLamQr
        bHVpS044UlN4b0dQSzUxMGEwRW5RZ0pJV3NNY29KUG5PQjZsSjBlaktUZUNlcE1P
        bUdVTU5qakFqdnhiZXhlMnhXcWdPbkJaa2dBTTluTTZWbEpldDJJckhRWkNjS0tn
        Sk9yTjJwYk5SY0JrWDAvY1MwWjRTQk5WOUs4eVpvcXZDNWFXMDZ5NFpzUkl2RC9m
        dm5acy9ja3NPQ3gvUTQ2NXc2aFJYbWRUSjlJMkhGbXFPZG9ycVJWVTMzRkxISFdH
        SmNoblEvNjhxK2RlZ3FaZS9JbVhkdm1YeS9Ic0JxVnhLdnJGUHh0cDRWL0V5dXMz
        THN6NU0rLzVQSUNKYXBsSlhqTHJoUjZWZ2pHYUJJRGFweFNGdy9IRFlieU9lSkdl
        dzVzZGhSci9BRTN4RWpkNVQ2WEw0eFk3VHUrYUpwVzF6eHBvWUxwek9qVHV5UjIv
        OFYwOE5GcGVlVW9TelhhLzgwdVp3K1BRYVFxZVdRN2lidE83ZVd6QzFCcVlVLzFt
        MlN3Wmk1WDRCbytzeVd3ZThpSC9Jd1JvUmtvTStYblFZMHczdUN0K3U2a0ZjWE5N
        SStaVGlIVmlpUUpXTjVaRk4xY3psczJxWjB5UzRLTndNZGxTcFpRc3dYSEMvaEIy
        WllJNHo3VmUxbkIvOGl2VmRuK1lESzVwU1VWaVdkUFh4bXd3cTBkSG9YLzFXTUZX
        VTZhUE9jZjgvUkxoaVF2ZnF2VjFmb3UyNS9RWnJKdEJMMWVsQU82dEMxZXZFMVZW
        Q1JJb1Y2M2psTFp5UFVnQkJDclV5YjUrcXgzSU1aaGlUek1DWFoxbm1nanBhWGVh
        U1dsRUI3aDFiVnNUYlNtb2J6OXovKzRucys5K3hqaS9NUlhSSkl6b0l3aHBXa01u
        MnRLTlRKY1BNNTlwVklHY1hRRUZWSUpKYWppOUhCV2RYclRHUHBaYVJTM2Zzc0V1
        T212bFFMUSsrL3VQZlRIUWNaRHhOUXZHa050Y0VsL3VDNFJFeUhrYUVDTzlYdHVk
        MXRFeVBmM0lGVkFtNnpGSUVOOVBpbCsyVk1sUk91NXV6SGRyYTBEeUlDcENhdy82
        ZnR2U3dmbHpQaDI3QWxWN0gzcFRRdHRNY0o0c21OZUFacjkvU1dXQ05DMysrb0Zp
        K3V6VzNKT0ovazEvWVRkVS9pTlFsSk5QdlQyQk9HVmN2WnU2YjQzS1dFQnhnVGFZ
        SWZKMFE5Y0E1ZWJnTktXQjNsYnNIZnBtNldQUStHdlhEczRacmhjOXZnUWlFZwow
        aXkyWFRTb0hic3BWMW1WNGFKNEw1bW1neW84bkhJVHRhc3N5d3pMUGJFCi0tLSB2
        UjFtTjFuN3Z4T2JDSjVuMWJKU25jUzc4ODFBSjhGOU5SZ3Q3UTUydjVzCov5qV3L
        lZnnvp19A4L5ghC2JfOMtwhMNj1Jv/ZTfSLlnFjcWcX2qXiekHN4gjBJwfLViFH8
        tNaQM3+2uN/K++o=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-05-03T13:31:13Z"
  mac: ENC[AES256_GCM,data:qIWNblNL3q1zpeNSZ7D7V5F2q0ASwZy0gt9EtVOko1cegaZOisLqDMIa4i9+MF2TsbchzX7Me1uc8YicR4aldayc5itqEtFsPXN4Itg1r4NmOLRuZNGwf6WbFQTX7IPP2lvcEV38Um3b7T5eAWs1iTND01F1RXTzIA0W9ocSD9s=,iv:K+oMJ8UkoUw4+7pYrVXVyD/6hdDl7YU5kKQbnnSTryA=,tag:9yTLrQPZHFOrYjc071LQqA==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
