# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Au5C1YaOAwcui/xX8pCDmV8ARBvm4TNwnYgR+GEVslfO9Tes5oIxwg==,iv:wdtvV9OWKPD2sRdKiN1BMUtEiLjZS25d1DsVIR5px44=,tag:ET2ztoMcbe+Ss93t04Ka0w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybnM5WVBFTDVDL0FicDRO
        SWtwTG9FRTN3dTlzOWhXQlRlMXRNRnV5dHdnCjhWNzNSWHhVUWxjL2VqaFB3dzVW
        V3BZZDVEQ2UrbjhSZnZ4OVM5c1d6YTAKLS0tIExZTUNMUlFaWjVQdzQ1VGU3akp5
        SVJaNTVraGRIcHNRbkplVlBSUWN5UlkKz2ZERXGZiTbfVqrEzBIPWVbyXm2+kIPm
        FhkWKjV2lzIgGkNuJH6Jk9O1nZORzRqtxTuZcCHDhHqGj0/prAg/Mw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHhPMWx1amlE
        R0hPcFllbStHUStLN0JUYk0rTGlXbnp4QWo4NW0vaG82TXB3Yll5aktrc3JocktP
        cDh4MEJGWFNlSEFmb2k3UUNZSVdmY1F4M0tMaVFxckZodVgvMTZsZHVWa0lNY0Nj
        QWlIV1hKU21IbXhIZTFFcld0NE1lMHU2M0ZTeWNXTEFlNG1XR3JnWUxIZFhLSFBE
        WmNCREk5dkR4OEFtRjZldVJySC8wYktJakgvd1JCeVVZcXVncFFGVHZ3andKb3pZ
        OThhMjdWbE56T0pJZ3V4SU9RUnl4SnZqKzRCR1haWWd4eityckRtMGwwUFByWGJp
        Q2FzL2J4OEpYQ09oR2NGemwrQmdna09mMnNtOXkvaUNVZXgyK3MwL3M0cG1lSUto
        bVJuaEZiVzJ3cEpYVG53RUE4MTRhdnVUY0pKOFZKeElPNzlDTlhqK0d6Nm1lbDhL
        M1V3eHFNdS9yK1dwZC9kblBCTkd0VEtxVExUUDFHZlJhSExBSUUzODFGcUdSc3No
        OXlHSGxDU0hPc2R4bDIxZUdkZ3ZTdkh6bi9NQVEwRUhaMDNCdngwY2ZqUDhUZHNl
        cURnREorWGVqV0VCYmhXUVQ3WjZCc2ZLWVRURlIrYVMyT0xtVzNXM2dkTTc1cURx
        OElFOWJFR3BRT3hlM3pyOFdBU21aNDhRMDRTbWhZZTJBalBxSkcyRjJCTWUvSDcz
        MzNtZndIVHV6d2pnNnY1aUpMQmtrMTRhbG5QTzZPbzl6SG84S1BUSUZnNUg2cmF5
        Um04T2pnbERWWDRDaXVRL2F5c09QM1VhM3FNeVFYeGNEby9wTnNaSlpRMi9XT3Bv
        QldaR3Z3SUFtTmNEUDFBSzcydWxBci9DLzlGbTdHMlNWMUZmQVZjRWMxdFNHYk1Z
        UVhjY1RCZ3U3anRUaXlnYzQzUllYRVZWNmNtZEpxRTRoL2RpTEVFWkJ0K0FvYU5a
        QTV0S0h4U1htOGdNT1lUbEQzU1lzMy9lZXhZT2Q5SGwxSjJmVERsYXJBVWh4WUx0
        d2FYWW5NSDNsUmZLcW9VaG1nQU9sNjROYWpFekZXOGRseU0zakczRWxHSmkxb2dZ
        WUhtZS8xNVNkT0ZFOE1VYWc3QUVKaGh6R1pJY3lNaHNPaUkvdFhDWWRaeThtM1Zx
        L1NxY0thUTFnZmpnWXZ5QzhmN2M4RUUzcGs0bnF6VVRtM0FXRkxaZDAreFJLUEFu
        QjFDZUN4dFBWSnk5L0NpRFZKckx6WlVnNE1TZ0Fna0xZNUpiNkhzYkhSUWVtMTdp
        WUNnTk1pbmZnSjBkMU5YLzVHRTFRNUNHMXR3S25sVHJ1QjlFNDF1aVd2aGc1dFBH
        S1lpTXR0Rlhla094VGxtWUhzOTNjeUtWSUwwUzc4VElsQkNzOUVwVmgyMHZ4eEYw
        aHhvOEN5ZWVvbjhkV2VqRWJMT2E0ODdEaG9kZXArQjhNcWxjeHFvb0xhTXdxQjJP
        cFRoVy93SlJkS2Y3MEpab2E4MUs0aDhnWmVlWndrSEZhL3BTcTk2NWNnRzUydVpD
        L2xiNGlaYklFTkY5UkpaRUZqQytQYk9obldDRmpUeXl4UlFST1VJeWc4SFdlbzZG
        QmZSbEtDb0EvTHhaL3RmNUtQeCs4ZlNzYzNPM2hSKzhHMnllRlE3UHRVM09rMk1q
        SWc4eEhvcDNWenh6RndjTWtEQ2R6RmcvY2tNeEJoUnFHRkhCSW10ZVROVFBGUUNQ
        cVNUanRKaktrVkRaalNyZmtuZjBaL0xPZThxVFFwamhwaEVXM1RqRjR0MFhiSS9y
        RE44dE1tZjZPZCtpbkM3Zk1DQXI3WHM3eU1LU3paazlhWnFsVmliNDRhems2S1l0
        VWtVS3VSejVKRU02ZWtXTVRrdG1MOTdidTlkMmFzYXB0dFJMS3R2OFczV3NUNjVM
        NytOaktQLyt4ZzFteW85b2pucWl1c29qMW1wK21UVjNWaTN5bDJNL3JaQnRDdwpi
        WHdzMnp4V1JFY3pEQnI2VFROUTNpam1rRWhRVFhwckxpZjBEUXpEVVZvCi0tLSBt
        dTdMYWxoWHFaSVJadWwrUnR1R05HQlNXU0ZwbVFwbEtQbGt3YlE2WFRBCmhY7DRu
        7TBCx4B/Xb1KfmDnYpiqEEbk9WwJO6HzcCpuFElPHExawSt9g5QPi84iJrdLunTW
        BkEadQt+zGnmaOA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-05-03T13:31:13Z"
  mac: ENC[AES256_GCM,data:qIWNblNL3q1zpeNSZ7D7V5F2q0ASwZy0gt9EtVOko1cegaZOisLqDMIa4i9+MF2TsbchzX7Me1uc8YicR4aldayc5itqEtFsPXN4Itg1r4NmOLRuZNGwf6WbFQTX7IPP2lvcEV38Um3b7T5eAWs1iTND01F1RXTzIA0W9ocSD9s=,iv:K+oMJ8UkoUw4+7pYrVXVyD/6hdDl7YU5kKQbnnSTryA=,tag:9yTLrQPZHFOrYjc071LQqA==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
