apiVersion: v1
kind: Secret
metadata:
    name: volsync-maintenance-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:SzHKmuAp3Xw=,iv:y5SfzkhN55iOAbnWhnC4fhOJLM0zKA5h6gJxcYcTYaI=,tag:UaIWcRdKPdC2tdC/hHuEiw==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:idKfKDL50GpaIrKfWHXXWNDbBsb3aFlm45SLzQ==,iv:RbeDfluiHFk7EgWNo360ypdo6Ge87vjv2qRmoH1PzO0=,tag:1E85EfmNLcwPFwZvYUrZ+w==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcHRCemJiTHdyZWFxODVI
            b2ZpeEFINko4N2FOd3loQkNWS2VzVDNDTEE0CjlVOTlsaFlXS2N6VlVGMHdFS2pF
            a0dJbDRqalJGQm9QelJrQjI3eS9TYjAKLS0tIFd6RkFNejBrekJXQjAreTMzYUl6
            R0JCNTJybk9yQWt3SFo3NXg0cDZ1aFEKewD3K2im66SLFhVhUBbIj69dvrsWvphZ
            c9ZORmLdDON3Argdorql1MfEGIV7y4E9HF62VVeJvzgsv156kxxP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T21:31:14Z"
    mac: ENC[AES256_GCM,data:VfAC20K3ammJG6MVkGwZuDQz6Jz99nN11BNot09TzLZinT4ug98hV0NFFV9gk9QUzPiWG4mJy5FV6UENGKWhSTVfCglav7iAMVwz8bn7OO08hc5ObfdSJJ1QqCK7T3gUHv/1Gaiu6NJVUrHL7JY9Il1tJ/64+m85ex9yMsDJaks=,iv:t9ogLl+bFkJxO+s9QbgMZVTKdOoLaFzIOD8DUScTJzw=,tag:d3Gm4EPbjxvjXQy2Axbu9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
