apiVersion: v1
kind: Secret
metadata:
    name: volsync-maintenance-secret
type: Opaque
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:8T3HVVJSOZgJxAc=,iv:0mZsWx1I/+FPvpuGkzvHuKjXsWvQxkjuti+6ZMjceUA=,tag:EZY02bG9pe2M2RqjrvkiqQ==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:SzHKmuAp3Xw=,iv:y5SfzkhN55iOAbnWhnC4fhOJLM0zKA5h6gJxcYcTYaI=,tag:UaIWcRdKPdC2tdC/hHuEiw==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:idKfKDL50GpaIrKfWHXXWNDbBsb3aFlm45SLzQ==,iv:RbeDfluiHFk7EgWNo360ypdo6Ge87vjv2qRmoH1PzO0=,tag:1E85EfmNLcwPFwZvYUrZ+w==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcHRCemJiTHdyZWFxODVI
            b2ZpeEFINko4N2FOd3loQkNWS2VzVDNDTEE0CjlVOTlsaFlXS2N6VlVGMHdFS2pF
            a0dJbDRqalJGQm9QelJrQjI3eS9TYjAKLS0tIFd6RkFNejBrekJXQjAreTMzYUl6
            R0JCNTJybk9yQWt3SFo3NXg0cDZ1aFEKewD3K2im66SLFhVhUBbIj69dvrsWvphZ
            c9ZORmLdDON3Argdorql1MfEGIV7y4E9HF62VVeJvzgsv156kxxP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:15:06Z"
    mac: ENC[AES256_GCM,data:+4b/LJoQ0YVhm3ehBKxHhU9nBFz9/Qz6YT2htrrwfv0cpf+uwAZR7BdlPTBAtaDu3m9VfcJSvk3R36QG2FOR/btaUC5JYxJis47rWh0/1krAHNzaQOVROmIRtCAw/SPd2JoeVnmZeg6REZCcAIdPdCX6cIT5Cw6MJGc8YXIlpoo=,iv:DXcuZ7a2fM7O6uMTNNkPwFphhWsh2nPaE3xcaj/macc=,tag:Q0rBbjaHS5pvg5IVzNM3gg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
