apiVersion: v1
kind: Secret
metadata:
  name: hermes-secret
  namespace: ai
stringData:
  API_SERVER_KEY: ENC[AES256_GCM,data:Vp5+kkqmFkNiiipFzk3dFm72mBmKMfag/nR/YGPr/3jP6ns1npw9yTfBz+aiyNaJET0n9H1uXZYMQbyDhOj5jg==,iv:LjeU8I7MHAApO0psM+5a/wJx7NGtDF527yPQvU5pNuA=,tag:v03hJ+A0rsDpyeg7Jdf/Lg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZFliM1BJZ1RiT05pVjFp
        aWUzS1MzZ2xMVnVZOGUraU1CcGc3cjEzYjBBCjZHZllzSnUydGtmYVk5aDczNlpW
        enJ2YjhKNXFVd0I2Yll0dDhKcmJ1Uk0KLS0tIGtDV0RWZDZFY1BDNy81RmFqekZk
        RGVCN01OdlVUSmt6cUFzVTFqS1dtemsKrPALA2/SfcbXF2QCoqPv9rcMM2NXAt0r
        DFzg4ML7nDnWvGhkKvxtBZIpL6aKzBrpfbr+/80CXfWli1lnFHhv0A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-28T18:24:13Z"
  mac: ENC[AES256_GCM,data:lNOXM4Mx+FEOlnum20TMbaPg66BGlongRYjSLTVOVbDQ6/sXSI5qNfs+rnCHr5JrnGWq8nRE5qmq7QfFB5imij5Gc51x5Vd6OTiDF+PBol1pkGDC/I2q8mPq//3pTRUxSZxkaIRCZEF7wi32pPWSKX4UCW18rugOFYDNl7xx2K0=,iv:GYD5DP5DYiZTpwDnYGyeNGrI9oR9vQKMwjifUSPdOes=,tag:i0MltulkM2qDPVIVYqF2Gg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
