---
ingress:
  - hostname: ${SECRET_DOMAIN}
    originRequest: &originRequest
      http2Origin: true
      keepAliveTimeout: 3600s
      originServerName: external.${SECRET_DOMAIN}
      tcpKeepAlive: 7200s
    service: &svc https://envoy-external.network.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN}"
    originRequest: *originRequest
    service: *svc
  - service: http_status:404
