apiVersion: v1
kind: Secret
metadata:
  name: kguardian-db
  labels:
    cnpg.io/reload: "true"
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:So6akghYQgyU,iv:f9CZE8JDBUAIM4stgmG9hoPZnLHpi06jYBn51R31rpk=,tag:m6H0PvOPEGoqhl+uYz2BwA==,type:str]
  password: ENC[AES256_GCM,data:kBGVXW4m9vW8Hfn8bQI9Nnuwvn1Id7nCDhRzo4yWOJEgkVqBmIOJDvAVbua+O4CvZFPB/uwFExqyqg6VYRE/sQ==,iv:I5v+nLTadeHTtB4Z53ELaS/aEQgzidiyGLD1gnidnwo=,tag:WJo/VX0buQUJ83a7FIiwBQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbkovbEQxUUlIajVENlVP
        alBGWlNDeDJVcWpmWlJqdy9MNGJTUktLaEZ3CnNQekptUm1iOW8rSGRsbTJNUFAy
        RXRtczIxV2o4QitBTnF6aDVkOGJZbE0KLS0tIGNvOW1uTmZjbTdOTW80TGJlSGh2
        Q091dTd1cE12MW50NVFIVEtweTJnaFkKoauAlbXQurjt8Eds7DokPaoS4gPfbr1g
        9DTQTX6WzNRz4ab8vta90ad1hKLqKAYrVmLva3KNtG1QmmaR4hMReg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T22:08:39Z"
  mac: ENC[AES256_GCM,data:c0BZGYr/1RN8QkHWHJKXw0J1SvXO46n5HHKeU2mmIYChPz7TKKWPH/V4L1jQFQFr4UBaYPU9GLrq83jR85UQkCbnYn4pOY15DJoolKuiVKFVjruGcqj5EYBvcmYNWd7NEttNeKoD3XkxsceMJu3aEPF3YXQN4GgkJ94bpP5KOpM=,iv:t3iY1oshrqTISRb0cTNgFQoXtnU87gqgilmh7LdWYXg=,tag:mKK/tRo9Wgfwyaz5H4COOg==,type:str]
  version: 3.13.3
