apiVersion: v1
kind: Secret
metadata:
  name: kritik-app-db
  labels:
    cnpg.io/reload: "true"
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:lQzjMPlFv2i8NQ==,iv:jTsGlQ9vQ3DRL4PYMzohH7Bp5Ckfnrd2efrH44aG498=,tag:k9u9GGAGqysjGi8T/j48zA==,type:str]
  password: ENC[AES256_GCM,data:vJCTBePpNiPp0DIP/6KrL/40UxyJcllCKW2bDubdUATUQrojKw+Ghfpu0Al3S1yh,iv:5LezfA3gRnujNx3UQSfwCJNGAYlA18yGDZi0yi3wzQg=,tag:KnCqKSK7/IOffnGpt2cUMQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGd4cnoweERO
        eU14NHd4dzhXcFlScmpWNzZ2b3ZyV0diTlovbTJBTStyTDFNU3ZvRWtvL0RDLytt
        M01sejVCVmxHdHhFU3pFb3dUejNwRmtRK2xnVk1JYk5qdTdOYnF5eGdFZ05FMzlr
        aWxDdlJNYjRjbGlyWmNFOXNibmhJRElEbktsM2YrYTlCTWxKbm96VXZpc2JMblJH
        Z1hUMnRKQlNqVUpIYnpLMUdLZzkvMWszMDZ6Z0J4R1FWeFpFWTdtT2RYbytSTTJi
        cm54bDBTV2lyejhOak9DcC9aamk2U3ZKN3RkbGpjb3lkSk9IRXZhWXhLRDk2UXpi
        cmdFdUxBcEp2dGFMWTRNN2c5ZEhXalVoeG1mc0VnSGtyVDV1U0NPd3F4QVJjbXA5
        N1RwWVo5eFM1Q2JFNHdFYUdlanlzeTdFeFQ1U2dVUEs4NnpZc1VlK3QwSUtHbFA1
        Tm8ycDNjM3R2c2NscEoreUdHK05xVTVyRHcxUjVUMC9CNm9Vb1Z4THJRa0xWeUpL
        SUFLS2h3Ung2UVpUVUkwNDVMT2VoNEJWSUhqWG81QmdldXdjNWwwejAzbkc5bmJq
        cjZKZFhIQW9rS1RENkQ1TldvaTNGcGhTaFRGU0NVdFhMKzUvc0w1dVB5YnpjNTFu
        K1QxNXd5QU92SEVybXhvT0ptUC9hMDcvbUYzVkREVEt4eUx6MUhoMU9jZE4rdzhH
        NXkrQVNqMjBxTDRJS2JBNTV3N05VYm9iSVp3OVhNSjBQQnJuaFRibFo1NnhmM2cx
        NkY5bW54bk1nakZCYkhSOTBnSHp0emhLUzNDWWROb1Zwd3BFRzdiTzd5aXd4QmlL
        dmlCUFRiT0RsczE3TFBINGVuNWZMQ1hQcW92VUF4czZUWEkvckg4UUpINmN0Wkk2
        U3BUUUJxY0lOZzBEcXFXZjFhM21zNzBSQWFMeVhMZUlMalFFdzNRNnVtK29JYWMy
        eUwrc3V2R3hRSTI3Mkk1TlRGNUlLV1E3L0RsSFBhenFTSG9uQWRNRmN6aWRzZmxK
        YThqSUZ1UDZrZTdKaTN6R2xpRmhZNWRkYjNvNDhBSDNGL2RDaTBtNk03dTRwYmJk
        aTE2Q2VSWTVMQzBGTUVuT05jNGhKRzZrSlNHblNDWW9IdHBJKzNtR3BRYmhGSHMy
        emZNM2pHS2U2cGYyL3RyUlJmY0t1T0YzVnhORjBCaTByT1lIUlFOYU15Mm5HaGFF
        ZEtrWjJUenlMa1FnaWFzdjB4YnFrKzczQWQvRlB4RDl0ZWNXWjJEK0YwRnRpdmtU
        NENXTVJRVWVuSXk4MjhEM0JtUU1DUkhpZ1NIWGdXQXlMZEtwWldQd3c3bXlHSmh1
        MzlBNEhIdll3NFpQL1d2RlZuTXJ1VVk3WUtKd0pEd3h3RU1sQUpmcFZ0OXdtMlds
        dnEzNFBEOHRiZXk3VldnYys3cXVPWEpKUHRXbUpSOVllWDZPczdFVWZpSFFrS2Yw
        dUNWZ1BNTDd1aU1KY04wemQwNm8wMGJpSDAweUNDK1pOcWQxeGE5UkROem0wK09R
        R0pPVHNTNmxQVzBwRDFOSzRJSWE5Y01JQkdIQjZ2UEpKRkZBdVAxZWhiN1MxV2Uw
        V25RaGF1NXd5Z3gvdjFQY2w5TTVtbEd2ZFExbWN4VE5yeTZsZWdwa2dyV3BWLzFp
        WEpKUW00Q0J4K1lxZWl3cSs3VDNtUnNXYUZLeTdDam51aUZaQUhMOVowaVJuZnZu
        cENkbnZBbURGM2JkaEt0SkNkOTZFd000dFk4TGxtMERRVjlLdVFHYTVGT2FBaXNB
        QnJQam54WXE3RGE3Nm5qUkU1K2RXQXVZVzZNRDdMUEVoVzN3M1BGQXpwSW5tMGdJ
        QWZTK0NFN2p2YXRWYzl1aXQ2RFJjd1U0N1dFbVpxdGk4L2xxc0w1blZVQjJjUmd1
        a3lHd3UweVNEcjJVZytzVGxGMWFnYlBYcnU4SEhxR0g5ZFQ2dCtleGQycVNPZwoz
        M0duRmdTbmlSWUU1d1cybVZVL1Q0VHdFdnJ5YUlyczRJUG14TDRGbldFCi0tLSA4
        WnFNcWd6dWx5aTNiQ1E4WXhwMEVIWFp6VVFnNVpET1hiV2gzQ2xOUm9ZCo3azO+U
        9erd4hlyhjNPY9TpSbglNCONHEL6SNPvKPyNR/vVRdSnK1tlLvKDtNir4otDisHS
        BY2aPWdBTUkt/u4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T21:56:16Z"
  mac: ENC[AES256_GCM,data:2r32pBKrmwTUGtjb2Q9dN4o7s5RmVHS+cAZx3Mhn8XpFnGhryhADGnuXcsXxOdsv0927edPQsA56vwKo4y5Z+eyXnSwSBuljtKusDLtyndxYoPuWOm96eok3T3wfG4a42fQMJIHoqe/XdJKb5MsmrRr87u4+mumxbmAUHWiDQlM=,iv:36aIC4VjquqvpzP2xQjQ8gkd3G3J8/GSGJTsCbo7FyI=,tag:QnsHNkh35nmwqE9pKbEP6w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
