---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keda
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.19.0
    digest: sha256:5354bf809b1ddb671a55a95db6fb9e3da6a9aecf4e11e42476066fe895737989
  url: oci://ghcr.io/home-operations/charts-mirror/keda
