apiVersion: v1
kind: Secret
metadata:
  name: nut-exporter-secret
  namespace: observability
type: Opaque
stringData:
  NUT_USERNAME: ENC[AES256_GCM,data:H3IWOU5reT7+,iv:g/RlprSvsfCppBMMEhDpjZJgXS1jQxDSyMzQqZ4HTCE=,tag:BAHoZpsthCAd3pBiJnVw6Q==,type:str]
  NUT_PASSWORD: ENC[AES256_GCM,data:5RHfor1BP2k=,iv:tniuCdU482I2d2ptpxw8Qp+HNVkJ5UfzMNuHF4caKMA=,tag:A4uHLW3WfdqjtRV+6fYIhw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFg5eWJNUmZs
        SU9zOEljQ05WaW9KWHFjOVo5NmFlMzFhUmIrQ1ZweEFSclMyZ2FhMXRmazJjVExw
        QWVNRGNFYXFpVWdlazZjcTI2VTAranNjYStlbVhHVFNKRzYyaVJERG1iZEN6L2cr
        Ylliam5RWHRVRVR1WWRXRXpIelVpSDFBU0RwREJkL0xzVE9EWTRCb0I5VXdhTVNC
        UGp4QXM1YjIzMVhRVUNFYzBXdXJJQ1JzQ2k2bmdIeGlPUjlOWmRpLzg1bHFPOWM4
        V2VOOWRDYTNOVVF6aEJpSi9FTW1VaFRic2VXZVYyYWJnb0pJMXBXMTI3MjVza1Jo
        Yzc4emVsL1dsb01NTEVRVGJWZTdwMURFQklHZEpRRk5rOVpjNXJBdnRPbkRkY3Vp
        RkdxeFllZDNTZlBVaWNUVkFvcWdiMGQ0UkNyWkFmUGV1d0kwZE84TTNlKzhxS2ZI
        WjJsYXNwaVlsZVdNUXpYSjN2bTlVSFNmcGprMzBad2V1Wk02a2RGVmg1di8vemNi
        bldpRkF6dWgrSmZpV1Ftb0R4RG11aWxydkpTMmN6bGFPaFVMVU5oU1lBS0RLL3Vh
        YnEzUVlaVE91ZDZiWUZtMTdmL3VOWnpaR0creDVwT24rU2hmdXVSRTdlemQ5NUpL
        aWcrYWh4dUt5dHA4dTZyVXRxU0NmWXFNbGF5SDNjRjBSL0ZjR0ZQVUhGR1lxUWpN
        Y0FVV1V0eWtrWlVUMzZ0OE1GdU04YkRySnBXcDd6cThqOE1jRjF5VGJHVEIwZCtz
        dzhFWkx2R290MnYzUFN6QklsYWZBSVN4c2tVekYza1dyblRNYm83eDRLOFd0VVRD
        TW1vMlhGa1hSRGU2NUZuaVdzQ3JwZkJLVVVNUHFSQ1ZLWnhVYmRkN2gzMnh2NDNk
        dGtwL1NHUlY2Wk1vbnJlMURNdGN3L1dMZlQ2VFMzLy9tNElEbkx3SGs3L0hCUm1p
        M3RPOG8vR1RMQ0ZKQkNWeTlKc293Y09RcTErK2psT2ltRFFVOFpMaXpTbFB0aEZa
        cEtnSWxzd25NSHdQM29JbytmVVFCNDNrSEw5UTI3YzJ3OGpFVzhUTjMyUTd3NGxn
        Uk11ZEZQM1JkWWN0dXgxNVl6YXYwbys2TzNab1JFVTBPeTdpODJrU0JWQllmU2Vl
        Z1ROSG1oVHhiNW1zZXhTWEtDakJta3R6NW04c1dwaWR1MDl5UlVPL2VTOFZaRXFW
        YUEyWHlRODF5WlZObkdFeldnd1BCWEdJcitZR1lObERpNHFtZm9YNXZHQ3Y1aUYz
        UEtoMFhPbm13R0lzY0tNdDVVeFhRV25KQ1FXVjdCUEFFODNsei9tRjJIOEtseklI
        SHdacHYzYTVETGEzK0tGR2xINE1VODNlME1obVJwUXJqKzRSWWhDWWoyZENzTTdK
        R3luZkt2RlBBcEdsbWxiQTRJN0FmQ2pCcUxiRVVrNXAvekpIa3N1QnkrQk5RQmcz
        cEpBNkhiZW5JVTJBZDkyTWhSbU9tdVZjaitjK0d2cjVvUWE5YTl5RU5HM3MvWHpD
        YTBJQmlYdzE3QndLZFd2TmtjQjNCVGdjbk9TbDVmcGtISnJVNWphdTFSQnBXNzQv
        MzBCYUN1YkhYQkwrZjZCTzBBT1BDU1lZbFM4MzE2dDZoNzhhaUJvbVYxaDZPU3Z6
        d1ZBdDkwZXljVmRxeWVRMlMrSjdSOFp1T2c5QVJROVlNRHE2ZkdIR09nYUhPbzhz
        U0lHWWN1NFZkU1luQnRWYWkwbC9yMjM5NFlRVmNXTW4wUVlmVUdZN2RTN0JYdXFH
        T3FldFVpRnE1WW4wWWJkYXI2WkkydUxoc1RZd1E1N2o0YXRHRGt5dTY5WEUxQVVQ
        R3lOYmFNQS85Y2Z0NEJWeVJaQVhwWk1tazVpamF3UGxoSi8zMzJORWRvZ3JmQTlT
        d2x6K0c5S3AzSzBDRDVpdDN5cGZ0KzgrSEo0a0syVzlyVFJHK2NPaDczN3pBdwpF
        MlZ6MC9mdVh0dGkxTVVpSWhpYjdKWTlFVHJteldpeXg4RzlOY0FINkVRCi0tLSA3
        b214M1RJYzkzWTRxeFl4RC9kWWZlYlgxUlNlT1dwK1ZwRUovRjZ6dDZBCuGbVxRP
        Da5K5sRReP7KuUsBW3cnU0m5+WoqnQvLXMSN5JAxr+GlaGDQYmNr9Dekt9zRkWUa
        9wY1EeQP0Lfh0u0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-01-01T15:48:45Z"
  mac: ENC[AES256_GCM,data:eE6CguDqBdrjEKF4lnb2K2Ww31JoAG5LUvBsYnrVc930hQ3phRMBytZXeMJAlu68YrDrg0JFamcnWiw2K7ZG+2gB6cm7QhX9w3kzvIFp6IA2VjdtbtM97IhThNPuV/clw7EQi56xmGxMvIRW/8JDpmE3mkJQVfni+L27glxaWco=,iv:+rNwrBF8i8FgtqG6QFysQlWEbCJNVUUtgSJJDpg4SFo=,tag:s3SUdqwZOhHMOd2ijeAsVA==,type:str]
  version: 3.9.2
