---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.7.1
    digest: sha256:67c00488b14afe868028b63b5f745ef543e2445e9d56086af8f7e2d16fe581af
  url: oci://mirror.gcr.io/envoyproxy/gateway-helm
