apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:c4mnuHVRP2E=,iv:L7bwCXUE1fs+YO00EIBwo6AaJCYeO6QdYf/RFz3J8+M=,tag:WKUD/2HGY8AUsAfqDWLI4w==,type:str]
  password: ENC[AES256_GCM,data:wlijQvmJY1I=,iv:Bwibc5nfrmnXE3BxpN5dV0jU8AhWxuaSzyC398bqNnY=,tag:r3kJ3ylz0ktvdByTZW7BxA==,type:str]
  aws-access-key-id: ENC[AES256_GCM,data:y+mNO/DMWWz3VnAaiH1rHKjDE/ciw8zAJ7l5NSDKoP4=,iv:kHidTemDFqqfFB+yYlE8jEYbjKfLrcVyAc/6aUoJPcA=,tag:PDpgB4b2sTnrFUSZKKRJvw==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:HvWA/LGgsPo2oP/R8dzlMf4rHnceOmGqM/nPJKhS3cXEpD4NzTRKs7qzyD7Ng8Eol3JhuElqli7W+5apOd9Pxw==,iv:i2/D/w2QyKJOL70RJj6PRwbTNhOM9cvy9Sx1aGzmu08=,tag:zfpRWNK3VjQYxFR00ErjAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGdnK3pYcUc0
        TEZhV2I0Q1FjcEphY2VHblNSMDFwZjVja1FKTTlVaittMFRlWFFPNVJOUE9rbVli
        V2s1VDZONnNSZVZOSDB0OUduT0lJN1VaK2cwSk1XaVBYTTdLaTFPRTJmK1RQcnZp
        b3Z3azVnTkdTOHZxalNmd0orUk9SOVBtY1J5ZzB6N3NKbUZTRVZtYUdISU5BZ2tF
        c1BLOVU2QTkrdnR1V3h2MWdNZWhrVUJZUU5CeDhCNS9wZjh2amFmRE5UZWJmWlFF
        VkxPaGpBUWs1blJVQmZDdTVIeEpHRzYzdGJ1T1A5akNPZVlSaTRwZXQrUGVUeWVY
        b2Nha0NSdE1SeGNmeWpOOFJpR21qTnpDd0JBUDRmako4ZVdVaUZOaVVLZWt5Z0hM
        SlQyV25ueUduUEluMGloR3VpSDFpVkFnNjNJUjFNZ0F5M3I5bWZqMHpwS09rL1l0
        Q3UwUUxRZzVxM3pTOExWenJiU2o3LzhLLzVKamZ3M1BpQ0o0TWRidVYxaGJJOWNq
        bU1idElFMmtxdEhUSjlYV1NzM21yNThaenQvWlQvbU9KWlRBZi9aZXVmNFdvdHQ3
        RWZNY1E2NUR5dHFKbmszbUFPRGUzamNsTFZqSFA4MURLM1VxckM4K3NheDhjT0RX
        RmZhZ0k1REZ3ZmJRS1BFRW1lMUhaRytoY0l5TXB2Qm9VbzNMWkhWaGh6RWtkbmQw
        eTkybmEvNkx5V1RGVmdqcW5uTmNCZkxWR0F1UGZDdmVoMmxFakRoVG83Wk5aYlo1
        WDI3ZTczT0RocUVYZ2tZVVgyKzl2bTJDVGN1MGttYWNXUjBtK3RZVEJKeG5LOGJ6
        OG43bXI0dk1sZy9ETWpHWmZ3bzQvdWUzMHhDK0x5T1BrTW92Y21xaDZySnlLRnFa
        N0djc1ZUaGU0Q2VjdFFURkp3WUNjdDJna1ArKy92dCtrUEtKd0VKOS94Ty82Znlt
        SXcwZWI3S0p4RGFYRWFvdE5vN3pjekF2SjkveVhZSHV5U3ZRQ3hrU2JPekFKYXc5
        eXdtejFUOHNuK0xZYm5wdmZhRHpKYnhjZXVuN2FaMTFUY1N3N3BzcFZmWk0xNXFS
        dzdWNm9PZ0RsVWlKTjVzRkc1K2pxYU1Zam4zOThCYzRKMENqZ0JvZXI2ZWNLdGxq
        V2ZZQWpvWHhFcXBlRjFxWm1LQi9VS0tmazNWdCs5ckhtTzk4Qi9QMmg3OUFVNGJ4
        Zy9RSTRQV1hvdmZTYnF5M3NYNWowNnBoU0QxQ2NFbnF1dkozejYyZktQQVBBdWd6
        TGtadkZKUWx1SVpkK0NHb3QyT2c5VmVqY2JkMlk0SGo4dktYU0NQMks1YlZyNE5R
        Q0tEWEE5R3VJN0w1cUh1dSthNGtvUnNZQkN5R1pEQzQ3NXJqYTZoU2N2WFhyZGFH
        Zmp0Z3VoRTRaMjJFditxVk1TdERUOTNlaldyNHJPNE9hc2V5NERMYVRWS284N2d0
        VE9jRDM2ZTJDTUVpckRhdmgwTXNCbGJHaWxWMjB5cENTM1hZQis1VVRieDg3bS9s
        TFVUcjQxMUpqciswM2JuRGduclhzT1FCVDQvSm9vRFhFdlhVNHNMdmEvVGFvUUZO
        N05NRC8wTWp2RXBjNnp0S3Y0NXllcjVTakpZbEpJcFZ0NVpqY0hyYTduQTF6cDJF
        K1NMY0RINnB1alV6bytVQVZoZDBGQWpQbURUeWgwWTMwZm40MnBXampSU2xBR09k
        WENXMSthTkZPNHVZN0tTd1lDSitCUlZlK21JUjNvSkRxbk5nVXpOV0dNL3dyZVU4
        a2hudERwN0lyM1VJUnhpOTUvVFF6VEFoVTNITk1ZbUNqZWloSVcwR2tKaEZGeGcy
        KzdLb2JpRnNMb3BMSTZIb29iSmJ6bDRHYmozMlQrMHRINGxBQ2JtYW96SnZwOXhZ
        bXBlWm1QZW1McStzRmtIUVVqKytoZm9TVzlHdWVMZTJmRzNZK1hBajFtd09JZwpD
        N3VVR1A2WGJkQktmTllzQno3bDV5bFN5RkdRSmpEWTJKSHZLZnZCM1JnCi0tLSBm
        NHFHcXQ0R0VkV1daUEhCNjNiNUFhcVZqWEpTY2RHWmFLNGtPU1ZyNWdJCulS/XWL
        MOOG63VF+0T6kH4ylFT4aZkYrL0TDxQ/Ly1I6lBjJWNL+a6f1aEjgU8p3ASktiqf
        5X2uLm11HXhXFZU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-06-08T17:36:02Z"
  mac: ENC[AES256_GCM,data:KgA66WY4ZScpZ0mQU2FD+NNMutkJtSU3/kEdzdbVe0OzWm0r+hlIuaGekCeJWlIRioAkWtwnpKPPe9O4V9w+MlEokl4dH4TcHP1zXerQmiCn8kr7iwjXgfvsBrtaBmNPxBXughJORVT1xuByU54m2gmR2xYIxlg5lmvukLWrgtY=,iv:SADjWrdIYsaJRigSyVuEGTfJXwp5cYEw63gfhNeQI8I=,tag:Io7AomictP7uI+v/4xqx4Q==,type:str]
  version: 3.10.2
