apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:c4mnuHVRP2E=,iv:L7bwCXUE1fs+YO00EIBwo6AaJCYeO6QdYf/RFz3J8+M=,tag:WKUD/2HGY8AUsAfqDWLI4w==,type:str]
  password: ENC[AES256_GCM,data:wlijQvmJY1I=,iv:Bwibc5nfrmnXE3BxpN5dV0jU8AhWxuaSzyC398bqNnY=,tag:r3kJ3ylz0ktvdByTZW7BxA==,type:str]
  aws-access-key-id: ENC[AES256_GCM,data:y+mNO/DMWWz3VnAaiH1rHKjDE/ciw8zAJ7l5NSDKoP4=,iv:kHidTemDFqqfFB+yYlE8jEYbjKfLrcVyAc/6aUoJPcA=,tag:PDpgB4b2sTnrFUSZKKRJvw==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:HvWA/LGgsPo2oP/R8dzlMf4rHnceOmGqM/nPJKhS3cXEpD4NzTRKs7qzyD7Ng8Eol3JhuElqli7W+5apOd9Pxw==,iv:i2/D/w2QyKJOL70RJj6PRwbTNhOM9cvy9Sx1aGzmu08=,tag:zfpRWNK3VjQYxFR00ErjAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdDQ1QlJSb28rWEU1TkF3
        QUQvMXZRRjJtQTdLVE1DaVE2T0YycGZ4aVNzCkQwb0NLWlNROTh6KzJocGVxYU5Q
        ZlkvcWc5V0thaWExK3duZnE5Nkh4TGMKLS0tIFQ5S1g0N0RsdjlyTnI3ZnZDcnRV
        ZTI0K1U0OWVYOGl5eFpFd0IvUHdnN3cKakMQWKN/M72a2lvJdvgseH5HKtweP/41
        yqHjDvVYomFt7E0qTWTmj1Gclk98KSjrOy2vd5FVcQwYthT25J47IA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFdFUjk5dVh5
        aUdBSXhLYSt2MlJUT3NDNExqN2ZPZElYTDdzUGl2UVB2SDQ4WHI4MXcyNW5pS0hs
        M0lYY3ViWmsvWW50NEFGbkNtanRiOEpIM045Z0R0UEd5cnV1enJROG5LUHV4UDJq
        UFpyUTRlemJXZ2JGbzJOT2hOZlpqWWMzT1U3UWdNRkF6RDF5R215SFdRckxPOGR3
        WWxYSktnTkRzTURDdHU2Q3lWZStQMklucmZvL0xnanU1VmtaSjU3cVE4NzFPK0d1
        MmhudU1FTE1KTWxpOHBKWFlRMHZ0U05vdnlpZitsWEJMSWtOeXVTZFFSVS8yMFZx
        R0VvRmJzUldsN0xDaElmaUpjRHNGSStKdUhBWGV3NENzMERGdXJCR2lwRk0xRG1v
        VHFOWmtJa1ZPUEZod1NSSFpJcFlCWWZSN3RlYWZ1TFBPMldwNHJ2eURwVDZubFJt
        ditFVFdsMTlpd055dWoySUlzdVlGL3NYQUxPYy9RdmkyUmlTajFiazZrNjJBTnhJ
        bUFmdUVaRU5VVTlDblpQMDViSHorZXpacnNFL2xVeHZQTnpJL2dGU3ptbFhRcndV
        Mk1uSGhDN3hLZjRDa1c1RUk2R3NWcnhBWW15RmFBUkY1U3BRb3NrdEtPaFAwaW8z
        MSt1REcvVXhJWVhGbWdjdEpWNE40QlJDVlBPSG9ZcjBZb0NsMDdta1BsOU1lM2FW
        SFd0QnVtb1ZkSnNJeHlSWFM5ZWUweTM4QStienRpUHR3Q3VOOXlPdnA4cTJoVE9m
        eWt4Ny9tdUM0SnhudGthQXJDV0ZHOFMyUTVvUGkxU1dCN1hYek85N1VUZmNDWXlF
        N2ZoSXNVTS9aZkp3emlmVHZtc09qSlF4TWJpVW16YzJQY0F6VnhYUHl5alNNUG5l
        eWhyZUlzTFUzODM2cWtWa3dsV2RDei9DbXBieUpkVythMzI5Wk9pSmtCSGdSNDRK
        Y3NHcjd1cGQ4TEY3WmZEeHhmUmtMQ2kzVFNGNUhySkFPWlIzSWpDZGx0UTZ5czdK
        Wmt1SFJIMkFza0ZmcEUyOWl2K2hUOVdBekpNSzU3L0dGL3I1WHZ4dEJvOVFtL1Z6
        akRNcVZ6eFYzSCtpVUtrL0hnRlJ1bG8rcDVuUSt0YTd6MlMwMUUvV1EzWXpYNTBw
        bk16VlltQ1FYalZWYm5yVnAxcGlTcEhVWFdLUVpQRWo0MEJianlCb2huZ3NCVy9V
        eHlOcjNHZ2s0VFhQSUJlbk9ZQi9EK2d4VGZ6Z2NtMGQrYmQxb3lLbzVGcnQ5cDRl
        REN0Mk1EcTVLVHNXZVhyVGl1RkJPbU5IUkk5dFhLeFBZMXp5M0hvVzI5c1Fjb29Z
        THBWcG8vc1hqZ0R5ZlZKVjZaWERUazJuQUM1QUVhWko5TG05NE1wNkFKYlNNZHF6
        azhSN1VQR2k2N1dURXZTMW80UWxaL2xjZ3lIQnVKNUx5V3RmY1hhWmJxU0V6V3Uy
        Y1A0YWZ5L0o2c2ZjRHE4V0VZSGhSNWRabkR5Zk8weVlsK1FXQmZIdTdLd0ZqVjlV
        ZFRYSGRxMFU1R0ZHWnVvU0IyU3Y3aGdPMzFnZHVNY2JaQjJxK2JSOU0rTmJDUVF5
        dkF0R25jNTNvbXB1bWNDbEdNNWZJYVRTM2FYUWh0VVBXSWVSb0thdHRZcklxZGNp
        dmpEU2QxNGY5TlhJYUZVNXlBandLVXRqUENhM1N6c3NZcjRBcTZBUjN1Ym8rMklk
        b1QyZnVUNmFTK2NaVktYTks0MzhCdTBRNkY4Zk54Tk10TDBXWHREL1MrZ0o3Wkxs
        ZE9Bdll5cGRSM2QwMUxjZk1waFMvY2x2Myt0Q05uYkJjcXg0ZzRJdUt1cXhURzFq
        ZFhLc0ZsTUR6aUlIN3lqVTV4UjR1eHVxL3Jydm0vUjZ6T2RxZ1J6NG1oQ0RtaE5u
        U1JqYVV0anNBVjNPUitxK21HRndnUk95cGdIYlBqY29aelk4NXV5Rm5mc3dEZwpN
        QTJjYUZxeXJ4amNPTi9XNERlRjdoWGlweUI2UVQxMnJvV1pLekdSRFA4Ci0tLSBh
        QjFseCtEWGZvQyt4RGlzc2cySlV0bDZ3ZlNPUmZsT25nUHltbktyaWxBCuVvKeAb
        JFvp/gLGvtaXgkS7ZIa8EDf1UHEgwO7uyI0kWDy3PvEMfRfCsW4TPA9ZAPl8QV98
        TQS3eWx9sxXb2MA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-06-08T17:36:02Z"
  mac: ENC[AES256_GCM,data:KgA66WY4ZScpZ0mQU2FD+NNMutkJtSU3/kEdzdbVe0OzWm0r+hlIuaGekCeJWlIRioAkWtwnpKPPe9O4V9w+MlEokl4dH4TcHP1zXerQmiCn8kr7iwjXgfvsBrtaBmNPxBXughJORVT1xuByU54m2gmR2xYIxlg5lmvukLWrgtY=,iv:SADjWrdIYsaJRigSyVuEGTfJXwp5cYEw63gfhNeQI8I=,tag:Io7AomictP7uI+v/4xqx4Q==,type:str]
  version: 3.10.2
