apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:SzHKmuAp3Xw=,iv:y5SfzkhN55iOAbnWhnC4fhOJLM0zKA5h6gJxcYcTYaI=,tag:UaIWcRdKPdC2tdC/hHuEiw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:gmF4vmUWr5EsXhod9ZueV8ayWfC2OHwZDNmqIQ==,iv:kq0keOK5T1ZmyP0mTLUtO2uNgbmnJ/0my0m12Jvy0tA=,tag:Zg/2zcEeydeuEuyrIIqc1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OHAzVTllVDRBbUROWjdG
        VkhKSGJPcW5VOVFUbDV3QUE2cnJ1VytVWFV3CnB6WDh1WGF6VWRRNVdiMXFvekFE
        V2hNRkp3UzEwTjd2OTQ0blVHNmpxc2cKLS0tIGx1a3pvUkU4TVlKMWNmcjd0Ukti
        alFHbXY0Z0h0MnBYV1BqZ2lkUUsxRncKXPxW7e6iOHKc76jElfzzabEot7pDAMNY
        oqgLs5K0vze8fH2qmdKvubi/MRYrQc0EYop30h0K1C6HUVmDyE2/3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGcxY2oyVUJx
        TERxd3FvUVdaUDJmZ1l1dmlFcWZJUHZTbEtSWHM4cjVNWWVsYzk0U2xqUHhwRlpV
        Qk9HY0NKejV4dmtybHpVc1owNFp1eEVPVmJpSUZPNWhnM0dEdFJMQUgzbHVmcHpm
        V21TRWhkU0ZlbEVESVl4YmhqZTVKQkFpUXJ6ZU82dmswbm5sVzRGR3N5b3IwWFdy
        Tzdvam9zYWgvLzRxd2xHTXlIcVZKTHhWMlNDNGhJYm91QThKOENScThmR0VMRGdV
        bnNkaGF0TjFsMEtqOXRVZytOZzBRakZVemVIODQyTkZVRy9uZXRZMnNkV0orTGJp
        RTdEMWpzV0tnYjRHSjZhbXN0bnZtTTVzMURXWE1GU01CRjZJYmRCSGFvRy9BMWNw
        N3piSGpBbVo4NnJIMmw4bGwxam9INHd1M2d1bndpRU40cmwwYXU4aGhEbkFsWG04
        UXRCT2ZRWUZWMFR0ZWcxNTJSOTMyOGhud24yUVNqQnF0RWgxZ0lCSGh3Y3VYbDkz
        ZnVMK3ZNWXJvdlA0T2VqelFvZXErV2FzTzBVTmdPRjh4clZOT0N2VktqY1lxZTcx
        ZFZuUUM1STEvUTdmamRXUTdYMmZZK3J4a2FqYkZHczdrNk5PY2dnNGdHWjNpWHZR
        dnduaXcxd1dGY0ZNY2V3OVFacS9YMzJPTDUzOEcrU20xMDV1ZEZwOUUreExBR3dY
        c204QjJqZ2d6ZU8ycmZRWUU2UUZRdDNPWHFZZzNGMFVxOUJaZFdzRWpzK01WVmIx
        TXltQ1QxMnMzS2ZhaWVLTVVKakZXQTREUjZoUndCejllU1JIdlNDdE5RV1hidURG
        TGt0cVNMSEd0WEtMcjNGdDRweW5TNkdVTXl0bmFqVkwyQkdka0I1am51RWlVbkpJ
        ZDU5MUJ1MzR1bmJxUWd4L3FnamhZbEZDaXVyZG5FYnRmN2Z1R0R0Vk13aERlUktO
        U1FjdTJHUHE1emVaOXRYVHJvN0JVOXR3c2c0d3BDOFRwQnJFVkVZVUtwQVhIQklP
        NmFHODBjZVNvdzFlU0o5TFErVU9xNW5OT1ZidEVCVG5hYWY1a2FId3JNOVJWbVRz
        ZWdwREdpQ3pFSG5kODNDWkVFYnJxRTVlSTNISVh4NVRwd0U0T0tyNE9IeDBSK1My
        K2FndU40akVjT21jdXV5empxcEJLWVZXbkNPNXZQMXo4VHFWc0RHYWxsUElzbW40
        MDZpNUdUb3pQU3F5TUd5ZVpTdDdkbVZlNkRCNGdLaFFLT25rYzNRcG1lMkZKWWd2
        ZHY2RU16eER1OSsxdjNUZ1B6eVgrME5udjc4WTByZmVCbnBOU1FybU41VFMrYmZu
        VGp1d0ZHdkhBdkdpaHdjWlIrTEV2TnlXSk1VeGtKMHY2MkdpZENQbHMzT3BCRlQr
        WEFlUWsyUFRVL3dvRlRSSGd3clFTazEwSzhxbGNyc1hMSTdtSlYzRXhuSzU5SjRU
        aUFqd0dDakZSNHVEVXowWGRwNmMreU54NW1pYkRpSFgyVHpqQVhuQVNIb0FzeWFq
        LzVmMjNkOWxZYWxiSTlYR0pxK05mL3dDQjNiSE81SXg2ZDhlVjhFZVVhT1VDSEMz
        b1FnOGsyOUxJZ3krVE40cnFjc1l4b1NhUkYxWlRuenlNU3BRZFRkeXczakVnM0tR
        Rk9uV25TbUVqODZoVDJHRlltZHc2OXlUKzR6c0ZuYzJMYkt5a0pBMmhPeXJScGtw
        d2ZZWHprLzFibWtUeG5xejd0eFRKeXU5bXJVVFZ2L25EYThwNmpvYkducTl0bDhP
        Z2hiMmJsUGdYdjZZV1ZVOTFlV2wweVRMa0JBVjZvdk1TUmQ3VXo4UUZkQk00VVlj
        eG1obFVhZDJRZlRKUTVONEMydjhJTlFNMHI1TVBKeEdGOEtwVStFMWhrUE1xd3JK
        YlJTMTdGMUlDR28wY1BXZzNUK3RtT016YklWZVl3aW9ETm5hMDdubUVIaElJQQpI
        aDNtVE9MOElCdnJkMmYyM20yOTFndXk0Y3lvK1dYeXd5eXI4SDZqOExrCi0tLSBV
        b3JKV1ZMQ3lRa1FSOERQaExqV1o5Q2NTN0JlcVRGWEgwZlRVTWpuNU04Cla8QQ52
        oUmK5hoLNbVpjTgrY95ep9Z2wqEzIJ0KuX4htM0Brch41jsSUJmk+KBhAcEoU7rF
        Rz00/Udo4x1zMuY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-03-17T21:31:02Z"
  mac: ENC[AES256_GCM,data:S3AASb0n/quxnKksoOoE8vmKqfp1/0+rR2PIGUsob7XTnMMcCLzSgjXU99u09TQs57YO6ND5AIAiGBbcMH4jevqWswJgEhmmZWWd533ltT/RF8rnWKgxYkAdKdODw6XIM3Htmq3vCY9LW48w4Kzoi8RykA4uasaGK5zHkLy890o=,iv:yEepmjtkNkQD+0pVUeANpBZ4g8lAExb0/Zp6gqdT12Q=,tag:VyDYEgNiIdG8z6MV6wPtlg==,type:str]
  version: 3.12.1
