apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: Opaque
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:AqUHnrujaX0Qldo=,iv:A43wSbvkkwGWHTLE19u//SFO6F3GBTWtYJTLSyIgleo=,tag:Yx+gGZ1judHOXOB9QEK93g==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:SzHKmuAp3Xw=,iv:y5SfzkhN55iOAbnWhnC4fhOJLM0zKA5h6gJxcYcTYaI=,tag:UaIWcRdKPdC2tdC/hHuEiw==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:gmF4vmUWr5EsXhod9ZueV8ayWfC2OHwZDNmqIQ==,iv:kq0keOK5T1ZmyP0mTLUtO2uNgbmnJ/0my0m12Jvy0tA=,tag:Zg/2zcEeydeuEuyrIIqc1w==,type:str]
sops:
    age:
        - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcHRCemJiTHdyZWFxODVI
            b2ZpeEFINko4N2FOd3loQkNWS2VzVDNDTEE0CjlVOTlsaFlXS2N6VlVGMHdFS2pF
            a0dJbDRqalJGQm9QelJrQjI3eS9TYjAKLS0tIFd6RkFNejBrekJXQjAreTMzYUl6
            R0JCNTJybk9yQWt3SFo3NXg0cDZ1aFEKewD3K2im66SLFhVhUBbIj69dvrsWvphZ
            c9ZORmLdDON3Argdorql1MfEGIV7y4E9HF62VVeJvzgsv156kxxP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:18:22Z"
    mac: ENC[AES256_GCM,data:uB+Idfe6vI8MoVN3J0m9kvTJCs/vP0o+OiAYP32WnquD68KXGI8L0laUn/2paEqiOcjcJvPgLNughv0mewEHfSpLy7EKCvOrvbKBRYnCM46YT8CnNbRTrni6J8qDX0Dw++eYOkfUSgJLKpLQ5R+IbBBYgUictAhZPRoS4e9MlcU=,iv:8kijIABHsCwVpafP60NLRgpnYZM4KXKvC7/ASwZQv1g=,tag:FCdZMbKU+IcWcs5OaaXlgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
