apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:Tbadf1UvdNjzWM4KqOGGvPiCAdbkW15D7qoKLsARUyY=,iv:+Il0/BlxF4rAijoSRmArpm169VPiF6LIrRLe6pBh37I=,tag:9qkZ8mJBgG5S/nnG0IrSYw==,type:str]
    HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:sidbnf2e4kIvFLMzeVOrGBI1edW2b4fT3GdqbAUgnt0=,iv:w9XXW9Fe6P+bGjbP3kKz+k530SDOOFt4itiSw2mt1t8=,tag:qZsh0j0x94Ks4ZUmwA1eag==,type:str]
    HOMEPAGE_VAR_JELLYSTAT_API_KEY: ENC[AES256_GCM,data:nI9YfHIFnHQg6iD8dNusPVtr2OReYvRhCeCdsnLr3WzKPu+F,iv:o6VzwSTOkeIPUAePs2KrpxAFFtk+KReggipRMoclotQ=,tag:CLi+T1xoIOVXEw8lviEw4Q==,type:str]
    HOMEPAGE_VAR_NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:cjqlrvi9EL7q,iv:3OpKy2taQNPIggBdC3o3QDqmF/GfsfviRA1MzmE4dOI=,tag:eNlCkp8Ofzzotn4VzBHEqg==,type:str]
    HOMEPAGE_VAR_NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:04Lg8C5TWSpzagXLpWuP,iv:aC+fA+JYvpQGor/VLwCLe3LD4g3nQWGNQhO4AktQm9g=,tag:QASgfUd1zkTrjbuJkorKhw==,type:str]
    HOMEPAGE_VAR_CHANGEDETECTION_API_KEY: ENC[AES256_GCM,data:++BxmqN4M1cgA2mdhrrJUoSZXFxVH6ZgtVpFymYXdqo=,iv:ePjJsG8YjgYpDeiiEBIzZUx1R5t0YYaH9XYvPi/QgyM=,tag:EWu1uYfiQ/dkY0NYx24sNw==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:FBCxiEY=,iv:ItnTY6sNCTUH9t3U9ATabaOy+7IOe27gXWKTfJ0M1K0=,tag:HHyK+DNQm0n/88qf/+9yZw==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:AI2QYdcdo8k=,iv:5TCwHTUVsg+mMm1iAcFgGU/F9vq8oQoC/LB6YvdPEjg=,tag:GlxMUTQjjmSr0qmrOcBg8g==,type:str]
    HOMEPAGE_VAR_CROWDSEC_USERNAME: ENC[AES256_GCM,data:jKYsrbxQZnZt,iv:D0geO0w3KUT6epjiiW3JPubVrnaiXT+7hEXLJHL6YAQ=,tag:L4leaG0MDzsYQpVIPwRAFA==,type:str]
    HOMEPAGE_VAR_CROWDSEC_PASSWORD: ENC[AES256_GCM,data:3X2LJunaZ9c=,iv:cvesdycPG6GOMJiEjz8VyRjmRzgiaWZqaHu3r0xT+Ig=,tag:kiI6o4d3yPfZJays/I+J0Q==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:t5TR8JTC/GZi1ioWSGJULkTyAE8ZNIu3Ziuc9hKytR3jyL74eQ+ObBO14o+ysDJ6R51bb8fK/n+cIWaFLBR5c2LUXGNZ/HDdFHa3MSDruRUWLGq3IacKPamH6ktvwAT9HcsE8I48y5bQ3oLJYyS8m2xO8L8jr3ZEHc8A/fzAZ/mBbU42JOYB6ZWe3zT8nluoxRJOZsz75SodZUoN0A1+8FmLsXmQGOkyFA/gwmlom0sF+hEkwIIX,iv:HxrWwqUB6aaJAFL5GxZCzK8y4EBWQIYtWUgc1QayTas=,tag:234BQGyNwShpxBSOnjqu9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN3lBeSs4N2ZBcVF5Syt3
            c2pvbFFzQTFxeWFFVWVLVXRLZUp1bFFnQzBNCjQ0WWRiQy9SOTVXSTdKWSt3L01P
            TnFrU0graWxGcVZQbEtBdENpd3gvWWsKLS0tIERsR0cvS3p3SUcwdS8yUVlXUU1l
            bjY5NkxRbjV0amo4MFhtNklrWTI1QmcKFO3zkXuoiYoi32FibI5TbPhl5TwcI7fh
            +6vwxwb2yOiKGA5K4gZ44vDMMiIJSXIqU6mGig7mYXA6eFh5XgDsvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T16:12:46Z"
    mac: ENC[AES256_GCM,data:JYhF0I4j2OVcHZ6EPQr6Jp4MCJ623HHNcyJfGeduUgIS8guOYVvGRUQ4HICL7ugi3eqtD5HhT/ZabRX/HfySG/kRrZIO8A6DUaQrBOGVcrYmlntdByaRaC4aTh84ta5ByU7vXOoJYylLlwJSN3Bjvt11PUxfYjuwn/LOIQMmV30=,iv:7F2hLZBnRK43k510IlcDatWZHtnIISAJPkcjvxlPO1A=,tag:JJksTLBLqtYr1i8TvaKIpQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
