apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:dlUSbeq/i264OsKoeqzQdjjiQEOFHlq0MbqxSYP+,iv:V7V+4W13t5Fc3SJ9tf5Eh1mJ43rSt70sCNFy6gTBr4k=,tag:kw87HPElJ/IGnQMgKrMInw==,type:str]
  HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:8z42LMgQfzHvQ8vzi17b+YnfwS4p7RFGoK+GM8+Y,iv:bWNVSC6AUOtRtIIy4V6gKCsYS7y3dXSDsVH/vD1QBUo=,tag:M1Qow9fD0QlHR2dE5/BCJw==,type:str]
  HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:7tR0UL4dcB/IgDzDIMmy4cVF4X8W+SJnDnn3JYBi,iv:aV2EtoMhx+uJpmyhK+/AYxflw8dkdhDC4jrIIWXnRAM=,tag:qrM3I9+ER8fXUpWr6JZemQ==,type:str]
  HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:VoSVSfxi4PZ0BX5cthHQI5u7cf95LaLJJJp3Wbxb,iv:6/OgowL2ztM3n5wmc1ZeG8OUDfO71oTsslkEWqec66o=,tag:COU4lxqmXB/Ixvca37gUUQ==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:FmVMgXrHnaO24cqtQ+heqDez1WG2WgdI3RY/HHCu,iv:S3T7ugnvR05hY2X85sxFnKIMEIg/vxZGX0C+TD5Q3Dg=,tag:oUghX2m4wO753qtR+RnRfA==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:syzbDz4eC5hJitsybk2sCW0Dv59RB2gCprSHCBZi,iv:wvPUuHWG4RElTw7XXK+Dv9tXPrOzci5gXk3LpOTyGKA=,tag:0E3M4nrbBEKUsXIrqfrETg==,type:str]
  HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:6qzYzKUd+5r67xon6M809yozOOG5RUIRlc109tk4,iv:uDwj7H2N7vDUYYcK0bvXQzor0cIemlbfQDvxg/siAIA=,tag:UOLb7s1jCEmvhVnQKCTqIw==,type:str]
  HOMEPAGE_VAR_JELLYSTAT_API_KEY: ENC[AES256_GCM,data:JD0pLXf0i+Zb95Va9TqtdhjnzJN7GsCsUt9N4EEo,iv:DIbSNSITi5VwVz82O9sVfqsg+MdpOw/f2ZDOVOU+6ho=,tag:tMxkSD7gBmZtcq747zD0bw==,type:str]
  HOMEPAGE_VAR_JELLYSEERR_API_KEY: ENC[AES256_GCM,data:WphFtMPMwD+3I8V4qfXA3POGuKnIhbNg8/uIAwBm,iv:ZQhKz5AXpudtB2V2420ivrrzOTPdVbqs6FMyXRyS7yw=,tag:R11QwDI6l2t389eNHpy2Vg==,type:str]
  HOMEPAGE_VAR_FILEFLOWS_API_KEY: ENC[AES256_GCM,data:aTCSXAmV6Qry+pA13SP9VhVxE4GaE3m+oLn8AA+H,iv:sTt6Ax/KMXdlWl1YayfuvAwzLUPhwxzTaGmm7ciEkpU=,tag:a5BinVN+whjoyS3rAhmNbg==,type:str]
  HOMEPAGE_VAR_IMMICH_API_KEY: ENC[AES256_GCM,data:4NC/BnjQB7loZymOdlzohpj0yTlestoGfXaru4EO,iv:kmum2wnPUCied9K0Oky7jm58TJ+Ln3A42bRg3CKFZ94=,tag:7wihmCS2XMKqmXu5wKMpBg==,type:str]
  HOMEPAGE_VAR_NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:Mw7XVlG6mF1H1o0AjQyzUoMbM3KWL7FUViZlzu9T,iv:xPM0clqvhPYfWMKWHAn1rFhXV9GrY7MSxjQ/p1yisYg=,tag:8aUtNjqwiJBWhgo4ziCOIw==,type:str]
  HOMEPAGE_VAR_NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:F05qFS0n+dowcf1Ng5vrizQyhT8RQCjdau5IMrwp,iv:zbAa24wlZyM6XIxnbfZJX4fkLgP6ntLv8jXpT9jVRkY=,tag:/9HsQo//O6OOxHPBHWzQCA==,type:str]
  HOMEPAGE_VAR_CHANGEDETECTION_API_KEY: ENC[AES256_GCM,data:AO4SZfz4n1gGz5CSJ6DSKwwc93gGzTgNvX+qzBu5,iv:Jkc+77Bs8Zr8s0TGFU2MBc/XW5qJSLhaoa6X8xMXBqg=,tag:SOKq2C+shtNtZDhrKQvZ2g==,type:str]
  HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:pNbz6QDQzWAFmsEz1XyXTp2EAFmq8afDlB9MuRol,iv:ijAAIOTNnLfGKKCXB6x97mne5/FPSLHHQMyWm1g103g=,tag:vb6DteMcXE5+ZCwUOsF/YA==,type:str]
  HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:RFdUQ9qAKh9AZ6HCrLsY0F6U8UotT5NfNlP7m2KE,iv:nCf2FRAfRHX3K1JstJWGMDDGDGQ5xtokXvy28dae0tU=,tag:wwCHbDzwsuco2cwZNOQ3/A==,type:str]
  HOMEPAGE_VAR_CROWDSEC_USERNAME: ENC[AES256_GCM,data:iavOV07at4Z2BxSH9UkhGM0aIbg3LdgyMZVpC2nr,iv:/5gZRgjpUL2iwe+73uszHBWgQ3nsg6n5Cv8dxSG09o8=,tag:Gx40qXhaK5UlT/q/gL91Ow==,type:str]
  HOMEPAGE_VAR_CROWDSEC_PASSWORD: ENC[AES256_GCM,data:PLdWryn6sGyaCDtNphb6GGSHbYK4wyb9QD5zu+iQ,iv:c8IeqrUeZNVaDB9Jb0trSnD+lHL5v8PIE7XLn42EvtY=,tag:pcZJpS54uF+Mn/qT5gTtIA==,type:str]
sops:
  age:
    - recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR2FwVE8vYWJ2eHVtak9h
        YUs0c3JNaGpwa2FqOVA1d0pyS0V0OXpDUzIwCklWT01NZ2loQmFjUWVodzlzdVFC
        T3ZqR0gxcURwSXNyRlNJSTN3a2lpZUEKLS0tIEhMVEsvU0FPWjV1LzBETUdoM0Vr
        UVZOVHZCT2JwM3NhWkVhTENKbGpERXcKyhy5b3fzpOG6c/JAef5j8waoZu0tqUgx
        2QIlllquf8LXPlILlbwMJbFe3LoMlfOBfltkzwtMF9ImHjJN1Pm21Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T20:54:50Z"
  mac: ENC[AES256_GCM,data:8XixL+d10bJQlF93bgyYWG8YDrwaVsLxDZF3DpuCezYInqmqSJf/12igkZD0UKl/pyIYdBH2bP3nLa9FZH96Arf8E7ISFFEm+PHYYOI5mMxXVsr8WqfenkK313newDf3L6VaTk/HIe+82CAjQ5GEdQ/WqO5GGlBJZONiqMZ1PgQ=,iv:/hZZMhuugRs1TNd6U+SxU7tnCnx2mj5F9EHUEbjiujA=,tag:2QViM2we10NfaPGxmPk3lw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
