apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:P7y1mjqInHjxRLnujzqASicuWGeFSeosE/h3a1RW,iv:d/LkqAh8v8TX9vC5hHe3rSNEAboFpfu0xBPiqW04y08=,tag:wsj9YmlrFRv0ZW/wBKR4Zw==,type:str]
  HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:MQ9+Eru6JrlYNxC4Vk9qbbynsAns25clpDb7bfSW,iv:cnmUDC4Ow8utmhEfPvT3R7P6aw39+Y76oQxVFirgWfk=,tag:qHH0WS7ncDPAv6JT/2Pqtw==,type:str]
  HOMEPAGE_VAR_JELLYSTAT_API_KEY: ENC[AES256_GCM,data:yzHmANrHB2a+y6kdz1L3QVs5L/CJ7QzEsSRXPRy4,iv:SUGK0zyYKnUgTqy3qjtv1jXZhkIit4Ald6bJsXQDBs0=,tag:/CSDt25RHqpKLAGUNrWfHA==,type:str]
  HOMEPAGE_VAR_FILEFLOWS_API_KEY: ENC[AES256_GCM,data:QJIoGfGTcZ86c1BYEmVr14HAgrKFzbhs0DlARh+w,iv:tBw6hNBDxDPKf+5UY68qSpCW0VfzStiotAF6YhS3Od4=,tag:O9WVzSmAtKyKRNl8BGTeiw==,type:str]
  HOMEPAGE_VAR_NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:bNeNfzpuIJzp8IRf1DBL2jKzgXmGwJUNPca+C1CZ,iv:LcHYYjRKbD05fgiy7o7VwBTGNI9uIt93RfHcntpzYrE=,tag:jWirQSjb2c371aKVzQj56A==,type:str]
  HOMEPAGE_VAR_NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:QfwA40VtWSfKwLVp0aGq2zQdBaK1FNsd+TEvE87w,iv:9CbqgGEs+j8zy7Ik9ofY1zcdupGhZViPME6LAS1odzg=,tag:82jTH2shrTGUd+PcUDfC/w==,type:str]
  HOMEPAGE_VAR_CHANGEDETECTION_API_KEY: ENC[AES256_GCM,data:paP+M7TBR8WqXzhFSF+ssrn8R4/Y+nzTTfblbZOV,iv:F15Th+MrKhcNHequCys5c+pDiZlC/yU29KR2G159XG4=,tag:y76rjqnWfzZO11x4ciCpmA==,type:str]
  HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:mAcinQCXpMPrnHtxhlYAUyyK4ssTHHDdHwHd7AcI,iv:VgC3jHXZp53B6FT5NeSdixlNCVabrh07XfUmyMDfv90=,tag:RU5gC90hXEoYZNmZvQbs4g==,type:str]
  HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:2GXvPL5IT4oFF/MRIgaL/RFcRacYlEzccDJdGM7p,iv:bTt5VBNfrApLEWhh+wONLS/WJS8pIX42q0NbOsqZLAE=,tag:mz9rIspkXw0CdrwOa125Mg==,type:str]
  HOMEPAGE_VAR_CROWDSEC_USERNAME: ENC[AES256_GCM,data:XDFBI18dT+NzJerOMvI8Y++e4SBSjzeUG8HMwLbA,iv:bHv95qQhm+c44cBKkLtQZIzS6ovfy0H/CrHUYvBhIxU=,tag:UOmYwRd6XnhXhlB+0W6MEA==,type:str]
  HOMEPAGE_VAR_CROWDSEC_PASSWORD: ENC[AES256_GCM,data:Vjz3slerI77NEokFOz1pLtwE2GSFNtHt7qXP5po/,iv:HiwxDS28cgV/tFR6w7xgIqPCSJmknyN3KC+O7UAkuno=,tag:yQ1U6RYwknJTLdrxP6vFPA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN3lBeSs4N2ZBcVF5Syt3
        c2pvbFFzQTFxeWFFVWVLVXRLZUp1bFFnQzBNCjQ0WWRiQy9SOTVXSTdKWSt3L01P
        TnFrU0graWxGcVZQbEtBdENpd3gvWWsKLS0tIERsR0cvS3p3SUcwdS8yUVlXUU1l
        bjY5NkxRbjV0amo4MFhtNklrWTI1QmcKFO3zkXuoiYoi32FibI5TbPhl5TwcI7fh
        +6vwxwb2yOiKGA5K4gZ44vDMMiIJSXIqU6mGig7mYXA6eFh5XgDsvw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T16:08:22Z"
  mac: ENC[AES256_GCM,data:O0NaC7IyRd/wOobCc0N4TEXYlLIv3DWZx+rKSBcMU4srIO6En9IyO+75S8ZDR0wJCop+qqWKntLTtFu/yuF5e5o3p3/ZNR8hL4Xkl6AiiB5jM7Sv9k3OPGPdWk2mc+eWZQqtmBGkS7VkW2VkOsLODKgA783mNQdKG421Ye7niIo=,iv:mrKGRtylSflpaZX6/gDkkECK16J5CER2+DZlh6gSXBw=,tag:/GcsUZ/eagIEgHLBztwiFw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
