apiVersion: v1
kind: Secret
metadata:
  # rook-ceph expects this name
  name: rook-ceph-dashboard-password
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:rH/pCiH7Hcc=,iv:Y/IIhaOUNnNIcKTi+64k9A7H4q4Yg084UJzAA+Ls65k=,tag:nVfdBSLLRLFRsGWouozkGw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFY1U0hIU0tI
        RnBJeE11Zk53eHVhMGQxQUxqMHcySHlTOWxrVXBrTnQzTWJBb2liYTM4YU1oamp5
        MjJLb0lVOGMyWjErNHBYV2RiWkRzKzNGRWpzdHhOOUNWaW1PR25iOGVjTnVmcnZX
        MG9QcDhKYmhQcWloLzJYRGd5UEErMyt2K0tlNFIwUHJINVl1bzViRWhWQXdyRXZW
        aVVDNENHRzhtQXJ5eTYvWitLNzlNZlJjRnY1RFVUbUhUWUtLMi9Eb2IyQ3o1Ry8r
        OHE2MnhSQUwzRk8yekhUODk2K0tNMXRWV29sR3pwOEt5R2V5RkU0RytmUTBJaHBB
        S1JpNmpNU01jRmh3OEU5YnZwNUFHaTg1YUE2R2M3cVh6TSs4aktiQUx2clhpUy9o
        a2t1Z2tHeEkxSEtuZ0QxUEtMbDhvS2pQQTZVL0ZNeEFqSkhBbTFJQkpaK0hSNGo5
        cTRCN1prSldHKzZvZ25jaDZDeCtGMzZmZm50ampRN25mS3VXdVdQcmExWmsxTkZ4
        dm9DVjVWVWh5OXBzRnBRZ0dFZWs3aXhTZ0RhSnFoVDQ3aVMrWWgrcUJRTkRNK0s1
        dmo0ajdvRXR2VHlVRnJpdW1tUjBBMTJQRStJSEY1NGlpYkZFcXVBK1NHMjlLM0Y4
        bEh0Qm1ITC9FUFZPLzBJdnBhNzZ0empPNDliN0N0endyZjdVSk5oeVorTnBrVWo0
        Mk10aXB3Tzc4R3RqT0hrQ05SNDIrOTVZYUNOd1F2ZkxneEJSckFPYXplcVd5bTNW
        VzRaMFpETmRDb2VRZlBMTFlpL1JFa2pxMEhZUHRQYStZMFhzbCt3QWR5MTVaMXM0
        cDRCOWtjSXlYb2kyMEEzRzJVSHAyS1U5OTJUNjJ5cjdGZ2ZUTmdEa05QZmx6bWRD
        enVhUk0wQkpJcUhNeUJxUHlnUHJrNy9yWEhQMkpueHBXZWxMZkhjeTF1aFBRbjdM
        WEJmTWxqVXUxU3laM3lGUGVHaUZhbWlmc05LTzZDY0tXMDh6cXpoTDRjdWU0QzBZ
        REYrNEhwbkcwQS9NUVEyZk5TQ1J3NldQNGdHTkkvZ3l5cmRiYncxOUowWTk1L25a
        aW1zY05CVnVMb2l0ZEN6akRqbVQxQWV2Z3IvWU44TEFnWmdMcHF3OGp2RGYzZkF4
        UnFrMVowcGhTeDFwTzBiaDdteVFWQm5CYlB5cTZybGVIZkQxVkJSSUJaMFVFdXdv
        YmlzcHhyOEF6aUhnNWtxK2MxRnFZaWI1cHF2R0I3UTUzVXZrMEhZYlhmSHYvTUVY
        aWhBY3hwZEtabGlIM1hEVk9XQkhpM2o3MU9ReERDWTM0MDRJbEJuVFRrbUJFVHBs
        ZlNrSEVDbVJFNGxUQnMxaUd2UDBRd1ExanJUajEyNmpYc3hQM1JTQTZDWU1GUlY4
        TWVJZFI3enl0ZDJFSWc5bnRQNnArZXh2b2gwVmxZTHRSa09qNFcvMmNHU0pwR1B1
        VHhzdjFBNXZ4Rk5KVG1ielpLUHQwN1N1WUcwYU95UUo2cUdmdXRTcjBzaHdDUXhu
        UmlFRE9wYjAvQVpwNmdXUWpKdVI3cjhQeHFoRElwRTZLQ2ZHMU5ybmpXOWVCUVZU
        emdodVlZdVdZYUZ5ZTRtME9FNVRsTFpUSTNCN05ldW9janQ4TnI0TEtpUVVtcWc5
        VDJGWGNPRGkwemZRNGtkSlQrVDErLzVZK0gxT3U1V1pCTGozRTVFVW05RnBrQjVH
        ckxrM3BMbkJucG9IQjNpU3QzbzF1TWtPbmhLbGtVRmZkeVpNQTI4Q0kvRTkzcEZw
        a2JQOEhxcGkrdFExZTQvV0M0M3VKb0pEME45RGdJRE50blg5MDRGMlEwUWNDZXFy
        bXFTK1dWZi9hQ1R0NDNBSERhZ2VkaFEzRldLV2JDaHlveVhJbCt0SG04K2RFZDhH
        TDNhQ1N4cWcrckFMclB0eXMvV1RyKzMvQzdSU0dvNUZZWlNsSUZ0M09tMnZmdwpO
        QitnWmhvRGd0UFUyZXJyRVVRSDFiYUU1MlIyZjZKcURFc1QvWFgwSlhVCi0tLSBy
        NFFUeTZ6N012RHZ5M1RoN3ZhQU00SkN1SFQ0eDB4M21HSWR4M29LUnY4Crdoyg3p
        Bd1sXr6gNIIfo5sz7E/PCpEifNJvqVpyIYXmx/VUXn1lP5foXtaA1jqM0ykBgjFj
        O4lwcHOpbzSPZuU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-28T19:25:51Z"
  mac: ENC[AES256_GCM,data:SaWXVzfq0c6HoIklkOejNZGXCV1Nok5N4zFgVucbJQYw26SbcG4HwzR6uaHwg1Hd3qieIGvaz/OA+Uc0tzNNAh0QhxJsqb9lkhyR+yBDfr0IIh5r23yfur54CMEmGVmpsEpnBjsjqYq17lX+G14FlSKJh/krEFihD8/Z0sE4H90=,iv:Ig0t7292Kck817IygtF3ibUf4TKLRREGUV8ccGtrlFQ=,tag:S8FaVGFqTAPHBmst0YY+nA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
