apiVersion: v1
kind: Secret
metadata:
    # rook-ceph expects this name
    name: rook-ceph-dashboard-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:rH/pCiH7Hcc=,iv:Y/IIhaOUNnNIcKTi+64k9A7H4q4Yg084UJzAA+Ls65k=,tag:nVfdBSLLRLFRsGWouozkGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSlpNbWZVbEgvK2Q4eVRV
            WWpueHg2bmNwUW5CZHJsVmdBbDJZNkhRN1FzCi9qSHRGZEQxRVMxRm5pdHBFZjQy
            bWRNWkF2N296elFHSkUvaE96dDJtYnMKLS0tIGY0NEVOempCRWxBaFg4SGViRVpT
            cVN3eHhoaEpYTmg3bEcrNDNGdklqaEkKkDq6X7LZwBIOlJSJfku76/8wyFialBeW
            y4aH0If+Q112z7T7mkXFEqvxqOrGHmrv3XpzywRU8NTynLJ0R9dZUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T19:25:51Z"
    mac: ENC[AES256_GCM,data:SaWXVzfq0c6HoIklkOejNZGXCV1Nok5N4zFgVucbJQYw26SbcG4HwzR6uaHwg1Hd3qieIGvaz/OA+Uc0tzNNAh0QhxJsqb9lkhyR+yBDfr0IIh5r23yfur54CMEmGVmpsEpnBjsjqYq17lX+G14FlSKJh/krEFihD8/Z0sE4H90=,iv:Ig0t7292Kck817IygtF3ibUf4TKLRREGUV8ccGtrlFQ=,tag:S8FaVGFqTAPHBmst0YY+nA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
