---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: fluent-bit
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.57.2
    digest: sha256:53cbd7d90e2a93e4c27fdb505333c837f582d12bf56a4a71809f4175ed83456a
  url: oci://ghcr.io/fluent/helm-charts/fluent-bit
