apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:JT3Nz7c7Fw6nOVHl7L3CZIToq9aVkybGQ7DqkPFN1qO+q7oEWMzQyg==,iv:q4pMngp4u8AZwFzGK7ndch8J/I8e0C4kSWaPwaTU6zo=,tag:4nlN1v+vT3S+274p6/yrvQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UE9XVWNlcDgyc3FqelM2
        RVA0TW15Nm51TGJwdmIxUm52M2FBbHd3dVZnCkIxbVplbFZGWEw5eXQxQ2dOclNq
        cHVEcWdvVFB1V3JKSEZPeXdZOTYzNDQKLS0tICs1a1dtUzRCQW5jdHBCa2FWMXpJ
        dkw1UXg4WXR3S0RFZ290UVowQzRXRmMKhR/NLYhY860iksBAlpzMmChSsyOrj5lG
        VMqj+oODP2eDbIsEklgs2H0+I1tof/rzYq5Ml5OcrQVoRhn/DUSuMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEhtZVcxc2Zw
        M3dPZWVJalEvbUZYbWM0M0E1N3krWkc1clpHRjI2VGRZM3JzMmRFRC9RbTJGWVlr
        bGFkUkNDb0FHRE1yNDEvSmlDc1dLOE90WndHcXhXYmcxMnZFeXBCVVFaL3RHOU5Z
        bC9kVUE1UFJTeWVXd0YxVVBjWEJlMm5DWGxaNm1BVlloeVRKTlJHUE1kVHlHczhr
        ZlByVENUdmxCOHFMVnRPZ0JhUWl4Um8zNUVPb0F2cG1oR3Y1cWN3Skc4OUZlc3Nk
        K2FhTExseElINUs0a3RLOXdHRlJreHozZmdJYVFtcnhwYjNPS2ltVTlMQ0dLT2tx
        MklKaHRJQnFvTm9VMEUwSFA0dTl2NEFBV3Bick8vYm9FQmNDZ1dGQnlWMHFROW9I
        ZjdzWHpFMHpFYWdFZko2V0syQ09uZ2o3bFVoL3Nod1JrY0xiY3EzKzV6dVRLSFVV
        OE16dVVIY3ZlNjVRSnNYQW81L0s3RmlnQTh6SEhLckxmWGtpWElVYlBLRTdzNWNw
        aW83OFlhOGtyMFlNQVpGcUg5VWV3SGRRbWZncXJEMngyQ0JZWm9XS0pkYzZrVUZn
        TzJ3TWQ2YzFMTDFBelJPcnc2WlZ1WVlPTWNRRjFjc095TXJHcURxVUtuUm5MU2Fq
        Y1NwU2hDMGRHd2VmMml1ZUxIKzJKb3htUEJYdGgxL3hZbHkwQ2VPc3E1SlpnNkxs
        eVAxNFluT0tqRjFKZVR0clJCSmRZaHk3ZWR5LzVCUmVVSkJSZ1pvUEhKcVlrdTIr
        bUFUQTYxN0NjRXBoK25LMEpPN1VlbkdySEdwM2JlMDJENll4bENXaitid1d6a0Fs
        djd0OUhNc0lzK0JFS0kvQWpjcVZiblVkMElIcWpjaEpXNmJPSkRteHJhZXZMd0p2
        Z2FjUHdkdXBiOEdXWjNGakIwOFRqY3ZqeTZNZ04vZXgvMFVxUlJqWE1YTVo3cXBv
        N05CcDNFUk05R3Yxb3B0MjJrRVErUE4zcW9qcjN2dnlhbURDNDJZZHNIcVdnV0hs
        SVRRbk1LVitlOWxVTjB5dWJTZlhlZm1NeFNRVVZ2UU1TMS9CNHVvREZxZHViVWxE
        NTNPOEJrcnJPSCtxNzdaaEJqQWl0dUJVVHppaEd4Zzd2TnA1SDFBSE5UUGJHYnhE
        MFN4RE9tbkVZaE1IUEN0VEhLOFY3OS9tY1F6TkhDSzlYWXZvdWpwVk1FMUhtaVp5
        S0RrWVVRcTdveU9IODAyRjN1N0JrZUFwMFl6L3ZYK3BiQmRsOUVtdU53SmpQdFh0
        WjNvYWdQZGlyNWUzVTQ1VDBOQ3htcDE1cjY1dWhtY0Z1U3lCd0E0SUpqRjJ6a3hD
        bUpNM0ZEMm0rYXVMdFRCK29nQU9BQml0YTgrci9wL3pxRGVtUWN1a1hBWm9qSWVI
        anRscEJVaVJiLzE2ZjhLdllIQjNiQ1FSUkJVSHNyZmk5R2RKbGcxOE1Jb0hzNW9M
        VnpDMGFPQm5YdXhpaXV4bENUU0hGOHdhclpYdFNIc0ZkeU5qRlpOUldyUkt4WXYx
        Qkc5a1FsaUJ2a0lDb0VsbnJyVUo3RWdrL3JlK1drc09BWjRYczlIbC9UOWRtdkw5
        L1RNQzhPNFExVlIxVi8yNEhSSlVpL0loTDkzaU8vUmxGQ2pBTmZJdUxqV09zd1My
        ZytpbVZNd3N6Q3JVZmtCNlFMTFpzck9CRzhpcVVqek1OMGtoRG5PcXp2M3F0ZzE5
        WUtsQjFmMDZUSzliWmg2azBaeC9TN1ZhbE9QMTNpRlU1c0J1TUxicGRiUjlzV2h3
        RlZ1MGcwY3J5V3FyWmhNeFlVUG1ZZ1RPTGppVWFmcFFMTC9rNC9uOXRDcFdLc3dL
        WEZibWFvZkN0UytyVlZZb3JyUTVmbktBSW9zeG1LZjFqakJIVnhEaDZSNHBMQ0Qz
        RHZZWk5Uek9yaUxVMzBZL0RYbDlBSFJZYUJSTlN4TzBQS3ZRRUdubmRCNlRJZwpq
        Rm1wZUZVeFA1N0JjdnlSSytwQVdQS2RvQ01TdmhURjF2TzRtbXl3MGJjCi0tLSBS
        VWk4aUFIMjdFYkJDMFVqN0d4MkRJeXJtU2J3VE9GTEFPRmlNZUJycENnCjWc+3Nt
        tzLxeH7MG7wAbe7o1YyBM7KofMPsD7PJzkNqBY5tjh6AG+HVrkK16woQQCImRu85
        fa1XxKOiiwLynK8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-02T19:38:50Z"
  mac: ENC[AES256_GCM,data:nsuZHl/oZwoXWwC/3WjhLmzYak92Q4EQQzmabC1b3r7o6Pws2/tcn4g7N5qT2F890Y5KZRLk8pwcXLIblRCJJ9D19MXluwqRG8nqqUoz/0Na+xnkCIj2SHanZ1sUuMwPeAPDE0EFRkZ+dheIb6XBQUt7uzOfTx6qeT00BBUKkDQ=,iv:bLFuVNSp806lqfZAUo8x8Eupj5LRuuGRnAQxdGzoDtU=,tag:2g1QaFZjvOjlvC/btwVk/g==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
