apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:JT3Nz7c7Fw6nOVHl7L3CZIToq9aVkybGQ7DqkPFN1qO+q7oEWMzQyg==,iv:q4pMngp4u8AZwFzGK7ndch8J/I8e0C4kSWaPwaTU6zo=,tag:4nlN1v+vT3S+274p6/yrvQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IExEWE9TTlVQ
        WDBxdCtRbzhrQ0FxVWY4Q0NvTUEyTkVVRkt5SzdCbXJhb0xaczlJZEdjUGxZT1I4
        ZVFGUEQvb3NEZVpudzZ6UWFmSUh6V09MK2lvZWhWd3R3aW8xbWFiSFFieWNVVEl6
        SWk0dHREUno1cU1DN2ltbnZKQnVaczFqS2RCZ05QT2pSRVNrQWdEUE5uSnVHU0R5
        eEt3ODdrd2lKdThYamtqWlhQc3RuNmxPVG9TdnlWNWVvUHdpcDlpb2pnTzBwek4y
        MVEvY1pDRUJjWVkzejZmWEVBNHBRMlR2ZkJnek96SXZ4VVRxVnJSTVhmeWtWNDNC
        dUhZMG5iSmtFWmdFZDhOdjdyOElHbENPYk9sbnhMNFpNZ1hQWEM2WU12aHJLS1Nn
        SFpTMWNJSmpmenRQbWg1MU1SMlpZUm5lRWVlKzBkUEVEam5tU2VHV0MwYlFsZ3d4
        VlBsOEp1NU80SmNXamJIYWlUQjdxSm1wOHcvaHlWR0E0RGJjVVV6eWI4V0Mwcnc5
        L29wSUIwNVlHYTZ5SjF2UW82Y0FJMFZ3TG9BRnlzOW1RbGdYTnNLdkZJKytTN3Zn
        Z0dqeUdvQy93MVdJN3NKVFNKbkQ2TjhLdWRxc29lVjd3SXBlL1IzVlBwV2pMWlg3
        VEx4Y25UN0dYK09YWWV4WnFQV1JqT2lwdGZIQ3cxSHNGK09YbWlHa2gxa2xiZWFH
        YWJ2dEpaMmJ5YzJVaVJBK3Rud0RHOHdYT29sRm9EN0hOMzJvamZqdnk3N0QvRXRk
        amZIeGdqR05lOWpETXJheXNsSmFMT3NURTBkS3RTWElOWjQ4Wno0eGV6Nm9yeUQy
        aFdkSXczUkpWZ2s1aHpGYWVYTTBMWkR1WHVaUFdrMVExaUlPdG5jKzlRTDRIaDNI
        WGhtdlBiSjh6cnlsZnptZTRmZXBaNWhBWXY0d1Frb1dFTmJuUHMrMjRkSERrVFQr
        RGg0YnNIUDlEMFJOL3BNYXBKT2s4VVdqdmY1MDVzSGNCekFwd3c1WGlmc3FsbTZp
        ZXVDdU9YVk13ajVDTVRmbitacHJJTDdwRGFPTzZSdmxWQW1Ka00xc0dsT015U1dL
        QTVTVjRMWXBGcG9pL0NiRDJTU3RLenNHaHI5cTBvZ2JtWGZIYTArc1ZxMVN5cFVw
        Q2dZMnFJQ1huUkF2VGRYeG1wSGpvNTR3enFtNEMzbTQ1K0xWWnozRkF0V3JRWWR3
        cXdMdlhXZkE3U3VTcUZWdVp3WCtyWk5QUVVLeC8zV1J4WkxXWTRmdGFMVTJiV2th
        VWx0NFZkWVk2dWVjTHZIdGpjZFRBOXhwRjg4MnZpQm9OUy8xVERqbDFSZko5ZzJQ
        VWNrM0RrTWhESTVjbHM0NS95NjNUMGF1UHN3dmdzbzI1UHVCc2ZpNVFZV3dKQ0or
        TlhVaElhMGZYSlBuUkxQMUhwVUFWTWZIY2N5MUdWVmtWU3FTZkR6KzZsdnJTWjdk
        WE0rSHd5a2loMGVKTTNVZnhoV2ZiTHF5NldUTE56cmlXRnJFQXVySzJmZmdDNEEx
        OUFOenRCVGVuZ09hOVF3ZHM3UWt0by9NR2s5UnZzbS8wTWwwNmQvanlxKzhpTUts
        aldDSkxpZW5Fa2lrRnY1dHhOaUVXMGpkY3M2ajhTa2pILytmZzB6dFhzTVIvVnlk
        MlZJL3Vhc2pUTjdmOUZhWkRvTGJ6UEFSVlFTVmpzNGY2bVl0bGpocXJEWWpqQlZQ
        V1NQUThXQ0RuYlltbWo4SEc0Z0RQTG1ESytDMTlZSVlCaFJhTE9hcnI1TUdVTVls
        RUdSWFNzaGZxQ2VmaTRtQUxobUZadnpDeHlHblZnaUw5eXYrSmUzTFAvbEphaEFi
        R2VpcEtrOFQ2bVN4QnVDdXdYN3g3bmdkU04rZDA4Ti9SNDE1NUIxYmwwT203V2l0
        VEFPWEt0RjZVK1pFbWhGUUVxS3crRUNhL0hPOFJtaCtndGR0TGR0YUh2WjNTUQpo
        SnVOZnYvd216clE4V0JaakdUVzg2THQ2M1R5VHBjUk1VaEhleUxNSkYwCi0tLSBD
        UGZXNzFCMUpnRlJSb1BSbklheGVnc2pFdHl4L2svUkFCVXVWZUlSTm13Ct3yTYnz
        HzubYk+7xCR2HXGYhIAxWrAhaEwlWgS/2IoxbqLP/dJM6eI/P7l3XSaJSliy/zhj
        8P3ZQA1TUNHPVI4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-11-02T19:38:50Z"
  mac: ENC[AES256_GCM,data:nsuZHl/oZwoXWwC/3WjhLmzYak92Q4EQQzmabC1b3r7o6Pws2/tcn4g7N5qT2F890Y5KZRLk8pwcXLIblRCJJ9D19MXluwqRG8nqqUoz/0Na+xnkCIj2SHanZ1sUuMwPeAPDE0EFRkZ+dheIb6XBQUt7uzOfTx6qeT00BBUKkDQ=,iv:bLFuVNSp806lqfZAUo8x8Eupj5LRuuGRnAQxdGzoDtU=,tag:2g1QaFZjvOjlvC/btwVk/g==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
