apiVersion: v1
kind: Secret
metadata:
  name: opencode-auth
stringData:
  OPENCODE_SERVER_PASSWORD: ENC[AES256_GCM,data:p8XbgA7s6+F86iHy0+IQUUQYWTltpSEpzTf35GA6VgZl+wQUyU6bBI9OSfU=,iv:4Wv1UJ3/nA8r0RNZZrG+ZMXoUXEVRc/5qjl7NAeO3m0=,tag:Rehz2MxHHmMMEKkJ88PH0g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDFzTXRsZTdo
        Y09rK05Fb1F6M3F6b3M5VkR2dzhEZDBKZXNwT2E5WVRFUjZsYUlvcWx3Y3A3aHlQ
        V2x1UVlQS3haeGN4R1JYanhYODFXd2NUbVNKQlhlOHpxL3JyN3k3S1dIc1h5OTh4
        S0FsQm5xZW14eTNUMzhDa0Z3SWJlVzlYdmFnZ1Q1WnpzeGU5YWFQRFp6alBCWkJB
        aHRKbkhpOEI3UjdzNnBCRmtLNjNQeTMzM1RiOGVkdGJJZy9ESzFDbEtjMEpsTUhM
        TTBEQ214VDhkdlJOdjJ6aTUwSDQ0YkI0Mm8zQjd4ZGkweUdjeHRPL0NzL2lCZTAz
        OUtUZXZVMDRxWUhhV1ZIOE1zcDdYNDlOU2JjZjQ0T1pYZmwvemg3cW5RMkRsTlV5
        NWFKZUlCWFpRNlVJVFoxdnQxT0YxVXAwc2tjRFEwWEtrVHFITzlvMEFPclM1N3Ex
        SHdGNG5wcGJVWTJ4bEJPa3ZwbzlWWlVFNFpnVEJYZm5YUWlMNGcybmVZbEtRSGQy
        MzE3NDZ2TkliQUE3S1h5ZnlDREgyWWkrZDZYeW5JT3Y3RXNMZHF4OTV5YllhNTZU
        T28rVWRFL2EvZ3pMSWEySnVsSUFCRkRFbWZSQ001MFNwWlgwUDZLQWZsYlphZDdm
        VlhsbGpQQ0o0cUVGSUZFWVNZdlM3ZFZuSy95UnhJUGZJMGRTVG42emNsZy8yeDBB
        ZGdrdGhjVVVWUE5nZUFGK25nUlN1MEhuUDRXYmx5K2pFVVN0S3c0eDIxK3ZyY2RP
        S2ZaN3dJazRLeGF5Nnc0bmpVWmx0MURpazY1TkRjN1pVckQybFM5a0F4MlRPUUVl
        YzlCSThMbGVzaTZFZEpCK0hLb0ljMTBWVTZYTTE4dEw0Vk1WN29JdHFZYkRtMUxH
        aXBhNmtCbnc2RlA5LytDcG1oSllRUVhOaE1HYnpUMWtNSFJhSHJtZHdIZlF5STZt
        R0t3bER1OTRwcTM5V1ZFRHJuM0V5cmh6dTk5UmxQdHk0VGQ2SWFaNUpwNXNKMXN0
        bWVLaTVkYW5lelJSMENDNTdlZ3lUOWhoUTFjNDBBUnBXQWNPTkRtRElYcWRsZ0pB
        eXNYcVR0ZTZDRXBqaG51eC9xVkNYOG1kTndKVTFzTlJiMHc0Yk9FTkRFSEJtRDda
        YTIzTHd0M3VQUlRXYUVNN3kxNnVhNUYwc2pCZWc5RXB5ZFl0NjMrM3BKeXpnUkJn
        L1VsZlhzb21peW9JZWhoSk5NVHR4aEtadkFaQTRzOEJCYkVIMS8vWURKQzlmWi9q
        WTFEYTRKWDBHVnhWT3pZS1ltaHUwV0ZOTkRpOHNXOTN0R2xzb1ZEcnpLSEFwVkNW
        V3lZT1pXdEJQdzhMVWhoQjk3ZDZ6RkMrd1ZvanJVTGhRSGRORWsvRWhsQ3pPeVpB
        WTBqZkRqaHhWWjUvV0ZkVTM4T2t1NmxWVXVILzI1dm1XM2lSVTFaSTYzRHV5TTFU
        R1ROcnpCK25FMEpBR2JMYncyZHVQUnBkb3J4QllCYjF6NjF2YjlybVl1RUY5WW50
        MkIzOXVrYm1NN3loQXB3aU1xcTJVQ0g0dFFZSHB2dzMwSEdNMnJVZC92c0dpWHU4
        WFhLb2VWR09jemhCUEpoeWlHV2ZacXM0T2EvWlJOanpCWWx5U3lWNTBneVpJTnVl
        SEp1ZWMwc0pIN09FZkxHdC9QYXFtTVZXVURkYjJ4YlZKeE9VNTlHSGNDQTIyT0dP
        a3QyVVJRbm51TU15Yi9NRUtBTndMaGpxYnVkdGxxRTRjN3RGS3NlaWRydjQyZnZl
        dGhSZmdOSUh0QmQ3dHF5RytpdDNKR0drb2daRkRiNzJqdlVhLzdKRUtjR1h6NnBv
        R0ZaMnlmT0pDcXFwT1Z3dHhVSnNSd2tDV01HVkdrL0F5Qlp2bXBPbTZ4dmtMSVI5
        VzUwaG5pVkJEenoyTXJ4ejI1a1VrYk9HZ2RRWUJpQ1RVZ1h1anJsQ0N0YWlUZwpR
        ek5PTlp2WS82QmlVYzFPVXZHSmRwMFBWNW1qb2xjSTNYWHVtNFBja1lnCi0tLSBT
        KzZKdE1GS0hxWGZMcmJ6KzdkalJXV1IrVjY5NmJ5TERtUVJQZnhtNmVvCiaVRZg8
        KS3d7HMy6hGk4nKHqIH5qdzI6to/DCj/cQcYW1xjWzIFI18IwPYQNNV4R0rI3aVJ
        ihYRKv1k9bU3D58=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1f696t70thmae32r7s6eqscyncz4tveaqsd53k2pw82kems2v02mcmeuj4j85swr6zdp3z3ay6kuq26z9d37928w58se3a7cvghzzlthmhfmdcn66sc8kcwp56672yjn5szvqet5q5v46a3kphepytfstdah95v95awn25jvc8ce2nmes0cqykax6n2tkf94pxqcjkn55wjjrgmk2dgh2xggl5gskxy4t20x88pqqtgnfe8pyymfuwmy3e9muvja9x3gf8can07seky8hv6ve9v0auzdyhpa2xwczme5ejxtdx6xtqp47cwe8q026gzh5wz0x82dezz5jkgznskq960ltwtfxsdj27seql0rtu3jqqkkm4xgqcfzjnxrzyevea8vgz5hr8053yt56qd9r6umydx93usfuzznen9wlew6500ydcqpjk2jm4x0ewy34ngjpj4uwu4p5dzynca4grrfghsnllum865u9f8py3nq69r0kjarppxfgvfgptuqpxkar2wvq7r8ys4vuuc2pj0433ceax49znp8sfqj5dl29ulcczqqw20pcjygxkc26tzv35ln8c7jjfre957v88wq9n8xxf4qgw3wpv2hh74gwuacnr2f4krkxzjs45a46v62jdkgmq0qnk3vhe9s2kgfjw3dzn6d4fnwyrt4ke6fverqc4x4mxpj6ffahw3mqv8g6vjgg2p46u53zrhgsnyr4x5dmxsmmpzdhjdu436ey89qmxgca8sjdwuzjhcvtewm9yppzjs9ef2p8q2mdjfcjh3uu3fq5py04sv8pskjvqd9y0ta8axmh239u4zlrgpdmwfe7r0wpgt788xgjwjx0vxdjr5gzk4quukyv2rvefjacg38mpwqyjaxv9q294v4f03g5x3ve79c27fgt3u34vmrcty09sje3yw2rraa5x9y5t3u4rtcpu5ay8jrx44u8dfehw5ulgfgqjza0lce4tz6s34uq00ayrg6vk6hgjuql55z6taltx04mjehmkk487ddd5zuzguqu8nvz2d5fhgl6sx3x775zdw29xnr8jgmltyfze2ymsz92u2dk4v70jzfsvc34m3ajkg9965rcqe9nn3aehwcr047p6xfnc55cv6tjewdrg6mff4glrwd9p8q5sa9repr0w3hzw42d9dys6u8hr50v83v8y5lzncql6ty9gfkcc4pcst683ddz2vky7u9g8gkrjy440r8yrsdw5cq6cpj23fjqxrj0t2gj5cpyv6407luycyd8p6pmjym3g46w2aj7f79nce73g30zwr4hx7mz2emrwkkgst53q85zyveg7fen5vtfjc3y6m0f5mkwj3yq5643c3jstgcz9fgsgu5hdx4u27wud5a3kgv8ysdh9z295mxh6j2pp96qwk34jevrqhn8zutwvvzwla53mrqh6czjpq6ud0c0psd7zznkgjczqsppq36ujygqnz4nc5sg40ngkfh3k5qyfdvx4slv9xcaceu83mzzr0unc3y4fznt0dal42z2kye8vxjz4yur33azljufrzg3d0lmxw2n53efhjr8wxtfstz4jjhn9pynzf425jryfpgf23pc6ykm4049qgu2xsz2nyrhty5yjla9xueyxwka77ztx7n6ndak0lg5n2fpveff8j2g49dyp3wqsvqmnm638nxwrd3g4hxqese8mmwt3cmr0jdykdnvqsmd9zumt0e6jkaktpppspsw4szfu7ft79r8gqwspdw7256lqmpr6r6hm2xxv0uwzqw6q3ffcy4y9n7tzxzhr22gf3qwxu8rhq9ceuj8jd4qsc7yexsa27d3dkwelklhk77c8zlf5aeg8y3usluk4y749ltlt7eh5xyf8al09nwljekxe74s7uj0hd07sm0zxgqal48prwgvl9svx0ucvze2yy3yygsqjwpc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T15:19:46Z"
  mac: ENC[AES256_GCM,data:03NpK493b/a83UXIsIPf3IeoEdvH3R35ZVfD1Elr6uRQV7vjvvBHTgHrX4cBH6KjTNxVClmqE2ewtmBmkbo8eEMtndIGpvgfeLJqHvh+dw0o16IZyCCUIXgTROdkdNtjg0dJkqXIkT2/aHnIstrBtwvqJuvXUdjb2NfTDy/H8cY=,iv:0SDTB0JP/1LQK+l9D3a6yExk5XWkGFFIlJXTKfAaTK0=,tag:NaEK5FIYxrLbTptgAI94bA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
