apiVersion: v1
kind: Secret
metadata:
  name: litellm-next-secret
type: Opaque
stringData:
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:0yQa7A8HGma3J36oINzTTQBM/oASxb1g5iGzKVPnfwgE0NRSssB0EdN6JmkgEjT3FFodl0vybQ2aUGLwMSSw+9QWqA==,iv:b7fR3asPy4OyaWoxrivP1fU9qxwuSw8E4jAUF6US4rw=,tag:nxe9Zig6ODfRPueWrwr58Q==,type:str]
  LITELLM_SALT_KEY: ENC[AES256_GCM,data:MfDX9W1cNIX0ZVpRK7E6Hnx/LHwmRhqJzS4hrU8tdgbWAm4f9d70AENxpFSBTnHRoSyHDZI/xzsGCxVDMRi9agZklA==,iv:f8M/uu0essj4wOegal57MuW9hNyj7wEuHDYJeXCM/2k=,tag:ycj2BfgWJbHeorsbarKyCA==,type:str]
  LLAMA_SERVER_API_KEY: ENC[AES256_GCM,data:ljTW3kWadmP7zsGTkloZwC0q,iv:jtp+9w1m3zjj4c34kDny4KwBwWqw2MbdWzQKLs/RroM=,tag:emxXHRWQ3zeKbjqNpp5QyA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:M9/3n0pFhndK2CppKeWI4s/0FepVgc7GkjQb+yEfR1yoLQhoYN/wSvS9MXeC6l/w6Ux7LgCbg+/ZBllhoKdRfNnwelVJ3tostvuJNrroRuqEu+OkDfG59WXm4yS4NnGK12oGctR3ljwsAowq7TNnMlhIBwkBANS2NcvT,iv:yA46szAjKWDsNQpr6XQ+0AiH71W2eMqGjxqJs/ZHgpI=,tag:DkNxV9xXJLnlXJdZ1VnBug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOHd2bDZ2QUx0N0JTUUhG
        NUdhSkVwYUY4UjhoQzdNWjIyby9tVFBkOVhrCkNmMFFLZTYxSU4vbHdhUEtSQXRq
        N0Rma3lDeXNRSHM4UmVaY0UraXRIcUkKLS0tIEhoak9vTzZpRkRtRldKLzBiWFJ5
        TTB5SXVXZnU3VzUrQTVCY2xMY01RZUkKpzaTmkxwOUKTw+ujIK8nv0HczKd+cHYY
        aGC2k+4ao665h83h+nxqTUEc9Q8LC5u4Z9oY7XKPbRk/BmR+LS3pkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12gul5m0dg9nn2gk69uvzwdxyluh5xt02m8wvyg9hn7c93nz7xehswmdenq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T22:20:26Z"
  mac: ENC[AES256_GCM,data:qQVXT0iskkXtxal9sHhH7tagrrUnGHVDgqTMfUkdNJXgBxTj6OcNlDyAGiLgXeeJc3qHF4AhdnEPiHGGxO4C0xDHLKPTidiFgk0hVQsEOIu2wJ13XpALRBgzBV96nhfsdPY2pb1zoNycE3zLXHGzmCdq7eRzT+CQIKKKZHYudOI=,iv:ROT2DSKb0omevuvVrjI/Fcp2STBte8eQnuWTyq/XmNA=,tag:DNcLGMzN9Ft4BjzOR9P/9g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
