---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openebs
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.4.0
    digest: sha256:5aaf304bb3d0ce863b01b2f93d66f7862b90d9b5c4685d4f512c0ae15dd4223d
  url: oci://ghcr.io/openebs/charts/openebs
